resources/Makefile.java.include
On windows if the `src/install_scripts/msys64_installer.sh` is not run with the `--all` argument but the `JAVA_HOME` environment variable is set, the correct warning is displayed when trying to compile the Java API but not when trying to compile the controllers.
=> Fixed Compilation of Java Controller when Swig is not Installed.

change_logs/ChangeLog.html, docs/reference/camera.md, resources/nodes/Camera.wrl, resources/wren/shaders/gtao.frag, src/webots/nodes/WbCamera.cpp, src/webots/nodes/WbCamera.hpp, src/webots/nodes/WbViewpoint.cpp, src/webots/wren/WbWrenCamera.cpp, src/webots/wren/WbWrenCamera.hpp, src/webots/wren/WbWrenGtao.cpp, src/webots/wren/WbWrenGtao.hpp, src/webots/wren/WbWrenShaders.cpp, src/wren/Viewport.cpp
This PR adds advanced Post-Processing (GTAO & Bloom) onto color cameras in Webots.
The `ambientOcclusionRadius` field is 0 by default (disabling the effect) for performance reasons.
=> Advanced Post-Processing on Cameras

docs/guide/using-java.md
The preferences do not include the ability to change the default java command as wrongly stated in the documentation:
https://www.cyberbotics.com/doc/guide/using-java?version=fix-java-doc
👍
=> Fixed Java documentation

resources/Makefile.java.include
The make clean for the Java controller was broken from the main compilation process because the Java wrapper is deleted first and therefore the clean rule was never defined.
=> Fix Java Make Clean.

docs/reference/emitter.md, docs/reference/receiver.md
The Matlab Emitter-Receiver API is incomplete.
https://www.cyberbotics.com/doc/reference/emitter?version=fix-emitter-reciever-matlab-api#emitter-functions
=> Fix Emitter-Receiver Matlab API

change_logs/ChangeLog.html
This entry was duplicated and could let the user think that we dropped Python 2.7
=> Fixed Missleading Changelog entry

src/install_scripts/msys64_installer.sh
It is very useful to have GDB installed (I am always ending up installing it manually), at least when the msys installer is launched with the `--all` argument.
=> Add gdb Package to MSYS Installer as Optional Package

docs/reference/nodes-and-api-functions.md
The muscle node is present in the menu but not in the list of nodes of this page.
=> Add Missing Muscle in nodes-and-api-functions Page

src/webots/core/WbSysInfo.cpp
`WbSysInfo::isAmdLowEndGpu()` should not be defined on macOS, otherwise it leads to build issues:
```
core/WbSysInfo.cpp:555:17: error: out-of-line definition of 'isAmdLowEndGpu' does not match any declaration in namespace 'WbSysInfo'
bool WbSysInfo::isAmdLowEndGpu(QOpenGLFunctions *gl) {
^~~~~~~~~~~~~~
core/WbSysInfo.cpp:557:16: error: use of undeclared identifier 'gpuDeviceId'
quint32 id = gpuDeviceId(gl);
^
2 errors generated.
```
=> Fix macOS build

change_logs/ChangeLog.html, include/controller/c/webots/robot.h
Fixes #124.
I tested with C and C++ controllers with GCC 7 and GCC 8 and it worked in all cases.
=> Fixed gcc7/cygwin flush of stdout/stderr

projects/samples/devices/worlds/linear_motor.wbt
Partial fix for #171 (doesn't fix the transparent color difference on AMD/NVIDIA)
=> Removed useless Transform and Group

src/webots/core/WbTelemetry.cpp
I just reinstalled the development system on Windows following the instructions on the wiki and Webots compilation fails because of the missing include of `cassert`.
=> Fix compilation of WbTelemetry.cpp on Windows

src/webots/gui/WbGuiApplication.cpp
It is safer and more efficient to run Webots in batch mode when using it as a simulation streaming server. Adding a warning in case the batch mode is not enabled in streaming mode should save users from troubles, like the "new version available" pop-up window preventing Webots from running in streaming mode until a user press the close button.
=> Added a warning if Webots is launched with the --stream and not the --batch option

projects/vehicles/protos/abstract/VehicleWheel.proto
Edges should be invisible on a tire. The current computation is complex and do not take into consideration the tire curvature.
| develop | this branch |
| --- | --- |
| ![wheel before](https://user-images.githubusercontent.com/866788/53549503-9a9f9a80-3b34-11e9-92b0-58074b35c7b8.png) | ![wheel after](https://user-images.githubusercontent.com/866788/53549501-9a9f9a80-3b34-11e9-81a7-3ddd963b03dd.png) |
| ![session_1_wheel_before](https://user-images.githubusercontent.com/866788/53549500-9a9f9a80-3b34-11e9-89d2-4e5f903b341a.png) | ![session_1_wheel_after](https://user-images.githubusercontent.com/866788/53549498-9a9f9a80-3b34-11e9-9aa6-985e6a0f8a0b.png) |
=> Fix tire creaseAngle

src/webots/nodes/WbConnector.cpp, tests/physics/controllers/connector_static_autolock/connector_static_autolock.c, tests/physics/worlds/connector_static_autolock.wbt
When Connectors are used inside a SolidMerger, the connection (snapOrigin) is shifted because the rotations between the SolidMerger and the Connector are dealt in a too simplistic way.
=> Fix Connectors with SolidMergers

resources/web/wwi/webots.js
Given that `webots.showRevert` and `show.Quit` properties are not set to the simulation server, they doesn't have to be initialized in `webots.Server` constructor.
In any case this initialization was fixed in #241 and it is no longer needed.
=> webots.js: remove initialization of showRevert and showQuit in wrong method

docs/guide/appearances.md, projects/appearances/protos/Asphalt.proto, projects/appearances/protos/BrushedAluminium.proto, projects/appearances/protos/CarpetFibers.proto, projects/appearances/protos/ChequeredParquetry.proto, projects/appearances/protos/GlossyCarPaint.proto, projects/appearances/protos/MatteCarPaint.proto, projects/appearances/protos/MetalPipePaint.proto, projects/appearances/protos/OldSteel.proto, projects/appearances/protos/PaintedWood.proto, projects/appearances/protos/Parquetry.proto, projects/appearances/protos/RedBricks.proto, projects/appearances/protos/RoughConcrete.proto, projects/appearances/protos/RoughOak.proto, projects/appearances/protos/RoughPine.proto, projects/appearances/protos/Roughcast.proto, projects/appearances/protos/SandyGround.proto, projects/appearances/protos/ShinyLeather.proto, projects/appearances/protos/StonePavement.proto, projects/appearances/protos/ThreadMetalPlate.proto, projects/appearances/protos/VarnishedPine.proto
We decided to release all the appearances PROTO with the Apache 2.0 license to make sure that their use do not 'contaminate' the user PROTOs.
=> Change Appearances Licenses to Apache 2.0

change_logs/ChangeLog.html, projects/robots/gctronic/e-puck/protos/E-puck.proto
Since the introduction of PBR we did set the ambient intensity of the default TexturedBackground to 1.0, so that non-PBR objects are ambient illuminated in a similar way than the PBR ones are by the background.
Since the introduction of HDR the intensity range of light has increased.
These two reasons imply that the calibration of the e-puck light sensors had to be updated.
I checked all the e-puck worlds and now the behavior of the light sensors are correct, the sensors facing the light return 0, the ones on the opposite side return ~4095 and the ones facing not exactly the light return an intermediate value.
=> Fix E-puck Light Sensors Calibration.

projects/samples/devices/controllers/battery/battery.c, projects/samples/devices/controllers/gyro/gyro.c, projects/samples/devices/controllers/motor/motor.c, projects/samples/devices/controllers/position_sensor/position_sensor.c, projects/samples/devices/controllers/radar/radar.c, projects/samples/devices/controllers/receiver_noise/receiver_noise.c, projects/samples/devices/controllers/spherical_camera/spherical_camera.c, projects/samples/devices/worlds/receiver_noise.wbt
This PR adds examples of using `printf("\f");` to clear the console and have a better, more readable output in the Webots console.
=> Add \f examples printf in devices controllers

change_logs/ChangeLog.html, src/webots/nodes/WbFog.cpp
Fix #307: as stated in the docs if the `Fog.visibilityRange` is 0, then the Fog node is disabled.
=> Fix disabled Fog when visibilityRange is 0

src/webots/nodes/WbAppearance.cpp, src/webots/nodes/WbAppearance.hpp, src/webots/nodes/WbImageTexture.cpp, src/webots/nodes/WbImageTexture.hpp, src/webots/nodes/WbPbrAppearance.hpp, src/webots/wren/WbWrenTextureOverlay.cpp, src/webots/wren/WbWrenTextureOverlay.hpp
Remove unused functions: the information about appearance and texture transparency is only used by WREN and not by Webots.
Removing these unused functions helps understanding where the transparency is handled.
=> Remove unused functions

change_logs/ChangeLog.html, src/webots/gui/WbMainWindow.cpp, src/wren/GlState.cpp, src/wren/GlState.hpp
As reported by a user the GPU memory reading on AMD graphics cards was broken, probably due to an update of the AMD driver. This PR fixes the problem.
=> Fix AMD GPU memory reading

change_logs/ChangeLog.html, resources/Makefile.java.include
When compiling a Java controller in the GUI having a custom Makefile, `make -jX` is called. The first rule of the Makefile is called in this default case. Currently, the first rule is `clean`; this mechanism is broken.
=>  Fix controller builds using a custom Java Makefile.

projects/objects/apartment_structure/protos/Ceiling.proto, projects/objects/apartment_structure/protos/DoorKnob.proto, projects/objects/apartment_structure/protos/DoorLever.proto, projects/samples/robotbenchmark/pick_and_place/worlds/pick_and_place.wbt
Improve exported `pick_and_place.wbt` in THREEjs by unsetting the castShadows flag for walls, door and ceiling.
=> Fix shadows in pick and place benchmark

docs/guide/starting-webots.md
Using the option results in the following error:
```
$ webots  --enable-ogre-warnings
webots: invalid option: '--enable-ogre-warnings'
Try 'webots --help' for more information.
```
=> Remove invalid option --enable-ogre-warnings from documentation

change_logs/ChangeLog.html, src/webots/nodes/utils/WbNodeUtilities.cpp, src/webots/nodes/utils/WbNodeUtilities.hpp
Muscle are not available for Hinge2Joint, but the check was mistakenly checking the whole ancestor hierarchy instead of stopping at the first joint instance.
=> Fix check for Hinge2Joint ancestor when inserting a Muscle

change_logs/ChangeLog.html, resources/nodes/SpotLight.wrl, src/webots/nodes/WbSpotLight.cpp
Use 0.7 instead of 0.758 as default SpotLight.beamWidth in Webots to have a nicer effect.
=> Improve Spotlight default beamWidth

src/lib/Controller/Makefile
Following up a problem reported by cctung on Discord, this PR aims at reinforcing the build process on Windows by checking if all the dependencies of 32 bit libController are met before attempting to build it.
=> Better check for 32 bit libController build on Windows

src/webots/Makefile
Fix two kind of warnings since the last clang upgrade:
1. warning about the use of the `register` keyword when linking with libpico:
../../include/libpico/picoknow.h:167:53: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
typedef pico_status_t (* picoknow_kbSubDeallocate) (register picoknow_KnowledgeBase that, picoos_MemoryManager mm);
^~~~~~~~~
2. 'compilation_timestamp.h' not found
core/WbTelemetry.cpp:24:10: 'compilation_timestamp.h' file not found
#include <compilation_timestamp.h>
^~~~~~~~~~~~~~~~~~~~~~~~~
=> macOS: Fix build warnings

change_logs/ChangeLog.html, projects/objects/floors/protos/Floor.proto, projects/samples/robotbenchmark/humanoid_sprint/worlds/humanoid_sprint.wbt
Address #304:
- Floor PROTO instances in `humanoid_sprint.wbt` are outdated
- texture mapping in Floor PROTO is wrong and displays mirrored textured
=> Fix Floor proto

src/packaging/files_msys64.txt
Since the last update of MSYS2, Qt5 was upgraded to use ICU version 64 instead of 62. Hence our installation script should be updated accordingly.
👍
=> Upgraded to new version of ICU

src/install_scripts/msys.sh
This fixes a problem on Windows where the MSYS2 python command was used instead of the official Python3, thus causing a failure of the main build process during the compilation of the Python3 wrapper (Python.h was not found).
👍
=> Added Python3 path before msys2 path to prevent python conflicts

resources/web/wwi/texture_loader.js
Fix TextureLoader interface to propagating the texture if it was already loaded and cached.
=> Hotfix reusing an already loaded texture in webots.js

projects/default/controllers/ros/Ros.cpp
Hello Webots team,
today I was struggling with the time published by webots on the "/clock" topic when synchronizing with ROS.
The problem: - Sometimes the calculated times don't exactly match the expected times:
e.g. instead of 
`sec: 11
nsec: 120000000`
Webots was publishing:
`sec: 11
nsec: 119999999`
I'm not quite sure why this only happens sometimes (randomly), but I guess it might be a bit problem when multiplying both doubles.
On the first hand it doesn't look like a big deal but gives you headache if you want to use timer events in ROS (http://wiki.ros.org/roscpp/Overview/Timers), because the event might not be triggered for the second case.
Adding the round function helps getting the expected values to be published
=> Add round to time 

resources/Makefile.include, resources/Makefile.os.include
This patch fixes a problem reported by a user:
=> Fixed link failure if Webots installation folder contains parenthesis

tests/test_suite.py
This will prevent Webots been stuck on the welcome dialog on jenkins each time we update the version (see  #422).
=> Run test_suite in Batch Mode

change_logs/ChangeLog.html, src/webots/nodes/WbCapsule.cpp, src/webots/nodes/WbCylinder.cpp, src/webots/nodes/WbGeometry.hpp, src/wren/StaticMesh.cpp
Address #411.
Tasks:
-> make it clear that the ODE shape will be a real cylinder even if the subdivision value used for the graphical mesh is low
=> Fix Cylinder boundingObject representation

projects/default/controllers/ros/RosInertialUnit.cpp
Since it took me quite some time to find the answer to https://stackoverflow.com/questions/56074321/quaternion-calculation-in-rosinertialunit-cpp-of-webots-ros-default-controller I think it is good to document it.
=> Document RosInertialUnit Axes Switch

resources/web/wwi/x3d.js
Fix `X3dLoader.parsePointSet` method broken when improving check for undefined variables.
=> Fix broken if conditions in webots.js parsePointSet

.travis.yml, tests/sources/test_clang_format.py
Travis doesn't support officially tests written in Python, but I have been able to make it works by using the 'generic' language and manually installing python with brew.
=> Macos Travis Test

docs/tests/test_references.py, docs/tests/test_titles.py, resources/osm_importer/importer.py, resources/sumo_exporter/re_definitions.py
Python 3 interprets string literals as Unicode strings, and therefore the `\d` is treated as an escaped Unicode character causing the following pep8 warning: `DeprecationWarning: invalid escape sequence \d`
=> Fix Various Python Regex.

resources/osm_importer/importer.py
Hi,
I noticed that an osm file can have multiple <bounds> element like this example:
```xml
<osm version='0.6' generator='JOSM'>
<bounds minlat='48.710233' minlon='2.1460891' maxlat='48.7189244' maxlon='2.1602205' origin='CGImap 0.6.1 (19297 thorn-02.openstreetmap.org)' />
<bounds minlat='48.7189244' minlon='2.1512673' maxlat='48.7276158' maxlon='2.1602205' origin='CGImap 0.6.1 (26368 thorn-01.openstreetmap.org)' />
<bounds minlat='48.7107509' minlon='2.1602205' maxlat='48.7120839' maxlon='2.1743519' origin='CGImap 0.6.1 (19277 thorn-02.openstreetmap.org)' />
<bounds minlat='48.7272003' minlon='2.1602205' maxlat='48.730416' maxlon='2.1634099' origin='CGImap 0.6.1 (19296 thorn-02.openstreetmap.org)' />
<bounds minlat='48.7117459' minlon='2.1743519' maxlat='48.7157548' maxlon='2.2026146' …
```
=> fixed world's bounds check

docs/css/webots-doc.css
Fix #502 
Process: start from the [original hyperlink color](https://www.colorhexa.com/317589), increase luminosity (along the monochromatic scale) for the unvisited hyperlinks, decrease the luminosity for the hyperlink events (active / hover). The difference is subtle but visible, good looking IMO.
Preview: https://cyberbotics.com/doc/guide/samples-environments?version=hotfix-hyperlink-colors
=> Improve hyperlink colors (hotfix)

resources/osm_importer/importer.py
Use the codecs to correctly read in utf-8 file, preventing UnicodeDecodeError
=> Fix UnicodeDecodeError when importing OSM on windows.

projects/samples/rendering/worlds/physically_based_rendering.wbt
`SphereGrid.cubeMap` has been dropped in #500 but few references remain.
This prevents `physically_based_rendering.wbt` to be loaded correctly.
=> Fix references to the dropped SphereGrid.cubeMap field

docs/reference/robot.md
The extern world was not visible in the doc: https://cyberbotics.com/doc/reference/robot?version=develop#field-summary
And this version is more homogeneous with https://cyberbotics.com/doc/guide/running-extern-robot-controllers?version=develop#introduction
=> Fix Controller `<extern>` Doc

projects/samples/robotbenchmark/visual_tracking/controllers/visual_tracking/visual_tracking.py
Following #526, this makes the controller less efficient, but compatible with both Python 2.7 and 3.x.
=> Fixed controller to be compatible with both Python 2.7 and 3.x

resources/web/wwi/mouse_events.js
=> Rotate the Viewpoint around the picked point

projects/robots/telerob/telemax_pro/controllers/telemax_demo/telemax_demo.c
With clang, I have such kind of build errors:
```
telemax_demo.c:27:6: error: conflicting types for 'wait'
void wait(int time) {
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/wait.h:248:9: note: previous declaration is here
pid_t   wait(int *) __DARWIN_ALIAS_C(wait);
^
telemax_demo.c:75:8: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'int *' [-Wint-conversion]
wait(20000);
^~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/wait.h:248:19: note: passing argument to
parameter here
pid_t   wait(int *) __DARWIN_ALIAS_C(wait);
^
telemax_demo.c:85:8: warning: incompatible integer to pointer conversion passing …
```
=> Fix telemax warnings

dependencies/Makefile.mac, projects/Makefile, projects/default/Makefile
=> Fix Makefile call order

dependencies/Makefile.windows
The includes were copied into `include/openvr/headers/*.h` instead of `include/openvr/*.h`.
=> Fix openVR includes installation.

projects/default/libraries/vehicle/Makefile, projects/robots/robotis/darwin-op/libraries/Makefile, projects/robots/robotis/darwin-op/libraries/python/Makefile, projects/robots/robotis/darwin-op/libraries/python27/.gitignore, projects/robots/robotis/darwin-op/libraries/python35/.gitignore, projects/robots/robotis/darwin-op/libraries/python36/.gitignore, projects/robots/robotis/darwin-op/libraries/python37/.gitignore, projects/samples/robotbenchmark/humanoid_marathon/controllers/marathon/marathon.py
=> Fix Python3 Libraries

.travis.yml
The goal of this PR is to test on linux-python27 and mac only during the nightly build or if triggered with the `travis_sources` keyword).
=> Make travis per commit tests on one platform only

projects/robots/robotis/darwin-op/libraries/Makefile
`projects/robots/robotis/darwin-op/libraries/python/managers.i` is wrongly removed during a `make clean`.
=> Fix Robotis library "make clean" rule

src/ode/Makefile
Due to our recent modifications on the libode build, the RPATH in libode was wrong causing a crash on the Webots statup when installed from a package.
=> macOS Fix crash on startup

projects/robots/Makefile
The `moose` controller is not build in the main build process.
=> Add moose controller in the Makefile list

projects/samples/devices/worlds/camera_auto_focus.wbt
The warning is:
```
ERROR: 'RectangleArena.proto': Lua error: The 'wallTileSize' field is deprecated, using the new 'wallApperance' field instead.
```
=> Fix warning about deprecated wallTileSize in camera_auto_focus

projects/robots/k-team/hemisson/worlds/hemisson.wbt, projects/robots/k-team/khepera1/worlds/khepera_k213.wbt, projects/samples/howto/worlds/center_of_mass.wbt, projects/samples/robotbenchmark/square_path/worlds/square_path.wbt, projects/samples/tutorials/worlds/obstacles.wbt
The `test_world_warnings` test report errors in the following worlds:
- projects/samples/howto/worlds/center_of_mass.wbt
- projects/samples/tutorials/worlds/obstacles.wbt
- projects/samples/robotbenchmark/square_path/worlds/square_path.wbt
- projects/samples/devices/worlds/led.wbt (fixed in #593)
- projects/samples/devices/worlds/camera_auto_focus.wbt (fixed in #594)
- projects/robots/k-team/hemisson/worlds/hemisson.wbt
- projects/robots/k-team/khepera1/worlds/khepera_k213.wbt
=> Fix various warning and errors in worlds.

src/packaging/files_msys64.txt
Since the upgrade to gcc 9.1.0, this DLL is now a dependency of Webots (and probably of other binaries built with gcc 9.1.0).
👍
=> Added missing DLL needed by GCC 9.1.0

src/webots/gui/WbSplashScreen.cpp
We should not show the commit ID in the splash screen:
=> Fix Nightly Version in Splash Screen

projects/samples/devices/worlds/camera.wbt, projects/samples/devices/worlds/camera_motion_blur.wbt, projects/samples/devices/worlds/camera_noise_mask.wbt
Fix #609 
Since R2018b, an HDR background has been added to this world, changing the global light, and render more difficult the red blob detection.
I added a central light, change the pink color of this block to red, and increase the blob surface by rotating slightly the block. Should be much more robust now.
=> Fix camera_noise_mask to render more easy the red blob detection

src/packaging/publish_release.py
The nightly release was published twice, once because of the CRON table and once because the release creates a tag.
=> Fix Nightly Release

resources/web/wwi/x3d_scene.js
Fix #628 
In such case, the `_setupEnvironmentMap()` function was called without argument after the world load. The simplest solution seems to simplify the `_setupEnvironmentMap()` function in order to have no arguments, and to rely on the background scene (as it's already done for the other backgrounds).
=> Fix HDR environment maps when disconnecting/connecting the streaming viewer

resources/Makefile.include
This issue occurs when the user explicitly rename/move `/Applications/Webots.app` to something containing a space (e.g. `/Applications/Webots R2019b.app`)
=> macOS: Fix controller build in case WEBOTS_HOME contains a space

resources/web/wwi/animation.js
Previously `this.gui` was supporting the values `play` and `pause`, but when changing the icon from `play.png` to `real_time.png`,  `play` is internally converted to `real_time` in animation.js.
In order to keep compatibility and given that `play` is more descriptive it is good to continue using it from outside the Animation class.
This PR adds a function to return the status of the Animation and convert back `real_time` to `play`, needed on robotbenchmark to store the animation status in the `animation_gui` cookie.
=> Always use 'play' in cookie storing the animation status

projects/robots/robotis/darwin-op/libraries/Makefile
If the files were already deleted, the makefile failed.
=> Fix Robotis Makefile

change_logs/ChangeLog.html, resources/web/wwi/Makefile, resources/web/wwi/passes/bloom.js, resources/web/wwi/shaders/blend_bloom.js, resources/web/wwi/shaders/bright_pass.js, resources/web/wwi/shaders/gaussian_blur_13_tap.js, resources/web/wwi/x3d.js, resources/web/wwi/x3d_scene.js, src/webots/nodes/WbViewpoint.cpp
Aim: Add the bloom post processing in webots.min.js
Apply and improve #408, now possible thanks to #528
Around this PR:
=> Bloom in webots.min.js

src/webots/maths/WbPrecision.cpp, src/webots/maths/WbPrecision.hpp, src/webots/scene_tree/WbDoubleEditor.cpp, src/webots/scene_tree/WbVector2Editor.cpp, src/webots/scene_tree/WbVector3Editor.cpp
Fix #582: improve fix in #627 by changing the rounding method so that it uses the `WbPrecision::doubleToString` rounded value.
Using the string value to round reduces differences when saving the value to file and make it more robust to the intrinsic floating noise.
Note that for almost all the values the two rounding methods are equivalent.
This is the same principle it was used in #627 where the value was extracted from the spin box text, but now it has a higher precision that fixes the reset to default issue.
=> Hotfix rounding issues

.appveyor.yml
In this PR, we want to avoid launching useless AppVeyor source tests each time a branch is merged in master, revision or develop.
=> Skip AppVeyor test on merge

docs/reference/change-log-r2019.md, src/webots/nodes/WbImageTexture.cpp
The wrong pixel was taken, which was in some cases even causing crashes (e.g. is uv = (1.0, 1.0)).
=> Fix Texture Picking

src/packaging/webots_distro.c
This should fix #707.
Changing the compression ratio from "max" to "fast" and avoiding to compress `jpg` and `png` files (which are already compressed) allow us to lower the Inno Setup compilation time from 10:13 minutes down to 3:13 minutes on my computer. However, the resulting `webots_setup.exe` is 7% bigger (1,523 MB instead of 1,417 MB). On the appveyor VM, the Inno Setup compilation takes about 15 minutes, so the gain should be even better.
I believe this is a good compromise.
=> Speed-up Inno Setup compression

resources/web/wwi/.gitignore
This file was missing in the gitignore.
=> Add webots.debug.js to gitignore

docs/reference/changelog-r2019.md, src/webots/control/WbController.cpp, src/webots/control/WbController.hpp, src/webots/nodes/WbRobot.cpp, src/webots/nodes/WbRobot.hpp
Once an external controller was exiting the `INFO: 'extern' controller exited successfully.` message was never displayed, it was not possible to re-launch the external controller and the simulation was blocked (because waiting for ht controller).
=> Fix External Controller

docs/reference/background.md, docs/reference/changelog-r2020.md, projects/objects/backgrounds/protos/TexturedBackground.proto, resources/nodes/Background.wrl, resources/web/wwi/x3d.js, resources/web/wwi/x3d_scene.js, src/webots/nodes/WbBackground.cpp, src/webots/nodes/WbBackground.hpp, src/webots/nodes/WbPbrAppearance.cpp
Partially fix https://github.com/omichel/webots/issues/483#issuecomment-496243286
Implementation of the `Background.luminosity` field:
=> Feature Background Luminosity

projects/robots/dji/mavic/worlds/mavic_2_pro.wbt
Use `Background.luminosity` instead of `Viewpoint.exposure` in order to not affect the Background colors.
| Before | After |
| --- | --- |
| ![mavic_2_pro](https://user-images.githubusercontent.com/866788/61713220-536eac00-ad58-11e9-8857-28a04ec924dc.png) | ![mavic_2_pro_new](https://user-images.githubusercontent.com/866788/61713219-52d61580-ad58-11e9-873b-6e1bbb9e42c7.png) |
=> Improve Mavic 2 PRO lights

projects/robots/dji/mavic/controllers/mavic2pro/mavic2pro.c
The oscillation around the vertical component was too big to create nice looking movies, and the PID control shows limitations for the component control. I slightly changed the stabilization algorithm to reduce this effect and found better and simpler solution using a cubic function to adjust the thrust around the target altitude:
https://www.desmos.com/calculator/gtkbezos9z
The drone is now stabilized after one oscillation.
=> Improve the vertical stabilization of the drone

docs/reference/changelog-r2019.md, src/webots/nodes/utils/WbNodeUtilities.cpp
Following this discussion: https://stackoverflow.com/questions/57142908/why-cant-i-insert-a-rotationalmotor-node-in-device-field-of-balljoint-node-in?noredirect=1#comment100870939_57142908
The `BallJoint` case and the `BallJoint.device3` case were not validated correctly in `WbNodeUtilities::validateExistingChildNode()` causing the impossibility to insert a PROTO containing a BallJoint.
=> Fix the insertion of a PROTO containing a BallJoint

docs/reference/changelog-r2019.md, projects/vehicles/worlds/village_realistic.wbt
This world has not been updated regarding to default roughness and metalness:
| Before | After |
| --- | --- |
| ![village_realistic](https://user-images.githubusercontent.com/866788/61879399-3d492300-aef3-11e9-99dc-73b87f196cdc.png) | ![village_realistic_1](https://user-images.githubusercontent.com/866788/61879397-3cb08c80-aef3-11e9-905e-d695e5a39c58.png) |
=> Fix roughness and metalness in `realistic_village.wbt`

docs/reference/changelog-r2019.md, resources/web/wwi/x3d.js
| Webots | revision | this branch |
| --- | --- | --- |
| <img width="881" alt="bb-8 webots" src="https://user-images.githubusercontent.com/866788/62050463-8d84f580-b211-11e9-8d6a-2dcbdd65d47c.png"> | <img width="768" alt="bb-8 revision" src="https://user-images.githubusercontent.com/866788/62050462-8d84f580-b211-11e9-97d7-c48eb47392f5.png"> | <img width="768" alt="bb-8 pr" src="https://user-images.githubusercontent.com/866788/62050461-8d84f580-b211-11e9-83c5-d5ca662d3cc1.png"> |
| ![webots](https://user-images.githubusercontent.com/866788/62050466-8e1d8c00-b211-11e9-821b-f5813695d9ce.png) | <img width="636" alt="revision" src="https://user-images.githubusercontent.com/866788/62050465-8e1d8c00-b211-11e9-9d14-b1a185e4fea9.png"> | <img width="640" alt="pr" …
=> webots.min.js: Compute normals for ElevationGrids

docs/reference/changelog-r2019.md, resources/web/wwi/x3d_scene.js
- Open `physically_based_rendering.wbt`
- Remove the background
- Open the browser client
- Get this error when picking:
Note:  `threejs` do the assumption that the background is null at several locations, for example [here](https://github.com/mrdoob/three.js/blob/r104/src/scenes/Scene.js#L31).
=> webots.min.js: Fix background color

docs/css/webots-doc.css
Solution: Add a white background in every modal window images.
Preview on some cases:
- Cylinder schema:
- before: https://www.cyberbotics.com/doc/reference/cylinder
- after: https://www.cyberbotics.com/doc/reference/cylinder?version=hotfix-modal-window-background-color
- Hinge2Joint schema:
- before: https://www.cyberbotics.com/doc/reference/hinge2joint
- after: https://www.cyberbotics.com/doc/reference/hinge2joint?version=hotfix-modal-window-background-color
- generated images with shadows:
- before: https://www.cyberbotics.com/doc/guide/lidar-sensors
- after: https://www.cyberbotics.com/doc/guide/lidar-sensors?version=hotfix-modal-window-background-color
=> Hotfix modal window images background issues

docs/reference/changelog-r2019.md, projects/objects/backgrounds/protos/TexturedBackground.proto, projects/objects/backgrounds/protos/TexturedBackgroundLight.proto
I think we missed an HDR outdoor background take at noon with patterns in the sky (clouds) to increase reflection effects on the reflective materials.
This one seems to solve this issue:
Comparison on a car:
| HDR background | Result |
| --- | --- |
| `moutains` (default) | ![mountains](https://user-images.githubusercontent.com/866788/62457696-a21a3e00-b77b-11e9-9927-3a854afa5790.png) |
| `noon_cloudy_countryside` (new) | ![noon_cloudy_countryside](https://user-images.githubusercontent.com/866788/62457698-a2b2d480-b77b-11e9-80ae-1a1e3539b4f6.png) |
=> New HDR background

docs/css/webots-doc.css
Currently, the modal images are limited with the doc images max-height = 500px.
- https://cyberbotics.com/doc/guide/samples-environments
When the image is big, If the window is too small, the image is cut, it is too big the image is limited to a height of 500px.
Setting explicitly the max dimension as a percentage of the parent modal window solves these 2 issues:
- https://cyberbotics.com/doc/guide/samples-environments?version=enhancement-modal-window-image-size
=> Modal images dimension

docs/guide/installation-procedure.md
Use the https protocol instead of http.
The signature file is mandatory, not optional.
Improved English.
👍
=> Fixed Installation instructions

resources/web/wwi/editor.js, resources/web/wwi/toolbar.js, resources/web/wwi/webots.js
When running others simulations, `webots.User1Authentication` was `undefined` and not an empty string as expected.
Because of this, it was possible to open the editor but the controller content was not displayed. 
I improved all the checks for user ids and authentication so that they do no longer depend on the previously executed functions.
In case of the user ids we should explicitly check for `undefined` and empty string, because otherwise user ID `0` will also be detected as undefined.
=> webots.min.js: fix authenticated user check

projects/samples/robotbenchmark/visual_tracking/controllers/visual_tracking/visual_tracking.py
Fix the image URI sent to the robot window: in python 3 `base64.b64encode` creates a  bytes literal object that converted to string has the format `b'<value>'`.
The additional `b` and quotes was making the URI invalid.
=> visual_tracking benchmark: fix URI of camera/display images

docs/guide/using-python.md, docs/reference/changelog-r2019.md, src/webots/control/WbController.cpp
The python shebang of controller programs was totally ignored by Webots causing some misleading behaviors: although the shebang was indicating to run python 3, Webots may silently run Python 2.7. This PR fixes this problem by reading the standard shebang of controller programs to determine which version of python to use. On Windows, shebangs are not supported, so a warning is displayed in case of version mismatch.
=> Fix read controller python shebang

resources/web/wwi/toolbar.js, resources/web/wwi/webots.js, src/webots/gui/WbStreamingServer.cpp, src/webots/gui/WbStreamingServer.hpp
Complete fix #795 not working  and enabling/disabling of run mode buttons in the toolbar in broadcast mode.
Streaming viewer issues:
=> webots.min.js: fix toolbar run button status and context menu

docs/reference/changelog-r2019.md, src/packaging/files_core.txt
We document that Python37 is available on Linux (https://www.cyberbotics.com/doc/guide/using-python#introduction), but that was not actually the case.
=> Fix Python37 not released on Linux

docs/reference/changelog-r2019.md, src/packaging/files_msys64.txt
Following a user bug report (support ticket 2649), this fix guarantees that we use the correct version of libssl on Windows.
=> Fix possible dll conflict on windows

docs/reference/changelog-r2019.md, resources/web/wwi/console.js, resources/web/wwi/dialog_window.js, resources/web/wwi/editor.js, resources/web/wwi/help_window.js, resources/web/wwi/robot_window.js, resources/web/wwi/toolbar.js
Remove calls  to `this` object in static methods of `dialog_window.js`.
This was causing issues when calling `webots.alert` and `webots.confirm` functions.
=> webots.min.js: fix 'this' object in static methods

docs/reference/changelog-r2019.md, resources/web/wwi/mouse_events.js
Fix https://github.com/omichel/robotbenchmark/issues/344
I only see this issue on Firefox + Windows 10 (Edge or other Firefox versions are working fine with this). 
'#playerDiv' (the canvas parent) raises the context menu of the browser; this event should be simply prevented. It's probably safer to apply this patch systematically on every browser.
| Bug | Fix |
| --- | --- |
| ![bug](https://user-images.githubusercontent.com/866788/63363056-30ddac00-c373-11e9-9a0a-1c052d580d66.png) | ![fix](https://user-images.githubusercontent.com/866788/63363058-30ddac00-c373-11e9-9368-b2f4f90a83da.png) |
=> webots.min.js: Fix context menu on Firefox/Windows 10

.travis.yml, src/packaging/Makefile
This PR makes that travis install will the `npm` package the same was we do it manually following the new explanations here: https://github.com/omichel/webots/wiki/Linux-installation.
It is simpler and greatly facilitates the build on snapcraft.io.
=> Fixed the installation of npm on Linux

projects/samples/robotbenchmark/humanoid_marathon/controllers/marathon/runtime.ini
Fix issue https://github.com/omichel/robotbenchmark/issues/349: to support multiple versions of python we now also have to link to the specific python folder other than the generic 'python' folder kept for backward compatibility.
=> Fix path to python versions of robotis managers

resources/web/wwi/mouse_events.js
Fix issue https://github.com/omichel/robotbenchmark/issues/351:
the wheel event was overwriting the `MouseEvents.moveParams` and deleting the `scaleFactor` variable. Due to this when moving the mouse the computed `zoomScale` value was NaN and the viewpoint position was broken.
Steps to reproduce:
1. start tilting/zooming the viewpoint by pressing the middle/wheel button
2. move the wheel (without releasing the wheel button)
3. move the mouse (without releasing the wheel button)
=> Fix handling mouse wheel event while running another mouse event

dependencies/Makefile.linux
These links are not part of the package on the ftp.
=> Remove opencv soft links

docs/reference/changelog-r2019.md, src/webots/nodes/WbSolid.cpp, src/webots/vrml/WbProtoModel.cpp
Fix #841: escape characters in Solid.name that have special meaning when used as a regular expression pattern string.
=> Fix regular expression pattern for Solid.name

src/webots/nodes/WbBackground.cpp
Stack:
```
5   WbMFString::item(int) const + 124 (WbMFString.hpp:56)
6   WbBackground::exportNodeFields(WbVrmlWriter&) const + 447 (WbBackground.cpp:445)
7   WbNode::exportNodeContents(WbVrmlWriter&) const + 51 (WbNode.cpp:1092)
8   WbNode::writeExport(WbVrmlWriter&) const + 89 (WbNode.cpp:1101)
9   WbNode::write(WbVrmlWriter&) const + 221 (WbNode.cpp:960)
10  WbWorld::write(WbVrmlWriter&) const + 432 (WbWorld.cpp:361)
11  WbWorld::exportAsVrml(QString const&) const + 182 (WbWorld.cpp:338)
12  WbWorld::exportAsHtml(QString const&, bool) const + 448 (WbWorld.cpp:281)
13  WbAnimationRecorder::start(QString const&) + 349 (WbAnimationRecorder.cpp:368)
```
=> Fix crash in Background

docs/reference/changelog-r2019.md, src/webots/scene_tree/WbSceneTree.cpp, src/webots/vrml/WbProtoModel.cpp
For objects in a folder containing underscores in the name, like the ones in the "living_room_furniture" folder, the generic `Solid` documentation page is shown instead of the specific one when selecting the "Help..." item from the context menu.
Steps to reproduce:
1. open the `inverted_pendulum.wbt` benhcmark
2. right click on the sofa to open the context menu
3. select the "Help..." item
-> The `reference/solid.md` documentation page is displayed instead of the `guide/object-living-room-furniture`
=> Fix search for objects documentation page

docs/guide/installation-procedure.md, docs/reference/changelog-r2019.md, src/lib/Controller/Makefile, src/lib/Controller/api/abstract_camera.c, src/lib/Controller/api/abstract_camera.h, src/webots/Makefile, src/webots/core/WbPosixSharedMemory.cpp, src/webots/core/WbPosixSharedMemory.hpp, src/webots/nodes/WbAbstractCamera.cpp, src/webots/nodes/WbAbstractCamera.hpp
By default Qt uses SYSV shared memory on Linux and macOS. This has several drawbacks:
- on macOS: the default size of SYSV shared memory segments is very small preventing many camera-based simulation to work out-of-the-box. We ask users to modify their system settings to work around this problem, which is not very user friendly.
- on Linux: the SYSV shared memory segments are not compatible with snap strict confinement, hence preventing us to package Webots as a snap package with strict confinement (which is better than the classic confinement).
=> Use POSIX shared memory instead of SYSV shared memory on Linux and macOS

resources/web/wwi/texture_loader.js, resources/web/wwi/x3d.js, resources/web/wwi/x3d_scene.js, src/webots/gui/WbStreamingServer.cpp
=> webots.min.js: hotfix single node load into existing scene

src/webots/maths/WbPolygon.cpp, src/webots/nodes/WbPhysics.cpp
Cppcheck 1.86 reports:
```
[src/webots/maths/WbPolygon.cpp:33] -> [src/webots/maths/WbPolygon.cpp:87]: (style) Variable 'det' is reassigned a value before the old one has been used.
[src/webots/nodes/WbPhysics.cpp:148] -> [src/webots/nodes/WbPhysics.cpp:155]: (style) Condition 'size==2' is always true
```
=> Fix CppCheck issues

docs/reference/changelog-r2019.md, src/lib/Controller/api/supervisor.c, tests/api/controllers/supervisor_import_remove/supervisor_import_remove.c
Fix #883: fix deleting the second node of the `node_list` list in libController `supervisor.c`. 
Previously both the first and second nodes were wrongly removed from the list.
=> Fix removing the second node from node_list in libController

docs/reference/changelog-r2019.md, resources/wren/shaders/pbr.frag, resources/wren/shaders/pbr_stencil_ambient_emissive.frag, resources/wren/shaders/pbr_stencil_diffuse_specular.frag
Fix #891: the case where all the texture coordinates are equal (i.e. `dFdx(uv) == vec2(0) && dFdy(uv) == vec2(0)`) was not handled in `cotangentFrame` function leading to a division by 0.
=> Improve robustness of cotangentFrame function in pbr shader

src/packaging/webots_distro.c
`cp` on travis fails with this warning:
cp: the -R and -r options may not be specified together.
=> Fix macOS package creation

src/install_scripts/qt_linux_installer.sh, src/packaging/files_core.txt
Wayland is not needed as we can disable it from an environment variable in the snap environment.
👍
=> Removed Qt Wayland platform plugin

.travis.yml, docs/guide/installation-procedure.md
We do not need libPCI anymore.
=> Cleanup libpci

resources/Makefile.include
When compiling a controller contained in a directory with spaces, it produces the following warning:
=> macOS : Remove warning when building a controller in a directory containing spaces

src/webots/nodes/WbPropeller.cpp
Fix export of Propeller node (Group node containing the `slowHelix` and `fastHelix` nodes) probably broken in #698.
=> Fix Propeller VRML export

projects/humans/c3d/controllers/c3d_viewer/c3d_viewer.py
The example C3D file provided was causing issues because it is missing the `POWERS`, `MOMENTS` and `FORCES` arrays.
=> Fix C3D runtime issue.

dependencies/Makefile.linux
Quick and dirty fix for OpenAL:
=> Revert OpenAL modifications, time to find a better fix

dependencies/Makefile.linux
Fix #964.
Note that it is not necessary to create a package to check the issue but this can be inspected directly on the development environment by checking that the soft link points to the library with a relative path and not an absolute path.
=> Fix libopenal soft link

docs/reference/changelog-r2019.md
MSYS2 updated Qt over the week-end.
You should run again the `src/install_scripts/qt_windows_installer.sh` script that will proceed automatically to the update.
I tested this update and it caused no compilation warning and Webots seems happy with it (we already used this version of Qt on Linux).
👍
=> Qt5 update on Windows

docs/guide/running-extern-robot-controllers.md, docs/reference/changelog-r2019.md, projects/robots/k-team/khepera3/controllers/khepera3_gripper/khepera3_gripper.c, src/webots/control/WbControlledWorld.cpp, src/webots/control/WbControlledWorld.hpp, tests/api/controllers/extern/extern.c, tests/api/worlds/extern.wbt
Extern controller should block the simulation while not started if the 'synchronization' field is set to `TRUE`.
=> Fix Extern Controller Synchronization

docs/reference/changelog-r2019.md, src/webots/scene_tree/WbTreeItem.cpp
Following-up on the good idea from @HefnySco proposed in #985, this implementation takes care of displaying only device names to avoid over-cluttering the scene tree.
=> Fix better scene tree naming

docs/guide/installation-procedure.md, docs/guide/running-extern-robot-controllers.md, src/lib/Controller/api/system.c, src/webots/gui/WbPreferencesDialog.cpp, src/webots/launcher/webots-linux.sh
Fixes #950.
This PR makes it easy to run extern controllers with the snap package (no need to be administrator). Basically, the webots launcher and libController were modified so that the snap version of webots can run extern controllers without any special setup. The user may override the `WEBOTS_TMPDIR` and/or `TMPDIR` environment variables before launching webots and the extern controllers if needed. Otherwise, they will be automatically setup to a default value (`$SNAP_USER_COMMON/tmp` = `~/snap/webots/common/tmp` for the snap version or `/tmp` for the non-snap version) that guarantees it will work smoothly with both the snap and non-snap versions of webots.
Additionally, the launcher now cleans-up the temporary folder and pipe files in case webots crashed without cleaning them up. …
=> Fixed extern controllers on snap

docs/guide/running-extern-robot-controllers.md
On Ubuntu 16.04 the system libraries are not the same that the one distributed within the snap package which causes conflicts when running external controllers.
Problematic libraries:
- lipng16 VS 12
- /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /snap/webots/current/usr/lib/x86_64-linux-gnu/libpng16.so.16)
https://www.cyberbotics.com/doc/guide/running-extern-robot-controllers?version=fix-snap-external-controllers#running-extern-robot-controller-with-the-snap-version-of-webots
=> Fix snap external controllers

src/webots/control/WbControlledWorld.cpp
At the destruction of the world, it happens that the robots are removed, and therefore the controllers also which causes issues with the `mRobotsWaitingExternController` list which is then referring to non-existing robot anymore which causes issues when removing them from the list due to connects.
No changelog entry as this was never released.
=> Fix possible crash with external controllers.

dependencies/Makefile.linux, dependencies/Makefile.mac, dependencies/Makefile.windows
Fixes #965.
In this PR, the dependencies Makefile checks the MD5 sum of each Webots dependency and fails if the check fails. The output of the Makefile was also cleaned-up, so that it is now much more readable.
=> Check MD5 for dependencies

dependencies/Makefile.mac
Fix issue introduced: https://github.com/cyberbotics/webots/pull/994
On macOS, `md5sum` is not installed by default. This issue is raised:
/bin/sh: md5sum: command not found
`md5` should be used instead.
=> macOS: Fix MD5 check

docs/reference/changelog-r2019.md, src/webots/engine/WbAnimationRecorder.cpp
Fix issue with digit translation export described in #829.
Bug Description:
The initial translation( and rotation) field value is not explicitly set and thus it is automatically set to `[0, 0, 0]`.
So if an object, whose initial position was different from `[0, 0, 0]`, is moved to the position `[0, 0, 0]` the change is not detected and not exported.
=> Fix exporting first translation/rotation field change

resources/web/server/session_server.py
The `WebSocketHandler.on_message` should be overridden to prevent raising the `NotImplementedError` exception (see #1006).
=> Fix exception in session_server.py script

dependencies/Makefile.linux, dependencies/Makefile.mac, dependencies/Makefile.windows
The `make cleanse` command was failing because of this.
=> Fix Clang Format Clean

docs/reference/changelog-r2019.md, src/webots/core/WbLog.cpp, src/webots/core/WbLog.hpp, src/webots/gui/WbMainWindow.cpp, src/webots/gui/WbStreamingServer.cpp
Fix #825: store log messages emitted before WbConsole instance and print them when the GUI initialization is over.
=> Fix logging messages in the console before GUI initialization

.travis.yml, docs/guide/running-extern-robot-controllers.md, docs/guide/using-python.md, docs/reference/changelog-r2019.md, lib/.gitignore, projects/default/libraries/vehicle/Makefile, projects/robots/robotis/darwin-op/libraries/Makefile, projects/robots/robotis/darwin-op/libraries/python38/.gitignore, resources/languages/Makefile, src/packaging/files_core.txt
Use Python 3.8 (already available on Travis) for source test.
Wiki edit: https://github.com/cyberbotics/webots/wiki/Linux-Optional-Dependencies/_compare/04e9983883a1a70422bf47ecd50d33b7483dbf58...f46061464a05a0a72885a0d5a34ef716a1459a6b
=> Update Travis to Python 3.8

resources/web/wwi/Makefile
=> Fix cleanse rule if npm is not installed

scripts/preferences_cleaner/preferences_cleaner.py
=> Preferences cleaner script: Minor improvements

resources/languages/python/Makefile, resources/languages/python/controller.i
Fixed #1052 bug introduced in #1033.
Unfortunately, with this patch, swig generates `pythonXX.cpp` files that have warnings about uninitialized pointers that are later freed. However, these pointers are likely always initialized.
I had to silence this warning to make our compilation process run smoothly.
=> Fixed bug in Python API with double arrays

src/packaging/copy_msys64_files.py
The creation of the Windows package was broken when the Makefile was called locally from the MSYS console.
=> Fixed creation of package on Windows

resources/web/wwi/.gitignore, resources/web/wwi/Makefile
`webots.min.js` is a standalone library (including three.js, minified, including babel resources, etc.).
But to include it in another JS application (like the robot designer) we just need to concatenate together all the files.
=> webots.min.js: compile library as module

projects/robots/abb/irb/worlds/inverse_kinematics.wbt
Thanks to https://github.com/cyberbotics/webots/pull/1060 fix.
=> improve IK world: use a "none" controller for the root robot

resources/web/wwi/Makefile, resources/web/wwi/package.json
We merged yesterday https://github.com/cyberbotics/webots/pull/1069 to fix this issue:
https://github.com/babel/minify/issues/967
Meanwhile, `@babel/core 7.7.2` has been released to fix this issue.
The present patch removes the previous hotfix and updates the npm dependencies to a new stable state.
=> Cleaner fix for the npm dependency issue

src/webots/control/WbController.cpp, src/webots/gui/main.cpp
In some cases, Webots was unable to start because of a different version of the platform plugins. A typical case is the following:
1. I install Webots R2019b.
2. I update MSYS2 and get a new version of qt5.
3. I compile and start Webots from MSYS2.
4. I start my installed version of Webots.
5. Webots fails to start complaining it cannot load the qt platform plugin. This is because it attempts to load the new ones which were somehow cached by Qt when I launched Webots from MSYS2.
The solution is to set the `QT_QPA_PLATFORM_PLUGIN_PATH` in `main.cpp` to point to the correct location of the platform plugins (the ones compatible with the current Webots binary), before the initialization of Qt.
Once this PR is merged into the revision branch, the revision branch should be merged very carefully …
=> Fix qt platform plugin trouble

src/webots/gui/main.cpp
It was wrongly introduced in #1075.
👍
=> Removed useless include statement

docs/reference/changelog-r2019.md, src/webots/engine/WbSimulationWorld.cpp, src/webots/nodes/WbAbstractCamera.cpp, src/webots/nodes/WbAbstractCamera.hpp, src/webots/nodes/WbLidar.cpp, src/webots/nodes/WbRobot.cpp, src/webots/nodes/WbRobot.hpp
Try to fix `mirror` test error.
Change the way the cameras are rendered by looping through the robots so that the order is always the same.
Previously the order was determined by the order in which the set sampling period command was received from the controllers.
=> Fix determism in cameras rendering order

resources/web/wwi/texture_loader.js
Fix issue #1086 introduced in  #751 preventing to animate the textures by changing the transform values.
=> webots.min.js: fix texture animation in webots.min.js

src/packaging/publish_release.py
Proposal to try to ensure that the revision and develop nightly builds are always published with the "yesterday" date.
=> Proposal to improve nightly build publishing rules

resources/web/wwi/toolbar.js
If you reset the simulation while it is running, the simulation should automatically run when the reset is completed.
=> webots.min.js: Fix variable scope

src/webots/core/WbWebotsUpdateManager.cpp
Fix https://github.com/cyberbotics/webots/issues/1107
Use the GithHub release REST API: https://developer.github.com/v3/repos/releases (using raw or jsdelivr seems to be bad long term choices)
=> Switch the service to retrieve the Webots version from Cyberbotics to GitHub

docs/guide/the-user-interface.md, docs/reference/changelog-r2020.md, src/webots/gui/WbGuidedTour.cpp, src/webots/gui/WbGuidedTour.hpp, src/webots/gui/WbMainWindow.cpp
=> Move `Check for updates...` menu

docs/reference/changelog-r2019.md, projects/robots/softbank/nao/protos/Nao.proto
Reported here: https://stackoverflow.com/questions/59020010/nao-robot-sinking-into-floor-webots
Fix `Nao.selfCollision`. Internal forces were present due to the feet bounding objects causing weird shrink in floors. The touch sensors bounding objects were overlapping with the foot body.
The present Transform should be equivalent to the previous one.
=> Fix Nao.selfCollision

tests/sources/test_pep8.py
The PEP8 test is the only test that was looking for files in this folder.
This will allow us to make branches ending with `.py` (I tested on purpose with the name of this branch) and speed up the test.
=> Fixed PEP8 Test not Ignoring '.git' Folder

src/packaging/publish_release.py
Hopefully, this will help us understand why the nightly is not uploaded from Windows on revision anymore.
=> Improve nightly upload failure error message.

docs/reference/changelog-r2019.md, resources/projects/plugins/robot_windows/generic/generic.js, src/lib/Controller/api/default_robot_window.c, src/webots/gui/WbRobotWindow.cpp, src/webots/gui/WbRobotWindow.hpp
Fix #1065:
the single quote `'` and backslash `\` characters need to be escaped before sending a message to the robot window.
The single quote character in the message will interfere with the message delimiters.
The backslash character is interpreted and has to be converted to the corresponding characters to avoid it (we have similar issues when using it in a QRegularExpression).
=> Escape characters before sending message to the robot window

projects/samples/curriculum/worlds/advanced_pattern_recognition.wbt
Probably when removing the Supervisor node, the supervisor capability was set to the wrong robot causing errors when running the `curriculum/advanced_pattern_recognition.wbt` simulation.
=> Fix Robot.supervisor field value in curriculum/advanced_pattern_recognition.wbt

.appveyor.yml, include/controller/cpp/webots/Brake.hpp
In #1130, when running the AppVeyor "webots-test-sources" on the branch I got again a clang-format test failure due to a wrong style configuration.
Note that when running the "webots-test-sources-revision" the test passes and it is using the `.clang-format-9` config file:
https://github.com/cyberbotics/webots/blob/ae4db5164bd22237bf8c8861698cf12dfaeae09d/.appveyor-test-sources-scheduled.yml#L13
=> Fix clang-format config file used in AppVeyor webots-test-sources

docs/guide/lidar-sensors.md, projects/devices/sick/protos/SickLdMrs.proto, projects/samples/devices/worlds/sick_point_cloud.wbt
According [these specifications](https://cdn.sick.com/media/docs/3/03/803/Operating_instructions_LD_MRS_3D_LiDAR_sensors_en_IM0032803.PDF), the SICK LD-MRS can has supplementary and overlapping layers with a shifted and bigger range (It was not a mode of operation as I thought at first).
The current PR is about to add another internal Lidar (which can be optionally switched on) to manage this long range case.
=> SICK LD-MRS: change the way to manage the overlapping layers

resources/web/wwi/x3d.js, resources/web/wwi/x3d_scene.js
Fix #1150
Unfortunately, the Mozilla implementation of WebGL doesn't support mipmaps generation for cube textures with float 32 type, which is required for the current background algorithm.
I tested it on supported on webkit (safari, chrome, opera) and microsoft (edge) and it's working smoothly.
Removing the HDR reflections is not a big deal on Firefox, the effect is not very big in our featured worlds (robotbenchmark). Only sun reflections are less intense. This is because of the fallback using PNG in case HDR is not present:
=> HDR Reflection Fallback

docs/guide/general-faq.md
❗️This PR targets `master`.
I have now more information about the supported versions. I think it's important to document this quickly.
=> Webots >= 8.0 and < 8.4 are not supported anymore because the modules packages are currently not restored.
=> Improve doc about old license system

resources/languages/python/Makefile
Since the last clang update, `-Wno-maybe-uninitialized` has been replaced by `-Wno-uninitialized`. Lot of warnings are raised with the previous argument.
=> macOS: Fix new clang warnings coming from swig

dependencies/Makefile.mac, src/packaging/check_rpath.py
Not very important, but it's more consistent, and makes the `check_rpath.py` test happy.
Before:
```
➜  packaging git:(develop) ./check_rpath.py 
Dependency error:
- File: ./lib/webots/libssl.dylib
- Dependency: /usr/local/ssl/lib/libcrypto.1.0.0.dylib
Dependency error:
- File: ./lib/webots/libssl.1.0.0.dylib
- Dependency: /usr/local/ssl/lib/libcrypto.1.0.0.dylib
```
After:
```
➜  packaging git:(develop) ./check_rpath.py
Dylibs dependencies: ok
Frameworks dependencies: ok
```
=> macOS: Fix RPATH of openssl

src/lib/Controller/api/receiver.c
It is required to call `wb_receiver_get_queue_length()` before `wb_receiver_get_data()`, but the warning in case this is not fulfilled is cryptic: `invalid device tag`.
The aim of this PR is simply to improve this warning to be self explanatory.
=> Improved receiver warnings

src/packaging/generate_projects_files.py, src/packaging/omit_in_projects_snap.txt
The XC16 folder was not included in the latest snap released (removed manually), this PR fixes the issue once for all.
=> Avoid including XC16 in the snap release.

src/packaging/Makefile
This hack was causing problem when compiling the snap package on travis:
https://travis-ci.com/cyberbotics/webots-snap/jobs/272051733#L6574
Furthermore, removing it seems good because it remove snapcraft specific compilation instructions/code.
=> Remove Problematic xvfb Hack.

docs/reference/changelog-r2020.md, src/webots/nodes/utils/WbSupervisorUtilities.cpp
The offset is wrongly computed, probably because of the ODE rotation which is not correctly taken into account. Using `dBodyAddForceAtPos()` instead of `dBodyAddForceAtRelPos()` simplifies and fixes this issue.
=> Fix wb_supervisor_add_force_with_offset()

.travis.yml, resources/web/wwi/Makefile
Fix this error on the Travis build:
```
454Error: Package exports for '/Users/travis/build/cyberbotics/webots/resources/web/wwi/node_modules/@babel/helper-compilation-targets' do not define a '.' subpath
455    at resolveExports (internal/modules/cjs/loader.js:419:17)
456    at Function.Module._findPath (internal/modules/cjs/loader.js:492:20)
457    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:787:27)
458    at Function.Module._load (internal/modules/cjs/loader.js:693:27)
459    at Module.require (internal/modules/cjs/loader.js:864:19)
460    at require (internal/modules/cjs/helpers.js:74:18)
461    at Object.<anonymous> (/Users/travis/build/cyberbotics/webots/resources/web/wwi/node_modules/@babel/preset-env/lib/debug.js:8:33)
462    at Module._compile …
```
=> Fix Travis on macos

docs/guide/installation-procedure.md
`libjpeg8-dev` is not required anymore to compile controllers.
=> Fix Installation Instructions

projects/samples/devices/controllers/camera/camera.c, projects/samples/devices/worlds/camera_motion_blur.wbt
Given the simplicity of this simulation and the low resolution of the camera, we can afford to decrease the time step to have a better motion-blur effect.
Master:
This branch:
=> Improve Motion-Blur Sample.

docs/reference/changelog-r2020.md, src/lib/Controller/util/g_image.c
When saving a BGRA image to jpeg the resulting image was wrong, this is visible in the robot-window of the e-puck2.wbt world.
=> Fix Camera Image Save to JPEG

docs/reference/changelog-r2020.md, projects/robots/robotis/turtlebot/protos/TurtleBot3Burger.proto
the 'Maximum rotational velocity' was used to compute the maximum wheel speed instead of the 'Maximum translational velocity': http://emanual.robotis.com/docs/en/platform/turtlebot3/specifications/
Reported by a user.
=> Fixed TurtleBot3 Burger max Velocity.

docs/reference/changelog-r2020.md, projects/robots/robotis/turtlebot/protos/TurtleBot3Burger.proto
The center of mass is now in the middle of the battery at the center of the robot.
=> Fixed the Center of Mass of the TurtleBot3.

resources/web/wwi/webots.js, resources/web/wwi/x3d_scene.js
Sometimes when an web animation (in pause mode) or web simulation is loaded some texture transforms are not loaded correctly.
This happens in particular if the browser cache is empty.
But as soon as a new rendering is called (by starting the animation/simulation, moving the viewpoint, etc.) the texture appearance is correct.
I can reproduce this on my PC loading the Highway Driving benchmark page: the grass texture is sometimes not correctly scaled.
This pull-request fixes issue  #1287.
**Tasks**
Force an additional rendering 1s after the scene has been finalized.
Note that textures loading is asynchronous and could still not be completed (in particular if the browser cache is empty).
=> webots.min.js: fix texture transform not applied at load

src/webots/nodes/WbRobot.cpp
A user reported that his model was not working in the web interface once exported as x3d file. It appears that the cause of the issue was that its controller was set to `<extern>`, this was breaking the xml syntax.
The regular S/MFString are already escaped but not the controller field.
=> Fix Robot X3D export.

docs/doc.php
Fix #1296.
The code to extract queries if the version is not specified has some issues:
* `$version` is not defined 
* regular expression should be adjusted
Moreover the code to parse the query is quite complex.
Using PHP built-in functions to parse the URL and the query string it is possible to simplify it.
URL to check the functionality (after uploading the new version on the server):
https://cyberbotics.com/doc/guide/running-extern-robot-controllers?tab-os=macos&tab-language=python
=> Documentation: fix extracting tabs if version is not specified

docs/reference/changelog-r2020.md, src/webots/nodes/WbImageTexture.cpp, src/webots/nodes/WbImageTexture.hpp, src/webots/scene_tree/WbSceneTree.cpp, src/webots/scene_tree/WbSceneTree.hpp, src/webots/user_commands/WbActionManager.cpp, src/webots/user_commands/WbActionManager.hpp, src/webots/user_commands/WbContextMenuGenerator.cpp, src/webots/vrml/WbNode.cpp, src/webots/vrml/WbVrmlWriter.cpp, src/webots/vrml/WbVrmlWriter.hpp
Currently, when converting a PROTO node to base nodes all the nodes are converted.
Ideally, only the root node should be converted, the nested PROTO node should remain PROTO nodes (e.g. we don't want to unprototize all the appearance PROTO nodes of a robot PROTO when converting it).
Fix issue #1297
**Tasks**
=> Improve Convert to Base Nodes

docs/guide/web-simulation.md, resources/web/server/simulation_server.py
Using the internal list of ports in use is to pick an available port is not sufficiently robust.
The only effective and robust way to check the status of a port is to try to connect to it.
=> Simulation server script: connect to check port availability

src/webots/engine/WbSimulationWorld.cpp
The problem was reported on [stackoverflow](https://stackoverflow.com/questions/60080991/warning-qobjectstarttimer-timers-cannot-have-negative-intervals-in-webots-ro). This patch guarantees that we never pass a negative value to the `QTimer`.
=> Fixed possible warning due to negative QTimer duration

docs/guide/irb4600-40.md, docs/reference/changelog-r2020.md, projects/robots/abb/irb/controllers/inverse_kinematics/inverse_kinematics.py, projects/robots/abb/irb/protos/Irb4600-40.proto, projects/robots/abb/irb/worlds/inverse_kinematics.wbt
Adding a `staticBase` field remove the need of a useless Robot node to pin the arm to the static environment.
=> Improve ABB PROTO

projects/robots/universal_robots/controllers/universal_robots_ros/universal_robots_ros.py, tests/sources/test_license.py
This controller should use python 2.7 as ROS1 supports only python 2.7 for now.
=> Fix universal robot ros python version

projects/default/controllers/ros/RosSupervisor.cpp
Currently, if the argument of the supervisor services in ROS1 is not valid, the controller will crash.
=> Add argument check for ROS supervisor functions.

docs/guide/gripper-actuators.md
Changed palm_finger_1_joint_sensor to finger_1_joint_1_sensor in the third row of the second column, because palm_finger_1_joint_sensor was mentioned in two places.
=> Fixed a mistake in the table for IDs

dependencies/Makefile.windows, src/packaging/files_msys64.txt
MSYS2 released a new version of QtWebKit which doesn't require any more libicu64, but has new dependencies. See details here: https://github.com/msys2/MINGW-packages/issues/5934. This pull-request fixes issue #1369.
=> Updated to the latest version of MSYS2

docs/reference/changelog-r2020.md, src/webots/nodes/WbGeometry.cpp
If the collision was lasting only one time-step the bounding object color was not updated correctly.
This pull-request fixes issue #1368
=> Fixed bounding object collision color update

docs/guide/tutorial-3-appearance.md
An instruction that has been already instructed in `Tutorial 2, hands-on 4, item 2` is deleted.
Link to the changed document:
https://cyberbotics.com/doc/guide/tutorial-3-appearance?version=fix-docs-tutorial
=> Minor fix to documentation (tutorial 3)

src/webots/nodes/WbReceiver.cpp, src/webots/nodes/WbRobot.cpp, src/webots/nodes/WbRobot.hpp, src/webots/nodes/WbSensor.cpp, src/webots/nodes/WbSensor.hpp, src/webots/nodes/utils/WbMouse.cpp
Since the time is reset to 0 but the controller is not restarted, we should reset the sensor to make sure the `needToRefresh` returns true after the next step even if the sensor is not re-enabled (which is not the case since the controller is not restarted).
This pull-request fixes issue #1384
=> Fix Receiver Reset

docs/reference/changelog-r2020.md, src/webots/control/WbControlledWorld.cpp
When a controller is restarted or changed at runtime, the stdout/stderr of the last step is lost because the process is deleted before any flush.
This is reported here: https://github.com/cyberbotics/webots/issues/1384#issuecomment-589219808
=> Force stdout/stderr flush when a controller is restarted.

.travis.yml
Travis tests are currently broken because of some bug in Homebrew.
The bug was introduced in https://github.com/Homebrew/homebrew-bundle/pull/643
This is already reported on the Homebrew repository: https://github.com/Homebrew/homebrew-bundle/issues/646
And here is a thread about this in the Travis forum: https://travis-ci.community/t/macos-build-fails-because-of-homebrew-bundle-unknown-command/7296
The workaround, for now, seems to ask for a homebrew update before using it, however, this slows down quite a lot the test (~7 minutes longer, we should, therefore, remove this as soon as the Travis Image is fixed).
=> Fix macOS Travis CI

src/packaging/webots_distro.c
When we install webots of debian-package, it does not work for not exiting libxkbcommon-x11-0.
https://github.com/cyberbotics/HsWebots/runs/451825815?check_suite_focus=true#step:3:685
**Tasks**
=> Add libxkbcommon-x11-0 to dependency of debian-package

src/packaging/publish_release.py
This script often fails during the nightly builds (this night on Appveyor, and the night before on Travis).
Adding several trials for uploading the package might make the script more robust.
=> Improve Release Publisher Robustness

docs/reference/changelog-r2020.md, src/webots/nodes/WbConnector.cpp, tests/api/controllers/connector/.gitignore, tests/api/controllers/connector/Makefile, tests/api/controllers/connector/connector.c, tests/api/worlds/connector.wbt
As reported by some user, the Connector nodes were sometimes not actually moving away from each other after being detached. Setting `WorldInfo.physicsDisableTime` to `0` was fixing the problem.
Awaking both Connector nodes when detaching them from each other was indeed missing.
This PR fixes that bug.
=> Awake connectors after detach

docs/reference/robot.md, src/webots/nodes/WbRobot.cpp
Fixes #1441.
This patch will prevent Webots from crashing following the procedure described in #1441.
However, the supervisor will not be working until the world is saved and reloaded.
=> Fixed supervisor crash

docs/guide/running-extern-robot-controllers.md, lib/controller/matlab/launcher.m
The instructions for launching an extern controller in MATLAB were not correct.
Also, the test in the MATLAB launcher was broken when run with nightly builds.
Link to [documentation](https://cyberbotics.com/doc/guide/running-extern-robot-controllers?tab-language=matlab&version=fix-matlab-launcher#environment-variables).
=> Fixed MATLAB instructions for extern controllers and launcher test

src/webots/control/WbControlledWorld.cpp, src/webots/control/WbControlledWorld.hpp, src/webots/control/WbController.cpp, src/webots/control/WbController.hpp, tests/api/worlds/supervisor_reset_simulation.wbt
When the supervisor controller resetting the simulation was using a bigger step value than the world, its step was then very long because the controller 'request time' was stuck at the time before the reset.
This pull-request fixes issue #1439
=> Fix Simulation Reset Timming

docs/guide/controller-programming.md, projects/languages/ros/controllers/ros_python/runtime.ini, projects/robots/saeon/controllers/vehicle_driver_altino/runtime.ini, projects/robots/universal_robots/controllers/universal_robots_ros/runtime.ini, projects/samples/robotbenchmark/highway_driving/controllers/highway_driving/runtime.ini, projects/samples/robotbenchmark/humanoid_marathon/controllers/marathon/runtime.ini, projects/samples/robotbenchmark/inverted_pendulum/controllers/inverted_pendulum/runtime.ini, src/webots/control/WbController.cpp, src/webots/core/WbIniParser.cpp, tests/api/controllers/runtime_config_file/runtime.ini
This pull-request fixes issue #1430
https://cyberbotics.com/doc/guide/controller-programming?version=fix-runtime-ini-path-section-header-name#environment-variables
=> Fix runtime.ini path section header name

docs/reference/changelog-r2020.md, src/webots/nodes/WbBallJoint.hpp, src/webots/nodes/WbBasicJoint.hpp
Fixed crash when resetting worlds with motorized BallJoint nodes.
The BallJoint is a special case, because the motor control is not applied to the main joint but on an auxiliary joint.
This pull-request fixes issue #1454
=> Fix motorized ball joint revert

docs/reference/changelog-r2020.md, src/webots/nodes/utils/WbSupervisorUtilities.cpp
As reported by a user (https://stackoverflow.com/questions/60586220/problem-while-setting-a-specific-rotation-to-a-humanoid-robot-in-webots) if the rotation vector given to the `wb_supervisor_field_set_rotation` function is not normalized, the node was 'broken'.
Example controller:
```Python
from controller import Supervisor
supervisor = Supervisor()
timestep = int(supervisor.getBasicTimeStep())
rotation = supervisor.getFromDef('ROBOT').getField('rotation')
rotation.setSFRotation([1, 1, 0, 1.5708])
while supervisor.step(timestep) != -1:
pass
```
master:
this branch:
=> Fix Supervisor set Orientation Normalization

docs/guide/youbot.md, docs/reference/changelog-r2020.md, projects/robots/kuka/youbot/protos/Youbot.proto
This PR adds a new field to the youbot robot which allows specifying the number of arms on the robot.
For the second arm, I used the `front` prefix for the devices, but any other idea is welcome.
=> Improve youbot

docs/guide/the-scene-tree.md, docs/guide/tutorial-1-your-first-simulation-in-webots.md, docs/guide/tutorial-2-modification-of-the-environment.md
Does it make more sense this way ?
Also should we add application icons (Play - Rewind - Forward) to the documentation instead of describing how the buttons look like ?
https://cyberbotics.com/doc/guide/tutorial-1-your-first-simulation-in-webots?version=remi-cyberbotics-patch-1#extend-the-controller-to-speed-control
=> Improve tutorial documentation - adding icons - typos

src/webots/nodes/WbGeometry.cpp
This crash was caused by a rare case when a supervisor changes a procedural field, the node was regenerated and the selection was temporarily set to a node whose mesh was not yet initialized.
=> Fixed Test Suite Crash.

.travis.yml
An update of ROS melodic did break the test suite because the `rosdep` command is not available anymore.
=> Fix Test Failure rosdep Missing

projects/robots/robotis/darwin-op/libraries/Makefile
Closes #1470 
This fix will not block the make process when compiling webots with no python2.7 installed.
=> fix python2.7 should be optional to compile webots

.travis.yml
This PR updates Travis to use the latest version of Xcode.
This new version is available on Travis since two month ago: https://changelog.travis-ci.com/xcode-11-3-1-is-now-available-136765
=> Update Travis OSX Image

src/lib/Controller/api/supervisor.c
Some Supervisor function were not testing that the robot is actually a Supervisor, which was then causing issue when trying to use the return value (reported by a user on Discord today).
=> Fixed Missing Supervisor Checks.

.travis.yml
The Mac image was updated tonight to fix this issue:
https://changelog.travis-ci.com
Unfortunately, it seems it broke pip 😠
=> Remove homebrew update on Travis

projects/default/controllers/ros/RosDistanceSensor.cpp
using Ros::fixedNameString() in `RosDistanceSensor.cpp` for fixing String instead of own, faulty implementation (`.` not handled).
fixes `ros::InvalidNameException` when using `Thymio_II` with ROS: http://prntscr.com/rpzfmc
=> using Ros::fixedNameString() for fixing String in RosDistanceSensor.cpp

docs/reference/changelog-r2020.md, src/wren/DynamicMesh.cpp, src/wren/DynamicMesh.hpp
When the contact point optional rendering is enabled an OpenGL error was displayed in the console.
This was because an empty mesh was cleared and therefore the `mCoordsDirty` flag was set to true while it should not because the mesh was not changed.
This PR might also slightly improve performance (but it is difficult to measure it) since the dirty flags are not triggering useless updates anymore.
This pull-request fixes issue #1434
=> Fix OpenGL error with contact point optionnal rendering

src/webots/nodes/WbConnector.cpp
Adds call to lock()/unlock() to WbConnector::updateIsLocked()  
See #1513 
Tested on the scene where I had the issue, it works now.
=> Add lock()/unlock() call to WbConnector::updateIsLocked()

docs/reference/changelog-r2020.md, src/webots/scene_tree/WbAddNodeDialog.cpp
This was causing a crash when using the search bar of the add node dialog if the result was not giving any result in the base node but a result in the USE node.
I am seeing sporadically this bug since a very long time ago but I am happy that I finally managed to reproduce it in a 100% reproducible way.
=> Fix Add Node Dialog Crash

docs/reference/jointparameters.md, docs/reference/motor.md
- `JointParameters.md`
A space was missing in a formula and I added a link to reproduce the same structure as in the [motor](https://cyberbotics.com/doc/reference/motor) page.
- `Motor.md`
Adapt content to be the same as in [JointParameters](https://cyberbotics.com/doc/reference/jointParameters) page.
[JointParameters](https://www.cyberbotics.com/doc/reference/jointparameters?version=michou214-patch-1)
[Motor](https://www.cyberbotics.com/doc/reference/motor?version=michou214-patch-1)
=> Fix typo and add link

.travis.yml
The new image of Mac on Travis released 2 days ago is supposed to fix the pip issue: https://travis-ci.community/t/missed-pip-after-xcode-image-update/7802/6
=> Update Travis Mac Image

docs/reference/jointparameters.md
Fixes a typo in https://www.cyberbotics.com/doc/reference/jointparameters?version=master
=> Doc: Fix typo in joint parameters

projects/objects/balls/protos/SoccerBall.proto
Set the SoccerBall recognition colours so that it can be seen by camera recognition.
=> Set SoccerBall recognition colors

docs/automobile/car.md, docs/reference/changelog-r2020.md, projects/robots/saeon/protos/Altino.proto, projects/vehicles/protos/abstract/Car.proto
It is not intuitive at all to define the wheels maximum rotation speed for a car.
This pull-request fixes issue #1541.
=> Replace Car 'maxWheelVelocity' field by a 'maxVelocity' field.

src/webots/nodes/WbConnector.cpp
The calls to the lock/unlock introduced in #1518 should not occurs in the passive case otherwise they raise a warning.
=> Fix Unwanted Warning with Passive Connectors

src/packaging/webots_distro.c
Follow-up of https://github.com/cyberbotics/webots/issues/1520#issuecomment-615372716
Since this library is very small (300ko) and not easy to install on all the distributions of linux, I think we can afford to add it to the tarball package.
=> Add libpjeg to tarball package

docs/reference/changelog-r2020.md, src/webots/gui/WbSimulationView.cpp
Fixes #1572.
@DavidMansolino: could you also test it on mac OS?
The testing procedure is:
1. open Webots.
2. ensure the text editor and the scene tree have a large width.
3. hide the 3D view from the Tools menu.
4. show the 3D view again from the same menu.
On the master branch, it will not show the 3D view again.
On this branch, it should work.
=> Fixed 3D view restoration

src/webots/gui/main.cpp
Following-up some bug report by a user attempting to launch Webots from a DOS console, I found that the reference to the `qt_warning_filters.conf` was wrong because it was computed from `argv[0]` which doesn't always contain a full path on Windows, but sometimes a local path. This PR relies on `GetModuleFileName` which always returns a full path and guarantees that `qt_warning_filters.conf` is computed from an absolute path and hence is correct.
=> Fixed startup from a CMD console

src/webots/user_commands/WbActionManager.cpp
This PR fixes the Wireframe view shortcut on Mac which was not working because the shortcut was already used by a system shortcut.
This pull-request fixes issue #1555
=> Fix mac Wireframe shortcut.

Contents/Info.plist, resources/webots_classic.qss, resources/webots_dusk.qss, resources/webots_night.qss
When using the system dark mode in macOS if Webots uses the classic theme, then the GUI colors are completely broken
This pull-request fixes issue #1580
=> Fix mac classic mode.

src/lib/Controller/api/system.c, src/webots/launcher/webots-linux.sh
The Linux launcher created a predictable temporary directory in an unsafe fashion.
This pull-request solves the most critical part of #1566
**Tasks**
Check all non-standard use-cases on Linux
=> Use safe temporary directory on Linux

src/packaging/webots.desktop
Currently the `WEBOTS_HOME` on Ubuntu1804 is `/usr/local/webots`, so the icon is at `/usr/local/webots/resources/icons/core/webots.png`.
=> fix icon path

src/install_scripts/qt_linux_installer.sh
- It seems that we could not download qt from qt.org anymore, I suggest change it to https://download.qt.io/official_releases/qt/
- since change dir to `$WEBOTS_HOME/lib/webots` at [line 115](https://github.com/cyberbotics/webots/blob/08af20daa37028f1d076ba123b1d2b5fa6822d6a/src/install_scripts/qt_linux_installer.sh#L115), we should use `cd ../..` to change to `$WEBOTS_HOME`, or we could not find the target files when creating a tar.
=> fix dir to create tar and update qt download link

docs/reference/changelog-r2020.md, docs/reference/lidar.md, projects/devices/velodyne/protos/VelodyneHDL-32E.proto, projects/devices/velodyne/protos/VelodyneHDL-64E.proto
The resolution of these two lidars were not correct, only the field of view of rotating lidars should be divided but not the resolution.
This pull-request fixes issue #1628
=> Fixed resolution of Velodyne HDL-32E and HDL-64E.

resources/web/wwi/Makefile
This was causing the creation of `webots.lib.js` to fail randomly because its dependencies were not yet downloaded.
=> Fixed missing dependencies

projects/default/libraries/vehicle/python/Makefile, projects/robots/robotis/darwin-op/libraries/python/Makefile
This PR fixes the compilation of the vehicle and Darwin-op Python libraries with Python 3.8.
The warnings were not raised when compiling the libcontroller Python3.8 library because there 
`isystem` was already used to include the Python includes.
This pull-request fixes issue #1622
=> Fix macOS Python3.8 compilation warnings.

docs/reference/changelog-r2020.md, projects/languages/cpp/controllers/driver/driver.cpp, src/lib/Controller/api/supervisor.c, src/webots/maths/WbVector2.hpp, src/webots/maths/WbVector3.hpp, src/webots/nodes/utils/WbSupervisorUtilities.cpp, src/webots/scene_tree/WbVector2Editor.cpp, src/webots/scene_tree/WbVector3Editor.cpp, src/webots/vrml/WbSFVector2.cpp, src/webots/vrml/WbSFVector3.cpp
Because this value was not initialized, Webots was receiving random values here, causing random crashes of Webots (observed on Windows).
However, we should also fix Webots as it should not crash when the controller is sending bad values.
=> Fixed Webots crash

Makefile, dependencies/Makefile.mac, projects/robots/robotis/darwin-op/libraries/Makefile.mac
The `cleanse` target was not fully functional on macOS as it was leaving many non-committed files.
=> Fix macOS cleanse target

projects/samples/contests/ratslife/controllers/contest_manager/round_manager.c
gcc 10 arrived on MSYS2 and caused just one warning after a global make clean / make release.
=> Fixed buffer overflow reported by gcc 10 on Windows

docs/reference/compass.md
Fix minor spelling mistake in compass.md
[https://cyberbotics.com/doc/reference/compass?version=master](https://cyberbotics.com/doc/reference/compass?version=master)
=> Minor spelling mistake in compass.md

src/packaging/files_msys64.txt
Fix #1650.
I am setting a generic version name for this *libicu* library whose version is changing quite often, so that this bug shouldn't strike back anytime soon.
=> Fixed Windows packaging

projects/default/controllers/ros/RosSupervisor.cpp, projects/default/controllers/ros/RosSupervisor.hpp, projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_bluetooth/DeviceManager.hpp, projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_bluetooth/Wrapper.hpp, projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_wifi/DeviceManager.hpp, projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_wifi/Wrapper.hpp, projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_wifi/test.c, projects/robots/mobsya/thymio/controllers/thymio2_aseba/Thymio2Model.cpp, projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/DeviceManager.hpp, projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/FireBird6InputPacket.cpp, projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Wrapper.hpp, projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/DeviceManager.hpp, projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Wrapper.hpp, projects/robots/robotis/darwin-op/remote_control/main.cpp, projects/samples/curriculum/controllers/advanced_particle_swarm_optimization/pso.c, projects/samples/curriculum/controllers/advanced_particle_swarm_optimization_supervisor/advanced_particle_swarm_optimization_supervisor.c, projects/samples/curriculum/lib/backprop.c, resources/projects/libraries/qt_utils/motion_editor/Motion.cpp, resources/projects/libraries/qt_utils/motion_editor/MotionGlobalSettings.hpp, resources/projects/libraries/qt_utils/motion_editor/MotionPlayer.cpp, src/lib/Controller/api/motion.c, src/lib/Controller/api/robot.c, src/lib/Controller/api/scheduler.c, src/webots/core/WbTranslator.hpp, src/webots/engine/WbAnimationRecorder.cpp, src/webots/nodes/WbBaseNode.cpp, src/webots/nodes/utils/WbDictionary.hpp, src/webots/util/WbPerformanceLog.hpp, src/webots/wren/WbWrenLabelOverlay.hpp, src/webots/wren/WbWrenRenderingContext.cpp
The source tests failed last night due to an upgrade of cppcheck from version 1.9 to version 2.0 which detects more problems.
This PR fixes the source code of this repository to pass the cppcheck-2.0 tests.
=> Fix cppcheck 2.0 errors

docs/discord/update.py, docs/tests/test_hyperlinks.py, docs/tests/test_images.py, docs/tests/test_lists.py, docs/tests/test_md_files.py, docs/tests/test_menus.py, docs/tests/test_paragraphs.py, docs/tests/test_references.py, docs/tests/test_titles.py, src/packaging/copy_msys64_files.py, tests/sources/test_pep8.py
Some of the files recently committed are not python2.7 compatible
=> Fix Python2.7 Test Suite

.appveyor-build-tag.yml, .appveyor-build.yml, .appveyor-test-sources-scheduled.yml
Since a couple of days, appveyor build are broken, originally due to a general update problem and now due to a [pacman update problem](https://github.com/msys2/MSYS2-packages/issues/1967). Since it is not sure the problem will be quickly fixed on the MSYS2 side, this PR aims at patching it.
=> Fix appveyor pacman update

.github/workflows/discord_updater.yml
Since time is expressed in UTC, moved it a bit sooner to not have this event triggered at the end of the day.
=> Fix Github Action Time

docs/guide/controller-start-up.md
A few grammatical errors are committed in the documentation, which are corrected by this PR.
**Tasks**
https://cyberbotics.com/doc/guide/controller-start-up
=> Update controller-start-up.md:- Corrects a few grammatical errors

src/install_scripts/msys64_installer.sh
`pactree` moved to the `pacman-contrib` package which is now a new dependency of our distribution script.
=> Fix appveyor build

src/webots/control/WbController.cpp, src/webots/control/WbController.hpp
Fixes #1712.
Note: This is a quick & dirty fix until we introduce `Robot.controllerArgs` as a `MFString` instead of a `SFString` that will provide a much better interface.
=> Fixed controller args with double quotes

docs/guide/tutorial-2-modification-of-the-environment.md
Small typo in documentation when listing the default nodes in the tree view.
No related issues.
**Tasks**
https://cyberbotics.com/doc/guide/tutorial-2-modification-of-the-environment
=> fixed typo in hands-on #2 name

docs/guide/tutorial-1-your-first-simulation-in-webots.md
Small typo in documentation when listing the default nodes in the tree view.
No related issues.
**Tasks**
https://cyberbotics.com/doc/guide/tutorial-1-your-first-simulation-in-webots#create-a-new-world
=> corrected typo in listing of tree view nodes

projects/objects/road/protos/Crossroad.proto
The `CROSSROAD_APPEARANCE` appearance was never defined.
This was reported by a user on Discord.
=> FIx Crossroad Bottom Appearance

projects/robots/pal_robotics/tiago_extensions/protos/TiagoGripper.proto
This assignment is useless as the variable is already assigned to the empty string by default.
=> Fix Tiago Gripper

docs/guide/scenes/tiagopp/tiagopp.meta.json, docs/guide/tiagopp.md, docs/reference/changelog-r2020.md, projects/robots/pal_robotics/tiago++/protos/Tiago++.proto
The two gripper were having the same name which was causing device name conflicts.
=> Fix tiago++ Gripper Names

.github/FUNDING.yml
Cyberbotics was officially accepted for GitHub sponsor as an organization.
This PR adds Cyberbotics in the list of sponsored beneficiaries for Webots.
=> Added Cyberbotics for GitHub sponsor

src/webots/gui/WbView3D.cpp
Readd the deprecation warnings fixes that were mistakenly removed in #1754.
=> Fix Qt 5.15 deprecation warnings reintroduced during merge

src/webots/nodes/utils/WbSupervisorUtilities.cpp
Fix #1604:
in case of PROTO and nested robots, the node passed during the supervisor `C_CONFIGURE` message is a PROTO parameter instance and not the node visible in the scene tree.
But the `wb_supervisor_node_get_from_def` function (and `wb_supervisor_node_get_self`) are supposed to return by default the visible nodes and not the instances, so that changes to the node are applied correctly from the Supervisor API in the exact same way they are applied from the scene tree.
=> Fix self node in supervisor.c for a Robot proto parameter node

projects/robots/abb/irb/controllers/inverse_kinematics/inverse_kinematics.py
The library only allows to pass 3D vectors as arguments now, the orientations is handled by the second argument
Reference: https://ikpy.readthedocs.io/en/latest/chain.html#ikpy.chain.Chain.inverse_kinematics
Without this change, the corresponding controller throws the following warning
```
[inverse_kinematics] Draw a circle on the paper sheet...
[inverse_kinematics] Traceback (most recent call last):
[inverse_kinematics]   File "inverse_kinematics.py", line 100, in <module>
[inverse_kinematics]     [0, 0, 0, 1]
[inverse_kinematics]   File "F:\Programme\Anaconda3\lib\site-packages\ikpy\chain.py", line 137, in inverse_kinematics
[inverse_kinematics]     frame_target[:3, 3] = target_position
[inverse_kinematics] ValueError: cannot copy sequence with size 4 to array axis with …
```
=> Update call to ``inverse_kinematics``

docs/reference/node-chart.md
This typo was making the ElevationGrid appears as non-valid in bounding object:
https://www.cyberbotics.com/doc/reference/node-chart
New version:
https://www.cyberbotics.com/doc/reference/node-chart?version=fix-node-chart-typo
=> Fix Typo in Node-Chart

docs/guide/object-floors.md, docs/reference/changelog-r2020.md, projects/objects/floors/protos/UnevenTerrain.proto, projects/robots/micromagic/mantis/worlds/mantis.wbt, projects/robots/sphero/bb8/worlds/bb-8.wbt
There was a mismatch between the bounding object and the shape (not the same size).
Now the same ElevationGrid is used both for the shape and bounding object.
=> Fix UnevenTerrain

src/packaging/webots_distro.c
Fixes #1387.
On Windows, when uninstalling Webots, the uninstaller will remove all the files that were installed by the installer. Then, if some files remain in the Webots installation folder (because they were added or modified by the user), the uninstaller will warn the user about it and ask confirmation to delete the whole installation folder.
=> Windows uninstaller warns and delete the whole modified installation folder

src/webots/vrml/WbNode.cpp, tests/api/controllers/robot_urdf/reference_robot.urdf
Before, URDF link names were in form `[name]_[unique_id]` and now this is avoided when possible leaving only `[name]` as the URDF link name.
=> Fix URDF Link Naming

.github/workflows/tests_sources.yml, tests/sources/test_cppcheck.py
This PR creates a Github action workflow that runs the test doc at each commit/pull request.
For now, for a transitional test period, the test will be duplicated with the Travis/Appveyor ones (but this will not hurt).
Tests output: https://github.com/cyberbotics/webots/actions/runs/143593466
Note: for now Windows is not included as I am having issues installing packages with pacman.
=> Add Github Action Sources Test

src/webots/nodes/WbMesh.cpp
Fix crash of the Mesh node with some meshes (private mesh sent to support by a user).
These sometimes large buffers can overflow the stack, allocating the memory on the heap instead fix the crash.
=> Fix Mesh Node Crash

projects/languages/ros/webots_ros/src/e_puck_line.cpp, src/lib/Controller/api/remote_control.c, src/lib/Controller/api/supervisor.c, src/webots/nodes/WbDisplay.cpp, src/wren/DrawableTexture.cpp, src/wren/Font.cpp, src/wren/PostProcessingEffect.cpp
A new version of cppcheck is available on macOS with homebrew and gives new warnings:
```
projects/languages/ros/webots_ros/src/e_puck_line.cpp:580:15: style: Modulo of one is always equal to zero [moduloofone]
if (nStep % 1 == 0) {
src/lib/Controller/api/remote_control.c:68:12: warning: The address of local variable 'mandatory' might be accessed at non-zero index. [objectIndex]
if (ptr[i] == NULL)
^
src/lib/Controller/api/remote_control.c:64:28: note: Address of variable taken here.
void (**ptr)() = (void *)&remoteInterface.mandatory;
^
src/lib/Controller/api/remote_control.c:68:12: note: The address of local variable 'mandatory' might be accessed at non-zero index.
if (ptr[i] == NULL)
^
src/lib/Controller/api/supervisor.c:1362:7: style: Condition 'filename' is always …
```
=> Fix cppcheck Warnings

docs/reference/changelog-r2020.md, src/webots/nodes/WbShape.cpp, tests/api/controllers/distance_sensor_infra-red/distance_sensor_infra-red.c, tests/api/worlds/distance_sensor_infra-red_vs_transformed_planes.wbt
In the untextured case, the color (red component) was not taken into account when computing the distance of infra-red distance sensors.
=> Hotfix infra red distance sensors

docs/reference/changelog-r2020.md, src/webots/nodes/utils/WbWrenVertexArrayFrameListener.cpp, src/wren/Scene.cpp
Replaces #1834, targetting the master branch instead of develop.
Fixes #1808.
=> Fixed rendering of tracks and muscles in robot cameras (master)

.github/workflows/test_suite.yml
This dependency is not required on develop anymore.
=> Removed develop worflow dependency

dependencies/Makefile.linux
Ubuntu 20.04 is using clang-format version 10, which is not compatible with our clang-format6 configuration file, but it is with the clang-format9 one.
=> Fix Ubuntu 20.04 Clang-Format File

projects/objects/road/protos/LaneSeparation.proto, projects/robots/fp_robotics/p-rob3/protos/P-Rob3.proto, src/webots/vrml/WbField.cpp, src/webots/vrml/WbProtoModel.cpp
Fixes #1843.
This PR:
- removes some useless piece of code: we never need to write the IS keyword in a `.wbt` file.
- fixes missing warning about IS datatype mismatch for procedural protos.
It doesn't automatically fixes the backwards compatibility problem related to the controllerArgs datatype change (which should be nevertheless relatively rare).
=> Fix warning for is datatype mismatch in procedural protos

src/install_scripts/bash_profile.mac, src/install_scripts/bash_profile.windows, src/install_scripts/bashrc.linux, src/webots/app/WbPerspective.cpp, src/webots/app/WbPerspective.hpp, src/webots/gui/WbHtmlExportDialog.cpp, src/webots/gui/WbMainWindow.cpp, src/webots/gui/WbView3D.hpp, src/webots/nodes/WbLight.cpp, src/webots/nodes/utils/WbWorld.cpp
The goal of this PR is instead of providing a way to disable all the wbproj update (with the current `WEBOTS_DISABLE_SAVE_PERSPECTIVE_ON_CLOSE`), disable only those who are computer (more precisely screen) specific.
This should help us maintaining the wbproj up to date (they were updated a few weeks ago and already most of them outdated), it will also allow us to test from the test suite that they are up to date.
@cyberbotics/maintainers a few questions remains:
- should this replace `WEBOTS_DISABLE_SAVE_PERSPECTIVE_ON_CLOSE`.
- what can be a good name for this new environment variable?
- the goal yet is to disable only the window perspective update, all the rest (e.g. files open in the text editor) will be saved. Do you see something else important to disable?
=> Disable Screen Specific Perspective Save

resources/osm_importer/webots_objects/road.py
It sometimes happen that the road has no coordinate, making the importer crash.
=> FIx OSM Exporter Empty Road

docs/reference/changelog-r2020.md, docs/reference/display.md, src/webots/nodes/WbDisplay.cpp, src/webots/nodes/WbDisplay.hpp, src/webots/nodes/WbImageTexture.cpp
Fix #1329.
The crash is caused by an update of the Display's PBRAppearance triggered too early on reset just after the textures are delete, i.e. before all the references to deleted external texture are removed:
https://github.com/cyberbotics/webots/blob/master/src/webots/nodes/WbImageTexture.cpp#L308
So the fix consists in postponing the wren material updated after all the external texture references are removed.
Currently in the Display doc, it is also stated that "PBRAppearance" should not be used for Display:
https://www.cyberbotics.com/doc/reference/display#description
But this is not the case for the distributed samples (including the problematic `apartment.wbt`).
The only problem I see with the `PBRAppearance` is that the resulting displayed image colors don't match as good the …
=> Fix Display reset

src/webots/nodes/WbTransform.cpp
`translationFrom()` doesn't return correct translation when multiple nodes are involved.
**Tasks**
=> Fix Chaining URDF Link Translations

.github/workflows/test_suite.yml
Without the package update, the installation of `libpulse0` is failing.
=> Fix Github Actions

src/webots/gui/WbMainWindow.cpp
When the `WEBOTS_DISABLE_SAVE_SCREEN_PERSPECTIVE_ON_CLOSE` was set and the wbproj file was not existing an assertion was raised because the main and view window state were not defined.
=> Fix Perspective Assertion Failure

docs/reference/changelog-r2020.md, docs/reference/supervisor.md, src/lib/Controller/api/supervisor.c, tests/api/controllers/supervisor_start_stop_movie/supervisor_start_stop_movie.c
Currently, the `wb_supervisor_movie_is_ready` function requires a step to be updated, but this is often unwanted (we don't want to have to let the simulation run while waiting for the movie to be finalized).
This pull-request fixes issue #1905
=> Make wb_supervisor_movie_is_ready Function Immediate

docs/reference/changelog-r2020.md, src/webots/gui/WbVideoRecorder.cpp, src/webots/gui/WbView3D.cpp, src/webots/gui/WbView3D.hpp
Fix #1407.
Using a counter in the `WbView3D::refresh` to take a video frame is not a good idea as several events can trigger this slot, even in synchornous mode (controller, supervisor world edition, mouse, etc.).
=> Fix video recording with asynchronous controllers.

src/lib/Controller/Makefile
The Makefile automatic dependency system was broken for the libController.
For example, after recompiling the libController, if you would modify `robot_private.h` and type `make release`, it would say: `make: Nothing to be done for 'release'.` which is obviously wrong as at least `robot.c` needs to be recompiled because it includes `robot_private.h`.
This PR fixes this problem.
=> Fixed libController compilation dependencies

src/packaging/set_commit_and_date_in_version.py
This script was failing when WEBOTS_HOME was not set and not called from the script directory:
- https://github.com/cyberbotics/webots/runs/887859883?check_suite_focus=true#step:6:7
=> Fix set_commit_and_date_in_version.py

docs/reference/balljoint.md, docs/reference/hinge2joint.md
The `HingeJointParameters` node is included in the `jointParameters` field and not in the `jointParameters2` one.
=> Fix hinge2joint Documentation

docs/reference/accelerometer.md, docs/reference/changelog-r2020.md, src/webots/nodes/WbAccelerometer.cpp
Fixes #1693.
There was actually two problems:
1. If an `Accelerometer` has a parent node without a `Physics` node, it cannot determine its velocity from ODE needed to compute the acceleration and will return a wrong value. This is now fixed by displaying a warning in this case.
2. The computation of the velocity was not taking into account the complete offset of the accelerometer in case the parent node of the accelerometer was merged with an upper solid (solid merger). The computation of velocity is now based on the absolute point position instead of the wrong relative point position to work around this problem.
The code snipped provide in #1693 now returns correct values (after fixing the missing Physics node).
=> Fixed accelerometer measurements

src/packaging/publish_release.py
The tag key from the Github action contains the 'refs/tags/' prefix:
https://github.com/cyberbotics/webots/releases/tag/untagged-00a50a0e4de7ace5d9c2
=> Fix Release Tag

src/webots/gui/WbMainWindow.cpp
When creating a movie, when saving the movie a new Webots console was open.
This pull-request fixes issue #1970
=> Fix unwanted new console after creating a movie.

docs/reference/changelog-r2020.md, src/webots/nodes/WbTriangleMeshGeometry.cpp, src/webots/nodes/WbTriangleMeshGeometry.hpp, src/webots/nodes/utils/WbTriangleMesh.cpp, src/webots/nodes/utils/WbTriangleMesh.hpp
Fixes #1975.
The triangle mesh passed to ODE trimesh constructor was wrong. The number of vertices was three times too much causing ODE to read uninitialized garbage data beyond the actual vertices data, sometimes including nan values and other oddities. This was causing the AABB of the resulting mesh to be wrong, and the ODE "near" callback was never called, thus missing the collision detection.
=> Fixed random triangle mesh collision detection bug

src/webots/nodes/utils/WbSupervisorUtilities.cpp
Fix detecting self node and node from id as proto internal: this fixes issues with the `highway_overtake` and `highway_driving` reported in #1966.
Issue introduced in  #1925.
=> Fix computing if node is internal to a proto

projects/robots/abb/irb/controllers/inverse_kinematics/inverse_kinematics.py
Print a warning if the ikpy available version is too old and not compatible with the provided controller.
Following  #1782.
=> Check for ikpy version in inverse_kinematic controller

docs/guide/tutorial-8-using-ros.md
`rosdep` is not automatically installed on a fresh Ubuntu 18.04 machine and should me installed manually.
=> Add instructions to install rosdep

docs/reference/changelog-r2020.md, src/webots/gui/WbDragTransformEvent.cpp
Fix issue #2007 introduced in R2019b revision 1 (#693): when converting from WbVector3 to WbVector4 the forth value was scaled too.
=> Fixed wrong conversion from WbVector3 to WbVector4

src/lib/Controller/Makefile
Fixes #2009.
It seems the printf command is more portable than echo when it comes to prevent new lines.
=> Fixed Makefile of libController

.github/workflows/test_suite.yml, .github/workflows/tests_sources.yml
To avoid saturating the Github action, auto-cancel previous workflow when a new commit is set on a branch.
=> Add auto-cancel for source test workflow

projects/samples/devices/controllers/motor/motor.c, projects/samples/devices/worlds/motor.wbt
Fixes #1966 (last item).
The instability was due to a closed mechanical loop.
Making the box lie on a the static world (instead of the dynamics object hitting it with the needle) broke this loop and made the simulation rock stable.
=> Fixed stability of motor sample

projects/robots/festo/robotino3/protos/Robotino3.proto
The joint now match the wheel solid origin.
This pull-request fixes issue #2026
=> Fix Robotino Joint Anchors.

docs/guide/using-your-ide.md
Many users have issues when using pycharm because they do not read the documentation of extern controllers and don't set the environment variables.
So this PR aims at making more clear that also the variables requires for extern controllers have to be set when using pycharm.
https://cyberbotics.com/doc/guide/using-your-ide?version=documentation-enhacement-pycharm-instructions#run-the-controller
=> Improve instructions to use pycharm

docs/guide/using-ros.md, docs/reference/changelog-r2020.md, projects/default/Makefile, projects/vehicles/controllers/Makefile, src/packaging/exist_in_projects_mac.txt
The ros controller on Mac is crashing because of RPATH issues:
```
dyld: Library not loaded: @rpath/projects/default/libraries/ros/libroscpp.dylib
Referenced from: /Applications/Webots.app/projects/default/controllers/ros/ros
Reason: image not found
```
We can fix the RPATH fo the ros library, but since nobody is using the ros controller on Mac and we have the python external controller interface, it is probably better to drop it on macOS. @cyberbotics/maintainers do you agree?
This pull-request fixes issue #2042
=> Removed ROS controller on macOS.

src/webots/nodes/utils/WbNodeOperations.cpp
The goal of this PR is to warn the users when he is importing a 3D file that contains meshes with too many vertices.
Related to #2048
=> Add Warnings when Importing Big Meshes.

tests/api/controllers/robot_wait_for_user_input_event/robot_wait_for_user_input_event.c
The user input test was randomly failing on Windows depending on the load of the machine.
This PR increases the tolerance on this test to avoid this kind of failure.
=> Fixed user input test on Windows

docs/guide/running-extern-robot-controllers.md
C and MATLAB extern controllers on Windows don't need the `PATH` to include the `cpp` folder.
https://cyberbotics.com/doc/guide/running-extern-robot-controllers?version=hotfix-extern-controllers-setup&tab-os=windows
=> Added precision to extern controllers setup

docs/reference/changelog-r2020.md, src/webots/vrml/WbNode.cpp, tests/protos/controllers/nested_mixed_template_proto/nested_mixed_template_proto.c, tests/protos/protos/Empty.proto, tests/protos/protos/SlotWithInternalProto.proto, tests/protos/protos/SolidCylinder.proto, tests/protos/worlds/proto_nested_2.wbt
Fix #214: internal PROTO nodes are reset flags needed to correctly redirect fields.
=> Fix nested PROTO field redirection

docs/guide/starting-webots.md, src/webots/core/WbTelemetry.cpp, src/webots/gui/WbMainWindow.cpp, src/webots/gui/WbNewVersionDialog.cpp, src/webots/gui/WbPreferencesDialog.cpp, src/webots/gui/WbSingleTaskApplication.cpp
Cleanup the hyperlinks in Webots:
- remove the `www.` header.
- use the `https` protocol.
- change the newsletter subscription URL (which is broken).
=> Cleanup hyperlinks

.travis.yml, docs/guide/running-extern-robot-controllers.md, docs/guide/using-python.md, docs/reference/changelog-r2020.md, lib/controller/.gitignore, resources/languages/Makefile, resources/languages/python/Makefile, src/packaging/files_core.txt, src/webots/control/WbController.cpp
On MacOs it seems much more common to use the python version coming from Brew (e.g. GitHub action, travis, etc, all of them are using brew, and all the tutorials for installing python3 are mentioning brew).
We should probably use the brew version to compile the Webots Python 3.x API (possibly in addition to the standard Python3.x).
This pull-request fixes issue #2066
=> Add Python Brew API Compilation.

resources/web/wwi/package.json
NPM was displaying a warning on outdated packages during the build process.
This PR fixes this warning.
=> Updated NPM packages to fix build warning

docs/reference/changelog-r2020.md, resources/web/server/simulation_server.py, resources/web/wwi/server.js, resources/web/wwi/stream.js, src/webots/gui/WbMultimediaStreamingServer.cpp, src/webots/gui/WbMultimediaStreamingServer.hpp, src/webots/gui/WbStreamingServer.cpp, src/webots/gui/WbStreamingServer.hpp
Various cleanups and bug fixes for the streaming server:
=> Cleanup of the streaming server protocol

src/webots/vrml/WbProtoModel.cpp
Address  #1867: try to reduce the false positive detection of template regenerator fields.
An example are the deprecation field warnings where previously the new field "floorAppearance" was detected as regenerator just because used in the text message:
https://github.com/cyberbotics/webots/blob/323d9231584325b0da9106c2bea2f91a90199df7/projects/objects/floors/protos/RectangleArena.proto#L36-L38
=> Improve detection of PROTO template regenerator fields

src/webots/vrml/WbNode.cpp
Fix #159:
the assert was wrong and in case of PROTO it could happen that the field was not found when searching in fields instead of parameters list.
I changed the field search so that now it searches in the parameters instead of fields for PROTO nodes given that PROTO parameter changes are propagated to the internal fields but not the other way.
=> Improve update of USE nodes

docs/reference/changelog-r2020.md, projects/default/controllers/ros/RosMathUtils.cpp, src/webots/maths/WbMatrix4.cpp, src/webots/maths/WbMatrix4.hpp, src/webots/nodes/utils/WbSupervisorUtilities.cpp, tests/api/controllers/supervisor_get_position_orientation/supervisor_get_position_orientation.c, tests/api/worlds/supervisor_get_position_orientation.wbt
Fix #1993 and #1986: remove scaling factor from matrix returned by `wb_supervisor_node_get_orientation` and fix conversion from identity matrix to quaternion in `ros` default controller.
=> Fix scaled matrix returned by wb_supervisor_node_get_orientation

docs/reference/changelog-r2020.md, src/webots/nodes/WbBasicJoint.cpp, src/webots/plugins/WbPhysicsPlugin.cpp
Fix #1411: ignore solid references when computing the bounding sphere.
For the graphical functionalities it is fine if the bounding sphere doesn't include the referenced solid and for ray tracing is not a problem because the solid instance is included in a bounding sphere.
=> Fixed selection of robots with closed loop

tests/manual_tests/test_worlds_warnings.py
The current version of `test_worlds_warnings.py` only works with python >= 3.7.
There is no need to make it compatible with previous versions, but it is better to have a nice message explaining why it doesn't work.
=> Add minimum python version for test_worlds_warnings.py

docs/reference/changelog-r2020.md, src/webots/vrml/WbNode.cpp, src/webots/vrml/WbNode.hpp, src/webots/vrml/WbNodeReader.cpp, src/webots/vrml/WbNodeReader.hpp, tests/parser/expected_results.txt, tests/parser/protos/DefaultDef.proto, tests/parser/worlds/proto_default_def_parameter.wbt, tests/protos/controllers/proto_default_def_node/.gitignore, tests/protos/controllers/proto_default_def_node/Makefile, tests/protos/controllers/proto_default_def_node/proto_default_def_node.c, tests/protos/protos/DefaultDef.proto, tests/protos/worlds/proto_default_def_node.wbt
=> Fix DEF not found on load for default PROTO parameter values

resources/web/streaming_viewer/setup_viewer.js
Improve documentation of `setup_viewer.js` and explicitly unset the timeout so that the simulation is not automatically stopped when changing the broadcast value to false.
=> Add comments to setup_viewer.js

src/webots/nodes/WbSliderJoint.cpp
Before:
```
<joint name="left gripper sensor" type="prismatic">
<parent link="solid_3865"/>
<child link="left gripper"/>
<axis xyz="0 1 0"/>
<origin xyz="-0.042639 -0.007087 -0.00119" rpy="0 0 0"/>
<limit effort="57.5" lower="-0.01" upper="0.012" velocity="0.2"/>
</joint>
```
After:
```
<joint name="left gripper sensor" type="prismatic">
<parent link="solid_3865"/>
<child link="left gripper"/>
<axis xyz="0 1 0"/>
<origin xyz="-0.042639 -0.007087 -0.00119" rpy="0 0 0"/>
<limit effort="57.5" lower="-0.01" upper="0.012" velocity="0.2"/>
</joint>
```
=> Fixed indentation of the URDF export.

docs/local_exporter.py
This script was failing with `HTTPError = Forbidden` because it seems that https://cdnjs.cloudflare.com is now requesting the `User-Agent` to be set in HTTP requests.
I experienced the problem twice this morning on Windows and mac OS.
=> Fixed local_exporter script

resources/web/wwi/Makefile
Fixes #1623.
It seems that the version of npm we have on mac OS is somehow calling make again without the '+' prefix causing this problem.
I simply disabled the output of this error as I cannot fix npm.
It may be fixed with an update of npm.
=> Fixed make warning due to npm on mac OS

docs/reference/changelog-r2020.md, src/webots/control/WbController.cpp, tests/api/controllers/extern/extern.c, tests/api/worlds/extern.wbt
When a extern controller is stopped and restarted the robot-window was not linked to the new controller.
This pull-request fixes issue #2080
=> Fix robot-window not up to date.

projects/default/controllers/ros/Makefile
Fix python command in `ros` controller Makefile in case `PYTHON_COMMAND` was set.
=> Fix ros controller Makefile

docs/reference/changelog-r2020.md, projects/vehicles/plugins/robot_windows/automobile_window/Viewer.cpp
This motor is an internal motor and should not be displayed in the robot-window.
=> Hide Indicator Motor in Vehicle Robot-Window

projects/vehicles/importer_demo.sh
Fix #2173: the command `python` is not available by default on Ubuntu 20.04 (and Ubuntu 18.04).
Given that the script is not compatible with python 2.7, the used command can be changed to `python3`.
=> Fix importer_demo.sh on Linux

scripts/packaging/exist_in_projects_linux.txt
Currently the ros controller is missing from the snap package because ROS is not installed in the snap environment, this PR does not fix the issue, but makes sure that the ros controller is available in all the Linux packages.
=> Enforce check of ros controller in package

src/webots/nodes/WbJoint.hpp
This member is never assigned and is highly confusing as one can think it does represent the actual joint anchor.
=> Cleanup Unused 'mAnchor' WbJoint Member

.github/workflows/test_suite_linux.yml
Since the upload of the artifacts is sometimes failing (not very often but I saw this in one of the nightlies), it is safer to upload the release first to the github release and after to the action artifacts.
=> Improve Github Action Nightlies Stability

docs/reference/changelog-r2021.md, docs/reference/procedural-proto-nodes.md, docs/reference/worldinfo.md, resources/nodes/WorldInfo.wrl, src/webots/nodes/WbBackground.cpp, src/webots/nodes/WbCompass.cpp, src/webots/nodes/WbGps.cpp, src/webots/nodes/WbInertialUnit.cpp, src/webots/nodes/WbViewpoint.cpp, src/webots/nodes/WbWorldInfo.cpp, src/webots/nodes/WbWorldInfo.hpp, tests/api/controllers/compass/compass.c, tests/api/worlds/compass.wbt
This PR implements:  #2220
In addition, it brings several cleanups from #1643 and generalizes the coordinate system implementation (it will be extremely simple in the future to add more coordinate system).
=> EUN Coordinate System

.github/workflows/test_suite_linux.yml
It is good to make sure that these tests are run at least once per day (unlike on Travis, the nightly build will be released even if the test fails like on AppVeyor).
=> Run Test in the Github Action Nightlies

src/webots/gui/WbAboutBox.cpp
With some locale settings, the date is not displayed correctly (see https://github.com/cyberbotics/webots/pull/2223#issuecomment-693992002).
To avoid this kind of issues, the format is now hard coded in the format `MMMM dd, yyyy` (i.e. `September 17, 2020`).
=> Fix date in About box

docs/guide/web-simulation.md, resources/web/streaming_viewer/index.html, resources/web/streaming_viewer/setup_viewer.js, resources/web/streaming_viewer/style.css
Documentation for web simulation is well written, but it is missing a good quick start guide. Also, the streaming viewer does not support URLs in the format: `ws://localhost:1999/session?url=webots://github.com/cyberbotics/webots/branch/develop/projects/languages/python/worlds/example.wbt`
**Tasks**
https://cyberbotics.com/doc/guide/web-simulation?version=documentation-web-simulation-quick-start
=> Improve streaming viewer and add web simulation quick start

docs/reference/motor.md
Omitting detailed description because I think this is fairly self-explanatory.
=> docs: fix acceleration units for rotational motors

docs/reference/changelog-r2020.md, src/Controller/api/system.c
Fixed synchronization bug when starting an extern controller while specifying the `WEBOTS_PID` environment variable.
=> Fixed startup of extern controllers with WEBOTS_PID set

docs/reference/changelog-r2020.md, src/webots/gui/WbView3D.cpp, src/webots/nodes/WbRobot.cpp, src/webots/nodes/WbRobot.hpp
A user reported a bug on macOS: when pressing the <kbd>Ctrl</kbd> key in the 3D view together with another key, it was not taken into account by the keyboard API. This PR fixes that bug.
=> Fixed Ctrl key keyboard interface on macOS

docs/reference/changelog-r2020.md, src/webots/engine/WbSimulationWorld.cpp, src/webots/nodes/WbCamera.cpp, src/webots/nodes/WbDistanceSensor.cpp, src/webots/nodes/WbLightSensor.cpp, src/webots/nodes/WbRadar.cpp, src/webots/nodes/WbReceiver.cpp, src/webots/nodes/WbSolid.cpp, src/webots/nodes/WbSolid.hpp, src/webots/nodes/utils/WbObjectDetection.cpp
Fixes #2234: the animation recording system publishes the changes too early, before the Solid nodes translation and rotation field values are correctly updated.
This issue alone won't create so big position/rotation mismatches if it was not for the `WbSimulationCluster::step` that updates the Solid coordinates earlier (in the middle of the physics step) in order to update the DistanceSensor rays.
This should also be inspected, because the translation values computed when updating the rays are different from the ones at the end of the step and could lead to wrong detection.
Note that these intermediate coordinate values are not simply "one step old" values.
**Tasks**
=> Compute Animation step update after Solid coordinates have been updated

docs/reference/changelog-r2020.md, src/webots/gui/WbVideoRecorder.cpp
This bug was reported by a Discord user:
> I'm trying to record video and I'm having  an issue. The video acceleration won't let me change it from inf. I then get an error when it tries to save. Unable to parse option value "inf" as video rate.
This actually happens if the `WorldInfo.basicTimeStep` value is greater than 40.
=> Fixed movie recording when WorldInfo.basicTimeStep was greater than 40

docs/reference/changelog-r2020.md, src/webots/nodes/WbDistanceSensor.cpp
DistanceSensor rays used to disappear after the simulation reset.
Fixed #2221
=> Fix optional rendering on reset

docs/reference/supervisor.md
Fix missing field types in Supervisor documentation for the C++, Python, Java and MATLAB documentation.
Currently they are only documented in the C API.
https://www.cyberbotics.com/doc/reference/supervisor?version=documentation-fix-missing-field-types&tab-language=c++#wb_supervisor_field_get_type
=> Supervisor documentation: add missing field type values

docs/reference/worldinfo.md
Following a Discord discussion:
> yes Webots doesn't accept a CFM value negative or equal to 0 and the brackets in the documentation are wrong. But when changing it from the Webots scene tree I don't get any crash, just a warning in the console.
=> Document the limits of WorldInfo.CFM

.appveyor-build-tag.yml, .appveyor-build.yml, .appveyor-test-sources-scheduled.yml
Because some MSYS2 server is down, the AppVeyor builds fail: https://ci.appveyor.com/project/omichel/webots-master
See also https://github.com/msys2/MSYS2-packages/issues/2171
This patch temporarily fixes the problem by referring to a mirror server.
=> Fixed AppVeyor builds

docs/reference/robot.md
Before: https://cyberbotics.com/doc/reference/robot?tab-language=c#wb_robot_get_device_by_index
After: https://cyberbotics.com/doc/reference/robot?tab-language=c&version=DavidMansolino-patch-2#wb_robot_get_device_by_index
=> Fix missing function Anchor in doc

dependencies/Makefile.linux
Currently, the main build process on Linux is broken because the lua website switched from http to https only.
=> Fix lua dependency download

docs/reference/changelog-r2020.md, src/webots/launcher/launcher.c
A user reported on Discord that he was unable to open a world file that includes spaces in the path when starting Webots from a Windows DOS console. He tried several things, including adding double quotes around the world path, but that didn't work. I found that adding 3 double quotes around the world path worked, but is quite odd:
```dos
C:\Users\Olivier>"C:\Program Files\Webots\msys64\mingw64\bin\webots.exe" """C:\Program Files\Webots\projects\samples\devices\worlds\camera.wbt"""
```
This PR fixes the problem and makes that adding a single double quote around the path is sufficient, as it should be:
```dos
C:\Users\Olivier>"C:\Program Files\Webots\msys64\mingw64\bin\webots.exe" "C:\Program Files\Webots\projects\samples\devices\worlds\camera.wbt"
```
=> Fixed Webots Windows launcher to escape properly spaces in arguments

docs/reference/changelog-r2020.md, src/Controller/api/motor.c, src/webots/nodes/WbBallJoint.cpp, src/webots/nodes/WbHinge2Joint.cpp, src/webots/nodes/WbHingeJoint.cpp, src/webots/nodes/WbMotor.cpp, src/webots/nodes/WbMotor.hpp, src/webots/nodes/WbSliderJoint.cpp, tests/api/controllers/motor/motor.c
Previously, when changing the 'position' field of a joint parameter, a save and revert was required to update the motor target position, otherwise when starting the simulation the motor was pushing the joint to the 0 position again.
=> Fix Motor Target Position when Changing Joint Parameter Position

src/webots/nodes/WbBallJoint.cpp, src/webots/nodes/WbHinge2Joint.cpp, src/webots/nodes/WbHingeJoint.cpp, src/webots/nodes/WbSliderJoint.cpp
New cppcheck issues raised after merging #2326:
```
AssertionError: Cppcheck detected some errors:
src/webots/nodes/WbBallJoint.cpp:240:26: warning: Possible null pointer dereference: motor2() [nullPointer]
if (motor2() && !motor2()->isConfigureDone())
^
src/webots/nodes/WbBallJoint.cpp:241:11: warning: Possible null pointer dereference: motor2() [nullPointer]
motor2()->setTargetPosition(position2);
^
src/webots/nodes/WbBallJoint.cpp:242:26: warning: Possible null pointer dereference: motor3() [nullPointer]
if (motor3() && !motor3()->isConfigureDone())
^
src/webots/nodes/WbBallJoint.cpp:243:11: warning: Possible null pointer dereference: motor3() [nullPointer]
motor3()->setTargetPosition(position3);
^
src/webots/nodes/WbHinge2Joint.cpp:554:26: warning: Possible null …
```
=> Attempt to fix new cppcheck issues.

.appveyor-build-tag.yml, .appveyor-build.yml, .appveyor-test-sources-scheduled.yml, .appveyor.yml, .github/workflows/test_suite_linux.yml, .github/workflows/test_suite_mac.yml, .github/workflows/tests_doc.yml, .github/workflows/tests_sources.yml, .travis.yml, docs/guide/using-python.md, docs/reference/changelog-r2020.md, lib/controller/.gitignore, projects/default/libraries/vehicle/Makefile, projects/default/libraries/vehicle/python/Makefile, projects/robots/robotis/darwin-op/libraries/Makefile, projects/robots/robotis/darwin-op/libraries/python/Makefile, projects/robots/robotis/darwin-op/libraries/python39/.gitignore, resources/languages/Makefile, resources/languages/python/Makefile, scripts/install/bash_profile.windows, scripts/install/linux_optional_compilation_dependencies.sh, scripts/install/msys.sh, scripts/packaging/files_core.txt
=> Add python3.9 support

.github/workflows/test_suite_linux.yml, .travis.yml, tests/ros.sh
This PR removes the ros test on travis (as it is often making the nightly fail) and add it to Github Actions (which doesn't block the nightly if failed and use a more recent version of ROS1).
It also introduced a new tag `test ros` which allows to trigger the ros test only (or in addition to other tests).
=> Replace ros test

docs/reference/changelog-r2020.md, src/webots/scene_tree/WbSceneTree.cpp
Currently the `Help..` item is disabled in the context menu when a Recognition node is selected.
All the other nodes without WREN objects have the same issue: ContactProperties, Focus, Zoom, etc.
=> Fix enabling Help item in context menu for Recognition node

src/webots/control/WbLanguageTools.cpp
It was not possible to launch a python controller with Python 3.9.
This PR fixes the problem.
=> Fixed Python 3.9 support on Windows

docs/reference/changelog-r2020.md, src/webots/nodes/utils/WbSupervisorUtilities.cpp, src/webots/nodes/utils/WbSupervisorUtilities.hpp
Fix #2287: fix field operations order not respected in Webots.
The reason of the crash was that the INSERT operation was applied immediately and before the SET operations that were queued. As a consequence, when applied, the SET operation requests were referring to an old field pointer.
=> Fix field operations order in Webots

src/wren/demo/default.cpp
default.cpp (a demo program using wren) was not compiling because it misses one argument (the culling)
I added this last argument
=> change scene_render to correspond to prototype

docs/reference/changelog-r2020.md, src/webots/control/WbControlledWorld.cpp, src/webots/control/WbControlledWorld.hpp, src/webots/engine/WbSimulationWorld.cpp, src/webots/engine/WbSimulationWorld.hpp
Fix #2253: Webots uses too many computer resources when waiting for extern controllers (especially in run/fast mode).
This fix consists in pausing the timer that triggers the ``WbControlledWorld::step()`` if Webots is waiting for an extern controller and restart the timer when an extern controller connects.
This way the step function is not continuously called and aborted.
Another change of this PR is that a user clicks on the step button while waiting for an extern controller first connection, the step request is ignored and the step button is not grayed out (see  #2284).
This could be more intuitive and we could even print a warning in the console explaining that Webots is waiting for an extern controller.
=> Fix active loop waiting for extern controllers

src/Controller/api/supervisor.c
=> Fix argument order so `isProto()` returns `true` the node is PROTO

.github/workflows/tests_sources.yml, projects/robots/k-team/khepera1/controllers/pipe/pipe.c, projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Serial.cpp, projects/robots/softbank/nao/controllers/nao_soccer_supervisor/nao_soccer_supervisor.c, projects/samples/devices/controllers/spherical_camera/spherical_camera.c, src/webots/nodes/WbViewpoint.cpp, tests/api/controllers/gps/gps.c, tests/api/controllers/gps_coordinates_north_direction/gps_coordinates_north_direction.c
Since clang-format was updated to version 11 on Windows, the tests on appveyor are not any more passing. This PR attempts at fixing the problem.
=> Fixed clang-format 11.0.0 issues

docs/reference/changelog-r2020.md, src/Controller/api/supervisor.c, src/webots/gui/WbMainWindow.cpp, src/webots/gui/WbSimulationView.cpp, src/webots/nodes/utils/WbSupervisorUtilities.cpp, src/webots/nodes/utils/WbWorld.cpp, src/webots/nodes/utils/WbWorld.hpp
Address #2386: cancel supervisor movie recording on reset only if controllers are restarted (i.e. reset from the UI).
=> Fix movie recording behavior on simulation reset from Supervisor controller

resources/wren/shaders/pbr.frag, resources/wren/shaders/phong.frag, resources/wren/shaders/phong_stencil_ambient_emissive.frag, resources/wren/shaders/phong_stencil_diffuse_specular.frag
WebGL does not accept shaders where a float has the form 1 or 0 (instead of 1.0 and 0.0). 
I changed the float in some shaders in order for them to be compatible with WebGL
=> Modify shaders to have float in the form 1.0 and not just 1

src/wren/GlslLayout.hpp
Wren uses the size of the struct Lights to initialize the corresponding uniform buffer.
In the shaders, we redeclare this struct with the std140 layer.
However, std140 always rounds up to size of vec4 (16 bytes) but we have a vec3 (12 bytes) in the struct. (https://www.khronos.org/opengl/wiki/Interface_Block_(GLSL)#Memory_layout)
So the sizeof is short of 4 bytes compared to the size expected by GLSL.
=> Fix padding of vec3 for std140

.github/workflows/tests_doc.yml, .github/workflows/tests_sources.yml, projects/robots/abb/irb/controllers/inverse_kinematics/inverse_kinematics.py
It should be around 6 times faster now. We could run it even faster, but we need to modify the `ikpy` library.
---
The new CI skipping mechanism didn't work properly for the first commit in a PR (the first commit is always skipped). Adding `concurrent_skipping: 'false'` should fix it.
=> Improve stability and performance of the IK example

resources/wren/shaders/pbr.frag, resources/wren/shaders/pbr_stencil_ambient_emissive.frag
WebGL does not accept shaders where a float has the form 6 instead of 6.0
I changed the floats in some shaders in order for them to be compatible with WebGL
=> modify shaders to have float in the form x.0

docs/guide/installation-procedure.md
These instructions allow you to install Webots on macOS without administrator privileges (thanks to @brettle).
See https://cyberbotics.com/doc/guide/installation-procedure?version=doc-improve-mac-os-installation-instructions#installation-on-macos
=> Improve macOS installation instructions

docs/reference/camera.md, docs/reference/changelog-r2020.md, docs/reference/display.md, resources/languages/python/controller.i
Address #2441: improve documentation of the image format returned by the Camera API and how to display a Camera image in a Display.
Tasks:
_edit:_ fix free of invalid pointer in the Python API if the passed image has string format
=> Fix Python Display.imageNew and improve documentation

scripts/install/linux_compilation_dependencies.sh, scripts/install/linux_optional_compilation_dependencies.sh
Address issues with `npm` installation mentioned at https://github.com/cyberbotics/webots-snap/pull/22
default version available through apt is still depending on libssl1.0 that it is not compatible with ROS
- `zip` and `unzip` for compiling robotbenchmark and e-puck xc16
- `dirmngr` to to add the key associated with the ROS install.
=> Enhancement Linux installation scripts

resources/languages/cpp/Robot.cpp
While compiling a C++ controller from Visual C++ 2019, the following warning was displayed:
```
1>C:\Users\Olivier\AppData\Local\Programs\Webots\resources\languages\cpp\Robot.cpp(411,31): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>C:\Users\Olivier\AppData\Local\Programs\Webots\resources\languages\cpp\Robot.cpp(421,31): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
```
This PR fixes it.
=> Fixed a warning displayed by Visual C++

include/wren/texture_cubemap.h
Remove the ```wr_texture_cubemap_set_wrap_r``` function from texture_cubemap.h as there is no corresponding function in texture_cubemap.cpp or texture_cubemap.hpp
=> remove unused function

include/wren/skeleton.h, include/wren/skeleton_bone.h
Skeleton.h and Skeleton_Bone.h missed the 'H' in there header guard
=> Add a missing 'h' in the header guards

src/wren/TextureCubeMapBaker.cpp
In WebGL2, the RGB16F format is not color-renderable whereas the RGBA16F format is (https://www.khronos.org/registry/webgl/extensions/EXT_color_buffer_half_float/). I propose to replace RGB16F by RGBA16F is these two functions that I need in WebGl.
=> replace rgb16f by rgba16f in order to be compatible with webgl

.github/workflows/test_suite_mac.yml, .github/workflows/test_suite_mac_develop.yml
Since Travis is not used anymore we need to publish macOS packages from GitHub Actions
=> Publish macOS package from GitHub Action

projects/objects/kitchen/fridge/protos/Fridge.proto
The doors used to be around 100kg each
=> Reduce weight of the fridge doors

docs/reference/changelog-r2021.md, src/webots/nodes/WbBasicJoint.cpp, src/webots/nodes/WbGroup.cpp, src/webots/nodes/WbGroup.hpp, src/webots/nodes/WbSlot.cpp
Fix #2476: import even in joint is not propagated to the top robot node and the list of devices is not updated.
=> Fix updating device list after importing a joint descendant node

src/webots/nodes/WbImageTexture.cpp, src/webots/nodes/WbLight.cpp, src/webots/nodes/WbViewpoint.cpp
Added export for the ambientIntensity variable of Ligth, filtering of ImageTexture, far and ambientOcclusionRadius of Viewpoint.
The far field is called "far" and not "zFar" because the zFar field is already utilized by the current streaming viewer and it expects another default value (2000 instead of 0)
=> extends the exported fields for the stream viewer

docs/reference/changelog-r2021.md, src/webots/engine/WbSimulationCluster.cpp
Callback function `webots_physics_collide` used not to be called if `boundingObject` is a `Group` node. This PR fixes the behavior.
Fixes #2420
It also seems to be fixing #2455 (it is not crashing anymore)
**Tasks**
=> Call the physics plugin callback `webots_physics_collide` on Group node

src/webots/nodes/WbBasicJoint.cpp
Fix check for joint's parent node introduced in #2482.
Previously the test_suite was failing if Webots was compiled in debug mode.
=> Fix propagating import information to joint with slot parent

docs/reference/changelog-r2020.md, docs/reference/changelog-r2021.md
Since R2020b-rev2 is not going to be released, we need to move its change log into the one R2021a.
=> Moved R2020b-rev2 changelog into R2021a

scripts/proto_splitter/proto2multi.py
Fixed a naming bug for the generated meshes protos. It generated the names as 
`<robotName>Mesh<number>Mesh.proto`
instead of
`<robotName>Mesh<number>.proto`
Change:
Instead of creating a backup of the directory to convert, it leaves the original directory as is, and generates a new directory with the changes. For example:
```bash
python .\proto2multi.py --input=../../projects/robots
```
will convert the entire robot directory, but leave the original untouched. The converted one will be in webots/projects, next to the robot directory
=> Proto splitter script fix

resources/wren/shaders/lens_flare.frag, resources/wren/shaders/lens_flare.vert
Fixes #2528.
This is an emergency patch that fixes the compilation error of the shader. However, with this patch, the lens flare effect doesn't show up any more. The lens flare effect is anyhow broken (see #939). Therefore, I would suggest to fix it there as soon as possible.
=> Fix lens flare shader compilation failure

projects/samples/howto/controllers/vision/Makefile
OpenCV libraries on Windows MSYS2 are now more similar to ones on the Linux/mac OS as the version is not included any more in the shared library name. This actually simplifies the Makefile 😄.
=> Fixed compilation of OpenCV sample controller on Windows

src/wren/demo/Makefile, src/wren/demo/phong.cpp
The WREN demos are useful to debug WREN and to better understand it.
It's nice to have them working on Windows as well.
This PR adds support for Windows in the Makefile.
It also fixes the phong demo which was broken due to a missing shader and missing function parameter.
=> Fixed the WREN demos to run on Windows as well

projects/samples/robotbenchmark/highway_driving/worlds/highway_driving.wbt, projects/vehicles/worlds/highway_overtake.wbt
Disable shadows for the grass that could cause z-fighting issues on some particular camera settings (see #2281).
=> Improve highway grass shape

projects/samples/devices/controllers/sick/sick.c
The example was displaying many warnings in red in the console.
This was due to the return value of the lidar which can now return infinity and was not properly handled.
This PR fixes it.
=> Fix sick example after range finder behavior change (infinity return value)

docs/guide/installation-procedure.md
It is wrong, it should be like here:
https://cyberbotics.com/doc/guide/running-extern-robot-controllers?tab-os=linux#environment-variables
=> Fix controller external path for snap packages

projects/robots/universal_robots/worlds/ure.wbt
Running the `ure.wbt` shows the following error:
```
WARNING: The current physics step could not be computed correctly. Your world may be too complex. If this problem persists, try simplifying your bounding object(s), reducing the number of joints, or reducing WorldInfo.basicTimeStep.
```
=> Reduce timestep in the `ure` world to avoid warnings

resources/Makefile.include
There was a problem with the detection of Visual Studio 10 on Windows.
If it was not installed, the Makefile was setting its path to a non-existing folder instead of ignoring it.
This was breaking the compilation process in case Visual Studio 10 is not installed.
This PR fixes the problem.
=> Fixed detection of Visual Studio on Windows

projects/samples/devices/controllers/hokuyo/hokuyo.c
Fix #2563: in the VM some lidar values are NaN causing Webots to freeze when handling the `wb_display_draw_line` function.
However, on my native Ubuntu 18.04, it never occurs that lidar values are NaN.
=> Fix Webots freeze on NaN value in hokuyo.wbt

scripts/install/msys64_installer.sh
The current version of MSYS2 is somehow broken as a dependency of ffmpeg doesn't get automatically installed.
This PR fixes the problem.
I will upload a patched version of Webots R2021a for Windows on the release page to fix the problem.
=> Fixes movie creation on Windows

scripts/packaging/ffmpeg_dependencies.sh
The script will now fail if `ffmpeg` cannot be executed (because of missing DLL or so).
This would have saved us from releasing a version of Webots with broken movie creation.
=> Reinforce mjpeg dependency test

.github/workflows/test_suite_windows.yml, .github/workflows/test_suite_windows_develop.yml
The full versions of Python (e.g., 3.9.0 or 3.9.1) is hard-coded in the workflow file, which may not be a good idea as it will break the nightly build at each Python minor version. This patch fixes the problem until Python 3.9.2, but I will investigate for a better solution.
=> Fix Windows nightly builds

docs/reference/changelog-r2021.md, src/webots/gui/WbRenderingDeviceWindow.cpp, src/webots/gui/WbRenderingDeviceWindow.hpp, src/webots/nodes/WbAbstractCamera.cpp, src/webots/nodes/WbAbstractCamera.hpp, src/webots/nodes/WbCamera.cpp, src/webots/nodes/WbCamera.hpp, src/webots/nodes/WbDisplay.cpp, src/webots/nodes/WbDisplay.hpp
Fix #2585:
add methods to listen to changes in the attached camera image and request the rendering of the Display external window.
=> Fix Display external window update

docs/reference/changelog-r2021.md, src/webots/nodes/WbSolid.cpp
The reset function of WbSolid explicitly treats solids having a ballJoint parent differently from all other types of joint, suggesting that in this particular case the parent doesn't take care of it, hence it forces a manual reset of these types of Solid to their initial values.
In practice, that doesn't appear to be the case, as the reset propagates through the chain just fine:
> BallJoint::reset() ---> WbHinge2Joint::reset() ---> WbJoint::reset() ---> WbBasicJoint::reset() ---> endpoint reset (in this case, the _upper_surface_ solid)
It also explains why in issue #2539 resetting twice the steward_platform.wbt works:
- **first reset:** _upper_surface_ solid forced to its initial position, then when the rest of the chain updates it messes up (the pistons reset fine, only …
=> removal of the forced reset for solids with ballJoint parents that causes incorrect reset

docs/guide/starting-webots.md, src/webots/gui/WbSingleTaskApplication.cpp
Remove remaining "run" mode from the documented starting mode.
=> Remode deprecated run mode from instructions

docs/reference/changelog-r2021.md, src/webots/engine/WbSimulationCluster.cpp
This pull-request addresses issue #2605
The root of the problem appears to be that IndexedFaceSets are different to classic Solids with regards to ray collision. With solids like boxes and spheres there appears to be always only one point of contact (n = 1 [here](https://github.com/cyberbotics/webots/blob/3766a52ca250cc6ba41a777182a4aeb61d2d3642/src/webots/engine/WbSimulationCluster.cpp#L582-L585)) which might explain why the collision callback:
> ds->rayCollisionCallback(odeGeomData2->geometry(), o1, &contact[0].geom);
is always called with `contact[0]`. With IndexedFaceSets however there can be more, I'm not sure if more than 2 but at least 2 for a box-like shape built using IndexedFaceSets, as shown in this video. …
=> use closest contact for ray collision

docs/reference/changelog-r2021.md, src/webots/core/WbSysInfo.cpp, src/webots/core/WbSysInfo.hpp, src/webots/gui/WbView3D.cpp
Fixes #2588.
In addition to fixing #2588, this PR also removes some annoying warnings with recent Intel or AMD graphics cards which support OpenGL very well and should not cause such warnings.
Our [telemetry](https://cyberbotics.com/telemetry) reports the following GPU usage: [gpu.txt](https://github.com/cyberbotics/webots/files/5769060/gpu.txt)
=> Fix GPU tests

docs/reference/contactproperties.md
Such typos should go to the released branch, so that they appear now in the online documentation.
=> Backporting minor doc fixes from the master branch

docs/reference/changelog-r2021.md, src/wren/StaticMesh.cpp, tests/api/worlds/pen_cylinder_scaled.wbt
Fix #2628: texture coordinates for the bottom face of Cylinder where wrong.
Note: in the changelog I changed "Fix" to "Fixed" (form that we always used in the change log) for the existing entries.
=> Fix Cylinder unwrapped texture mapping

docs/reference/changelog-r2021.md, src/webots/gui/WbView3D.cpp
This pull-request relates to issue #358
As suggested in issue #358, if an external force is applied to a node without physics (typically a sensor which by default don't), and a node ancestor with physics exists, then it should be possible to apply the external force anyway.
The proposed solution goes up the chain until it finds a dynamic solid and does fix issue #358.
Currently, **it searches upwards, not sideways,** so if there's a Transform or a Group with multiple children (some with and some without physics), applying a force on a children wouldn't actually move the entire Group. (Like the stacked box/cylinder on the video)
The search can be extended sideways too, but in practice I don't really know if it's desirable because:
- If the Group/Transform …
=> Rework of external force/torque logic

docs/css/webots-doc.css, docs/guide/bioloid.md, docs/guide/debugging-c-cpp-controllers.md, docs/guide/installation-procedure.md, docs/guide/matlab.md, docs/guide/samples-devices.md, docs/guide/samples-howto.md, docs/guide/the-3d-window.md, docs/guide/the-scene-tree.md, docs/guide/tutorial-1-your-first-simulation-in-webots.md, docs/guide/tutorial-2-modification-of-the-environment.md, docs/guide/tutorial-3-appearance.md, docs/guide/tutorial-6-4-wheels-robot.md, docs/guide/using-your-ide.md, docs/reference/keyboard.md
Fixes #2640.
See the result at https://cyberbotics.com/doc/guide/the-3d-window?version=fix-documentation-keyboard-shortcuts
I also took the opportunity of this PR to fix the appearance (CSS) of the `kbd` tag (keyboard keys).
=> Fixes documentation with respect to 3D mouse controls on Mac

tests/default/controllers/test_suite_supervisor/test_suite_supervisor.py
This was causing many warnings in the log of the test suite.
=> Fixed use of deprecated API method

docs/js/showdown-extensions.js
Locally, the `setup` variable is not defined, I was getting a warning:
```
Critical: Uncaught ReferenceError: setup is not defined(%s:%u, %s)
```
=> Handle undefined `setup` variable in `showdown-extensions.js`

docs/reference/changelog-r2021.md, src/webots/nodes/WbLidar.cpp
This pull-request addresses issue #2660
After changing lidar out-of-range behavior in PR #2509, vertexes can have INF components, in which case they shouldn't be added to the mesh for rendering, as it wouldn't make much sense.
PS: As to why having a single vertex that contains an INF component in an otherwise valid cloud of points prevents all others from being drawn wasn't investigated in this PR. It's normal or should be addressed in a different issue? 
**Video**
https://user-images.githubusercontent.com/44834743/105106992-58c8c600-5ab7-11eb-813b-91c1baff1497.mp4
https://user-images.githubusercontent.com/44834743/105107008-5ebea700-5ab7-11eb-8c50-511c2afb3fbb.mp4
**Test**
Validated only on ubuntu 20.04.
=> Fix lidar point cloud visualisation issue

docs/reference/changelog-r2021.md, src/webots/nodes/WbDisplay.cpp
Display's image loaded in memory was not properly de-allocated, when the simulation is reset iteratively, the Display node increased the memory use.
=> Fix #2663 memory use on Display node

docs/reference/rangefinder.md, src/controller/python/controller.i
This PR introduces a new `data_type` keyword parameter on the `getRangeImage` method. The default value, `list`, preserves its existing behavior. The new alternative, `buffer`, returns a `bytes` object with a copy of the machine-dependent `float` buffer.
The behavior of `getRangeImageArray` is unchanged. I opted to add the new functionality to `getRangeImage` rather than `getRangeImageArray` because a byte buffer more closely resembles a 1D list than 2D. 🤷 
Fixes issue #2661. There's a full description in that issue.
API is modelled after #2321.
**Tasks**
I don't know what tasks I'm supposed to put here, but... I added the option and updated the documentation.
I have _not_ introduced a changelog entry.
This MR is sourced from my fork …
=> Expose new API for accessing RangeFinder's raw float buffer in Python

docs/reference/solid.md
Currently the documentation of the meaning of the `boundingObject` outline color is contained here:
https://www.cyberbotics.com/doc/guide/the-3d-window#selecting-an-object
but it is not easy to find.
I also added in the `Solid.boundingObject` section.
=> Add description of the boundingObject color in solid.md

docs/reference/changelog-r2021.md, src/webots/nodes/WbBaseNode.cpp
Fix #2685:
PROTO parameter nodes are not exported to X3D.
So, when exporting the DEF node id linked by a USE node, we should write the id of the first finalized (and exported) instance instead of the PROTO parameter node id.
=> Fix X3D USE node export

docs/guide/object-backgrounds.md, projects/objects/backgrounds/protos/TexturedBackground.proto
Following-up discussion in #2695.
__Note__: this `reflections` parameter is never used in the examples we distribute.
=> Removed now useless reflections parameter of the TexturedBackground proto

scripts/proto_splitter/proto2mesh.py
It sometimes happens that a face is too small (ridiculously small) to compute normals properly. In that case, we should simply remove the face from the IndexedFaceSet and run the script again. It happened twice when converting the UR5e robot (but not with the UR3e and UR10e robots).
=> Added sanity check for wrong faces in proto2mesh.py script

.github/workflows/discord_updater.yml
This PR aims at fixing a problem spotted in #2702: the update of the discord pages should target the released branch in order to be immediately displayed on cyberbotics.com web site.
=> Fixed discord updater

src/webots/control/WbControlledWorld.cpp
This is gonna be a little long winded but it's kinda necessary.
**Related issue**
This fix addresses issue #2658
**Test world**
Same as #2658, just printing to console instead of to file for simplicity. Results are the same in this case.
To summarize, the situation is :
- ROBOT_A (is a supervisor)
- has a controller `position_tracker`
- this controller spawns ROBOT_B and tracks it
- ROBOT_B (is a supervisor)
- has a controller  `dummy_controller`
- this controller applies a force to itself
After looking into it the lack of reproducibility boils down to these 2 situations that should be equal but aren't. 
**Situation (1)**
1. load scenario
2. step, step, step, step (call this output RESULTS_1)
3. reset from GUI
4. step, step, step, step (call this output RESULTS_2)
5. reset …
=> fix reproductibility issue when resetting

.github/workflows/tests_sources.yml
Any PR targeting the `released` branch should skip the source code tests as they are irrelevant and causing maintenance overhead.
See details here: https://github.community/t/how-to-ignore-branch-names-on-pull-requests/16627/5
=> Don't test source code on the released branch

docs/reference/changelog-r2021.md, src/webots/app/WbApplication.cpp, src/webots/app/WbApplication.hpp, src/webots/core/WbLog.cpp, src/webots/core/WbLog.hpp, src/webots/gui/WbMainWindow.cpp
Fixes #2671:
logs generated during world load were sent to the consoles of the previous world and thus no longer visible once the load and the new world consoles were open.
This fix consists in queuing the logs during the world load and send them to the new console once they have been opened.
=> Postpone sending logs to consoles during the world load

src/controller/c/robot.c
This PR fixes the `wb_supervisor_simulation_reset` function which crashes the controller in some cases. The controller example is here:
https://github.com/cyberbotics/webots/pull/2725#issuecomment-778678263
=> Initialize device reset callback

src/webots/core/WbHttpReply.cpp, src/webots/core/WbHttpReply.hpp, src/webots/gui/WbMultimediaStreamingServer.cpp, src/webots/gui/WbMultimediaStreamingServer.hpp, src/webots/gui/WbStreamingServer.cpp, src/webots/gui/WbStreamingServer.hpp, src/webots/gui/WbX3dStreamingServer.cpp, src/webots/gui/WbX3dStreamingServer.hpp
Webots does no check to verify if a streaming-viewer client already has an image in its cache or not.
To fix that, I implemented a simple etag mecanism.
- When webots send a file, it put the hash off the image in the etag header.
- If a browser want to query again webots about a file, it will put the hash from the etag field in the "If-None-Match" header. (this is done automatically by the browser)
- When receiving a query about a file, webots will check if their is a "If-None-Match" header and compare its content with the hash of the requested file. If the two hashes are the same, webots will answer with a 304 Not modified and not transfer the file again.
I implemented it by hand because I did not find such an preexisting option in Qt.
=> Improve webots server caching 

docs/guide/the-console.md, docs/reference/changelog-r2021.md, src/webots/control/WbControlledWorld.cpp, src/webots/control/WbControlledWorld.hpp, src/webots/control/WbController.cpp, src/webots/gui/WbMainWindow.cpp, src/webots/gui/WbSimulationView.hpp
Fixes #2709:
execute the instructions to flush the controller buffers once all the read requests are completed.
Additionally, I also fixed an issue with the step button that is not enabled after simulation reset (BUG B in #2284) if the reset button is clicked during the step computation, i.e. when the step button was disabled.
=> Fix controllers logs printed in Webots console one step too late

docs/reference/changelog-r2021.md, src/webots/nodes/WbPointSet.cpp
Fix #2752: always connect to new subnodes even if they are not valid yet.
Otherwise all the subsequent changes to the subnode won't be notified.
=> Fix update of PointSet

docs/guide/starting-webots.md, src/webots/gui/WbSingleTaskApplication.cpp
It seems we forgot in  #2286 to document this command line option from the `webots --help` message (and document it).
https://www.cyberbotics.com/doc/guide/starting-webots?version=fix-no-rendering-help
=> Add missing help for --no-rendering command line option

src/webots/nodes/WbWorldInfo.cpp
Exporting the coordinate system type was not needed in the old version of the streaming-viewer as it supported only NUE.
But as we want to support several coordinate systems in the new version, we need Webots to export it.
=> export coordinateSystem

docs/reference/changelog-r2021.md, src/webots/nodes/utils/WbPaintTexture.cpp
Fix #2757:
on simulation reset the paint data on Webots side was correctly reset, but the WREN paint texture was not cleared.
=> Clear Pen ink on simulation reset

docs/reference/balljoint.md, docs/reference/changelog-r2021.md, docs/reference/hinge2joint.md, docs/reference/hingejoint.md, docs/reference/joint.md, docs/reference/sliderjoint.md, docs/reference/solid.md
For consistency with the rest of the docs, hidden fields in joint nodes shouldn't be mentioned. The position field is visible in JointParameters and should be mentioned only there.
=> Separate visible and hidden fields more clearly in the docs

docs/reference/changelog-r2021.md, projects/samples/howto/physics/plugins/physics/flying_mybot/flying_mybot.c
Fixes #2643
Since #2505 the callback function is called for Group nodes (spaces) as well, so the ray was colliding with the Group node in the robot's body.
=> Fix physics example

scripts/packaging/files_core.txt
This should fix the failure of the nightly builds for Webots R2021b on Windows.
=> Fixes nightly builds of Webots R2021b on Windows

docs/reference/changelog-r2021.md, src/webots/vrml/WbMFNode.cpp, tests/api/controllers/robot_urdf/prob3_reference.urdf, tests/api/controllers/robot_urdf/tiago_reference.urdf, tests/api/controllers/robot_urdf/ur5e_reference.urdf
This PR should fix #2503. URDF links were not generated for the leaf nodes.
Visual inspection to check for regressions:
Visualization command (may be useful in the future):
```
ros2 launch urdf_tutorial display.launch.py model:=/tmp/robot.urdf
```
=> Fix URDF exporting of leaf nodes

docs/reference/changelog-r2021.md, resources/wren/shaders/pbr_stencil_ambient_emissive.frag, src/webots/nodes/WbViewpoint.cpp, src/webots/wren/WbWrenCamera.cpp, src/webots/wren/WbWrenShaders.cpp
This PR should eventually fix #1738.
---
Notice: I am directly accessing WREN's low-level functions (e.g. `wr_shader_program_set_custom_uniform_value`) from `WbViewpoint`. Please let me know if it is a good approach or you have some kind of convention for this kind of thing.
=> Fix wireframe rendering

docs/reference/changelog-r2021.md, docs/reference/lidar.md, src/controller/java/controller.i, src/controller/python/controller.i
Fix #2672:
overwrite default SWIG implementation of `Lidar.getLayerRangeImage` to return just part of the full image array.
This approach is the same also used for the `Lidar.getLayerPointCloud` function.
=> Fix Lidar.getLayerRangeImage returning full image on Python and Java

scripts/install/msys.sh
Python 3.9 is not yet mature enough to be used in all Webots scripts (some dependencies are missing), this PR reverts to Python 3.8.
=> Fixed default python version on Windows

Makefile
On Linux, if JAVA_HOME is not set and `javac` is not found, the following error is displayed when running the top Makefile:
```bash
readlink: missing operand
Try 'readlink --help' for more information.
```
This PR fixes this problem.
=> Fixed Makefile in case JAVA_HOME is not set and javac is not available on Linux

docs/blog/index.md
We currently miss the last post in the index: https://cyberbotics.com/doc/blog/index
This PR fixes it.
=> Fix blog index

docs/guide/using-ros.md, docs/reference/changelog-r2021.md, projects/default/controllers/ros/Makefile, projects/default/controllers/ros/Ros.cpp, projects/default/controllers/ros/Ros.hpp, projects/default/controllers/ros/RosSensor.cpp, projects/default/controllers/ros/RosSensor.hpp, projects/default/controllers/ros/highlevel/RosControl.cpp, projects/default/controllers/ros/highlevel/RosControl.hpp, projects/default/controllers/ros/highlevel/WebotsHW.cpp, projects/default/controllers/ros/highlevel/WebotsHW.hpp, projects/default/controllers/ros/highlevel/WebotsHw.cpp, projects/default/controllers/ros/highlevel/WebotsHw.hpp, projects/vehicles/controllers/ros_automobile/Makefile, scripts/install/linux_test_dependencies.sh
This PR significantly simplifies the usage of the `ros` controller:
- Integrates `ros_control` (the `--use-ros-control` flag) to allow usage of a differential drive, joint state publisher, trajectory follower, and other controllers.
- Adds the `--auto-publish` flag that automatically enables all sensors and creates necessary topics.
- Adds the `robot_description` ROS param which contains the robot's URDF (necessary for many ROS packages).
**Impact**
Take [the Pioneer controller](https://github.com/cyberbotics/webots_ros/blob/master/src/pioneer3at.cpp) from the `webots_ros` package as an example. The controller with over 300 lines of code is not needed anymore. Furthermore, to simplify the controller, we "cheated" by calculating odometry from GPS and IMU. There is no way something like …
=> Significantly simplify the usage of the `ros` controller

projects/default/controllers/ros/Ros.cpp, projects/default/controllers/ros/Ros.hpp
Since the `ros_control` needs the `robot_description` parameter it is better to load them in a different order.
=> Fix load order in the `ros` controller

.github/workflows/test_suite_linux.yml, .github/workflows/test_suite_linux_develop.yml, .github/workflows/test_suite_mac.yml, .github/workflows/test_suite_mac_develop.yml, .github/workflows/test_suite_windows.yml, .github/workflows/test_suite_windows_develop.yml, .github/workflows/tests_sources.yml
It seems that:
`https://github.com/rokroskar/workflow-run-cleanup-action/pull/14`
broke our tests.
In any case, I believe it is better to specify the version of our dependencies to be more resilient to similar issues.
=> Fix the `workflow-run-cleanup-action` version

projects/default/controllers/ros/highlevel/WebotsHW.cpp
This is an attempt to fix the ROS API compilation that fails when creating the snap package due to `isnan` not declared.
=> Fix ROS api compilation

docs/reference/worldinfo.md
The documentation of the `WorldInfo.physicsDisable*` fields was wrong.
=> Fix wrong WorldInfo.physicsDisable documentation

projects/default/controllers/ros/highlevel/RosControl.cpp, projects/default/controllers/ros/highlevel/WebotsHW.cpp, projects/default/controllers/ros/highlevel/WebotsHW.hpp
Before, `wb_motor_get_velocity` returns the same value as `wb_motor_get_max_velocity` if we are doing position control. This PR makes the `ros_control` returns the real velocity.
=> Fix `ros_control` velocity feedback

projects/robots/pal_robotics/tiago_extensions/protos/TiagoFrontArm.proto
The initial position of the `ARM_1_JOINT` joint is equal to the `minPosition`. In some scenarios, this throws out-of-bounds errors as the initial position is very close to `minPosition`.
=> Change initial position of the Tiago arm

docs/reference/changelog-r2021.md, docs/reference/robot.md, src/webots/engine/WbSimulationCluster.cpp
Currently, when `selfCollision` is active, only consecutive bodies connected by a joint are ignored. With this PR, colliding bodies connected by a chain of joints which share a common `anchor` are also ignored. For instance when using `HingeJointWithBacklash` or `Hinge2JointWithBacklash`, by construction the hidden limiting joints in these PROTOs are superposed and the presence of intermediary bodies for each triggers collisions despite not being interested in them.
=> Changed chained joints collision logic to ignore superposed joints

docs/reference/changelog-r2021.md, src/webots/vrml/WbNode.cpp, tests/api/controllers/robot_urdf/prob3_reference.urdf, tests/api/controllers/robot_urdf/tiago_reference.urdf, tests/api/controllers/robot_urdf/ur5e_reference.urdf
This PR solves the problem of inconsistent link/joint names as a suffix for non-unique names is generated from `WbNode::uniqueId()` (identifies nodes within a whole world -> if the world changes the IDs change as well).
In addition:
- a name generation is much faster as there is no recursive check and
- DEF name is also added as a fallback option (if node name is not defined).
=> Improve URDF naming convention

docs/reference/changelog-r2021.md, docs/reference/emitter.md, docs/reference/receiver.md, resources/nodes/Emitter.wrl, resources/nodes/Receiver.wrl, src/controller/c/emitter.c, src/controller/c/messages.h, src/controller/c/receiver.c, src/webots/nodes/WbEmitter.cpp, src/webots/nodes/WbEmitter.hpp, src/webots/nodes/WbReceiver.cpp, src/webots/nodes/WbReceiver.hpp
* closes 2826
Signed-off-by: Adrian Matejov <ado.matejov@gmail.com>
This feature allows to specify allowed channels for Emitter and Receiver nodes. When calling `wb_emitter_set_channel` or `wb_receiver_set_channel`, the channel is checked against allowed channels.
This pull-request fixes issue #2826 
**Tasks**
https://www.cyberbotics.com/doc/reference/emitter
https://www.cyberbotics.com/doc/reference/receiver
There are some small things that I don't know how or where to implement, so I would appreciate some advice on those :)
I'm also not that good in C++, so there might be some non-compilable mistakes there.
=> Ability to restrict Emitter/Receiver channels

projects/objects/balls/protos/RobocupSoccerBall.proto, projects/samples/contests/robocup/worlds/adult.wbt, projects/samples/contests/robocup/worlds/kid.wbt
The Robocup ball was calibrated according to the following measurements:
We recorded a shoot:
https://user-images.githubusercontent.com/1264964/111494285-a02da480-873e-11eb-882c-bbc9e3d28330.mp4
The length of the artificial grass is 1.07 m.
The initial velocity of the ball (computed on the first two frames) is 0.841 m/s.
The distance traveled is (computed) 0.621 m.
When testing in Webots, we applied a force of 3.28 N at the top of the ball, so that the initial velocity was 0.84 m/s.
The distance traveled by the simulated ball was 0.62 m.
We dropped the ball from 2 m on the artificial grass and it bounced up to about 0.5 m.
The bounce parameter in the simulation was adjusted so that when dropping the ball from 2 m, it bounced up to about 0.5 m.
=> Calibrated Robocup ball

projects/samples/contests/robocup/worlds/adult.wbt, projects/samples/contests/robocup/worlds/kid.wbt
This PR add Hinge2 joints and backlash in all Robocup worlds.
It also enable the cameras for all players, including the goal keepers for a fair performance evaluation.
=> Added backlash in robocup worlds

docs/reference/hingejointparameters.md, resources/nodes/HingeJointParameters.wrl, src/webots/nodes/WbHingeJoint.cpp, src/webots/nodes/WbHingeJointParameters.cpp
The current version loads user-defined `stopERP` and `stopCFM` correctly and also handles invalid values. However, if the world being loaded uses non-default values for global `ERP` and `CFM` (i.e not 0.2 and 1e-5), then in [this](https://github.com/cyberbotics/webots/blob/e80fb802139d4645eed30f9865017a742607c185/src/webots/nodes/WbHingeJoint.cpp#L142) line the `stopERP` and `stopCFM` actually being imposed on the joint are the default ones defined in `HingeJointParameters` [here](https://github.com/cyberbotics/webots/blob/e80fb802139d4645eed30f9865017a742607c185/resources/nodes/HingeJointParameters.wrl#L15) which could be fine as long as the global ones are also at default. If they aren't however, it doesn't respect it and imposes 0.2 and 1e-5 anyway. In other words, …
=> Fix incorrect stopCFM and stopERP imposition when world uses non-default global CFM/ERP

.github/workflows/tests_sources.yml
This is not needed and might cause maintenance problems.
=> Remove tests on Ubuntu 16.04

docs/reference/changelog-r2021.md, projects/objects/buildings/protos/RandomBuilding.proto
As discussed in #2893 (specifically [here](https://github.com/cyberbotics/webots/pull/2893#discussion_r599545236)) the `RandomBuilding` proto is supposed to generate (potentially) different buildings for every instance. As such, neither the change introduced in #2893, nor the prior state of the proto, results in the desired behavior.
=> Fix randomBuilding proto

docs/reference/robot.md
The Python API should now rely on the generic `getDevice` method.
=> Fixed documentation about getting device tags

projects/joints/protos/HingeJointWithBacklash.proto
The conditional here, as is, doesn't actually work as `startPoint` is actually a MF and can't be checked against `nil`. Irrespective of that, having the conditional to begin with is undesirable as if this block doesn't exist when loading a world, users can't add anything to the `startPoint` since no compatible nodes show up in the interface.
=> Remove conditional around startpoint for HingeJointWithBacklash

projects/samples/contests/robocup/controllers/referee/team_1.json, projects/samples/contests/robocup/controllers/referee/team_2.json
In the files provided initially, the initial pose of the robot at start of half time were invalid because they were inside the field.
=> RoboCup controllers: correction of halftimeStartingPose in config files

docs/reference/changelog-r2021.md, src/webots/gui/WbMainWindow.cpp, src/webots/gui/WbSimulationView.cpp, src/webots/nodes/WbCamera.cpp, src/webots/nodes/utils/WbObjectDetection.cpp, src/webots/nodes/utils/WbVisualBoundingSphere.cpp, src/webots/nodes/utils/WbVisualBoundingSphere.hpp
Fix #2920: fix detected object size when using the bounding sphere that was not handling the scale.
Tasks:
=> Fix camera object recognition detection using bounding sphere

docs/reference/camera.md, docs/reference/changelog-r2021.md, src/controller/java/controller.i, src/controller/python/controller.i
Fix #2922: wrong return type for `CameraRecognitionObject.get_size` in Python API.
The Java API also has some issues.
Tasks:
This is better than changing the test_references.py code because in general we want to skip h5 anchors but in this case.
=> Fix CameraRecognitionObject API in Python and Java

projects/robots/epfl/lis/controllers/blimp/js.h, projects/samples/curriculum/controllers/intermediate_behavior_based/intermediate_behavior_based.c, projects/samples/curriculum/controllers/intermediate_behavior_based/intermediate_behavior_based_corr.c, resources/projects/libraries/qt_utils/motion_editor/MotionPlayer.cpp, resources/projects/libraries/qt_utils/motion_editor/PoseWidget.cpp, src/controller/c/default_robot_window.c, src/webots/core/WbSysInfo.cpp, src/webots/gui/WbMultimediaStreamingLimiter.cpp, src/webots/nodes/WbAbstractCamera.hpp, src/webots/nodes/WbBallJoint.cpp, src/webots/nodes/WbDevice.cpp, src/webots/nodes/WbDevice.hpp, src/webots/nodes/WbDisplay.cpp, src/webots/nodes/WbLed.cpp, src/webots/nodes/utils/WbDictionary.cpp, src/webots/wren/WbWrenCamera.cpp, src/wren/PbrMaterial.cpp, src/wren/PhongMaterial.cpp, src/wren/Scene.hpp, src/wren/StaticMesh.cpp, src/wren/StaticMesh.hpp, tests/sources/test_cppcheck.py
New cppcheck errors are thrown during the macOS sources tests where the new version 2.4.1 is used.
When checking the projects sources, many `ctuOneDefinitionRuleViolation` errors are thrown because the same class name is used in many plugins and libraries for different robots.
For example the Qt robot windows of the e-puck, RobotisOP2, automobile have classes named `Viewer`.
However given that these are different programs this doesn't cause any issues and I disabled the check.
=> Fix cppcheck 2.4.1 errors

projects/robots/robotis/darwin-op/protos/Darwin-opHinge2.proto
The main parameters of the joints and motors are now accessible using local
variables (as it was done for backlash).
This change has the following impacts for all joints:
- maxTorque is slightly decrease (2.5 -> 2.3)
- maxVelocity is strongly decreased (12.26 -> 5.24)
- dampingConstant is strongly increased (0.002 -> 0.27)
- staticFriction is strongly increased (0.025 -> 0.80)
- resolution of the sensor is now limited
Impact of the behavior has been tested in the following way: on a RoboCup field,
the robot can still walk and stand-up from both side.
Note that the procedure might still evolve, but the parameters are now much closer to what should be announced by the teams for this kind of motors.
=> Updating Darwin-opHinge2.proto with virtual RoboCup procedure

tests/api/controllers/robot_urdf/robot_urdf.c
We want to get more details when URDF export is broken
=> Print generated URDF test file if test fails

src/webots/gui/WbSingleTaskApplication.cpp
On Ubuntu 16.04, Webots doesn't compile because of this variable shadowing.
Even if we don't want to support Ubuntu 16.04, I think it is anyway good to improve the variable name so that it uses a unique name.
=> Fix variable name preventing compilation

docs/reference/changelog-r2021.md, src/controller/cpp/Robot.cpp, src/controller/java/controller.i, src/controller/python/controller.i
The C++ API functions Robot::getDevice() and similar (Robot.getCamera(), Robot.getPositionSensor(), etc.) were behaving wrong as they were sending a new pointer each time they were called with the same device name as reported [here](https://github.com/RoboCup-Humanoid-TC/webots/issues/32).
This PR fixes this bug.
=> Fixed bug in Robot::getDevice()

src/webots/vrml/WbField.cpp
The proposed fix removes the connection for hidden fields, which are source of overhead in the `postPhysics` step, specifically `linearVelocity` and `angularVelocity` of solids. This solution is more proper than the one considered in #2927.
The larger issue of the overhead with nested PROTO will be addressed in that PR.
As can be seen, the saving of a world mid-execution still works as intended.
```
#VRML_SIM R2021b utf8
WorldInfo {
coordinateSystem "NUE"
}
Viewpoint {
position 0 0 1.2232405575066063
}
TexturedBackground {
}
TexturedBackgroundLight {
}
MainProtoSimple {
hidden linearVelocity_1 0 -3.9793883743761297e-10 0
hidden angularVelocity_1 0 0.2 0
condition TRUE
pos 0.7551999999333323
rot 0 1 0 0.7551974221411469
}
```
As for the performance impact, it was tested on …
=>  Remove hidden parameter field connection

resources/wren/shaders/default.frag, resources/wren/shaders/default.vert
We need to add a fragNormal output to the defaultShader.frag in order for it to be usable in WebGL.
I implemented the calculation of the fragNormal in the same way as it is in Phong.
defaultShader is use when there is no appearance or when there is a Phong appearance with a texture but not material.
However it does change a bit the rendering, especially when there is a texture. 
It does not really change when there is not texture :
Before:
After:
With a texture:
Before:
After:
With a Phong materiel (so phong shaders) to compare:
=> Enhancement defaultShader for webgl

docs/reference/changelog-r2021.md, src/webots/nodes/WbGroup.cpp, src/webots/nodes/WbSolid.cpp
This pull-request addresses issue #2963
It appears that indeed the saving of the hidden parameters for `BallJoint` wasn't working. 
Before the fix:
```
#VRML_SIM R2021a utf8
WorldInfo {
coordinateSystem "NUE"
lineScale 0.4
}
Viewpoint {
orientation -0.36364034235430376 -0.9164891884416874 -0.16677310599116954 0.9279522774354931
position -1.0729115992676148 0.5311913032755937 0.9792082997483017
}
TexturedBackground {
}
TexturedBackgroundLight {
}
RobotWithHinge2Joint {
hidden position_0_0 0.12800000000000003
hidden position2_0_0 0.25344000000000005
hidden rotation_1 0.44864394902849164 0.8918808888552964 0.05715843852666757 0.28377458981805487
}
RobotWithBallJoint {
hidden position_0_0 0.19199999999999998
hidden rotation_1 -0.436450151027134 …
```
=> Fix the saving of hidden field for BallJoint

docs/reference/changelog-r2021.md, resources/wren/shaders/lens_distortion.frag
Fix #2295 and #2934:
Camera lens distortion uses the Brown's distortion model, but there were bugs in the implementation and the center was not used for the radial and tagential components.
Additional, to apply lens distortion it is needed to apply an inverted Brown's distortion model.
Now, the distortion is correctly applied both in X and Y directions, as well as symmetrically on the right/left of the image. Here is the result using `Lens { center = [0.5, 0.5], radialCoefficients = [-0.5, 0], tangetialCoefficients = [0, 0]}`:
=> Fix Camera lens distortion

projects/samples/devices/controllers/gps_lat_long/gps_lat_long.c, src/webots/nodes/WbLidar.cpp, src/webots/nodes/utils/WbBoundingSphere.hpp, tests/api/controllers/joint_end_point_collision/joint_end_point_collision.c
A users reported a typo in the Lidar warning messages.
Same typo is found in a couple of other files.
=> Fix typo in various files

docs/reference/changelog-r2021.md, projects/devices/hokuyo/protos/HokuyoUtm30lx.proto
The verticalFieldOfView of the HokuyoUtm30lx was computed using a value for the fieldOfView that was corresponding to other Hokuyo lidars.
Datasheet : https://www.hokuyo-aut.jp/search/single.php?serial=169
Webots doc : https://www.cyberbotics.com/doc/guide/lidar-sensors#hokuyo-utm-30lx
=> Fix typo verticalfieldofview

docs/reference/changelog-r2021.md, src/webots/nodes/WbLidar.cpp, src/webots/nodes/WbLidar.hpp
Many internal structures (WREN camera, image arrays, etc.) depends on the `Lidar.type` value but the size of these structure was not updated when then `Lidar.type` was changed causing some issues in particular when switching from "rotating" to "fixed" (height and width of the lidar is bigger for the "fixed" type).
Here are some of the issues:
- crash #2982 when executing the `memset` instruction in the `WbLidar::reset` method
- wrong graphical point cloud representation
There are already a number of fields for Camera (width, height) and Lidar (fieldOfView, verticalFieldOfView, horizontalResolution, numberOfLayers) nodes whose modification is only applied after saving and reloading the world.
So the best and more consistent fix is to require saving and reloading the world also to change …
=> Fix updating Lidar.type during simulation run

docs/reference/changelog-r2021.md, src/webots/nodes/WbMatter.hpp, src/webots/nodes/WbSolid.cpp, src/webots/nodes/WbSolid.hpp, src/webots/nodes/utils/WbSupervisorUtilities.cpp, tests/api/controllers/supervisor_set_position_of_dynamic_object/supervisor_set_position_of_dynamic_object.c
Fix #2899:
Independently if the node physics is reset before or after moving it artificially with the supervisor, during the physics step ODE handles the jerk and overwrites the linear/angular velocities, etc.
The only alternative to run a simulation step between the artificial move and the physics reset, is to reset the node physics again after the ODE step computations.
Additionally I also found that the ball joint was not handled in the ODE joint physics reset.
=> Improve wb_supervisor_node_reset_physics

src/webots/vrml/WbProtoModel.cpp
Remove the blank line appearing for PROTO nodes in the small info window that appears on hover. This is done by removing the last character which is in this case always '\n' in non-empty strings.
=> Remove blank line proto info

docs/reference/changelog-r2021.md, src/webots/engine/WbSimulationWorld.cpp, src/webots/gui/WbSimulationStateIndicator.cpp, src/webots/nodes/utils/WbWorld.cpp, src/webots/util/WbPerformanceLog.cpp, src/webots/util/WbPerformanceLog.hpp
This PR adds additional info to the performance log.
Loading time options:
1. Measure time only for node structure creation
2. Entire load process (basically from [here](https://github.com/cyberbotics/webots/blob/1367ab2560688c435afa50b8713522b9897afe7c/src/webots/nodes/utils/WbWorld.cpp#L102) to [here](https://github.com/cyberbotics/webots/blob/1367ab2560688c435afa50b8713522b9897afe7c/src/webots/engine/WbSimulationWorld.cpp#L106)) including things like `handleInitialCollisions`, loading plugins, etc
The current solution corresponds to option (2)  for loading timing.
=> Add loading time and average real time factor to performance log

projects/samples/contests/robocup/controllers/player/player.cpp
Variable `rgb_image` can't be static because we want to redefine it in every new step of simulation.  
This pull-request fixes issue #3020
=> #3020: Fix bug with static variably rgb_image

resources/web/templates/x3d_playback.html, resources/web/wwi/x3d_scene.js
The labels are now send along the updates of positions/rotations/...
The labels that are set before the connection with the streaming viewer are sent with the first update.
However, it happens that this first update is droped by the streaming viewer because the scene is not fully loaded.
As labels are HTML elements, it is not a problem if some nodes or textures are not loaded, we can already draw them.
**Fix**
Instead of fully dropping an update if the scene is still loading, we drop everything but the labels.
Additionally, we restore the correct link in the animation template (the file will be changed on the server when merging)
=> Fix initial labels in streaming viewer mode

scripts/install/linux_compilation_dependencies.sh, scripts/install/linux_optional_compilation_dependencies.sh, scripts/install/linux_runtime_dependencies.sh, scripts/install/linux_test_dependencies.sh, src/controller/python/Makefile
Following the feedback in #3006, I tried to improve the Linux installation instructions:
* clearly state that automatic scripts only fully works on Ubuntu LTS
* clearly state that the `.bash` configuration should be adapted to the user system
* clearly state that on other Linux distribution python-dev package 
https://github.com/cyberbotics/webots/wiki/Linux-installation/_compare/ac6b97088b70a397ad9f1ebcd0ff0c1265c1eb54...3e45f2826bcb70df7025a7c6d75f44e30bad6d34
=> Improve Linux installation instructions

.github/workflows/test_suite_windows.yml, .github/workflows/test_suite_windows_develop.yml
Temporarily disable the broken Windows tests in case the "test suite" label is set to have more relevant tests outputs.
=> Disable broken windows tests for test suite label

projects/default/controllers/ros/Ros.cpp
Fixing a bug which affects sampling period of sensors enabled from a ROS service. Sensors enabled from ROS are publishing values based on the basic time step of the world and not on the given value when enabling the sensor. mStep was not increased in ROS::run method. Additionaly I changed mStepSize by mRobot->getBasicTimeStep() in ROS::run, when passing the elapsed time to the publishValues method. mStepSize seems to be always equal to 1, even if the basic time step is bigger than 1ms.
None (Discord discussion)
**Tasks**
None
None
Bug was discovered while creating a VIO module using ROS environment.
=> Added mStep increment in ros.cpp

docs/guide/controller-plugin.md
The path to the e-puck sample in the "Controller Plugins" section of the user guide is incorrect
https://www.cyberbotics.com/doc/guide/controller-plugin?version=master
=> Fix path to the e-puck remote_controls sample

docs/reference/changelog-r2021.md, src/webots/nodes/utils/WbNodeUtilities.cpp
Webots crashed when we were inserting a solidReference and the top node of this solidReference was a transform or a group.
For example: Transform->Solid->HingeJoint->SolidReference.
With the introduction in developp of the possibility to introduce robots in transform, Webots would crash if we inserted the Shrimp robot in a transform.
CAUSE: to get the top solid, Webots was retrieving the top node and casting it to solid. But in the case of a group or transform as the top node, it would fail.
FIX: instead of retrieving the top node, we retrieve the uppest solid.
This pull-request fixes issue #3037
=> Fix crash solidReference

resources/projects/plugins/robot_windows/generic/Makefile
The MATLAB controllers crash in the _develop_ branch, because they fail to load `lib/controller/libgeneric_robot_window.so`  from `resources/projects/plugins/robot_windows/generic/libgeneric.so`.
This pull-request fixes issue #2996.
**Tasks**
This has been solved by adding `lib/controller` in the rpath of `libgeneric.so`.
=> Fix crash Matlab controller

resources/lua/modules/webots/wbgeometry.lua, resources/lua/modules/webots/wblimits.lua, resources/lua/modules/webots/wbrotation.lua
The `wbrotation.equal` function refers to non-existing variables instead of function arguments. 
Also fixes some trailing spaces present in these modules.
Not sure if it warrants a changelog entry, none of the PROTO is using it and if nobody reported it so far probably doesn't have much use.
=> Fix wrong  implementation of `wbrotation.equal` in LUA module

src/webots/nodes/WbRenderingDevice.cpp
Fixes the mentioned in the https://github.com/cyberbotics/webots/pull/3032#pullrequestreview-657983394 comment. Probably the Camera was affected as well.
**Steps to reproduce**
Compared to the steps explained in the comment we should be more aggressive to reproduce the crash almost every time:
- open `range_finder.wbt`
- start the simulation
- change the RangeFinder image width and height to 1000
- change the RangeFinder.spherical value to TRUE
The `WbRenderingDevice` doesn't support changing the camera resolution at runtime. However, changing the `spherical` parameter fires an event that setups the `WbRenderingDevice` again. Setting up the `WbRenderingDevice` with the new resolution during the runtime crashes the simulation.
I am not sure whether the bug is present …
=> Fix crash after camera spherical change

docs/guide/hinge-2-joint-with-backlash.md, docs/guide/hinge-joint-with-backlash.md, projects/joints/protos/Hinge2JointWithBacklash.proto, projects/joints/protos/HingeJointWithBacklash.proto
As reported by a Robocup user (Uli), the default mass used in the intermediary solids of the `HingeJointWithBacklash` and `Hinge2JointWithBacklash` might be too small for most use-cases and could lead to instabilities.
=> Increase default mass for intemediary solids in `HingeJointWithBacklash` and `Hinge2JointWithBacklash`

src/webots/maths/WbPrecision.hpp
See https://github.com/RoboCup-Humanoid-TC/webots/pull/112
Apparently this include is needed on some systems.
=> Fixed compilation problem in WbPrecision.hpp

docs/reference/changelog-r2021.md, docs/reference/distancesensor.md, resources/nodes/DistanceSensor.wrl, src/webots/nodes/WbDistanceSensor.cpp, src/webots/nodes/WbDistanceSensor.hpp
Allows tuning of red color sensitivity of infra-red distance sensor with a new property `redColorSensitivity`. It's a floating point number, with default value 1 it will behave like before, with value 0 the red color sensitivity will be completely disabled.
**Tasks**
https://cyberbotics.com/doc/reference/distancesensor?version=develop
This is my first PR to Webots and I may not know all the things that have to be done.
Should I update the changelog file?
Should I include controller method to get the new property (`wb_distance_sensor_get_red_color_sensitivity`)?
=> Allow tuning red color sensitivity of infra-red distance sensor

src/webots/gui/WbMainWindow.cpp
Add a missing break statement.
Otherwise on Windows displaying we run the default statement, which raise an assert.
=> Fix potential crash on Windows

docs/reference/changelog-r2021.md, include/wren/static_mesh.h, src/webots/nodes/WbGeometry.cpp, src/webots/scene_tree/WbNodeEditor.cpp, src/wren/StaticMesh.cpp
The triangle count for `Mesh`/`IndexedFaceSet` shows `0` when there is too many triangles. 
This is because the count function relies on the size of the `triangles` vector from the `wren`. However, the renderer currently does not  display shadows  for meshes with more than (2^16-1)/3 triangles, to avoid an overflow of the index. Thus the `triangles` vector is empty.
This PR instead directly use the `indexCount` (divided by 3) to get the number of triangles. Also, it displays `(no shadow)` next to the number of triangles if it is beyond the limit for which Webots casts shadows.
**Linked PR**
[Enhancement display triangles geometry node](https://github.com/cyberbotics/webots/pull/1456)
=> Fix triangle count

projects/default/controllers/ros/Ros.cpp
Incrementing `mStep` in the #3040 made the `ros` controller wait for the `time_step` service by default instead of running normally. This PR reverts the behavior, but I am not sure what was the purpose of the `mStep != 0` in the first place.
=> Run Webots step() in ROS controller by default

scripts/packaging/sync_controller_lib.sh
According to the discussion, I have changed the name of the `webots-controller` repository to match better its purpose.
In addition, the PR fixes the branch naming (removes spaces).
=> Rename `webots-controller` to `webots-libcontroller`

include/controller/c/webots/robot.h
Change macro definition to use a do{}while(0) construct
In particular, it avoid duplicate `wb_robot_step(d)`
Note that modern compiler recognize do{}while(0) construct and optimize it away without emitting extra code.
=> Change macro definition

resources/web/wwi/Parser.js, resources/web/wwi/nodes/wb_preferences.js, src/webots/nodes/WbViewpoint.cpp, src/wren/Scene.cpp
Fix the naming of the `far` variable according to x3d.
Fix the far calculation in wrenjs
This pull-request fixes issue #2501
=> fix far webotsjs

docs/guide/robotis-op2.md, docs/guide/robotis-op3.md, docs/guide/tutorial-6-4-wheels-robot.md, docs/js/showdown-extensions.js, docs/reference/connector.md, docs/reference/display.md, docs/reference/lightsensor.md, docs/tests/test_references.py
The `slugify` function used in `showdown-extension-js` to create the documentation HTML code doesn't match the one used in the documentation tests.
As a result wrong anchors that won't work in the documentation are passing the tests instead of the correct ones.
In particular there are issues with text in parenthesis.
Also `showdown-extensions.js` doesn't properly convert the `+` symbols in its slugify function but just the first occurrence.
=> Fix mismatch between slugify function in documentation test

docs/guide/running-extern-robot-controllers.md, src/controller/cpp/Makefile, src/controller/python/Makefile
We add the `rpath` to better support a dynamic library loading in Python. Otherwise, we have to configure `LD_LIBRARY_PATH` before the `python3 myscript.py` call.
Unfortunately, this works fine only for Linux. For macOS, it may be possible (https://longwei.github.io/rpath_origin/), but Windows doesn't support `rpath` at all (https://stackoverflow.com/questions/42497999/build-project-with-libraries-in-other-directories-windows-mingw).
=> Improve controller linking

resources/web/wwi/WebotsStreaming.js, src/webots/gui/WbStreamingServer.cpp
Add the following API functions to the WebotsStreaming webcomponent:
- HideToolbar
- ShowToolbar
- SendMessage: allow the user to send message through the websocket, to play, pause, change the controller,...
An example of usage is present here:  https://cyberbotics1.epfl.ch/open-roberta
with the configuration file here : https://cyberbotics1.epfl.ch/open-roberta/setup_viewer.js
=> Feature api webcomponent

docs/reference/changelog-r2021.md, src/controller/python/Makefile, src/controller/python/controller.i
Replaces #3103 aiming at the develop branch instead of the master branch.
> Fixes #2057. Comes at the cost of potentially increased overhead. See http://swig.10945.n7.nabble.com/How-to-release-Python-GIL-tp5027p5029.html
=> Release python global interpreter lock when running c++ code

src/webots/Makefile
I am getting the following error on CentOS 7:
```
/lukic1/webots/lib/webots/libode.so: error: undefined reference to 'pthread_mutex_trylock'
/lukic1/webots/lib/webots/libode.so: error: undefined reference to 'pthread_create'
/lukic1/webots/lib/webots/libode.so: error: undefined reference to 'pthread_spin_init'
collect2: error: ld returned 1 exit status
make[1]: *** [../../bin/webots-bin] Error 1
make: *** [webots_target] Error 2
```
I know we don't support CentOS, but it shouldn't affect the other platforms
=> Fix CentOS compilation

scripts/packaging/files_msys64.txt
It seems the libzzip DLL was renamed (again) breaking the distribution (nightly builds) on Windows:
```
Error on line 21620 in D:\a\webots\webots\scripts\packaging\webots.iss: Source file "D:\a\_temp\msys\msys64\mingw64\bin\libzzip-0.dll" does not exist.
```
This PR fixes the problem.
=> Fixes Windows nightly builds

projects/guided_tour.txt, projects/robots/robotis/darwin-op/worlds/soccer.wbt, projects/robots/softbank/nao/worlds/nao_room.wbt
I propose to improve the guided tour by :
- Replacing the nao_demo.wbt by nao_room.wbt. They have both a nao with the same controller, but the room world is nicer than a simple floor.
- Modernizing the soccer.wbt by changing the field for the new one made for robocup.
Old:
New:
Old:
New:
=> Enhancement guided tour

resources/Makefile.include
This `$(var)` variable is not defined and seems useless.
=> Removed use of undefined variable

projects/robots/mir/mir100/protos/Mir100.proto, projects/robots/mir/mir100/worlds/mir100.wbt
World-update test fails on develop because the `keybody_controller` is already the default controller in the PROTO so no need to have it in the world as well.
=> Fix world update error Mir100

src/controller/matlab/Makefile
It seems that `which python` is not available by default on ubuntu 20.
We should use `which python3` instead, moreover it is more pertinent as the mgenerate.py script is not compatible with python 2.7.
=> fix matlab makefile

resources/web/wwi/WebotsStreaming.js
Since `document.getElementsByTagName('webots-streaming')[0]` does not exist before creating the dom element, this throws errors when creating it with javascript via `document.createElement('webots-streaming')`. 
Instead use `this`, since it is in almost all cases the same as `document.getElementsByTagName('webots-streaming')[0]`.
=> Make WebotsStreaming createable by javascript

.github/workflows/test_suite_windows_develop.yml, .github/workflows/tests_sources.yml
As we removed `nodejs` from the develop branch, we need to modfiy the github action that target develop.
=> fix nightly build on windows develop

docs/reference/viewpoint.md, scripts/converter/convert_eun_to_nue.py, scripts/converter/convert_nue_to_enu.py
Added the conversion of the `Viewpoint` in the scripts to convert the `coordinateSystem` of a world.
**Tasks**
Note: if no `orientation`/`position` are given, it will adopt the `Viewpoint` as seen from a `NUE` world with the default Webots parameters. So for EUN-->NUE nothing is done, and for NUE-->ENU the default Viewpoint is adapted.
=> Added Viewpoint in world converter scripts

resources/web/templates/x3d_playback.html, resources/web/wwi/WebotsAnimation.js
Fix the size of the animation to 100% of the web-component. 
It was necessary to also set the width to 100% to allow both `flex` and `block` display to work.
The user can know determine the size of the web-component by changing it in the .html.
Fix #3159.
=> Fix size animation web component
