- projects/robots/festo/robotino3/worlds/robotino3.wbt
Fixes world update test on the develop branch: https://github.com/cyberbotics/webots/runs/1495907044?check_suite_focus=true
> Fixed world updatest on develop branch (robotino3.wbt)

- projects/default/libraries/vehicle/java/Makefile
- resources/languages/java/Makefile
Follow-up of the discussion in #2494.
> Fix Java Makefiles on master branch

- docs/reference/camera.md
Following a discussion on Discord, I believe it's good to add this precision to the documentation.
> Added warning about performance of getImageArray

- src/webots/editor/WbBuildEditor.cpp
> Clear console on make clean

- lib/controller/matlab/wb_inertial_unit_get_lookup_table.m
- lib/controller/matlab/wb_supervisor_node_get_velocity.m
- src/controller/matlab/mgenerate.py
> Fix pointer in Matlab API

- .github/workflows/test_suite_windows.yml
- .github/workflows/test_suite_windows_develop.yml
- .github/workflows/tests_sources.yml
This PR back ports the Windows workflow files from the develop branch to the master branch to fix the Windows nightly builds.
> Fix Windows nightly builds

- src/controller/java/controller.i
> Fix Java controllers

- src/controller/python/controller.i
> Fix `position_sensor.getMotor()`

- src/controller/python/controller.i
> Fix Python2 support

- scripts/packaging/publish_release.py
Fixes the creation of a non-draft prerelease for nightly build.
> Fix nightly builds on master

- scripts/packaging/publish_release.py
Fixes the creation of a non-draft prerelease for nightly build (develop branch).
> Attempt to fix the nightly builds (develop branch)

- projects/default/controllers/ros/RosSpeaker.cpp
> Fix ROS speaker service mismatch

- scripts/packaging/files_core.txt
> Include resources/web/wwi GIF images in package

- projects/guided_tour.txt
- projects/robots/clearpath/moose/controllers/moose_path_following/moose_path_following.c
- projects/samples/devices/worlds/.hokuyo.wbproj
- projects/samples/devices/worlds/.sick.wbproj
- projects/vehicles/worlds/.city.wbproj
> Minor fixes to the distributed simulations

- projects/samples/howto/controllers/ziegler_nichols/ziegler_nichols.c
- src/webots/scene_tree/WbNodeEditor.cpp
It seems GitHub updated their mac OS in the CI with a new version of ccpcheck and new warnings...
We have to fix our code accordingly.
> Fix new cppcheck warnings

- Contents/Info.plist
- docs/js/showdown-extensions.js
- resources/version.txt
- scripts/packaging/webots_version.txt
- src/webots/core/WbApplicationInfo.cpp
> Increase Webots version to R2021a rev1

- .github/workflows/test_suite_windows.yml
- .github/workflows/test_suite_windows_develop.yml
This should save us from updating the workflow file each time a new version of Python is released.
> Automatic detection of Python path in Windows CI

- scripts/install/bashrc.linux
> Fixed overwriting of LD_LIBRARY_PATH

- resources/translations/wb_de.ts
- resources/translations/wb_es.ts
- resources/translations/wb_fr.ts
- resources/translations/wb_generic.ts
- resources/translations/wb_it.ts
- resources/translations/wb_ja_JP.ts
- resources/translations/wb_zh_CN.ts
Translations files have been manually updated by typing the following commands in the `resources/translations` folder because they are currently not correctly updated from the main Makefile:
```
make clean
make update
```
I also updated the instructions in the release procedure wiki page to make sure that they are regenerated
https://github.com/cyberbotics/webots/wiki/Release-Procedure
> Regenerate translations files

- docs/automobile/cpp-java-and-python-wrappers-of-the-automobile-libraries.md
https://cyberbotics.com/doc/automobile/cpp-java-and-python-wrappers-of-the-automobile-libraries?version=documentation-driver-classpath
> Add CLASSPATH explanation for the automobile library

- resources/projects/plugins/robot_windows/generic/generic.js
Fixes gyro unit in robot window.
> Fixes unit for gyro in robot window

- docs/reference/contactproperties.md
> Fixed minor typo

- src/webots/core/WbSysInfo.cpp
Compilation fails without the header, since it's missing I presume the debug line slipped through.
> fix compilation error

- docs/reference/changelog-r2021.md
- src/webots/launcher/launcher.c
- src/webots/launcher/webots-linux.sh
> Fixed high DPI support on Windows and Linux

- docs/guide/tutorial-1-your-first-simulation-in-webots.md
There is no "Alt" key on US Macs.
> Added "option key on Mac" instead of Alt key

- docs/guide/the-user-interface.md
Minor layout issue.
https://cyberbotics.com/doc/guide/the-user-interface?version=doc-layout-indent
I took advantage of this PR to improve the documentation of normals display.
> Fixed wrong indent

- tests/sources/test_license.py
This PR aims at fixing the source test failure on the license year.
> Fixed license year in source test

- docs/guide/spot.md
This question is getting more and more asked by users.
> FAQ on Spot SDK

- src/webots/nodes/WbBackground.cpp
> Fixed Background irradiance when no colormap is set

- README.md
We don't use AppVeyor or Travis any more.
> Remove obsolete badges

- tests/api/controllers/robot_urdf/prob3_reference.urdf
- tests/api/controllers/robot_urdf/tiago_reference.urdf
- tests/api/controllers/robot_urdf/ur5e_reference.urdf
The node ids changed in this test world after the UR5e model changed.
> Fixed URDF test which was broken by new UR5e model

- .github/workflows/test_suite_windows.yml
- .github/workflows/test_suite_windows_develop.yml
Add Windows tests to GitHub Action:
> Build Windows package if test suite label is set

- docs/reference/changelog-r2021.md
- projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/Makefile
- projects/robots/nex/plugins/robot_windows/fire_bird_6_window/Makefile
- projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/Makefile
- projects/vehicles/controllers/racing_wheel/Makefile
- projects/vehicles/plugins/robot_windows/automobile_window/Makefile
- resources/projects/libraries/qt_utils/Makefile
- resources/projects/plugins/robot_windows/generic_window/Makefile
- src/webots/control/WbControlledWorld.cpp
Fixes  #2717: add link to folder containing the Qt libraries on Windows
> Fix link to Qt libraries on Windows

- src/webots/gui/WbX3dStreamingServer.cpp
- src/webots/gui/WbX3dStreamingServer.hpp
Remove variable that is useless since #2713
> Cleanup unused variable

- docs/guide/preferences.md
> Improved documentation

- .github/workflows/tests_sources.yml
- docs/guide/preferences.md
- docs/guide/spot.md
Fix (again) many conflicts with the webots github URL changes.
> Merge released into master

- projects/samples/howto/openai_gym/worlds/openai_gym.wbt
Fix indentation and fields order in `openai_gym.wbt`.
> Fix openai_gym.wbt

- src/webots/nodes/WbWorldInfo.cpp
Export basicTimeStep which is needed in the streaming-viewer for the viewpoint to correctly follow objects
> export basictimestep

- docs/reference/changelog-r2021.md
- src/webots/launcher/launcher.c
> Fixed handling of UTF-8 paths for world files opened from Windows GUI

- src/ode/ode/src/joints/transmission.cpp
Clean up and minor fix of transmission ode joint. 
PS: no other change appears to have occurred to transmission joint since ode fork.
> minor fix and cleanup of transmission ode joint 

- projects/samples/howto/openai_gym/worlds/openai_gym.wbt
This is making the nightly world update test fail: https://github.com/cyberbotics/webots/runs/1906940169?check_suite_focus=true#logs
Feel free to edit/merge this PR.
P.S: note that the ros test is also failing during installation since a while: https://github.com/cyberbotics/webots/runs/1906940068?check_suite_focus=true
> Fix fields order in openai_gym.wbt

- docs/reference/changelog-r2021.md
- lib/controller/matlab/wb_supervisor_node_get_velocity.m
Fix #2764: fix the wrong size when converting the C vector to Matlab.
> Fix vector size

- .github/workflows/test_suite_linux.yml
- .github/workflows/test_suite_linux_develop.yml
This is a backport from #2740, it fixes #2759 on the master branch.
> Fix ROS tests

- projects/robots/robotis/turtlebot/controllers/turtlebot3_ostacle_avoidance/turtlebot3_ostacle_avoidance.c
TurtleBot3 Burger controller was failing due to wrong handling of infinite values.
> Fix TurtleBot3 controller

- docs/reference/changelog-r2021.md
- src/webots/engine/WbSimulationCluster.cpp
- src/webots/engine/WbSimulationCluster.hpp
Moves #2775 to the master branch (fixes #2775).
> Fix Physics plugin collision for the Group nodes

- docs/reference/changelog-r2021.md
> Add missing changelog entry for Gears proto

- docs/reference/changelog-r2021.md
- include/controller/c/webots/utils/system.h
- projects/robots/gctronic/e-puck/plugins/robot_windows/e-puck/e-puck.c
- src/controller/c/g_pipe.c
- src/controller/c/robot.c
- src/controller/c/scheduler.c
- src/controller/c/system.c
> Fixed extern controller startup

- docs/reference/changelog-r2021.md
- projects/objects/traffic/protos/PedestrianCrossing.proto
Fix #2855: update the `PedestrianCrossing` PROTO following #2364.
> Fix PedestrianCrossing PROTO

- docs/reference/proto-design-guidelines.md
We have to describe special cases for the PROTO translation field.
> Improved PROTO design rules documentation

- docs/reference/proto-design-guidelines.md
This PR recommends the FLU orientation for new PROTOs.
> Recommend FLU orientation for new PROTOs

- docs/reference/changelog-r2021.md
- src/webots/nodes/WbCharger.cpp
Address #2843: remove reset of Charger energy to 0 if the robot battery is full.
> Improve Charger energy update when robot battery is full

- projects/samples/contests/robocup/worlds/adult.wbt
- projects/samples/contests/robocup/worlds/kid.wbt
This PR fixes the foot-grass friction which was too slippery.
> Fixed foot-grass friction in Robocup

- docs/reference/procedural-proto-nodes.md
- projects/bounding_objects/protos/PipeBoundingObject.proto
- projects/joints/protos/Hinge2JointWithBacklash.proto
- projects/joints/protos/HingeJointWithBacklash.proto
- projects/objects/buildings/protos/RandomBuilding.proto
- projects/objects/buildings/protos/SimpleBuilding.proto
- projects/objects/solids/protos/SolidPipe.proto
- projects/objects/street_furniture/protos/PublicToilet.proto
- projects/objects/traffic/protos/DirectionPanel.proto
- projects/objects/trees/protos/Forest.proto
- tests/protos/protos/TemplateTexture.proto
This PR verifies if the use of randomness in PROTO is justified and if the current tags are appropriate.
> Replace unnecessary randomness in PROTO

- docs/reference/supervisor.md
> Fixed typo in documentation

- projects/humans/c3d/plugins/robot_windows/c3d_viewer_window/c3d_viewer_window.css
- projects/humans/c3d/plugins/robot_windows/c3d_viewer_window/c3d_viewer_window.html
- projects/humans/c3d/plugins/robot_windows/c3d_viewer_window/c3d_viewer_window.js
- resources/projects/plugins/robot_windows/generic/device_widget.js
- resources/projects/plugins/robot_windows/generic/generic.css
- resources/projects/plugins/robot_windows/generic/generic.js
- resources/projects/plugins/robot_windows/generic/plot_widget.js
- resources/projects/plugins/robot_windows/generic/radar_widget.js
- resources/projects/plugins/robot_windows/generic/timeplot_widget.js
Follow-up #2854 and update the c3d robot window and fix some remaining bugs:
* 3D plot labels not updated if the timeplot is not selected
* PlotWidget and RadarWidget brackground not correctly set to white
* Timeplot graphs redrawn even if nothing changed
> Update c3d robot window

- docs/guide/pioneer-3dx.md
Fixed minor spelling errors on the Pioneer-3DX doc page.
No related issues
**Tasks**
None
https://cyberbotics.com/doc/guide/pioneer-3dx?version=doggo4242:patch-1
N/A
N/A
> Minor spelling fixes on Pioneer-3DX doc page.

- projects/robots/pal_robotics/tiago_base/protos/TiagoBase.proto
- projects/robots/pal_robotics/tiago_extensions/protos/TiagoFrontArm.proto
- projects/robots/pal_robotics/tiago_steel/worlds/tiago_steel.wbt
This PR introduces the following improvements:
1. Fixes #2910
2. Decreases `softCFM` so the robot sinks less into the ground
> Calibrate the Tiago robot and simulation

- src/webots/gui/WbSingleTaskApplication.cpp
- src/webots/maths/WbVector3.hpp
- src/webots/maths/WbVector4.hpp
- src/webots/nodes/WbBallJoint.hpp
- src/webots/nodes/WbBasicJoint.hpp
- src/webots/nodes/WbHinge2Joint.hpp
- src/webots/nodes/WbHingeJoint.hpp
- src/webots/nodes/WbShape.cpp
- src/webots/nodes/WbSliderJoint.hpp
- src/webots/nodes/utils/WbNodeUtilities.cpp
I missed some steps from the `preFinalize` stage and translation fields have never been updated. It should be fine now:
> Fix joint positions in URDF CLI export

- src/webots/gui/WbSingleTaskApplication.cpp
The description is here https://github.com/cyberbotics/webots/pull/2954#pullrequestreview-633190208
> Fix CLI URDF node search

- docs/guide/starting-webots.md
https://cyberbotics.com/doc/guide/starting-webots?version=R2021a
> add command to set WEBOTS_SAFE_MODE in windows

- docs/guide/controller-programming.md
> Fixed C++ include in the doc

- scripts/packaging/publish_release.py
> Fix publish release script

- docs/discord/development-2021.md
- docs/discord/documentation.md
- docs/discord/news.md
- docs/discord/technical-questions-2021.md
- docs/guide/controller-programming.md
- docs/guide/starting-webots.md
> Merge released branch into master branch

- docs/guide/youbot.md
Fix underscore not escaped in youBot documentation.
> Fix library name in youBot documentation

- .github/workflows/test_suite_linux.yml
- .github/workflows/test_suite_linux_develop.yml
> Fix Linux Build

- docs/reference/accelerometer.md
- docs/reference/distancesensor.md
- docs/reference/gyro.md
> Improve description of resolution field

- docs/guide/hinge-joint-with-backlash.md
> Wrong backlash default value in the docs

- docs/reference/changelog-r2021.md
Coupled motors feature was missing the changelog entry.
> Fix missing coupled motors changelog entry

- projects/robots/universal_robots/worlds/ure.wbt
> Fix typo in ure.wbt info

- projects/samples/devices/worlds/coupled_motors.wbt
> Fix test world update for `coupled_motors.wbt` sample world

- .github/workflows/test_suite_linux.yml
- .github/workflows/test_suite_linux_develop.yml
- .github/workflows/test_suite_mac.yml
- .github/workflows/test_suite_mac_develop.yml
- .github/workflows/test_suite_windows.yml
- .github/workflows/test_suite_windows_develop.yml
- scripts/packaging/sync_controller_lib.sh
We need C/C++ libs to build the new `webots_ros2` interface:
https://github.com/cyberbotics/webots_ros2/pull/221
> Publish Webots controller to independent repository

- dependencies/Makefile.linux
- docs/reference/changelog-r2021.md
- scripts/install/qt_linux_installer.sh
- scripts/install/qt_windows_installer.sh
- src/webots/Makefile
- src/webots/core/WbTemplateEngine.cpp
- src/webots/gui/WbMainWindow.cpp
Upgrade Qt to 5.15.2 under linux and add Qml module needed for #3087.
> Upgrade to Qt 5.15.2 on linux and add Qml module

- docs/reference/changelog-r2021.md
- src/webots/nodes/WbSolid.cpp
Fix #3041: fix use of invalid solid merger.
> Hotfix crash due to relative velocities viewer

- docs/reference/connector.md
fix https://github.com/cyberbotics/webots/issues/3094
> Fix missmatching tag between text and image

- docs/reference/changelog-r2021.md
- src/ode/ode/src/collision_cylinder_box.cpp
Fixes #2947
Before:
https://user-images.githubusercontent.com/2135826/119970315-dc3b7c00-bfaf-11eb-85fe-516c6b6973ff.mp4
Now:
https://user-images.githubusercontent.com/2135826/119970325-de9dd600-bfaf-11eb-94cc-f90ca325d568.mp4
> Fix box-cylinder collision

- resources/web/streaming_viewer/index.html
- resources/web/wwi/Parser.js
- resources/web/wwi/Selector.js
- resources/web/wwi/nodes/WbAppearance.js
- resources/web/wwi/nodes/WbBillboard.js
- resources/web/wwi/nodes/WbGeometry.js
- resources/web/wwi/nodes/WbGroup.js
- resources/web/wwi/nodes/WbPBRAppearance.js
- resources/web/wwi/nodes/WbShape.js
- resources/web/wwi/nodes/WbTransform.js
- resources/web/wwi/nodes/WbViewpoint.js
- resources/web/wwi/nodes/WbWorld.js
- resources/web/wwi/nodes/utils/utils.js
- resources/web/wwi/wren/WbWrenRenderingContext.js
- src/webots/nodes/WbBillboard.cpp
- src/webots/nodes/utils/WbNodeUtilities.cpp
Add support for the billboard node in animations.
> Enhancement billboard web

- resources/nodes/Robot.wrl
Removed outdated description of the `Robot` node.
This pull-request fixes issue #3115
Related pull-request: #2749
> Update Robot node description

- src/controller/c/supervisor.c
Some small memory chunks for strings were allocated but not free as they should.
This PR fixes 3 different leaks.
> Fixed several memory leaks in supervisor API

- resources/web/wwi/Server.js
- resources/web/wwi/WebotsStreaming.js
- resources/web/wwi/webots.js
- Remove unused variables of webots
- Add some api functions to webots-streaming
> cleanup webotsjs api

- docs/guide/scenes/mir100/mir100.meta.json
- scripts/web_component_studio/components.json
I added a description of the mir100 and the ned in the `components.json` file such that we are now able to automatically regenerate them (it will be useful in #2787). 
Moreover, the visualization of the ned in the docs was not updated for the new version version of the viewer and was not working anymore on develop. This PR correct that.
You can see the result here:
-  ned: https://cyberbotics.com/doc/guide/ned?version=docs-generate-mir-ned
- mir100: https://cyberbotics.com/doc/guide/mir100?version=docs-generate-mir-ned
> Generate mir100 and ned web robots components.

- docs/guide/actuators.md
- docs/guide/robots.md
- docs/guide/sensors.md
> Fix link to Contact Us section in documentation

- resources/web/wwi/WebotsAnimation.js
- resources/web/wwi/WebotsStreaming.js
Remove unused `div` in the streaming web component and change the animation component according to #3142
> cleanup web components

- tests/test_suite.py
Dummy branch to figure out why test suite step fails in CI (passes locally) despite passing all the tests.
> Fix `test suite` CI on ubuntu 18

- projects/robots/abb/irb/controllers/inverse_kinematics/inverse_kinematics.py
Inverse kinematics example had a typo
> EDIT: Changed apparent typo in active_link_mask

- docs/reference/billboard.md
> Fix reference to Shape documentation page

- resources/repo.txt
- resources/web/wwi/webots.js
Update the position and the size of the labels when resizing the window
> Resize labels on window resize

- .github/workflows/test_suite_linux.yml
- .github/workflows/test_suite_linux_develop.yml
- scripts/install/linux_test_dependencies.sh
- scripts/install/msys64_installer.sh
Apply the same workflows to master branch as well, as done in develop in #3173
> Fix `test ros` on master

- docs/reference/changelog-r2021.md
- src/webots/scene_tree/WbVelocityViewer.cpp
Allows to easily monitor the displacement speed of a robot with changing direction
> Display the magnitude of linear and rotationnal speed

- docs/reference/changelog-r2021.md
> Added the altimeter to the change log

- projects/humans/pedestrian/protos/Pedestrian.proto
Fixes #3250. After the fix:
https://user-images.githubusercontent.com/44834743/123965003-53e83680-d9b4-11eb-8515-013dab360f58.mp4
> Fix unmoving pedestrians

- projects/samples/howto/cylinder_stack/controllers/contact_points_supervisor/contact_points_supervisor.c
- projects/samples/robotbenchmark/highway_driving/controllers/highway_driving_benchmark/highway_driving_benchmark.py
- projects/samples/robotbenchmark/obstacle_avoidance/controllers/supervisor/supervisor.py
Fixes #3248. I didn't find other instances.
> Remove deprecated functions from samples

- resources/projects/plugins/robot_windows/generic/window_manager.js
> Fix errors in settings tab of generic robot window

- projects/objects/robotstadium/protos/RobotstadiumGoal.proto
Ditto. Fixes: https://github.com/cyberbotics/webots/issues/3287#issuecomment-872906344
> Fix bad url for robostadium net

- projects/samples/robotbenchmark/humanoid_marathon/worlds/humanoid_marathon.wbt
> Fixed bad texture URL

- docs/reference/index.md
> Fixed discrepancy between guide and reference manual

- projects/guided_tour.txt
- projects/robots/k-team/khepera3/worlds/khepera3_gripper.wbt
- projects/robots/universal_robots/worlds/ure.wbt
Fixes https://github.com/cyberbotics/webots/issues/3276 for worlds: `khepera3gripper.wbt`, `ure.wbt`, `hoap2_walk.wbt`
> Adjust parameters of guided tour

- projects/guided_tour.txt
Ditto. Fixes https://github.com/cyberbotics/webots/issues/3278.
> Add missing devices in guided tour

- docs/guide/scenes/fabtino/fabtino.meta.json
- projects/robots/rec/fabtino/protos/Fabtino.proto
Correct name fields in Fabtino.proto (fixes #3321 and #3324)
> Fix names in proto

- projects/samples/howto/Makefile
> Fixed missing binary controller

- docs/guide/tutorial-8-using-ros.md
In ROS instructions, set `noetic` as default and get rid of `kinetic`. (Issue #3304)
> Update Using ROS instructions

- projects/robots/softbank/nao/worlds/nao_room.wbt
- src/webots/nodes/WbBackground.cpp
- src/webots/nodes/utils/WbDownloader.cpp
- src/webots/nodes/utils/WbDownloader.hpp
> Fix nao room demo

- .github/workflows/test_suite_linux.yml
- .github/workflows/test_suite_linux_develop.yml
- scripts/packaging/Makefile
- scripts/packaging/Makefile.controllers
- scripts/packaging/update_urls.py
> Fix texture change controller

- src/wren/PbrMaterial.cpp
- src/wren/PhongMaterial.cpp
> Fixed wren compilation warnings on Linux

- resources/projects/plugins/robot_windows/generic/timeplot_widget.js
> Fixed GL_INVALID_OPERATION error in robot window

- scripts/packaging/files_core.txt
> fix night mode on windows

- projects/robots/kinematics/tinkerbots/worlds/braitenberg.wbt
- projects/robots/kinematics/tinkerbots/worlds/vision_car.wbt
Fixes #3309.
Using a PBR appearance with a better infra-red reflection did the trick.
> Fixed Tinkerbots demos

- scripts/packaging/Makefile
> Fix nightly urls

- projects/robots/robotis/darwin-op/controllers/symmetry_matlab/symmetry_matlab.m
> Changed arm that respond to force

- projects/samples/robotbenchmark/robot_programming/plugins/robot_windows/robot_programming/robot_programming.html
When removing JQuery from the robotbenchmark robotwindows, I missed those.
I replaced them in the same way of https://github.com/cyberbotics/webots/pull/3192/commits/77de3df2bbd9e5dcfdc6963217b83c3d22754625
> Cleanup JQuery in robot windows

- projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/e-puck/EPuckFacade.cpp
> Fix botstudio crash

- docs/reference/changelog-r2021.md
- src/webots/gui/WbGuiApplication.cpp
- src/webots/launcher/launcher.c
> Fixed restart of Webots on Windows

- resources/web/local/webots.js
> Fixed robot window javascript error on reset

- src/controller/c/supervisor.c
- src/webots/control/WbController.cpp
> fix crash controllers

- resources/web/wwi/webots.js
Display a warning pop up when trying to play an animation/open the viewer on Safari
> Add warning for Safari

- scripts/get_git_info/get_git_info.sh
Correct the script that get the name of the repo when it is cloned using ssh
> fix repo.txt when ssh

- projects/robots/universal_robots/resources/ros_package/ur_e_webots/src/ur_e_webots/trajectory_follower.py
> Stop sending requests to motor if goal is canceled

- projects/robots/fp_robotics/p-rob3/controllers/p-rob3/p-rob3.c
- projects/robots/fp_robotics/p-rob3/protos/P-Grip.proto
- projects/robots/fp_robotics/p-rob3/protos/P-Rob3.proto
> Fixed P-Rob3 motor names

- tests/api/controllers/robot_urdf/prob3_reference.urdf
The P-Rob3 proto was changed, but not the corresponding reference file in the test suite, so the test suite was failing.
> Fix prob3 test

- docs/reference/changelog-r2021.md
- src/webots/nodes/WbBallJoint.cpp
- src/webots/nodes/WbBallJoint.hpp
- src/webots/nodes/WbHinge2Joint.cpp
- tests/physics/controllers/ball_joint_reset/.gitignore
- tests/physics/controllers/ball_joint_reset/Makefile
- tests/physics/controllers/ball_joint_reset/ball_joint_reset.c
- tests/physics/worlds/ball_joint_reset.wbt
Fixes https://github.com/cyberbotics/webots/issues/3392.
> Fix `BallJoint` reset

- docs/guide/running-extern-robot-controllers.md
> Added explanation about extern controllers and runtime.ini file

- docs/guide/robotino3.md
Closes https://github.com/cyberbotics/webots/issues/3423.
> Remove restriction for Robotino from docs

- docs/guide/tutorial-8-using-ros.md
> Add the MoveIt dependency to documentation

- docs/guide/tutorial-8-using-ros.md
Fixes #3307, replaces (https://github.com/cyberbotics/webots-snap/pull/34)
https://cyberbotics.com/doc/guide/tutorial-8-using-ros?version=documentation-ros-snap
> Add ROS and snap usage documentation

- docs/guide/running-extern-robot-controllers.md
- resources/projects/plugins/robot_windows/generic/Makefile
- src/controller/python/controller.i
It should tackle this:
https://github.com/cyberbotics/webots/pull/3415#issuecomment-880673947
The test process:
```bash
make distrib
git clean -dfx
```
> Fix robot window linking with an external Python controller

- docs/discord/development-2021.md
- docs/discord/documentation.md
- docs/discord/news.md
- docs/discord/technical-questions-2019.md
- docs/discord/technical-questions-2020.md
- docs/discord/technical-questions-2021.md
- docs/tests/test_md_files.py
Discord docs
Remove test concerning the pi symbol
> Released in Master

- docs/reference/shape.md
> shape.md, appearance.md: link to PBRAppearance

- docs/guide/tutorial-8-using-ros.md
> Fix typo in the doc

- resources/web/wwi/Parser.js
Conflicts:
* resources/web/wwi/Parser.js
> Merge master into released

- src/webots/nodes/WbImageTexture.cpp
> Fix imageTextures urls format

- projects/default/libraries/vehicle/c/driver/src/driver.c
- projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/core/RobotObjectFactory.hpp
- resources/projects/libraries/qt_utils/widgets/LidarWidget.cpp
- src/controller/c/robot.c
> Fix new cppcheck errors appeared on macOS

- scripts/packaging/publish_release.py
Fix error recently introduced in #3470
> Fix publish_release.py script

- docs/reference/changelog-r2021.md
- src/webots/Makefile
- src/webots/launcher/launcher.c
Fixes #3485. I also checked that this patch doesn't break the resolution of #2750.
> Fixed start of Webots from Windows cmd.exe

- tests/physics/worlds/connector_static_autolock.wbt
> Cleanup FLU connector test

- docs/reference/changelog-r2021.md
As requested in https://github.com/cyberbotics/webots/issues/3499#issuecomment-889875474_
> Add the changelog entry about PR #3499

- scripts/install/msys.sh
Fixes https://github.com/cyberbotics/webots/pull/3427#issuecomment-890793108.
> Fixed Windows PATH setting

- projects/samples/robotbenchmark/humanoid_marathon/plugins/robot_windows/humanoid_marathon/humanoid_marathon.html
- projects/samples/robotbenchmark/humanoid_sprint/plugins/robot_windows/humanoid_sprint/humanoid_sprint.html
- projects/samples/robotbenchmark/inverted_pendulum/plugins/robot_windows/inverted_pendulum/inverted_pendulum.html
- projects/samples/robotbenchmark/inverted_pendulum/plugins/robot_windows/inverted_pendulum/inverted_pendulum.js
- projects/samples/robotbenchmark/obstacle_avoidance/plugins/robot_windows/obstacle_avoidance/obstacle_avoidance.html
- projects/samples/robotbenchmark/pick_and_place/plugins/robot_windows/pick_and_place/pick_and_place.html
- projects/samples/robotbenchmark/visual_tracking/plugins/robot_windows/visual_tracking/visual_tracking.html
- projects/samples/robotbenchmark/visual_tracking/plugins/robot_windows/visual_tracking/visual_tracking.js
- src/webots/gui/WbWebPage.cpp
- src/webots/gui/WbWebPage.hpp
> Fix robotbenchmark robot windows

- docs/reference/changelog-r2021.md
- projects/default/libraries/vehicle/c/driver/src/driver.c
Fixed the issue where only one wheel was used for the front speed sum.
[#3545](https://github.com/cyberbotics/webots/issues/3545)
> Update on calculation of front_speed_sum

- docs/reference/changelog-r2021.md
Try to better describe the bug fix so that when reading the ChangeLog it is possible to understand the change.
> Improve ChangeLog entry

- docs/reference/changelog-r2021.md
> Fix indentation of R2021b revision entries

- docs/reference/pen.md
- resources/nodes/Pen.wrl
- src/webots/nodes/WbPen.cpp
- tests/api/worlds/distance_sensor_infra-red.wbt
- tests/api/worlds/pen.wbt
- tests/api/worlds/pen_box.wbt
- tests/api/worlds/pen_box_scaled.wbt
- tests/api/worlds/pen_capsule.wbt
- tests/api/worlds/pen_capsule_scaled.wbt
- tests/api/worlds/pen_cone.wbt
- tests/api/worlds/pen_cone_scaled.wbt
- tests/api/worlds/pen_cylinder.wbt
- tests/api/worlds/pen_cylinder_scaled.wbt
- tests/api/worlds/pen_elevation_grid.wbt
- tests/api/worlds/pen_elevation_grid_scaled.wbt
- tests/api/worlds/pen_indexed_face_set.wbt
- tests/api/worlds/pen_indexed_face_set_scaled.wbt
- tests/api/worlds/pen_mesh.wbt
- tests/api/worlds/pen_plane.wbt
- tests/api/worlds/pen_sphere.wbt
- tests/api/worlds/pen_sphere_scaled.wbt
Change the default orientation of Pen to match ENU/FLU convention
> FLU pen default orientation

- docs/reference/changelog-r2021.md
- src/webots/gui/WbView3D.cpp
I found this speed more in line with the rotation/translation speed.
> Increase scroll velocity when zooming

- src/webots/nodes/WbCamera.cpp
- src/webots/nodes/WbRadar.cpp
This PR should solve #3567 and #3564
> Fix FLU Radar

- src/webots/nodes/utils/WbTriangleMesh.cpp
It seems cppcheck was upgraded on GitHub Action macOS machines and is now detecting more errors.
This PR addresses them.
> Fixed cppcheck error on macOS

- docs/reference/viewpoint.md
- resources/nodes/Viewpoint.wrl
- src/webots/gui/WbNewProjectWizard.cpp
- src/webots/gui/WbNewProjectWizard.hpp
Fixes https://github.com/cyberbotics/webots/pull/3538#discussion_r686682150
This default orientation is ENU friendly, it doesn't work nicely with NUE. Therefore, when creating a new project it is a bit weird but it should be fine once `NUE` is replaced in the `empty.wbt` world and the arena PROTO is converted.
> Fix the Viewpoint documentation

- src/webots/nodes/WbRadar.cpp
- src/webots/nodes/utils/WbObjectDetection.cpp
- src/webots/nodes/utils/WbObjectDetection.hpp
- tests/api/controllers/camera_recognition/camera_recognition.c
This PR attempts to resolve #3571
> Fix FLU camera object detection

- docs/guide/object-trees.md
- projects/objects/trees/protos/Sassafras.proto
This is useful for the wildfire simulation and might be useful to others.
> Added a burnt parameter in Sassafras tree proto (climate change update)

- docs/reference/nodes-and-keywords.md
Restore the `Billboard` keyword in https://www.cyberbotics.com/doc/reference/nodes-and-keywords
> Restore Billboard keyword

- src/webots/nodes/WbGeometry.cpp
- src/webots/nodes/WbGeometry.hpp
Initialize `mIs90DegreesRotated` in the .cpp file (as before) instead of in the .hpp file
> restore mIs90DegreesRotated init

- projects/humans/c3d/protos/C3dViewer.proto
> Fix typo in C3dViewer.proto

- projects/humans/c3d/protos/C3dViewer.proto
> Improve C3DViewer PROTO fields description

- .github/workflows/test_suite_linux.yml
- .github/workflows/test_suite_linux_develop.yml
- .github/workflows/test_suite_mac.yml
- .github/workflows/test_suite_mac_develop.yml
- .github/workflows/test_suite_windows.yml
- .github/workflows/test_suite_windows_develop.yml
- projects/default/libraries/vehicle/java/Makefile
- resources/Makefile.java.include
- scripts/install/bash_profile.mac
- scripts/install/bash_profile.windows
- scripts/install/bashrc.linux
- scripts/install/linux_optional_compilation_dependencies.sh
- scripts/install/msys64_installer.sh
- src/controller/java/Makefile
The package for `openjdk-14` has been removed (https://bugs.launchpad.net/ubuntu/+source/openjdk-14/+bug/1934892)
We need to upgrade to jdk16
> Fix java jdk

- resources/web/wwi/Animation.js
- resources/web/wwi/WebotsAnimation.js
- resources/web/wwi/css/animation.css
- resources/web/wwi/css/animation_slider.css
The animation were sometimes not loading correctly on Firefox due to some synchronicity issues. It is now fix.
I also changed the font of the timer to be monotype such that it will not "shake" anymore
> Fix animation bug on Firefox

- projects/objects/floors/protos/UnevenTerrain.proto
- projects/objects/stairs/protos/StraightStairs.proto
- projects/objects/stairs/protos/StraightStairsLanding.proto
- projects/objects/stairs/protos/StraightStairsRail.proto
> FLU: convert stairs and floors

- projects/robots/fp_robotics/p-rob3/protos/P-Rob3.proto
- tests/api/controllers/robot_urdf/prob3_reference.urdf
Fix the P-Rob3 after the change in `Capscrew.proto` introduced in #3612
> FLU: Fix capscrew in p-rob3

- docs/discord/development-2021.md
- docs/discord/news.md
- docs/discord/technical-questions-2019.md
- docs/discord/technical-questions-2021.md
- docs/guide/installation-procedure.md
- docs/guide/tutorial-8-using-ros.md
> Merge released branch into master

- projects/default/libraries/vehicle/c/car/src/car.c
- projects/vehicles/controllers/ros_automobile/RosAutomobile.cpp
- projects/vehicles/protos/abstract/VehicleLights.proto
Just to avoid further propagation of the spelling mistake
> Fix break lights spelling

- tests/api/worlds/motions_loop.wbt
- tests/api/worlds/motions_regular.wbt
- tests/api/worlds/motions_reverse.wbt
- tests/manual_tests/worlds/interaction_with_solid_reference_model.wbt
> Fix deprecated Floor field in tests

- projects/humans/skin_animated_humans/protos/CharacterSkin.proto
Use `PBRAppearance` instead of `Appearance` nodes in the `CharacterSkin` PROTO.
> Update CharacterSkin PROTO appearances

- projects/devices/nvidia/protos/JetsonNano.proto
- projects/objects/solids/protos/SolidRoundedBox.proto
- projects/robots/nvidia/jetbot/protos/JetBot.proto
- projects/robots/nvidia/jetbot/protos/JetBotRaspberryPiCamera.proto
- projects/robots/nvidia/jetbot/worlds/jetbot.wbt
Convert:
robots:
worlds:
and devices:
> FLU: Convert JetBot robot and JetsonNano device 

- docs/guide/jetbot.md
Documentation update was missing in #3702.
> Update JetBot documentation after converting to FLU

- resources/web/wwi/Stream.js
Restore log of stdout and stderr in the web console
> Fix log WebotsJS

- projects/robots/mobsya/thymio/protos/Thymio2.proto
- projects/robots/mobsya/thymio/protos/Thymio2Pen.proto
- projects/robots/mobsya/thymio/worlds/thymio2.wbt
- projects/robots/mobsya/thymio/worlds/thymio2_ball.wbt
- projects/robots/mobsya/thymio/worlds/thymio2_pen.wbt
> FLU: Convert Thymio

- tests/api/controllers/robot_urdf/tiago_reference.urdf
> FLU: fix robot_urdf

- .github/workflows/tests_sources.yml
- docs/reference/changelog-r2021.md
- docs/reference/distancesensor.md
- src/webots/maths/WbMathsUtilities.hpp
- src/webots/maths/WbMatrix3.cpp
- src/webots/maths/WbQuaternion.hpp
- src/webots/maths/WbRotation.cpp
- src/webots/maths/WbRotation.hpp
- src/webots/nodes/WbCylinder.cpp
- src/webots/nodes/WbDistanceSensor.cpp
- src/webots/nodes/WbGeometry.hpp
- src/webots/nodes/WbLightSensor.cpp
- src/webots/nodes/WbMuscle.cpp
- src/webots/nodes/WbSphere.cpp
- src/webots/nodes/WbTrack.cpp
- src/webots/scene_tree/WbPhysicsViewer.cpp
- src/webots/scene_tree/WbPhysicsViewer.hpp
Conflicts:
- `WbSphere.cpp` L375-376
> Merge develop into `feature-enu-plan`

- projects/robots/dji/mavic/worlds/mavic_2_pro.wbt
- projects/samples/robotbenchmark/pick_and_place/worlds/pick_and_place.wbt
- tests/with_rendering/worlds/billboard.wbt
> Fix flu mistakes

- src/wren/DynamicMesh.cpp
> Cleanup dirty variable in DynamicMesh clear

- .github/ISSUE_TEMPLATE/config.yml
Try to use HTML links instead of MD links... Not sure about the result...
> Fix issue template

- docs/discord/documentation.md
- docs/discord/news.md
- docs/discord/technical-questions-2021.md
- docs/guide/supervisor-programming.md
> Merge released in master

- .github/ISSUE_TEMPLATE/config.yml
No luck with hyperlinks, giving up 😒.
> Fix issue template again

- projects/robots/robotis/darwin-op/libraries/Makefile.mac
> Fix macOS dependency

- scripts/converter/convert_nue_to_enu_rub.py
- Add the possibility to change the rotation of specific objects.
- Include a non-exhaustive list of these objects.
- convert corners and path
- Improve verbose
- minor fixes
> improve script

- resources/web/wwi/WebotsView.js
> Fix typo webotsview

- projects/robots/softbank/nao/protos/Nao.proto
The transversal stick between the shoulders was wrong and the neck too.
> FLU: Fix nao

- docs/guide/the-user-interface.md
- docs/guide/web-animation.md
- docs/guide/web-scene.md
- docs/guide/web-simulation.md
- resources/translations/wb_de.ts
- resources/translations/wb_es.ts
- resources/translations/wb_fr.ts
- resources/translations/wb_generic.ts
- resources/translations/wb_it.ts
- resources/translations/wb_ja_JP.ts
- resources/translations/wb_zh_CN.ts
- resources/web/templates/x3d_playback.html
- resources/web/wwi/Animation.js
- resources/web/wwi/WebotsView.js
- resources/web/wwi/X3dScene.js
- resources/web/wwi/webots.js
- src/webots/gui/WbMainWindow.cpp
- src/webots/nodes/utils/WbWorld.cpp
Introduce the possibilty to load a `scene` with the `webots-view`
> Enhancement model webotsjs

- docs/reference/lidar.md
As reported in https://github.com/cyberbotics/webots/pull/3801#issuecomment-980504699.
> Fix lidar C API documentation

- projects/default/resources/Makefile
add sumo folder on ubuntu 18.04
> Fix-test-sumo

- resources/web/wwi/Animation.js
- resources/web/wwi/WebotsView.js
- resources/web/wwi/css/animation.css
- resources/web/wwi/css/wwi.css
> Disable css when not needed

- projects/objects/kitchen/utensils/protos/Spoon.proto
> Fix spoon.proto

- projects/samples/devices/controllers/light_sensor/light_sensor.c
> Better explanation for light sensor demo

- projects/samples/devices/worlds/coupled_motors.wbt
> Fix gear rotation in `coupled_motors.wbt`

- projects/devices/sick/protos/SickLdMrs.proto
Fixes https://github.com/cyberbotics/webots/issues/3996
> Fix lidar tilt in `sick_point_cloud.wbt`

- projects/robots/kinematics/tinkerbots/controllers/crane/crane.c
- projects/robots/kinematics/tinkerbots/worlds/tinkerbots_demo.wbt
> Fix tinkerbots_demo.wbt

- projects/samples/devices/controllers/track/track.c
- projects/samples/devices/worlds/track.wbt
To avoid the ODE warning proposing to reduce the time step, the time step of this demo was reduced.
> Fixed ODE warning in track.wbt sample demo

- docs/reference/changelog-r2022.md
> Restore rolling friction in changelog

- docs/guide/web-scene.md
> add pen limitation on the web

- projects/samples/devices/worlds/linear_motor.wbt
> Fix cylinder of linear_motor.wbt

- projects/samples/devices/controllers/receiver_noise/receiver_noise.c
Add a clamp function to avoid maxVelocity warnings.
This pull-request fixes issue #3994.
> Clamp-receiver-noise

- projects/languages/cpp/worlds/example.wbt
- projects/languages/java/worlds/example.wbt
- projects/languages/python/worlds/example.wbt
> Fix example worlds

- docs/guide/installation-procedure.md
> Fix-doc-installation-procedure

- docs/reference/changelog-r2022.md
- src/webots/app/WbPerspective.cpp
- src/webots/app/WbPerspective.hpp
- src/webots/control/WbController.cpp
- src/webots/core/WbFileUtil.cpp
- src/webots/core/WbPreferences.cpp
- src/webots/core/WbPreferences.hpp
- src/webots/editor/WbBuildEditor.cpp
- src/webots/editor/WbTextBuffer.cpp
- src/webots/editor/WbTextEditor.cpp
- src/webots/gui/WbGuiApplication.cpp
- src/webots/gui/WbMainWindow.cpp
- src/webots/gui/WbMainWindow.hpp
- src/webots/gui/WbNewProjectWizard.cpp
> Fixes behavior when attempting to save in installation folder

- docs/blog/Webots-2022-a-release.md
- src/webots/engine/WbSimulationWorld.cpp
- src/webots/gui/WbUpdatedDialog.cpp
> Fix-wiki-link

- src/webots/gui/WbDragScaleEvent.hpp
> Removed useless include

- docs/reference/changelog-r2022.md
[preview](https://cyberbotics.com/doc/reference/changelog-r2022?version=fix-changelog)
> Fix underscores in changelog and add flu/enu mention

- docs/guide/tutorial-3-appearance.md
- docs/guide/tutorial-8-the-supervisor.md
- docs/js/showdown-extensions.js
> Update date in tutorials

- docs/js/webots_documentation_loader.js
The online documentation is currently broken due to a broken link.
> Fix online documentation

- projects/objects/apartment_structure/protos/Window.proto
Some checks were not converted
> Fix window proto

- scripts/get_git_info/get_git_info.sh
The if/then/else rule appeared to be wrong.
> Fixed repository computation

- src/webots/gui/WbUpdatedDialog.cpp
> Change welcome message

- docs/guide/the-user-interface.md
**Description**:
Supported 3d model import format docs not up to date with R2022a changes.
> Supported 3d model imports docs

- docs/guide/installation-procedure.md
This PR also uses ` ```bash` systematically to specify bash commands.
> Added docker image upgrade instructions

- docs/reference/proto-design-guidelines.md
`static` is the default state for any new proto.
> Remove `static` mention

- projects/robots/gctronic/e-puck/controllers/e-puck/Dockerfile
This file was committed by error in #3977.
> Delete test Dockerfile

- docs/discord/development-2020.md
- docs/discord/development-2021.md
- docs/discord/development-2022.md
- docs/discord/development.md
- docs/discord/menu.md
- docs/discord/news.md
- docs/discord/technical-questions-2019.md
- docs/discord/technical-questions-2020.md
- docs/discord/technical-questions-2021.md
- docs/discord/technical-questions-2022.md
- docs/guide/cpp-java-python.md
- docs/reference/proto-design-guidelines.md
> Merge `released` into `master`

- resources/web/wwi/Server.js
> Fix check in WbServer.js

- docs/reference/changelog-r2022.md
Update of the r2022b changelog for reference to PR #4107 (New robot step API functions).
https://cyberbotics.com/doc/reference/changelog-r2022?version=documentation-changelog-add-new-API-step-func
> Added step_begin and step_end to r2022 changelog

- docs/reference/changelog-r2022.md
Small correction on r2022b changelog about new step functions (first added in #4142).
https://cyberbotics.com/doc/reference/changelog-r2022?version=documentation-fix-changelog-r2022b
> Added precision in r2022b changelog

- src/webots/nodes/WbTextureTransform.hpp
- src/webots/nodes/WbTrack.cpp
> Fix typo in `WbTextureTransform`

- resources/web/wwi/MouseEvents.js
Fix #4146 
I restored it close to what it is robotbenchmark, you can test it there: https://www.cyberbotics.com/animations/soccer_example/soccer.html
I advise you to switch in fullscreen mode to test on mobile.
> Fix mobile navigation

- docs/guide/nao.md
The NAO video was missing...
New version: https://cyberbotics.com/doc/guide/nao?version=fix-missing-video
> Fix broken video link

- docs/guide/using-matlab.md
> Updated to the latest version of MATLAB

- include/controller/c/webots/plugins/robot_window/generic_robot_window/generic.h
- resources/nodes/Robot.wrl
- resources/projects/libraries/generic_robot_window/generic.c
- resources/projects/plugins/robot_windows/generic/generic.js
- src/webots/gui/WbMainWindow.cpp
- src/webots/gui/WbRobotWindow.cpp
Fix bug with update world tests. Fix override buttons for the generic window.
> Fix-robot-window

- projects/robots/softbank/nao/protos/Nao.proto
> Quick fix for the Nao PROTO

- src/webots/nodes/WbMesh.cpp
Resolves https://github.com/cyberbotics/webots/pull/4172#discussion_r799217281.
> Fix camelBase name in WbMesh

- docs/guide/nao.md
- projects/robots/softbank/nao/protos/Nao.proto
> Change nao default color to red

- projects/robots/softbank/nao/protos/Nao.proto
> Fix  Nao.proto indentation

- dependencies/Makefile.windows
- projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_bluetooth/Wrapper.cpp
- projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Wrapper.cpp
- projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Wrapper.cpp
- resources/projects/libraries/qt_utils/motion_editor/MotionWidget.cpp
- src/controller/c/motion.c
- src/controller/c/receiver.c
- src/controller/c/speaker.c
- src/webots/nodes/WbAbstractTransform.cpp
- src/webots/nodes/WbCone.cpp
- src/webots/nodes/WbCylinder.cpp
- src/webots/nodes/WbDistanceSensor.cpp
- src/webots/nodes/WbEmitter.cpp
- src/webots/nodes/WbGroup.cpp
- src/webots/nodes/WbLensFlare.cpp
- src/webots/nodes/WbMotor.cpp
- src/webots/nodes/WbNormal.hpp
- src/webots/nodes/WbRadar.cpp
- src/webots/nodes/WbSolidReference.cpp
- src/webots/nodes/WbTrack.cpp
- src/webots/nodes/WbViewpoint.cpp
- src/webots/nodes/WbViewpoint.hpp
- src/webots/user_commands/WbUndoStack.cpp
- src/wren/Renderable.cpp
- src/wren/Scene.cpp
- tests/sources/test_cppcheck.py
- tests/sources/test_line_ending.py
I had to upload a new version of libpico.zip to be compliant with C++17 which is needed by Qt6.
This PR also fixes a compilation warning for lua which is back-ported from the develop branch.
Finally, it seems a new version of cppcheck on Windows was installed in the CI, so that many new cppcheck errors had to be fixed to pass the Windows cppcheck tests.
> Fixed md5sum of libpico.zip on Windows

- dependencies/Makefile.windows
- docs/reference/changelog-r2022.md
- projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_bluetooth/Wrapper.cpp
- projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Wrapper.cpp
- projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Wrapper.cpp
- projects/samples/howto/gears/worlds/gears.wbt
- resources/projects/libraries/qt_utils/motion_editor/MotionWidget.cpp
- src/controller/c/motion.c
- src/controller/c/receiver.c
- src/controller/c/speaker.c
- src/webots/nodes/WbAbstractTransform.cpp
- src/webots/nodes/WbCone.cpp
- src/webots/nodes/WbCylinder.cpp
- src/webots/nodes/WbDistanceSensor.cpp
- src/webots/nodes/WbEmitter.cpp
- src/webots/nodes/WbGroup.cpp
- src/webots/nodes/WbLensFlare.cpp
- src/webots/nodes/WbMotor.cpp
- src/webots/nodes/WbNormal.hpp
- src/webots/nodes/WbRadar.cpp
- src/webots/nodes/WbSolidReference.cpp
- src/webots/nodes/WbTrack.cpp
- src/webots/nodes/WbViewpoint.cpp
- src/webots/nodes/WbViewpoint.hpp
- src/webots/user_commands/WbUndoStack.cpp
- src/wren/Renderable.cpp
- src/wren/Scene.cpp
- tests/sources/test_cppcheck.py
- tests/sources/test_line_ending.py
> Merge master in develop

- tests/api/controllers/gps_speed/gps_speed.c
> Removed unused variable causing warning

- tests/api/controllers/robot_parallel_step/robot_parallel_step.c
> Removed unused variables

- docs/reference/robot.md
> Add python to controllerArgs

- docs/guide/web-simulation.md
- resources/projects/plugins/robot_windows/generic/generic.js
- resources/web/wwi/RobotWindow.js
- resources/web/wwi/Toolbar.js
- resources/web/wwi/WebotsView.js
> Improve robot window to be able to embbed it

- src/webots/gui/WbMainWindow.cpp
the local export of an animation was wrong.
> fix export animation

- projects/samples/howto/url/worlds/url.wbt
> Fix background of url.wbt

- src/webots/gui/WbMainWindow.cpp
- src/webots/gui/WbMainWindow.hpp
- src/webots/gui/WbShareWindow.cpp
- src/webots/gui/WbShareWindow.hpp
Add a checkbox option to save the scene or the animation locally. The user thus needs to choose if they wants the simulation be uploaded or saved on local and cannot do both from Webots.
> Enhancement-share-simulation

- src/webots/vrml/WbVrmlWriter.cpp
Put the x3d tag in upper case to be able to import it in Blender.
> Fix x3d tag

- src/webots/Makefile
> Fixed compilation on Windows failing after gcc update

- resources/web/wwi/Parser.js
Add a custom ID to nodes that do not have one.
> Correct parsing of ID

- resources/web/wwi/Parser.js
- Refactor urls handling of background.
- Handle the case where there is several urls in the same variable (take only the first one).
- Handle the case where the url was not surrounded by quotes.
> Sanitize urls in webotsjs

- docs/guide/web-animation.md
- resources/web/wwi/WebotsView.js
> Add callback for scene loading

- resources/web/wwi/Parser.js
> Improve robustness of parsing array

- docs/guide/web-animation.md
- docs/guide/web-scene.md
- docs/guide/web-simulation.md
- resources/web/streaming_viewer/setup_viewer.js
- resources/web/wwi/WebotsView.js
> Fix onready callback function in WebotsView

- resources/web/wwi/RobotWindow.js
> Cleanup robotWindow

- docs/reference/changelog-r2022.md
- resources/wren/shaders/encode_depth.frag
- resources/wren/shaders/encode_depth.vert
Related to https://github.com/cyberbotics/urdf2webots/pull/161#issuecomment-1055116459, the RangeFinder measures were not correct close to the near plane.
This PR change the way how the depth is measured.
> Correction of depth measures

- docs/reference/changelog-r2022.md
- resources/web/wwi/Parser.js
- resources/wren/shaders/encode_depth.frag
- resources/wren/shaders/encode_depth.vert
- src/webots/nodes/WbBaseNode.cpp
- src/webots/nodes/WbBaseNode.hpp
- src/webots/nodes/WbCamera.cpp
- src/webots/nodes/WbCamera.hpp
- src/webots/nodes/WbJoint.cpp
- src/webots/nodes/WbMesh.cpp
- src/webots/nodes/WbMesh.hpp
- src/webots/nodes/WbSliderJoint.cpp
- src/webots/nodes/WbSolid.cpp
- src/webots/nodes/WbSolid.hpp
- src/webots/nodes/utils/WbDownloader.cpp
- src/webots/nodes/utils/WbDownloader.hpp
- src/webots/scene_tree/WbExtendedStringEditor.cpp
- src/webots/vrml/WbNode.cpp
- src/webots/vrml/WbNode.hpp
- tests/api/controllers/robot_urdf/epuck.urdf
- tests/api/controllers/robot_urdf/epuck_reference.urdf
- tests/api/worlds/robot_urdf.wbt
Conflicts:
- src/webots/nodes/WbMesh.cpp
> Merge `master` into `develop`

- src/wren/Makefile
Remove the creation of the temp.txt file
> Cleanup wrenjs makefile

- resources/web/wwi/Toolbar.js
Add a basic mechanism to ensure that the toolbar looks fine on resize
> Enhancement toolbar min size

- resources/webots_dusk.qss
- resources/webots_night.qss
Fixes https://github.com/cyberbotics/webots/issues/4342
> Consistent progress bar across themes

- resources/webots_dusk.qss
- resources/webots_night.qss
Fixes https://github.com/cyberbotics/webots/issues/4342
> Fix progress bar text alignment

- src/webots/gui/main.cpp
> Fix stdin redirection

- docs/reference/changelog-r2022.md
- src/controller/c/supervisor.c
- src/webots/core/WbLog.cpp
- src/webots/core/WbLog.hpp
- src/webots/gui/WbConsole.cpp
- src/webots/gui/WbConsole.hpp
- src/webots/gui/WbGuiApplication.cpp
> Fixed stdout/stderr redirection when all Webots console are closed

- src/webots/nodes/WbImageTexture.cpp
- tests/test_suite.py
This PR is just to debug why the nightly test fails on the develop branch. I'll merge it later today so as to minimize the annoyance.
> Debug develop nightly test

- src/webots/nodes/WbImageTexture.cpp
- tests/test_suite.py
This PR reverts the changes done to debug the nightly develop test here https://github.com/cyberbotics/webots/pull/4377
> Remove debug prints

- scripts/packaging/files_msys64.txt
> Fixed missing DLL in Windows distribution

- docs/guide/installation-procedure.md
> Add instructions about minimum cache size for assets

- src/webots/nodes/WbTrack.cpp
> Fix crash when adding animatedGeometries when no trackwheels are there

- resources/web/server/simulation_server.py
- resources/web/wwi/Server.js
- resources/web/wwi/Toolbar.js
- resources/web/wwi/webots.js
also reset the value of this.ide in the view when closing the view.
> Change theia mention to IDE

- docs/guide/web-simulation.md
> Cleanup Doc of connect()

- docs/guide/web-simulation.md
- resources/web/wwi/Toolbar.js
> Do not create IDE button when IDE is not present

- resources/web/wwi/Parser.js
- src/webots/nodes/WbRobot.cpp
ditto
the new docker image to use: `benjamindeleze/webots-test:robotsTypeLowGraphics`
> Change robot=true to type=robot

- docs/guide/web-simulation.md
- resources/web/wwi/Stream.js
- resources/web/wwi/Toolbar.js
- resources/web/wwi/WebotsView.js
- resources/web/wwi/webots.js
> Restore timeout feature in webotsjs

- resources/web/wwi/Toolbar.js
In animations, no `stream` is present
> Add checks in toolbar

- projects/objects/lights/protos/DoubleFluorescentLamp.proto
> Fix FLU conversion of doubleFluorescentLamp

- resources/web/server/simulation_server.py
> Kill subprocess if they do not terminate and notice WebotsJS if an IDE is found

- resources/web/wwi/Parser.js
- src/webots/nodes/WbImageTexture.cpp
- src/webots/nodes/WbImageTexture.hpp
- src/webots/nodes/WbPbrAppearance.cpp
- src/webots/nodes/WbPbrAppearance.hpp
- src/webots/nodes/WbTriangleMeshGeometry.cpp
- src/webots/vrml/WbVrmlWriter.cpp
- For PBRAppearance, now export only PBR (and not also simple Appearance).
- Export `ccw` as boolean and not 1/0 to match consistency.
- Export version of Webots to the .x3d
- Remove unused parameters
> Cleanup pbr export

- resources/web/wwi/Server.js
> Cleanup stream.js

- resources/projects/plugins/robot_windows/generic/generic.js
> Fix multiple initialization of generic robot window resulting in bugs

- resources/web/wwi/Toolbar.js
As the toolbar elements are now larger, the min size must be increased accordingly
> Fix min size toolbar

- resources/web/wwi/webots.js
> Cleanup Webots Clock

- .github/workflows/test_suite_linux.yml
- .github/workflows/test_suite_linux_develop.yml
- scripts/packaging/publish_release.py
Temporary commit, will be removed tomorrow
> Debug nightly publishing failures

- .github/workflows/discord_updater.yml
Looks like the discord bot choked yesterday, I've re-run it today and it failed again. The issue appears to be related to this: https://github.com/actions/checkout/issues/760
> Fix discord uploader

- resources/web/wwi/nodes/WbTrack.js
- resources/web/wwi/nodes/WbTrackWheel.js
the call to the `super` constructor was not updated from #4457
> Hotfix Track and Trackwheel

- src/webots/engine/WbAnimationRecorder.cpp
- src/webots/engine/WbAnimationRecorder.hpp
- src/webots/gui/WbStreamingServer.cpp
- src/webots/gui/WbStreamingServer.hpp
- src/webots/gui/WbX3dStreamingServer.cpp
- src/webots/gui/WbX3dStreamingServer.hpp
> Revert change fps/animation

- resources/web/wwi/Parser.js
- resources/web/wwi/css/toolbar.css
Concerning the sanitization, https://developer.mozilla.org/en-US/docs/Web/API/HTML_Sanitizer_API seems promising but it still experimental and not well supported by browers.
I had to improve the robustness of the CSS due to the change introduced in #4423
> Sanitize html input and improve robustness of CSS

- .github/workflows/test_suite_mac.yml
- .github/workflows/test_suite_mac_develop.yml
- .github/workflows/tests_sources.yml
- scripts/install/linux_optional_compilation_dependencies.sh
Ditto.
EDIT: Took the opportunity to install python from official website rather than our own and to use the macos-11 instead of 10.15 in the CI.
> Fix build due to missing python 3.10

- .github/workflows/test_suite_windows.yml
- .github/workflows/test_suite_windows_develop.yml
> Fix windows nightly build

- projects/samples/rendering/worlds/animated_skin.wbt
> Convert salamander with animated skin to FLU

- scripts/install/bashrc.linux
> Update ROS_DISTRO in bashrc.linux

- resources/web/wwi/css/toolbar.css
- resources/web/wwi/webots.js
> Fix labels in webotsJS

- resources/web/wwi/nodes/WbGroup.js
> Fix bug when clicking on a CadShape

- docs/guide/web-animation.md
- docs/guide/web-scene.md
- docs/guide/web-simulation.md
- resources/web/wwi/Toolbar.js
- resources/web/wwi/WebotsView.js
ditto
Example: https://cyberbotics.com/animations/panda2/panda.html
> Add a function to change the ambiant occlusion level

- resources/web/wwi/FloatingWindow.js
- resources/web/wwi/Toolbar.js
- resources/web/wwi/css/toolbar.css
Previous changes in #4484 introduced bugs in the following areas of the web viewer:
* Information Panel
* Vertical list panes (worlds and robot windows)
**Tasks**
The fixes can be viewed locally, or by comparing the testing and beta branches of webots.cloud
> Fix web components

- src/webots/gui/WbX3dStreamingServer.cpp
> Fix typo in streaming error message

- projects/devices/sick/protos/SickS300.proto
> Fix SickS300 bounding object

- .github/workflows/discord_updater.yml
Adds a manual trigger because waiting 1 week per attempt will take forever.
> Discord publisher manual trigger

- projects/robots/epson/scara_t6/worlds/industrial_example.wbt
> Screw the Scara in its example

- resources/web/server/simulation_server.py
- src/webots/gui/WbTcpServer.hpp
Fix simulation server after #4344
> Fix simulation server

- projects/robots/epson/scara_t6/worlds/industrial_example.wbt
> Fix test world update

- resources/web/wwi/Parser.js
the node is called `PbrAppearance` but the tagName is `PBRAppearance`
> WebotsJS: fix PBR typo

- resources/web/wwi/FloatingIde.js
With remote servers we have (for now) urls of the form: `https://server_address.com/2505`
but when testing on a local server it is something like: `http://localhost:2500`
So we have to handle both `/` and `:` separator
> Fix local IDE

- src/webots/nodes/WbConnector.cpp
> Silence gcc false positive warning

- docs/reference/camera.md
Fixes issue raised in https://github.com/cyberbotics/webots/pull/3801#issuecomment-1146500683
> Improved documentation about camera objects array lifecyle

- resources/web/wwi/image_loader.js
> Fix loading of broken image to be non-blocking

- docs/reference/changelog-r2022.md
- src/webots/nodes/WbBaseNode.cpp
- src/webots/vrml/WbNode.cpp
- src/webots/vrml/WbNode.hpp
using the `./webots conver /path/to/a/proto` utility currently generates several crashes
> Fix urdf export crashes

- projects/vehicles/worlds/village_realistic.wbt
> Remove empty transform

- src/webots/gui/WbPreferencesDialog.cpp
- src/webots/nodes/WbCamera.cpp
- src/webots/nodes/WbCamera.hpp
> Fixed reinitialization of Camera memory mapped file

- src/webots/app/README.TXT
- src/webots/control/README.TXT
- src/webots/core/README.TXT
- src/webots/editor/README.TXT
- src/webots/engine/README.TXT
- src/webots/gui/README.TXT
- src/webots/maths/README.TXT
- src/webots/nodes/README.TXT
- src/webots/ode/README.TXT
- src/webots/plugins/README.TXT
- src/webots/scene_tree/README.TXT
- src/webots/user_commands/README.TXT
- src/webots/util/README.TXT
- src/webots/vrml/README.TXT
- src/webots/wren/README.TXT
> Cleanup remove obsolete readmes

- resources/web/wwi/Parser.js
- resources/web/wwi/nodes/WbElevationGrid.js
> WebotsJS: fix elevation grid bounding object

- resources/web/wwi/WebotsView.js
> Fix typo for webscene

- src/webots/control/WbLanguageTools.cpp
- src/webots/gui/WbView3D.cpp
> Fix crash on save

- src/webots/engine/WbAnimationRecorder.cpp
- src/webots/engine/WbAnimationRecorder.hpp
Timer now starts at zero when animation is recorded.
> Fix animation time start

- src/wren/StaticMesh.cpp
> Fix black sphere bug

- src/webots/control/WbLanguageTools.cpp
- src/webots/gui/WbMainWindow.cpp
- src/webots/gui/WbMainWindow.hpp
Fixes #4654: Checks for files 10 times every 100ms, if they don't exist, don't try and upload them.
> Enhance thumbnail upload robustness

- src/webots/gui/WbMainWindow.cpp
> remove upload filename warning

- docs/guide/preferences.md
Update `Preferences` documentation with addition of new `Thumbnail` checkbox.
https://cyberbotics.com/doc/guide/preferences?version=documentation-preferences-thumbnail#general
> Update Preferences documentation

- projects/samples/howto/cylinder_stack/controllers/contact_points_supervisor/contact_points_supervisor.c
Fixes a minor problem in a demo controller.
> Fixed index of red cylinder on contact point demo

- .github/workflows/test_suite_linux_develop.yml
- .github/workflows/test_suite_windows_develop.yml
More debugging regarding the develop nightlies failing if the test is triggered from master
> Fix nightlies on master side

- docs/guide/epuck.md
- docs/guide/robotis-op2.md
- docs/guide/thymio2.md
> Fix documentation for opening robot windows

- src/webots/editor/WbProjectRelocationDialog.cpp
- src/webots/editor/WbProjectRelocationDialog.hpp
> Removed the 'Include all PROTO files' option from the relocation dialog

- scripts/packaging/files_msys64.txt
> Fixed compilation of controllers on Windows

- src/webots/editor/WbProjectRelocationDialog.cpp
- src/webots/editor/WbProjectRelocationDialog.hpp
Fixes  #4772.
This PR fixes the missing copies of controller files as well as SUMO files.
> Fixed relocation of projects

- Makefile
- scripts/packaging/update_urls.py
Add target to reset all the assets URLs to the format `webots://`.
> Add 'clean-urls' target to main Makefile

- Makefile
Fixes #4807 (note that 4807 is the altitude of the Mont Blanc in meters).
> Fixed make clean(se) for proto-list.xml

- docs/guide/generate_objects_doc.py
- resources/osm_importer/config.ini
- resources/osm_importer/elevation.py
- resources/osm_importer/utils/misc_utils.py
- resources/osm_importer/webots_objects/barrier.py
- resources/osm_importer/webots_objects/road.py
- scripts/new_version/new_version.sh
Note that these urls will not be valid until the tag `R2022b` is created,
> Update remaining urls to R2022b

- src/webots/vrml/WbProtoTreeItem.cpp
> Fixed parsing of commented out EXTERNPROTOs

- .github/workflows/test_suite_linux.yml
- .github/workflows/test_suite_mac.yml
- .github/workflows/test_suite_windows.yml
> Fix workflow

- lib/controller/matlab/launcher.m
Fixes the execution of MATLAB controllers on macOS.
> Fixed MATLAB on macOS

- resources/web/wwi/viewer.js
> Fix broken url

- docs/reference/changelog-r2022.md
- src/webots/vrml/WbProtoManager.cpp
EXTERNPROTO change doesn't have a changelog entry. The wiki is still under development.
> Add EXTERNPROTO to changelog

- projects/samples/howto/rolling_friction/worlds/rolling_friction.wbt
> Fix rolling_friction urls

- projects/samples/howto/Makefile
> Correct typo in Makefile

- docs/reference/changelog-r2023.md
- docs/reference/menu.md
> Add changelog for 2023

- resources/web/wwi/Server.js
> Reset webotsjs session timeout on close

- resources/web/server/simulation_server.py
- resources/web/wwi/Server.js
The simulation server only parses through the `.yml` extension, when it should also support `.yaml`
> add .yaml extension

- docs/discord/documentation.md
- docs/discord/news.md
- docs/discord/technical-questions-2020.md
- docs/discord/technical-questions-2021.md
- docs/discord/technical-questions-2022.md
> Update discord docs. (#4859)

- src/webots/gui/WbMainWindow.cpp
In the wizard menu PROTO was written with the wrong case.
> Fix case of PROTO

- docs/reference/compass.md
Reported by a user here: https://discord.com/channels/565154702715518986/565154703139405824/966431158638379039
> Update get_bearing_in_degrees to ENU

- src/webots/nodes/utils/WbNodeOperations.cpp
Fix #4891.
This issue is also reproducible in the `master` branch, but to avoid conflicts can be fixed directly in this branch.
> Fix updating the selection from the scene tree

- resources/web/server/simulation_server.py
Apply suggestions commented in #4871.
> Break if yaml file found

- src/webots/sound/WbSoundEngine.cpp
- src/webots/sound/WbSoundEngine.hpp
> Update SoundEngine's viewpoint after regeneration

- projects/robots/neuronics/ipr/worlds/ipr_collaboration.wbt
> Improve graphics of ipr collaboration world

- scripts/converter/declare_externproto.py
> Fix declare extern protos script on macs

- resources/web/wwi/Parser.js
- resources/web/wwi/WebotsView.js
> Fix typo in webotsjs timer

- scripts/install/bash_profile.windows
> Enforce UTF-8 encoding for Python IO

- src/webots/core/WbHttpReply.cpp
I found the correct mime types here: https://www.iana.org/assignments/media-types/media-types.xhtml
> Fix mime type for models

- src/webots/scene_tree/WbAddNodeDialog.cpp
- src/webots/scene_tree/WbAddNodeDialog.hpp
- src/webots/vrml/WbProtoManager.cpp
- src/webots/vrml/WbProtoManager.hpp
> Cleanup not used function arguments

- projects/default/controllers/ros/Ros.cpp
`max` causes the parameter `description-prefix` to no work, it should be `min` I suppose
> ros controller argument "--robot-description" bug fix

- resources/web/wwi/FloatingRobotWindow.js
- resources/web/wwi/Parser.js
- resources/web/wwi/Progress.js
- resources/web/wwi/Server.js
- resources/web/wwi/Stream.js
- resources/web/wwi/Toolbar.js
- resources/web/wwi/X3dScene.js
- resources/web/wwi/nodes/WbViewpoint.js
> Style webotsJS

- resources/Makefile.include
- scripts/packaging/generate_proto_list.py
To make the output of the main Makefile more readable.
> Improved the output of the Makefile

- docs/guide/webots-cloud.md
> Update broken link in webots cloud documentation

- src/webots/launcher/webots-linux.sh
> Fix condition on high DPI detection in Linux launcher

- docs/guide/webots-cloud.md
Link: https://cyberbotics.com/doc/guide/webots-cloud?version=documentation-add-ref-to-simulation-examples#examples
> Add a paragraph about the simulation examples repository in the doc

- src/webots/gui/WbMainWindow.cpp
> Grey out share button when not available

- .eslintrc.json
I missed one dependency in #5050
> Eslintrc: add missing variable

- src/webots/gui/WbMainWindow.cpp
> Cleanup #5091 code

- projects/default/controllers/ros/RosCamera.cpp
- projects/default/controllers/ros/RosCamera.hpp
- projects/default/controllers/ros/RosRangeFinder.cpp
- projects/default/controllers/ros/RosRangeFinder.hpp
Ros camera sensors normally publish a camera info next to image topics. This pull request aims to provide a basic version for the Camera and RangeFinder Ros Controller.
> Feature camera info publisher

- projects/robots/pal_robotics/tiago_extensions/protos/TiagoRightArm.proto
> Fix tiago++ right arm shoulder

- projects/objects/chairs/protos/OfficeChair.proto
- projects/objects/lights/protos/CeilingSpotLight.proto
- projects/objects/lights/protos/ConstructionLamp.proto
- projects/robots/nvidia/jetbot/protos/JetBot.proto
A couple of PROTO files were not converted from Lua to JavaScript.
This PR fixes this.
> Converted Lua protos to JavaScript

- projects/robots/nvidia/jetbot/protos/JetBot.proto
> Fix jetbot without chassis

- src/webots/vrml/WbProtoManager.cpp
- src/webots/vrml/WbProtoManager.hpp
This method is not used anymore.
> Removed unused method in WbProtoManager class

- src/webots/app/WbApplication.cpp
- src/webots/vrml/WbParser.cpp
> Display progress while loading world tokens

- docs/reference/changelog-r2022.md
- src/webots/nodes/WbBackground.cpp
- src/webots/nodes/WbBackground.hpp
> Fix apply skyColor to appearance on background updates

- projects/robots/dji/mavic/protos/Mavic2Pro.proto
> Add missing documentation link in Mavic2Pro PROTO

- src/webots/nodes/WbCamera.cpp
- src/webots/wren/WbWrenCamera.cpp
Fixes: https://github.com/cyberbotics/webots/issues/5161
> Fix noise mask on distrib

- src/webots/editor/WbFindReplaceDialog.cpp
Failure was introduced in #5175.
> Fixed compilation failure

- src/webots/gui/WbMainWindow.cpp
Fixes https://github.com/cyberbotics/webots/issues/5180
> Show warning if the file to be edited isn't cached

- src/webots/gui/WbMainWindow.cpp
To test it, change the `Simulation upload service` in the preferences to `https://testing.webots.cloud`
> Upload the meshes folder to webots.cloud in case of animation/scene

- resources/web/wwi/nodes/WbCadShape.js
- src/webots/nodes/WbBackground.cpp
Fixes: https://github.com/cyberbotics/webots/issues/5183
> Fix `CadShape` animations

- docs/guide/webots-cloud.md
- projects/samples/environments/indoor/worlds/complete_apartment.wbt
> Improve `complete_apartment.wbt` title

- docs/guide/running-extern-robot-controllers.md
- resources/projects/plugins/robot_windows/generic/generic.css
> Fix robot window camera layout

- docs/guide/simulation-server.md
I did not put the whole `webots.cloud` address (https://webots.cloud/ajax/server/setup.php) as it is just for information
> Specify the default value of notify and shareIdleTime

- docs/guide/advanced-configuration.md
- docs/guide/setup-a-webots-project-repository.md
- docs/guide/simulation-server.md
- docs/guide/webots-cloud.md
> Update docker name

- docs/guide/web-animation.md
> add thumbnail as parameter for animation

- scripts/converter/declare_externproto.py
> Correct declare.py

- src/webots/nodes/WbLidar.cpp
> Update WbLidar.cpp style

- docs/guide/simulation-server.md
> simulation-server doc correction

- scripts/icon_studio/controllers/icon_creator/icon_creator.py
> Update deprecated option in icon_creator.py

- docs/reference/changelog-r2022.md
> Fix typo in Changelog

- resources/web/wwi/Server.js
Goes with https://github.com/cyberbotics/webots-server/pull/10
> Change keyword `docker:` to `loading:`

- docs/guide/tutorial-8-the-supervisor.md
https://cyberbotics.com/doc/guide/tutorial-8-the-supervisor?tab-language=c&version=doc-typo
> Fixed a typo in the doc

- docs/reference/changelog-r2022.md
- resources/web/wwi/Animation.js
> Fix recusion in animation update

- tests/test_suite.py
> Fix counting test suite failures

- docs/reference/changelog-r2022.md
- src/webots/control/WbController.cpp
> Fix controller restart after crash

- src/webots/control/WbController.cpp
Fixed compilation problem introduced in #5284.
> Fix compilation

- .eslintrc.json
- resources/web/wwi/nodes/WbCadShape.js
- resources/web/wwi/system_info.js
> Fix ecma version and coding style

- resources/web/wwi/nodes/WbCadShape.js
> Fix missing import

- src/webots/nodes/WbRobot.cpp
With external, none, and generic, don't change to generic.
Fix https://github.com/cyberbotics/webots/issues/5326
> Fix conversion of PROTO with special controller

- docs/reference/rangefinder.md
> Remove references to lidar device from RangeFinder section

- resources/web/wwi/nodes/WbIndexedFaceSet.js
- resources/web/wwi/nodes/utils/WbTriangleMesh.js
> Fix ccw of indexed face set for web proto

- docs/reference/proto-design-guidelines.md
> Doc: Fix example PROTO

- resources/web/wwi/Parser.js
> Webots.js: remove decimal points from progress value

- src/webots/core/WbAction.hpp
- src/webots/core/WbFileUtil.cpp
- src/webots/core/WbFileUtil.hpp
- src/webots/editor/WbProjectRelocationDialog.cpp
- src/webots/nodes/WbSolid.cpp
- src/webots/nodes/WbSolidDevice.cpp
- src/webots/nodes/WbSolidDevice.hpp
- src/webots/nodes/utils/WbDictionary.cpp
- src/webots/nodes/utils/WbDictionary.hpp
- src/webots/nodes/utils/WbSupervisorUtilities.hpp
- src/webots/nodes/utils/WbWorld.cpp
- src/webots/nodes/utils/WbWorld.hpp
- src/webots/nodes/utils/WbWrenVertexArrayFrameListener.hpp
- src/webots/scene_tree/WbSceneTree.cpp
- src/webots/user_commands/WbClipboard.cpp
- src/webots/vrml/WbNode.cpp
- src/webots/vrml/WbNode.hpp
- src/webots/vrml/WbWriter.hpp
- src/webots/wren/WbWrenTextureOverlay.cpp
> Replace deprecated QPair

- src/webots/control/WbControlledWorld.cpp
> Fix INFO condition when changing controller

- src/webots/control/WbControlledWorld.cpp
Fix compilation failure introduced in #5380.
> Hotfix compilation error

- src/webots/control/WbController.cpp
> Fix crash when robot with extern controller is deleted

- scripts/packaging/files_core.txt
> Fix js template files in files_core.txt

- lib/controller/python/controller/supervisor.py
- projects/robots/robotis/darwin-op/libraries/Makefile
- scripts/packaging/recurse_in_projects.txt
- tests/default/controllers/test_suite_supervisor/test_suite_supervisor.py
Follow-up #5297:
fix package creation expecting a python folder that has been removed in #5297.
> Remove robotis python library from package

- docs/reference/changelog-r2023.md
- resources/web/wwi/RobotWindow.js
Fix #5174:
the default robot window code wasn't properly handling concatenated message.
> Improve robot window robustness to concatenated messages

- docs/reference/changelog-r2023.md
- src/webots/vrml/WbTokenizer.cpp
> Fix header required for PROTO files

- src/controller/c/Controller.def
> Fixed missing exported function for Visual C++

- resources/translations/wb_de.ts
- resources/translations/wb_es.ts
- resources/translations/wb_fr.ts
- resources/translations/wb_generic.ts
- resources/translations/wb_it.ts
- resources/translations/wb_ja_JP.ts
- resources/translations/wb_zh_CN.ts
> Update translations for the release

- src/webots/core/WbTemplateEngine.cpp
This helped me when I bumped into #5477 and will certainly help users experiencing the same problem.
> Add a better error message to help debugging the problem

- src/controller/c/system.c
- src/webots/core/WbStandardPaths.cpp
Following #5484, we also need to fix the tmp directory for extern controllers.
> Fix tmp path on mac os

- lib/controller/python/controller/node.py
> Fixed Python API Node.resetPhysics

- src/webots/gui/WbNewControllerWizard.cpp
Update extern controller name.
> Improve extern controller name

- scripts/install/inno_setup_installer.sh
> Cleanup after innosetup install

- resources/translations/wb_de.ts
- resources/translations/wb_es.ts
- resources/translations/wb_fr.ts
- resources/translations/wb_generic.ts
- resources/translations/wb_it.ts
- resources/translations/wb_ja_JP.ts
- resources/translations/wb_zh_CN.ts
> Regenerate translation files

- .github/workflows/test_suite_windows.yml
- .github/workflows/test_suite_windows_develop.yml
Try to enforce Python 3.11 to fix the installation of PyGithub.
> Switched to Python 3.11

- .github/workflows/test_suite_windows.yml
- .github/workflows/test_suite_windows_develop.yml
This works on a simple test case at https://github.com/omichel/action_test
> Attempt to fix Windows build

- .github/workflows/test_suite_windows.yml
- .github/workflows/test_suite_windows_develop.yml
Remove printing of debug information now that the Windows workflows are working again.
> Clean-up Windows workflows

- lib/controller/python/controller/wb.py
> Fix libController path in Python API on macOS

- lib/controller/python/controller/node.py
- lib/controller/python/controller/supervisor.py
> Add default argument for some methods in Python API

- lib/controller/python/controller/field.py
> `removeSF()` calls the wrong C method

- lib/controller/python/controller/field.py
> Fixed Field.setMF/insertMF for vectors

- lib/controller/python/controller/node.py
> Fix returned node

- docs/reference/robot.md
Fixes #5579.
The current behavior is simply added to the documentation. Other APIs are not changed.
> Add documentation line for step functions in Python

- docs/reference/supervisor.md
Fixed small mismatch between the Supervisor Python API and its documentation.
> Fixed Python Supervisor API documentation

- docs/blog/Webots-2023-a-release.md
- docs/reference/changelog-r2023.md
- resources/translations/wb_de.ts
- resources/translations/wb_es.ts
- resources/translations/wb_fr.ts
- resources/translations/wb_generic.ts
- resources/translations/wb_it.ts
- resources/translations/wb_ja_JP.ts
- resources/translations/wb_zh_CN.ts
> Update dates + translations for the R2023a release

- docs/guide/installation-procedure.md
> Update snap size

- docs/reference/changelog-r2023.md
- lib/controller/python/controller/supervisor.py
> Fixed Python supervisor setSimulationMode

- resources/web/wwi/nodes/WbHingeJoint.js
- resources/web/wwi/nodes/WbSlot.js
- resources/web/wwi/nodes/utils/WbQuaternion.js
- Error when a bounding object was in a slot.
- Issue of position if the joint anchor was not 0
> Fix two bugs in feature-web-proto

- resources/web/wwi/InformationPanel.js
- resources/web/wwi/Parser.js
- resources/web/wwi/nodes/WbWorld.js
Add the version number in webotsJS information panel as requested in #5567 
you can test it here https://testing.webots.cloud
> Add version information in webotsJS

- resources/web/wwi/FloatingProtoParameterWindow.js
- resources/web/wwi/Toolbar.js
- resources/web/wwi/css/toolbar.css
> Reset button is grey when there is nothing to reset

- .github/workflows/test_suite_windows.yml
- .github/workflows/test_suite_windows_develop.yml
> Try to get rid of MSYS/git installation on Windows

- docs/reference/changelog-r2023.md
- src/webots/nodes/utils/WbSupervisorUtilities.cpp
Fixes https://github.com/cyberbotics/webots/issues/5584
> Fix invalid nodes in pose tracking

- resources/web/wwi/Toolbar.js
- resources/web/wwi/css/toolbar.css
- resources/web/wwi/nodes/WbViewpoint.js
- The node to follow is in the viewpoint of the `.x3d` file
- Possibility to turn on/off the follow with in the settings menu
> Allow to enable/disable the follow of the given node

- resources/web/wwi/nodes/WbAppearance.js
- resources/web/wwi/nodes/WbBackground.js
- resources/web/wwi/nodes/WbGeometry.js
- resources/web/wwi/nodes/WbPbrAppearance.js
- resources/web/wwi/nodes/WbPointSet.js
- resources/web/wwi/nodes/WbScene.js
- resources/web/wwi/nodes/WbShape.js
- resources/web/wwi/nodes/WbTriangleMeshGeometry.js
- resources/web/wwi/nodes/WbViewpoint.js
- resources/web/wwi/wren/WbWrenBloom.js
- resources/web/wwi/wren/WbWrenGtao.js
- resources/web/wwi/wren/WbWrenHdr.js
- resources/web/wwi/wren/WbWrenPicker.js
- resources/web/wwi/wren/WbWrenPostProcessingEffects.js
- resources/web/wwi/wren/WbWrenShaders.js
> Cleanup webotsJs import

- resources/web/wwi/nodes/WbAbstractCamera.js
- resources/web/wwi/nodes/WbLidar.js
- resources/web/wwi/nodes/WbLightSensor.js
- resources/web/wwi/nodes/WbPen.js
- resources/web/wwi/nodes/WbRadar.js
- resources/web/wwi/protos/ProtoCamera.proto
- resources/web/wwi/protos/ProtoSensor.proto
- resources/web/wwi/test.html
The `delete` function was missing and is needing in particular when a proto can be regenerated.
> Add delete function in devices

- resources/web/wwi/FloatingProtoParameterWindow.js
- resources/web/wwi/Parser.js
- resources/web/wwi/X3dScene.js
- resources/web/wwi/nodes/WbConnector.js
- resources/web/wwi/protos/ProtoSensor.proto
- resources/web/wwi/test.html
Test it here:
https://proto.webots.cloud/run?version=proto&url=https://github.com/BenjaminDeleze/sandbox/blob/master/protoExample/protos/ProtoSensor.proto
> Display connector in web proto viewer

- projects/default/controllers/ros/RosSupervisor.cpp
Fixes build, see: https://github.com/cyberbotics/webots/actions/runs/3661374245
> Fixed compilation of ROS controller

- projects/objects/factory/tools/protos/EmergencyButton.proto
> FLU: emergency buttuon

- docs/reference/altimeter.md
Added info regarding the default name tag in Altimeter.md.
Relates to the discussion #5449
https://github.com/cyberbotics/webots/pull/5459
> Update altimeter node documentation

- src/webots/maths/WbRotation.cpp
- src/webots/maths/WbRotation.hpp
- src/webots/nodes/utils/WbBoundingSphere.cpp
- src/webots/nodes/utils/WbBoundingSphere.hpp
> remove unused variable and fix default axis

- docs/reference/jointparameters.md
This missing information was reported by a user.
> Documented units for spring and damping constants

- docs/reference/changelog-r2023.md
- lib/controller/python/controller/camera.py
> Fixed crash in Python API when using several cameras with different resolutions

- resources/web/wwi/FloatingProtoParameterWindow.js
- resources/web/wwi/nodes/WbHingeJoint.js
- resources/web/wwi/test.html
- Add support for coupled motors in web proto viewer
- Correct a bug where the rotation of a joint was wrong if the initial position was not 0.
You can test it here:
https://proto.webots.cloud/run?version=proto&url=https://github.com/BenjaminDeleze/sandbox/blob/master/protoExample/protos/Panda.proto
> Support coupled motors on slider update

- resources/web/wwi/FloatingProtoParameterWindow.js
- resources/web/wwi/test.html
consider fields left empty as 0 instead of NaN (which was throwing exception)
> Handle blank field

- src/webots/nodes/WbCamera.cpp
- src/webots/nodes/WbCamera.hpp
- src/webots/nodes/WbRadar.cpp
- src/webots/nodes/WbRadar.hpp
- src/webots/nodes/utils/WbObjectDetection.cpp
- src/webots/nodes/utils/WbObjectDetection.hpp
Address #3535 and cleanup and simplify `WbObjectDetection` class:
* improve function names
* remove useless function arguments
> Cleanup WbObjectDetection class

- resources/web/wwi/InformationPanel.js
The version is not available in mjpeg.
> Fix informationPanel in mjpeg

- scripts/install/linux_compilation_dependencies.sh
- scripts/install/linux_optional_compilation_dependencies.sh
- scripts/install/linux_runtime_dependencies.sh
- scripts/install/linux_test_dependencies.sh
- scripts/install/linux_web_viewer_dependencies.sh
Given the recent instabilities with azure, this might help offset some of the random failures.
> Make installation scripts more robust

- docs/guide/nao.md
> Fix softbank link

- docs/README.md
- docs/tests/requirements.txt
- docs/tests/test_pep8.py
- lib/controller/python/controller/__init__.py
- lib/controller/python/controller/camera.py
- lib/controller/python/vehicle/__init__.py
- projects/default/controllers/ros/headersGenerator.py
- projects/default/controllers/sumo_supervisor/SumoSupervisor.py
- projects/default/controllers/sumo_supervisor/WebotsVehicle.py
- projects/robots/epson/scara_t6/controllers/scara/scara.py
- projects/robots/epson/scara_t6/controllers/scara_food_industry/scara_food_industry.py
- projects/robots/niryo/ned/controllers/ned_python/ned_python.py
- projects/samples/robotbenchmark/highway_driving/controllers/highway_driving_benchmark/highway_driving_benchmark.py
- projects/vehicles/controllers/highway_overtake/highway_overtake.py
- resources/osm_importer/parser_objects.py
- resources/osm_importer/projection.py
- resources/osm_importer/webots_objects/building.py
- resources/osm_importer/webots_objects/road.py
- resources/osm_importer/webots_objects/speed_limit.py
- resources/sumo_exporter/crossroad.py
- resources/sumo_exporter/math_utils.py
- resources/sumo_exporter/road.py
- scripts/export_function_js/export_function.py
- tests/sources/requirements.txt
- tests/sources/test_pep8.py
According to the [package](https://pypi.org/project/pycodestyle/) info:
> This package used to be called pep8 but was renamed to pycodestyle to reduce confusion.
The change was already done in webots_ros2 and urdf2webots, but not here.
After the change, several other failures were detected, likely because the pep8 packages hasn't been updated since the change
> Use pycodestyle instead of pep8

- README.md
- docs/README.md
- docs/tests/requirements.txt
- docs/tests/test_pep8.py
- lib/controller/python/controller/__init__.py
- lib/controller/python/controller/camera.py
- lib/controller/python/vehicle/__init__.py
- projects/default/controllers/ros/headersGenerator.py
- projects/default/controllers/sumo_supervisor/SumoSupervisor.py
- projects/default/controllers/sumo_supervisor/WebotsVehicle.py
- projects/robots/epson/scara_t6/controllers/scara/scara.py
- projects/robots/epson/scara_t6/controllers/scara_food_industry/scara_food_industry.py
- projects/robots/niryo/ned/controllers/ned_python/ned_python.py
- projects/samples/robotbenchmark/highway_driving/controllers/highway_driving_benchmark/highway_driving_benchmark.py
- projects/vehicles/controllers/highway_overtake/highway_overtake.py
- resources/osm_importer/parser_objects.py
- resources/osm_importer/projection.py
- resources/osm_importer/webots_objects/building.py
- resources/osm_importer/webots_objects/road.py
- resources/osm_importer/webots_objects/speed_limit.py
- resources/sumo_exporter/crossroad.py
- resources/sumo_exporter/math_utils.py
- resources/sumo_exporter/road.py
- resources/web/wwi/Animation.js
- scripts/export_function_js/export_function.py
- tests/sources/requirements.txt
- tests/sources/test_pep8.py
> Merge develop in feature-web-proto

- projects/robots/adept/pioneer3/controllers/pioneer3dx_gripper/pioneer3dx_gripper.c
- projects/robots/adept/pioneer3/protos/Pioneer3Gripper.proto
- projects/robots/adept/pioneer3/worlds/pioneer3dx_gripper.wbt
Also fix the corresponding world: since FLU conversion the tie was not perfectly flat and so the ball was rolling.
> Turn Pionneer3Gripper into a coupled motor

- docs/guide/web-streaming.md
- resources/web/wwi/Toolbar.js
- resources/web/wwi/WebotsView.js
This PR make the robot window appear by default for competitions on webots.could "try" page to mimic the behaviour of robotbenchmark.net
> Make the robot window appear by default for competitions

- resources/web/wwi/FloatingCustomWindow.js
- resources/web/wwi/FloatingIde.js
- resources/web/wwi/FloatingWindow.js
- resources/web/wwi/Terminal.js
- resources/web/wwi/Toolbar.js
- resources/web/wwi/css/progress.css
- resources/web/wwi/css/toolbar.css
Increment the z-indexes to take into account the new windows.
You can test it here: https://webots.cloud/run?version=R2023a&url=https%3A%2F%2Fgithub.com%2Fcyberbotics%2Fwrestling%2Fblob%2Fmain%2Fworlds%2Fwrestling.wbt&type=competition&context=try
> Fix z-indexes

- resources/web/wwi/FloatingProtoParameterWindow.js
- resources/web/wwi/css/toolbar.css
Test it here: https://proto.webots.cloud/run?version=R2023b&url=https://github.com/cyberbotics/webots/blob/feature-web-proto/projects/robots/softbank/nao/protos/Nao.proto&type=undefined
> Add a add button for mf field

- docs/dependencies.txt
> remove useless dependency

- resources/web/wwi/Progress.js
> Fix src image condition

- docs/reference/changelog-r2023.md
- lib/controller/python/controller/motor.py
Add missing argument to `Motor.enableForceFeedback`.
> Fix Motor.enableForceFeedback Python API function

- tests/rendering/worlds/meshes/colored_cube.obj
> Fix missing mtl import

- docs/guide/advanced-configuration.md
https://www.cyberbotics.com/doc/guide/advanced-configuration?version=doc-server
> Add tips on swap

- resources/web/wwi/protoVisualizer/Node.js
Fixes temporary urls, for testing the main PR. This will need once again to be adapted before merging into develop
> Fix web proto prefix

- resources/web/wwi/FloatingProtoParameterWindow.js
- resources/web/wwi/css/toolbar.css
You can test it here:
https://proto.webots.cloud/run?version=R2023b&url=https://github.com/ad-daniel/prefab/blob/master/protoExamples/protos/tesla/TeslaModel3.proto&type=undefined
> Enhancement display of vectors

- docs/reference/robot.md
Some information about wwi wasn't up to date.
> Fix documentation about wwi

- docs/reference/robot.md
"sensors requests" -> "sensor requests"
Describe the bug you are fixing, the new feature your are introducing or the enhancement you are proposing.
This pull-request fixes issue #
**Tasks**
https://cyberbotics.com/doc/guide/getting-started-with-webots?version=develop
If this pull-request includes any new robots/simulations/etc. add one or more screenshots of the result.
Add any other context about the pull-request here.
> Fix small typo.

- resources/web/wwi/protoVisualizer/Parameter.js
Nodes inserted in a MFNode were being inserted at the root level rather than respecting the IS chain link
> Fix MFNode insertion in web PROTO

- resources/web/wwi/NodeSelectorWindow.js
Support the insertion of proto devices in Robots
> WebotsJS: Add devices to robots

- resources/web/wwi/protoVisualizer/Vrml.js
> WebotsJS: default value MF

- projects/devices/robotis/protos/RobotisLds01.proto
> Fix variable name

- docs/reference/changelog-r2023.md
- src/webots/nodes/WbSliderJoint.cpp
> Fix parent when exporting SliderJoint to URDF

- resources/web/wwi/WebotsView.js
Translate the device and the nodes that need a robot ancestor such that they always appear above the floor:
To review along: https://github.com/cyberbotics/webots-cloud/pull/107
Note: I will modify the `testing.webots.cloud` in `webots.cloud` before merging.
https://testing.webots.cloud/run?version=R2023b&url=https://github.com/cyberbotics/webots/blob/doc-add-robots/projects/robots/gctronic/elisa/protos/Elisa3DistanceSensor.proto&type=undefined
https://testing.webots.cloud/run?version=R2023b&url=https://github.com/cyberbotics/webots/blob/doc-add-robots/projects/robots/franka_emika/panda/protos/PandaHand.proto&type=undefined
> WebotsJS: Translate device

- resources/web/wwi/WebotsView.js
I already pushed the change on webots.cloud
> Fix naming of php file

- projects/joints/protos/Hinge2JointWithBacklash.proto
- projects/joints/protos/HingeJointWithBacklash.proto
- projects/joints/webots.yaml
- resources/web/wwi/nodes/WbBallJoint.js
- resources/web/wwi/nodes/WbDevice.js
- resources/web/wwi/nodes/WbHinge2Joint.js
- resources/web/wwi/nodes/WbHingeJoint.js
- resources/web/wwi/nodes/WbJoint.js
- resources/web/wwi/nodes/WbViewpoint.js
- resources/web/wwi/nodes/utils/WbBoundingSphere.js
- resources/web/wwi/protoVisualizer/Node.js
- resources/web/wwi/protoVisualizer/Vrml.js
- Fix viewpoint when there is no boundingSphere
- Fix wrong defaultValues in jointWithBacklash MFNode
- Fix `toJS` method when the node is a baseNode and not a proto
Test it here: https://testing.webots.cloud/run?version=R2023b&url=https://github.com/cyberbotics/webots/blob/fix-web-joint-with-backlash/projects/joints/protos/Hinge2JointWithBacklash.proto&type=undefined
Note that if you try to remove one of the jointsParameters it will break the proto. However it comes from the proto construction.
> WebotsJS: fix parameters bugs

- resources/web/wwi/WebotsView.js
The previous approach had two limitations:
- It was not working well when the boundingSphere center was under the floor
- The device "jumped" when first modifying the translation with the parameter window.
Now we are moving the floor under the object, which solved both issues
Try it out: https://testing.webots.cloud/proto
> WebotsJS: Fix devices position

- projects/samples/tutorials/protos/FourWheelsRobot.proto
> Fix missing version

- projects/samples/tutorials/protos/FourWheelsRobot.proto
> Update FourWheelsRobot.proto version

- resources/web/wwi/nodes/utils/WbTriangleMesh.js
Test it here: https://testing.webots.cloud/run?version=R2023b&url=https://github.com/cyberbotics/webots/blob/doc-add-bo/projects/devices/velodyne/protos/VelodyneHDL-64E.proto&type=undefined
> WebotsJS: Fix default texture mapping

- resources/web/wwi/WebotsView.js
Related to https://github.com/cyberbotics/webots-cloud/pull/110
> Remove ajax call

- resources/web/wwi/protoVisualizer/Parameter.js
Test it here: https://webots.cloud/run?version=R2023b&url=https://github.com/cyberbotics/webots/blob/develop/projects/appearances/protos/Grass.proto&type=undefined
> Fix render on regeneration

- resources/web/wwi/protoVisualizer/Node.js
> Fix urls generated by js in the body of a proto

- src/webots/nodes/utils/WbNodeOperations.cpp
Fix #5913:
do not reconnect fields of newly inserted PROTO if the insertion trigger an ancestor node regeneration.
Additionally, also apply the same mechanism to postpone the regeneration as done in the mfnode case.
> Fix crash when inserting in node in regenerating PROTO paramter

- resources/web/wwi/FloatingProtoParameterWindow.js
This import is no longer used and do not exist anymore which was causing an error
> Fix dependency error

- projects/objects/kitchen/utensils/protos/Spoon.proto
> Missing IS

- projects/objects/factory/valves/protos/LargeValve.proto
- projects/objects/factory/valves/protos/SmallValve.proto
> FLU fix joint of valves

- docs/reference/changelog-r2023.md
- projects/robots/dji/mavic/controllers/mavic2pro_patrol/mavic2pro_patrol.py
The drone should not change altitude when printing the log that the target has been reached.
> Fix `mavic2pro_patrol` controller

- docs/reference/changelog-r2023.md
- projects/default/resources/Makefile
> Bump windows version of sumo

- projects/robots/clearpath/moose/protos/Moose.proto
I broke the moose wheels in #6006
> Fix moose wheels

- src/webots/nodes/WbCharger.cpp
Fix a compilation warning introduced in #6002.
> Fix nightly builds

- docs/reference/changelog-r2023.md
- src/controller/c/motion.c
Fixes https://github.com/cyberbotics/wrestling/discussions/57#discussioncomment-5467121
> Fixed clean-up of the motion library causing problems with the Python API

- docs/guide/starting-webots.md
- src/webots/gui/WbSingleTaskApplication.cpp
> Doc clear-cache

- docs/reference/changelog-r2023.md
- lib/controller/python/controller/lidar.py
> Fix python getRangeImageArray API function name

- docs/guide/introduction-to-webots.md
> Added technical user support documentation

- docs/reference/changelog-r2023.md
- src/webots/nodes/WbCamera.cpp
- tests/api/controllers/camera_recognition/camera_recognition.c
> Fix computation of Camera recognition object relative orientation

- docs/reference/changelog-r2023.md
- projects/objects/apartment_structure/protos/Window.proto
> Configurable window glass

- projects/samples/environments/indoor/worlds/complete_apartment.wbt
- projects/samples/environments/indoor/worlds/kitchen.wbt
> FLU: fix ceiling

- projects/robots/sony/aibo/worlds/aibo_ers7.wbt
Fixes the test worlds which [failed](https://github.com/cyberbotics/webots/actions/runs/4997446585/jobs/8952267685) last night thanks to #6136.
> Fixed test worlds

- resources/web/wwi/nodes/WbDistanceSensor.js
- resources/web/wwi/nodes/WbPose.js
- resources/web/wwi/nodes/WbTransform.js
Fix some leftover issues introduced with the pose node in webotsjs.
> Fix pose webotsjs

- docs/reference/changelog-r2023.md
Address https://github.com/cyberbotics/webots/pull/6026#discussion_r1211489058
> Improve ChangeLog entry text

- projects/robots/bitcraze/crazyflie/worlds/crazyflie_apartment.wbt
One url was not referring to `webots://`.
> Fix url test worlds

- docs/reference/changelog-r2023.md
- scripts/proto_formatter/README.md
- scripts/proto_formatter/proto_formatter.py
This new PROTO formatter script allows to automatically format the given PROTO file to get the correct block indentations.
> Add proto formatter script

- resources/web/wwi/NodeSelectorWindow.js
To be merged along https://github.com/cyberbotics/webots-cloud/pull/139
> Disallow add node

- resources/webots_classic.qss
I have missed that in the classic theme
> Fix node pane line edit

- resources/webots_classic.qss
- resources/webots_dusk.qss
- resources/webots_night.qss
> Fix classic theme

- resources/webots_classic.qss
> Fix background when choosing controller

- resources/webots_classic.qss
- resources/webots_dusk.qss
- resources/webots_night.qss
Fix #6211 
I checked all the QCheckBoxes and this was the only one that was not working.
> Fix video dialog QCheckBox

- projects/objects/balls/protos/RobocupSoccerBall.proto
- projects/objects/bathroom/protos/Toilet.proto
- projects/objects/bathroom/protos/WashingMachine.proto
- projects/objects/factory/containers/protos/MetalStorageBox.proto
I went through all protos (I may have missed some devices and slots) to fix #6221
> Fix bounding object scale

- src/controller/c/robot.c
Added a missing line feed and a couple of missing final dots in stderr messages from libController.
> Added missing line feed and final dots

- docs/reference/changelog-r2023.md
- src/webots/launcher/launcher.c
Address #6140.
This should fix a problem that several users are facing.
> Removed conflicting Qt5 environment variable on Windows

- docs/automobile/sumo-interface.md
- projects/default/controllers/sumo_supervisor/sumo_supervisor.py
> SUMO extern controller options

- docs/guide/installation-procedure.md
- docs/guide/setup-a-webots-project-repository.md
Update the size of the packets and the link towards the docker
> Doc update size

- docs/guide/web-streaming.md
> Remove open-roberta outdated exemple

- resources/web/wwi/X3dScene.js
The uselist was called on the wrong object
> Bug x3d uselist

- docs/guide/system-requirements.md
Add macOS 13 Ventura to the list of supported macOS versions.
n/a
**Tasks**
n/a
https://github.com/cyberbotics/webots/edit/released/docs/guide/system-requirements.md
n/a
n/a
> Add macOS 13 Ventura to the list of supported macOS versions

- Contents/Info.plist
- docs/js/showdown-extensions.js
- resources/version.txt
- scripts/packaging/webots_version.txt
- src/webots/core/WbApplicationInfo.cpp
- src/webots/gui/WbUpdatedDialog.cpp
> Bump version to R2023b-rev1

- resources/web/wwi/Parser.js
The parsing of these nodes was not adapted when we added a root node in the webotsjs scenetree
> Fix fog billboard js

- docs/reference/changelog.md
> Fix missing changelog reference

- resources/web/wwi/nodes/WbLookupTable.js
- resources/web/wwi/nodes/WbPropeller.js
> Fix missing node type

- scripts/icon_studio/controllers/icon_creator/objects.json
Entries where accidentally removed in #6295.
> Restore icon_studio/object.json

- projects/samples/howto/url/controllers/url/url.c
- projects/samples/howto/url/worlds/url.wbt
- resources/translations/wb_de.ts
- resources/translations/wb_es.ts
- resources/translations/wb_fr.ts
- resources/translations/wb_generic.ts
- resources/translations/wb_it.ts
- resources/translations/wb_ja_JP.ts
- resources/translations/wb_zh_CN.ts
- resources/web/wwi/ProtoManager.js
- tests/api/worlds/camera_color.wbt
- tests/protos/protos/Bc21bCameraProto.proto
Fix https://github.com/cyberbotics/webots/issues/6341
I've been careful while updating URL and checked if the new link was still ok, so it should be alright. Notice a change of extension of 6 images of a background.
I've not been too aggressive in the compatibility tools (script, world file) that still have old number, because I believe it's better to leave them as it.
> Fix version number to 2023b

- docs/reference/changelog-r2023.md
- src/webots/nodes/WbIndexedLineSet.cpp
Fix #6338 
CoordIndex was not checked if empty before iterating on it
> Fix crash IndexedLineSet

- resources/projects/libraries/qt_utils/motion_editor/MotionWidget.cpp
- resources/projects/libraries/qt_utils/motion_editor/PoseWidget.cpp
Fixes deprecated Qt methods (deprecated in Qt 6.6.0)
> Fix deprecated Qt methods

- .github/workflows/test_suite_mac.yml
Attempt to fix the failure of the macOS builds
> Fixed test suite on macOS

- projects/robots/gctronic/e-puck/protos/docs/e-puck.md
> Fixed e-puck speed

- .github/ISSUE_TEMPLATE/config.yml
Replaced Stackoverflow with Robotics StackExchange.
> Improve bug report template

- docs/generate_thumbnails.py
- docs/reference/changelog-r2024.md
Specify UTF-8 encoding for opening files. Required to support emojis (for example in `docs/blog/Webots-2019-b-release.md`.
**Tasks**
> Fix Thumbnail Generation

- .github/workflows/test_suite_linux.yml
- tests/api/controllers/display/display.c
- tests/lib/ts_assertion.h
Slightly increase tolerance to accommodate Mesa's latest software-only GL driver.
> Fix CI test suite failure with display.wbt on ubuntu-latest

- .github/workflows/tests_sources.yml
Build optimized/release `cppcheck` so tests run *much* faster.
> Fix slow source testing

- scripts/converter/convert_nue_to_enu_rub_to_flu.py
- tests/sources/test_clang_format.py
- tests/sources/test_cppcheck.py
- tests/sources/test_header_version.py
- tests/sources/test_textures.py
Fix/workaround issues that prevented source tests from passing on my local machine.
I can't promise that this is sufficient to make them work for all developers/environments, but it should make them work  for *more* of them.
> Fix-test-sources-to-work-locally

- dependencies/Makefile.linux
- scripts/install/linux_compilation_dependencies.sh
- src/webots/Makefile
Don't download openal lib from cyberbotics.com. Use the system's lib instead.
> Fix-to-include-system-openal

- .github/workflows/test_suite_linux_develop.yml
- projects/vehicles/plugins/robot_windows/automobile_window/AbstractWidget.cpp
- projects/vehicles/plugins/robot_windows/automobile_window/GeneralInformationWidget.cpp
- scripts/install/linux_compilation_dependencies.sh
- scripts/install/linux_runtime_dependencies.sh
The PR aims to address issues related to building Debian packages on Ubuntu, as well as Windows installer packages.
**Tasks**
> Fix main branch builds

- projects/samples/robotbenchmark/include/robotbenchmark.h
- src/controller/c/robot.c
- src/webots/gui/WbNewProtoWizard.cpp
- src/webots/scene_tree/WbBoolEditor.cpp
The PR aims to address issues related to building Windows installer packages.
**Tasks**
> Fix Windows build

- scripts/install/linux_compilation_dependencies.sh
- scripts/install/linux_runtime_dependencies.sh
This PR reverts #6736 on develop as planned (see #6736 for details).
> Remove Support for Ubuntu 20.04 in Dependency Installation Scripts

- src/webots/launcher/webots-linux.sh
Lanching Webots on x11 server solves the issues.
Fixes #6732
Fixes #6733
**Tasks**
> Launch Webots on x11 server

- docs/blog/Webots-2025-a-release.md
- docs/guide/installation-procedure.md
- docs/reference/changelog-r2023.md
- docs/reference/changelog-r2025.md
- projects/samples/howto/url/controllers/url/url.c
- projects/samples/howto/url/worlds/url.wbt
- resources/osm_importer/config.ini
- resources/osm_importer/elevation.py
- resources/osm_importer/utils/misc_utils.py
- resources/osm_importer/webots_objects/barrier.py
- resources/osm_importer/webots_objects/road.py
- resources/translations/wb_de.ts
- resources/translations/wb_es.ts
- resources/translations/wb_fr.ts
- resources/translations/wb_generic.ts
- resources/translations/wb_it.ts
- resources/translations/wb_ja_JP.ts
- resources/translations/wb_zh_CN.ts
- resources/web/wwi/NodeSelectorWindow.js
- resources/web/wwi/Progress.js
- resources/web/wwi/ProtoManager.js
- resources/web/wwi/proto_viewer.js
- src/webots/vrml/WbProtoManager.cpp
> Regenerate translations

- src/wren/FileImport.cpp
> backport from the develop branch

- projects/vehicles/protos/abstract/SimpleVehicle.proto
There was a small typo in the SimpleVehicle.proto where "showing" was written wrong.
> Fixing a typo in SimpleVehicle.proto

- docs/reference/changelog-r2025.md
- src/webots/scene_tree/WbExtendedStringEditor.cpp
Found this while investigating another issue; looks like a typo.
**Tasks**
> Fix Physics Plugin Search in Extra Projects
