src/webots/nodes/WbSolid.cpp
src/webots/nodes/WbSolid.hpp

The `&` was not sanitized correctly in solid names when exported in x3d and causes XML parsing errors.
It aims to fix https://github.com/RoboCup-Humanoid-TC/webots/issues/200.

Fix export of & in x3d

---

src/webots/scene_tree/WbSceneTree.cpp
src/webots/scene_tree/WbTreeView.cpp
src/webots/scene_tree/WbTreeView.hpp

Fixes #3169. Webots now updates the context menu before it is shown in the scene tree.

Fix Context Menu Refresh

---

scripts/packaging/files_core.txt

Addresses issue #3179.
It appears that for windows it's necessary to be verbose and include all folders.

Fix windows nightly build

---

.github/workflows/test_suite_linux.yml
.github/workflows/test_suite_linux_develop.yml
.github/workflows/test_suite_mac.yml
.github/workflows/test_suite_mac_develop.yml
.github/workflows/test_suite_windows.yml
.github/workflows/test_suite_windows_develop.yml
scripts/packaging/sync_controller_lib.sh

We need this one #3079 on the master as well, at least until the new release.
In addition:
- it doesn't upload Windows header files (since there are already managed by Linux and macOS and it seems Windows has different line endings)
- it creates a branch if it doesn't exist
- it uploads Linux shared libraries only from Ubuntu 18.04 (shared libraries from Ubuntu 18.04 and 20.04 are not binary the same, so the script generates a diff otherwise)

Publish libcontroller from master branch

---

.github/workflows/tests_sources.yml

These tests were causing PEP8 failures with python 3 code, such as some f-strings.
Since Python 2.7 is deprecated since January 2021, we should get rid of it.

Removed obsolete Python 2.7 tests

---

.github/workflows/tests_doc.yml
.github/workflows/tests_sources.yml

I don't understand the need for launching the sources and doc tests on the `ready_for_review` event, given that there is no code modification at this point and tests are run on each commit (`synchronize` event). We would save time by disabling this.

Don't fire tests on ready_for_review event

---

docs/reference/changelog-r2021.md
src/webots/control/WbControlledWorld.cpp

Replaces #3005.
Fixes: #3000 and #1903
> If the controller died, it can't call the cleanup function, and when I restart it, I get a error message from webots because he think that the controller is still running, so he can't find a spot for the new incoming connection.
> It simply remove the dead controller connection as usual, then recreate a new one.
The trick is to use the name of the robot to know which dead controller should be kill.
Otherwise, if no name is provided, the code execute as usual (scanning for free spot).
In case a single extern controller is defined, then the robot name is not needed and the currently connected controller is terminated and reconnected.

Fix reconnecting extern controllers

---

docs/reference/changelog-r2021.md
resources/wren/shaders/lens_distortion.frag

Fix #3068: show black pixels instead of repeating closest visible pixel colour when applying lens distortion.
Example with FOV 1.05, radialCoefficients [-0.26, -0.26]. 
Previous:
Now:

Fix border color for lens distortion

---

src/webots/vrml/WbProtoTemplateEngine.cpp

**Addresses**
Fixes #3199.
While Lua support is maintained, the formatting of fields and context has to be converted from JavaScript statements to Lua-friendly ones. Objects `{key: value}` are translated to tables `{key = value}`. If however the colon appears inside the value, it would also get replaced.
The proper way to handle it might be to use a regular expression like: `/(?<=\\w):\\s+(?=[['{\\d\\w-])/g` so that only the colons after the keys are replaced. 
The expression would specify a colon preceded by:
- word
followed by a space and:
- `[` : if value is a MFField
- `{`: if value is a Vector2/Vector3/SFNode
- `\\d`: if value is a SFFloat/SFInt
- `'`: if value is a string
- `-` if value is a negative SFFloat/SFInt.
- `\\w` if value is a word (true, false, undefined) …

Fix field/context conversion from JavaScript to Lua

---

docs/reference/speaker.md

It is written in the documentation that the speaker supports all types of sound extensions but this is not true in practice. Any sound with an extension other than .wav will cause a crash or a `Impossible to play '%1'. Make sure the file format is supported (8 or 16 bits, mono or stereo wave)`

Correct supported sound extensions

---

docs/reference/changelog-r2021.md
src/webots/scene_tree/WbTreeItem.cpp

Fix https://github.com/cyberbotics/webots/issues/3157
However, the fix is not the right way to do it, but I don't which one is the good one : 
- add "Solid" in either WbNodeUtilities::isDeviceTypeName or WbNodeUtilities::isSolidDeviceTypeName
- or remove the condition that this PR modify. In fact I don't understand why should we limit the display of the name to certains types. As long as the node have a "name" field, we should be good to display it.

Add the name of a solid next to it in tree

---

docs/reference/changelog-r2021.md
projects/robots/softbank/nao/protos/Nao.proto
src/webots/nodes/WbCharger.cpp
src/webots/nodes/WbLed.cpp
src/webots/nodes/utils/WbFieldChecker.cpp
src/webots/vrml/WbMFColor.cpp
src/webots/vrml/WbRgb.hpp
src/webots/vrml/WbSFColor.cpp
src/webots/vrml/WbSFColor.hpp

Fix #3183:
do not allow use of invalid SFColor values in PROTO parameters.
If invalid values are defined, they are clamped to the valid range [0.0, 1.0] and an error is printed in the console.

Fix crash due to invalid SFColor value

---

docs/reference/changelog-r2021.md
src/webots/nodes/utils/WbTemplateManager.cpp

test world: [bug_crash_kinetic_regeneration.zip](https://github.com/cyberbotics/webots/files/6711975/bug_crash_kinetic_regeneration.zip)
If the world file includes a PROTO  like the following:
```
#VRML_SIM R2021b utf8
PROTO MyHingeJoint
[
field SFNode                                 jointParameters   NULL
field MFNode                                 device            [ ]
field SFNode                                 endPoint          NULL
]
{
%{
local a = fields.endPoint.value;
}%
HingeJoint {
jointParameters IS jointParameters
device IS device
endPoint IS endPoint
}
}
``` 
where a field is a template regenerator (specifically of type Solid like the `endPoint` of a `HingeJoint`). If this PROTO is used in kinematic mode (i.e the `Solid` lacks a `Physics` node), when the …

Fix kinematic simulation triggering a field regeneration which leads to a crash

---

docs/blog/Webots-2021-b-release.md

https://www.cyberbotics.com/doc/blog/Webots-2021-b-release?version=documentation-acknowledgements
Added a section for acknowledgements. Don't know where is the best place to put it, if before or after the extra goodies.
The names are contributions (big or small) which have been successfully merged since the previous release (for repo webots, webots-ros, webots-ros2). Any other I should include?
If @sishamilton manages to conclude the altimeter feature before the release it might be nice to mention it as well.

Add acknowledgements to r2021b-blog

---

projects/samples/robotbenchmark/highway_driving/worlds/highway_driving.wbt
projects/samples/robotbenchmark/humanoid_marathon/worlds/humanoid_marathon.wbt
projects/vehicles/worlds/CH_Morges.wbt
projects/vehicles/worlds/village_center.wbt
projects/vehicles/worlds/village_realistic.wbt

The merge of the JS conversion PR broke the world update, a couple of things are provided out of order in the world file and a trailing empty line after the removal of a deprecated hidden field.

Fix world update after JS PR

---

docs/reference/changelog-r2020.md
docs/reference/changelog-r2021.md
docs/reference/supervisor.md
src/controller/c/supervisor.c

The `contact_points[descendants].last_update` was initialized to a random value, sometimes higher than 0, making the caching mechanism break.
Also, delete deprecated documentation:
https://www.cyberbotics.com/doc/reference/supervisor?version=fix-get-contact-points#wb_supervisor_node_get_contact_points

Fix `wb_supervisor_node_get_contact_points` caching

---

docs/reference/robot.md

As discussed in #3235.
See result: https://cyberbotics.com/doc/reference/robot?version=hotfix-remove-deprecated-methods-from-doc&tab-language=python#wb_robot_get_device

Removed deprecated python methods from the doc

---

docs/reference/supervisor.md

Address #3207: at the end I moved the node export function in a dedicated section given that the import from string functions are methods of the `Field` class and not `Node` class.

Documentation enhancement supervisor node export

---

projects/objects/road/protos/RoadIntersection.proto

Fix humanoid-marathon missing road

---

src/webots/gui/WbRobotWindow.cpp

Fix #3249: adjust regular expression for extracting the `src` from the `script` tag that was not supporting other attributes like `type`.

Fix regular expression not supporting script tag attributes

---

docs/guide/object-buildings.md
projects/objects/buildings/protos/RandomBuilding.proto
projects/objects/buildings/protos/SimpleBuilding.proto
resources/osm_importer/webots_objects/building.py

This fixes several errors popping-up in:
- `webots/projects/vehicles/worlds/CH_Vens.wbt`: Error opening https://raw.githubusercontent.com/cyberbotics/webots/R2021b/projects/objects/buildings/protos/textures/old_brick_wall.jpg
- `webots/projects/vehicles/worlds/village_winter.wbt`: Error opening https://raw.githubusercontent.com/cyberbotics/webots/R2021b/projects/objects/buildings/protos/textures/red_brick_wall.jpg
- `webots/projects/vehicles/worlds/village.wbt`: Error opening https://raw.githubusercontent.com/cyberbotics/webots/R2021b/projects/objects/buildings/protos/textures/old_brick_wall.jpg
It is better to remove these two textures from the `SimpleBuilding` proto as they are not really building textures (and they don't look very nice on a building).

Fixed bad texture URLs

---

scripts/packaging/webots_distro.c

It is usually better to install Webots for all users (if the user has administrator privileges):
Moreover, this PR allows users to specify the type of installation also on the command line.

Recommend for all users installation on Windows

---

.github/workflows/test_suite_windows.yml
.github/workflows/test_suite_windows_develop.yml
docs/guide/controller-programming.md
docs/guide/running-extern-robot-controllers.md
docs/guide/using-python.md
lib/controller/.gitignore
projects/default/libraries/vehicle/Makefile
projects/robots/robotis/darwin-op/libraries/Makefile
scripts/install/bash_profile.windows
scripts/install/linux_compilation_dependencies.sh
scripts/packaging/files_core.txt
src/controller/Makefile
src/controller/python/Makefile
src/webots/control/WbLanguageTools.cpp

Python 2.7 has been deprecated for long now. We should get rid of it.
Fixes #3310.

Drop Python 2.7

---

projects/samples/robotbenchmark/highway_driving/controllers/highway_driving_benchmark/highway_driving_benchmark.py

Fixes https://github.com/cyberbotics/webots/issues/3293. Give a proper warning concerning the missing module.

Fix shapely module error in `highway_driving_benchmark.wbt`

---

projects/robots/mobsya/thymio/worlds/thymio2_ball.wbt
projects/robots/mobsya/thymio/worlds/thymio2_pen.wbt

Fixes https://github.com/cyberbotics/webots/issues/3311.
The default controller `thymio2_aseba` is not integrated with the robot window therefore these two worlds cannot be played without external software. It is too premature to remove this external dependency altogether but this change at least makes the worlds playable.
The world `thymio2.wbt` already uses this controller.

Replace default controller for `thymio2_pen.wbt` and `thymio2_ball.wbt`

---

docs/reference/changelog-r2021.md
src/webots/nodes/WbPointLight.cpp
src/webots/nodes/WbPointLight.hpp

Fixes https://github.com/cyberbotics/webots/issues/3302.
Contrary to other light nodes, the PointLight has a `location` field which isn't otherwise reset. I believe during a reset it is desirable for the light to return to whatever state it was previously set to (be it at `__init__` or another `stateid`).

Fix pointlight reset

---

projects/samples/robotbenchmark/highway_driving/plugins/robot_windows/highway_driving/highway_driving.html
projects/samples/robotbenchmark/humanoid_marathon/plugins/robot_windows/humanoid_marathon/humanoid_marathon.html
projects/samples/robotbenchmark/humanoid_sprint/plugins/robot_windows/humanoid_sprint/humanoid_sprint.html
projects/samples/robotbenchmark/inverted_pendulum/plugins/robot_windows/inverted_pendulum/inverted_pendulum.html
projects/samples/robotbenchmark/maze_runner/plugins/robot_windows/maze_runner/maze_runner.html
projects/samples/robotbenchmark/obstacle_avoidance/plugins/robot_windows/obstacle_avoidance/obstacle_avoidance.html
projects/samples/robotbenchmark/pick_and_place/plugins/robot_windows/pick_and_place/pick_and_place.html
projects/samples/robotbenchmark/pit_escape/plugins/robot_windows/pit_escape/pit_escape.html
projects/samples/robotbenchmark/robot_programming/plugins/robot_windows/robot_programming/robot_programming.html
projects/samples/robotbenchmark/square_path/plugins/robot_windows/square_path/square_path.html
projects/samples/robotbenchmark/visual_tracking/plugins/robot_windows/pan_tilt_camera_view/pan_tilt_camera_view.html
projects/samples/robotbenchmark/visual_tracking/plugins/robot_windows/visual_tracking/visual_tracking.html
projects/samples/robotbenchmark/wall_following/plugins/robot_windows/wall_following/wall_following.html

The JavaScript "for of" construct doesn't work on Windows where the JS engine is older than the one on Linux and macOS. Therefore, we have to revert to an older construct to iterate on items.

Fix javascript construct

---

projects/objects/cabinet/protos/Cabinet.proto
projects/objects/cabinet/protos/CabinetDoor.proto
src/webots/scene_tree/WbAddNodeDialog.cpp

Fixes https://github.com/cyberbotics/webots/issues/3337.
The MRE of this bug is this PROTO
```
PROTO Cabinet [
field SFNode   primaryAppearance   PaintedWood {}    # Defines the primary appearance.
field SFNode   secondaryAppearance PaintedWood {}    # Defines the secondary appearance.
]
{
Solid {
children [
CabinetDrawer{
primaryAppearance IS primaryAppearance
secondaryAppearance IS secondaryAppearance
}
CabinetDoor {
primaryAppearance IS primaryAppearance
secondaryAppearance IS secondaryAppearance
}
]
}
}
```
The reason for the bug is that although `CabinetDoor` has a `primaryAppearance` parameter, this is not used anywhere in the body of the PROTO. As such, when removing the default node and attempting to add a new one (in the parent PROTO `Cabinet`), the candidates …

Fix cabinet `primaryAppearance`

---

projects/samples/howto/inverted_pendulum/worlds/inverted_pendulum.wbt

Fixes https://github.com/cyberbotics/webots/issues/3331.
Not exactly a fix, but I've noticed that choosing a size of 1000 or less and the issue virtually disappears. For the purpose of this world, even 100 would've largely sufficed.
The problem appears to be only affect `IndexedFaceSets` which are defined as a single quad (or 2 triangles) which are very long. I don't think it's very common to have a single 10 km-sided triangle. The only case I can think of is a 10 km straight `Road`. However after testing one, the issue doesn't show up at all even for a length of 100 km. Roads however are built as 8 triangles though, so even this case doesn't really fit the bill.
I've resized the floor so that the distortion doesn't appear, but I'm not sure whether it's practically useful …

"Fix" floor distorsion

---

src/webots/engine/WbSimulationWorld.cpp
src/webots/nodes/utils/WbDownloader.cpp

Several improvements to webots when worlds use URLs
**Tasks**

Improve Urls handling

---

projects/objects/cabinet/protos/CabinetDoor.proto
projects/objects/cabinet/protos/CabinetDrawer.proto
projects/robots/softbank/nao/worlds/nao_room.wbt

Fixes #3354
Removed the `Physics` of the node before the HingeJoint to which the door / drawer is attached to.

Fix Cabinet doors and drawers physics

---

src/webots/gui/WbRobotWindow.cpp

These jquery include files are not distributed any more, so including them from Webots was wrong.
Since they were not included in the distribution, removing them shouldn't break anything.

Cleanup useless/broken jquery includes

---

resources/projects/plugins/robot_windows/generic/window_manager.js

Fixes #3358 
Reset the scroll position to zero when changing tab in Robot Window.

Reset scroll when changing tab in Robot Window

---

projects/samples/devices/controllers/force3d_sensor/force3d_sensor.c
projects/samples/devices/worlds/force3d_sensor.wbt

Fixes #3300 
In `force3d_sensor.wbt`, added information in the `info` field of the `WorldInfo` node, so that they are displayed in the Webots Guided Tour interface.

Add instructions for force3d_sensor.wbt

---

src/webots/editor/WbProjectRelocationDialog.cpp

Fixes https://github.com/cyberbotics/webots/issues/3292
Based on what I understood, `copyExternalProject` comes [into play](https://github.com/cyberbotics/webots/blob/8eeccb12a698624634b877da7d0d0c0c4e1df5f9/src/webots/editor/WbProjectRelocationDialog.cpp#L211-L212) only if `mExternalProjectPath` is defined, hence if [this](https://github.com/cyberbotics/webots/blob/8eeccb12a698624634b877da7d0d0c0c4e1df5f9/src/webots/editor/WbProjectRelocationDialog.cpp#L446-L454) point is reached. This is the case only if the skins folder would be inside the `protos` folder but according to `WbSkin`, the skins folder must be at the [root](https://github.com/cyberbotics/webots/blob/8eeccb12a698624634b877da7d0d0c0c4e1df5f9/src/webots/nodes/WbSkin.cpp#L405) (same level as worlds) hence it …

Fix relocation of Skins

---

src/webots/gui/WbRobotWindow.cpp

This fixes a wrong behavior of the robot window on Linux when resetting the `custom_robot_window_simple.wbt`: the series of numbers was wrong after the reset.
It also fixes the following warning occurring when resetting a simulation while a robot window is open on Linux and macOS:
```
Warning: Release of profile requested but WebEnginePage still not deleted. Expect troubles !
```

Fixed deletion of robot window on reset (Linux and macOS)

---

tests/default/controllers/test_suite_supervisor/test_suite_supervisor.py
tests/test_suite.py

This PR:
- improves the error reporting of the test suite.
- fixes PEP8 issues in python script
- disables the parser tests on Windows which were never working because the stderr and stdout redirection doesn't work.

Improved test suite scripts

---

projects/languages/python/controllers/driver/common.py
projects/languages/python/controllers/driver/driver.py
projects/languages/python/controllers/slave/runtime.ini
projects/languages/python/controllers/slave/slave.py

Fixes #3011.
Actually, I cannot reproduce #3011 on Linux any more. Everything works as expected.
I believe the original issue description was wrong, mentioning the deprecated `[environment variable with relative paths]` instead of `[environment variables with paths]`.
I modified the python example to illustrate how to use `PYTHONPATH` in a `runtime.ini` file which is a common problem that Python controller developers are facing.

Improve python example

---

.github/workflows/test_suite_linux_develop.yml
.github/workflows/test_suite_mac_develop.yml
.github/workflows/test_suite_windows_develop.yml
.github/workflows/tests_sources.yml

As develop and master have the same version name (R2021b) and we do not plan to add modification on develop until the end of FLU conversion, we can turn off the building of packages on develop.
Moreover having master and develop with the same version name is a bad idea as it causes conflict between the packages build on develop and those build on master during the upload to the release.

Disable building of packages on develop

---

src/webots/nodes/utils/WbDownloader.cpp

Webots was crashing when trying to play the world with SUMO (like `highway overtake`).
The cause was that some `QNetworkReplys` where deleted locally but there entry was not removed/set to null in the intermediary cache.

Fix bug sumo

---

.github/workflows/test_suite_linux_develop.yml
.github/workflows/test_suite_mac_develop.yml
.github/workflows/test_suite_windows_develop.yml
.github/workflows/tests_sources.yml

Since we are increasing the version number on develop in #3397, we can now revert #3388 once #3397 is merged.

Reverts #3388

---

src/controller/python/controller.i

Fixes #3158 and replaces #3176.
It seems to be a cleaner path than #3176.

Acquire the python GIL for all functions except Robot.step()

---

docs/reference/changelog-r2021.md
src/webots/control/WbLanguageTools.cpp
src/webots/control/WbLanguageTools.hpp

The python executable is not found on MacOS when launching Webots from the GUI (Spotlight, Finder, Dock). 
To fix that, we decided to hardcode the standard MacOS path to both python from python.org and python from homebrew in Webots.
It it does not work, a warning will be displayed, requesting the user to set the full path to his python executable in the preferences of webots.
Fix #3285.

Fix mac pythonpath

---

docs/reference/changelog-r2021.md
lib/controller/matlab/launcher.m

User-defined controllers may contain characters that MATLAB does not accept for scripts/function names, such as dashes. Use a temporary file for launching the controller, delete it afterwards.
This pull-request fixes issue #3403. Thanks to @jgvictores for testing.

Sanitize controller name in MATLAB launcher

---

docs/reference/changelog-r2021.md
projects/objects/traffic/protos/HighwaySign.proto

Fixes https://github.com/cyberbotics/webots/issues/3406.
I've added it to the changelog since it was already broken in 2021a.

Fix HighwaySign proto

---

docs/reference/changelog-r2021.md
resources/web/server/simulation_server.py

This pull request address a bug that happens in the line https://github.com/cyberbotics/webots/blob/eca5ec4ce5774d175a75601a9ff396d4cb633a94/resources/web/server/simulation_server.py#L310 of the simulation server script.
*Bug behavior*: the thread that run webots hang after the user disconnect and the webots process is terminated. Because of that there exists proccesses using the server's memory (can be checked using htop - multiple processes appears linked to the simulation_server.py script) that leads to slow down and problems with the simulation server overtime.
*Solution proposed*: Check if the webots process in terminated in the blocking 'for' loop. If the webots process is None (meaning that the user disconnected and the webots process was terminated or killed) the …

solve thread hanging after webots process finishes

---

docs/guide/running-extern-robot-controllers.md
src/controller/python/controller.i

Address #3414:
Setting `LD_LIBRARY_PATH` is needed also for python controllers in order to correctly load the generic robot window.
The documentation was previously changed in #2940.

Fixed issues with generic robot window

---

docs/guide/installation-procedure.md

Fix #3410:
on Ubuntu 18.04, if Webots is installed using the tarball the previous instructions were not sufficient to successfully create and playback a movie.
It seems strange that even on Ubuntu 20.04 the given instructions will work as for sure `ffmpeg` is required.
But I will check if there are some differences.

Adjust installation instructions for tarball

---

projects/samples/devices/controllers/pen/pen.c
src/controller/c/pen.c
src/webots/nodes/WbPen.cpp
src/webots/nodes/utils/WbPaintTexture.cpp
tests/api/controllers/distance_sensor_infra-red/distance_sensor_infra-red.c

Fixes https://github.com/cyberbotics/webots/issues/3411.
Although the ink density is a floating point value in the API, the value was cast into an `unsigned char` when sending it to webots. For small values of the random seed, the first value of `rand()` was consistently very small which resulted in it being approximated to zero. On Webots side, there was no check to verify if a division by zero was occurring, hence this first segment of the trail was actually a NaN so it persisted despite the evaporation.
Mac:
Windows:

Fix pen evaporation

---

projects/robots/softbank/nao/worlds/get_the_candies.wbt

It was reported [here](https://github.com/cyberbotics/webots/issues/3265), but contrary to the others that just need to be beautified, this one actually uses a deprecated field.

Fix `get_the_candies.wbt`

---

src/webots/nodes/utils/WbDownloader.cpp

When copying a object (non-Proto) with a DEF and a USE with urls inside, there was an infinite downloading popup.
This is because a node was deleted before it could finish checking that the URLs were in the cache.
When deleting a node with a WbDownloader, it is not enough to remove the downloads, we also need to decrement the number of total downloads.
Fix #3419

fix assets downloads on copy

---

scripts/install/msys.sh

This PR cleans-up the msys.sh script:
- remove the path to node binaries which are now removed from Webots.
- add path to Python, Java and MATLAB only if the corresponding environment variables are set.
- in case several python versions are installed, prefer python 3.8, then 3.9 and 3.7.

Removed path to node.js and cleaned-up

---

resources/web/wwi/Parser.js

The branch should be `released` when the variable is an empty string

Fix default url branch

---

docs/reference/changelog-r2021.md
src/webots/nodes/WbGeometry.cpp
src/webots/nodes/WbGeometry.hpp
src/webots/nodes/WbShape.cpp

If a shape has a fully transparent (tranparency = 1) appearance, it should not be visible by the cameras.
Fix #3405

Fix range finder with fully transparent objects

---

scripts/get_git_info/get_git_info.sh

Compute the branch name correctly if Webots is in a `HEAD detached` branch.
I wonder if we should add a default value to `branch.txt` and `repo.txt` in case the script fails to get them.
For example, in the case a user build Webots from the `source code.zip`package and so is not in a github repository and doesn't  already has raw.githubusercontent urls.
For the default repo, I would put `cyberbotics/webots`
For the default branch I do not really know between `master` and `released`

Fix branch.txt creation

---

scripts/packaging/publish_release.py

Publishing a nightly build failed (https://github.com/cyberbotics/webots/runs/3071646906?check_suite_focus=true) with this error message:
```
Creating release "Webots Nightly Build (14-7-2021)" with tag "nightly_14_7_2021" on commit "5569ee04f8b281e6f8077883657717f4e396f9f7"
Traceback (most recent call last):
File "scripts/packaging/publish_release.py", line 103, in <module>
prerelease=True)
File "/usr/local/lib/python3.6/dist-packages/github/Repository.py", line 1009, in create_git_tag_and_release
target_commitish=object,
File "/usr/local/lib/python3.6/dist-packages/github/Repository.py", line 1061, in create_git_release
"POST", f"{self.url}/releases", input=post_parameters
File "/usr/local/lib/python3.6/dist-packages/github/Requester.py", line 355, in requestJsonAndCheck
verb, url, …
```

Add exception handling in publish_release.py script

---

scripts/packaging/sync_controller_lib.sh

For example, Windows builds different binaries even though the source code hasn't changed. It generates unnecessary diff in the `webots-libcontroller` repository.
This PR makes the `sync_controller_lib.sh` script skip the execution if the libcontroller hasn't changed.

Don't publish the libcontroller if it hasn't changed since yesterday

---

scripts/icon_studio/controllers/icon_creator/icon_creator.py

Fix #3268:
`getbbox()` behavior with RGBA images changed in Pillow 7.1.0 and broke the `icon_studio` controller.

Fix icon_studio controller with Pillow >= 7.1.0

---

src/webots/editor/WbBuildEditor.cpp
src/webots/editor/WbProjectRelocationDialog.cpp
src/webots/editor/WbProjectRelocationDialog.hpp

Follow up #3368:
It seems also possible to merge the `copyProjects` and `copyExternalProjects` functions.

Enhancement project relocation

---

src/webots/nodes/WbLidar.cpp
src/webots/nodes/WbLidar.hpp

Optimization proposed by @ShuffleWire in #3476. Replaces #3487.
Replaced ` bool isRotating()` and `Qstring mActualType` by `bool mIsActuallyRotating`, so that the bool is computed once and not at each step (as `Lidar` type changes are applied only after save & reload).

Cleanup Lidar isRotating

---

docs/guide/samples-howto.md
docs/js/showdown-extensions.js

Fix #3491 
The problem is that showdown-extension.js only test if branch is undefined and not if the branch variable is empty.
Also fix some outdated information in `samples-howto`

Fix github urls on released

---

projects/default/controllers/ros/Ros.cpp

The `ros` default controller uses rate control in its `Ros::run()` function. But the rate control is based on a `ros::Rate` instance, which breaks when using simulated time, hence when providing following arguments to the controller: 
```bash
--synchronize
--clock
```
The [line 469 of file Ros.cpp](https://github.com/cyberbotics/webots/blob/c5637734a664733a585219c178eb753c0ff8f37b/projects/default/controllers/ros/Ros.cpp#L469) was modified to ensure WallTime is used in any case. Failing to use WallTime when enabling simulation time does not allow the sleep function to terminate.

`ros` default controller: based sleep on WallTime instead of simulated time.

---

src/wren/FrameBuffer.cpp

Replaces the `glMapBufferRange` and `memcpy` calls by `glGetBufferSubData` in `FrameBuffer.cpp`.

Replaced memcpy by glGetBufferSubData in FrameBuffer

---

src/webots/nodes/WbLidar.cpp

After having pinpointed by @lukicdarkoo in https://github.com/cyberbotics/webots/issues/3476
The `WbLidar::updatePointCloud` method is probably the biggest bottleneck (by far) in the LiDAR implementation:
https://github.com/cyberbotics/webots/blob/c5637734a664733a585219c178eb753c0ff8f37b/src/webots/nodes/WbLidar.cpp#L354-L381
**Details**
The optimization is made using three way : 
1) Factorize code that could be, to avoid re-computations. In particular find a way to move the condition like `if (mIsActuallyRotating)` outside the loop.
2) Use increment instead of multiplication : replace values of the form (expression) + (counter) * (increment). We initialize the variable to an initial one, and then add at each loop a fixed amount.
3) Replace cos() and sin() usage by an …

LIDAR point cloud generation optimisation

---

docs/guide/installation-procedure.md
docs/guide/tutorial-8-using-ros.md
scripts/packaging/webots_distro.c

Drop support of Debian package on Ubuntu 18.04.
It is already stated in the documentation that the Debian package works only on the latest Ubuntu LTS:
https://www.cyberbotics.com/doc/guide/installation-procedure#installation-on-linux
This should fix #3503 and #3486.

Create Debian package from Ubuntu 20.04

---

src/webots/control/WbLanguageTools.cpp

The changes introduced in #3402 cause the pythonpath to always be the python of the system.
However, it is not possible to completely revert #3402, otherwise python controllers would not work if Webots is launched from the GUI.
So now if:
- Webots is launched from the GUI: use the hardcoded, system pythonpath.
- Webots is launched from a terminal: use the default python command.

Python in virtual env, MacOS

---

docs/reference/motor.md

Mechanical differentials drive, as described in https://en.wikipedia.org/wiki/Differential_(mechanical_device) could be very easily simulated using coupled motor. As I just figured out, even if the main role of it is to change speed to avoid slip, it also ensure that each wheel receive the **same** torque (so, for a regular car, each 2 (lets say front) wheel receive half the motor torque). That fact is often overlooked, seen as a drawback for many application (if a wheel slip, the other stop, cause no torque), but for simulation it actually awesome !
Been trying it on my project with a 4*4 configuration, and work really fine !
This is why that fact could be added in the doc.
However I do feel that my explanation is not very clear, English not been my mother-thong... feel free to update !

Add note about coupled-motor usage in differentials

---

src/webots/maths/WbQuaternion.hpp

This causes some undefined behaviours.
For example, if Webots is compiled in the debug mode, the following world will crash Webots after pressing Alt+1 (top view):
```
#VRML_SIM R2021b utf8
WorldInfo {
}
Viewpoint {
orientation 0 1 0 1.5707996938995747
position 0 0 6
}
```
with error:
```
webots-bin: maths/WbRotation.cpp:24: void WbRotation::fromQuaternion(const WbQuaternion&): Assertion `std::abs(sqrt(q.x() * q.x() + q.y() * q.y() + q.z() * q.z() + q.w() * q.w()) - 1) < 0.0000000001' failed.
./webots: line 90: 121749 Aborted                 (core dumped) "$webots_home/bin/webots-bin" "$@"
```
It doesn't happen with the released version though, the compiler manages to handle it somehow. However, it might cause some unwanted side-effects.

Fix matrix to quaternion conversion

---

docs/reference/changelog-r2021.md
src/webots/gui/WbDragTransformEvent.cpp
src/webots/gui/WbDragTransformEvent.hpp

When doing Shift+Mouse(left) drag on a Solid, Webots currently assumes that it has no parent Transform and is a child of root. Therefore, if it does have a parent Transform, the Solid is wrongly moved (#3523).

Hotfix shift+left drag

---

docs/reference/changelog-r2021.md
src/webots/control/WbControlledWorld.cpp
src/webots/nodes/WbRobot.hpp

Fix #3420:
properly notify `WbRobot` instance when an extern controller is restarted.
Remove the unused signal `WbRobot::controllerRestarted`.

Fix updating robot window on extern controller restart

---

docs/reference/changelog-r2021.md
src/controller/python/controller.i

As reported by a user on discord, currently the data retrieved using `getPointCloud` python API is no longer accessible.
The change done in https://github.com/cyberbotics/webots/pull/3322 broke the API. Although at the time I'm sure it prevented the crash of the `enable_all_lidars.py` controller from happening ( in `sumo_interface_example.wbt`, mentioned here https://github.com/cyberbotics/webots/issues/3281), now even after reverting the change the controller doesn't appear to crash any longer. So it was either something else provoking it to begin with, or I don't know.
It can be tested using this world: [WebotsProject.zip](https://github.com/cyberbotics/webots/files/6961390/WebotsProject.zip)

Hotfix inaccessible points in `getPointCloud` python API

---

docs/reference/robot.md

Address #3554: fix the documentation to properly document how the `Robot.controllerArgs` MFString items are passed to the controller program.
This works the same independently from the programming language.

Fix Robot.controllerArgs documentation

---

projects/objects/trees/protos/Forest.proto

Fixes #3557 (fully).
The trees should actually never cast shadows as they are semi-transparent.

Fixed forest shadow

---

docs/reference/camera.md

Fix example of `Camera.getImageArray`.
* check if `image` is valid: if called before the first sampling period is expired the `image` value can be `None`
* fix `print` instruction not working with Python3
* fix indentation

Fix Camera.getImageArray example

---

docs/reference/changelog-r2021.md
src/webots/nodes/WbBackground.cpp
src/webots/nodes/WbImageTexture.cpp
src/webots/nodes/utils/WbUrl.cpp
src/webots/nodes/utils/WbUrl.hpp
src/webots/scene_tree/WbSceneTree.cpp

When using the `convert to base node` option, textures and meshes defined with urls should not be saved locally.
This pull-request fixes issue #3513

Fix convert to base nodes for textures defined with URLs

---

src/webots/wren/WbTranslateRotateManipulator.cpp
src/webots/wren/WbTranslateRotateManipulator.hpp

Fix wren nodes initialization and cleanup introduced in #3540.
It seems there are two issues:
* if manipulator doesn't have rotations handles, the `mRotationLineTransform` and `mRotationDoubleArrowTransform` are not initialized to NULL and could cause Webots to crash when deleting them in `~WbTranslateRotateManipulator`.
* the material used to display the black line and double arrow is not deleted causing an assertion fault:
```webots-bin: Scene.cpp:99: void wren::Scene::reset(): Assertion `!PhongMaterial::cachedItemCount()' failed.```
This seems the cause of the test suite failure in  #3566.
Additional assertion and checks are added to prevent misusing these nodes.

Fix missing initialization of new rotation handles nodes

---

tests/test_suite.py
tests/with_rendering/controllers/billboard/billboard.c

Change the mode of the billboard test to fast.
However, the saving of screenshots is not synchronous (from the supervisor at least) and so we cannot be sure that the images are saved when the test tries to access them. That is why it was necessary to increase the size of the waiting loop if we wanted to run in fast mode (the supervisor exits the loops as soon as it detects that the images are ready).

Billboard test to fast mode

---

projects/objects/solids/protos/SolidBox.proto

Convert `SolidBox` from LUF to FLU: adapt texture mapping to produce the same results as before.

FLU: Convert SolidBox

---

scripts/install/bashrc.linux

It makes other packages crash. For example, RViz loads the Webots Qt library instead of the system Qt library. A developer should be responsible for configuring the `LD_LIBRARY_PATH` environment variable.

Avoid changing the `LD_LIBRARY_PATH` environment in the `.bashrc`

---

.github/workflows/test_suite_windows.yml
.github/workflows/test_suite_windows_develop.yml
scripts/install/msys64_installer.sh

Remove some debug statements and cleaned-up code after #3621.
We need to keep Qt5 installation into the installation script otherwise it breaks the manual installation instructions.

Clean-up Windows CI build

---

docs/reference/changelog-r2021.md
src/webots/nodes/WbCone.cpp
src/webots/nodes/WbCylinder.cpp

Fix #3643 
It seems like `setPickable` was missing in both `buildWrenMesh`functions

Fix pickable cone and cylinder

---

src/webots/nodes/WbMesh.cpp

When adding a local mesh via the scenetree, the new mesh was not pickable.
This PR fix that.

Fix pickable local mesh

---

resources/web/wwi/Parser.js
resources/web/wwi/Toolbar.js

In the streaming viewer, if the simulation was playing and the streaming viewer was launched as `broadcast`, the simulation was paused after the loading instead of resuming.
#Fix https://github.com/cyberbotics/webots_ros2/issues/299

Fix broadcast restore state when ready

---

docs/guide/installation-procedure.md
docs/guide/tutorial-8-using-ros.md

Address #3672:
back port text from develop branch specifying which Webots package is compatible with given ROS version in the R2021b documentation.

Documentation improve description of ROS support

---

scripts/install/linux_runtime_dependencies.sh
src/webots/Makefile

It seems the libusb library is not needed to link and execute Webots on Linux.
Moreover this library is not available on the JuMax HPC and it is a problem to compile Webots there.
So, I would suggest to remove it.

Remove libusb dependency on Linux

---

.github/workflows/test_suite_windows.yml
.github/workflows/test_suite_windows_develop.yml
scripts/install/bash_profile.windows

It seems the openjdk chocolatey package was silently upgraded from version 16 to version 17 without notice. Hence the openjdk-16.0.2 folder was not existing any more, and that broke our build process. Since the openjdk16 package doesn't exist, I upgraded to openjdk17 with the hope it will be more stable than the plain openjdk package which may be upgraded again in the future to version 18 or so. I also updated the [wiki](https://github.com/cyberbotics/webots/wiki/Windows-Optional-Dependencies/_compare/65c2be9769423f9cd7325b4a212cd6f4f4f8f617).

Attempt to fix Window CI build

---

docs/guide/ure.md
docs/reference/changelog-r2021.md
projects/objects/factory/conveyors/protos/ConveyorBelt.proto
projects/robots/universal_robots/protos/UR10e.proto
projects/robots/universal_robots/protos/UR3e.proto
projects/robots/universal_robots/protos/UR5e.proto
projects/robots/universal_robots/worlds/ure.wbt
projects/samples/devices/worlds/track.wbt
src/webots/engine/WbSimulationCluster.cpp
src/webots/nodes/WbTrack.cpp
tests/api/worlds/supervisor_node_set_joint_position.wbt

This PR also fixes a Track bug that existed even before R2021b. The tracks were not handling objects placed on top properly.
Before:
```
<-- force
_______________
|_______________|   
<-- force
```
Now:
```
force -->
_______________
|_______________|    
<-- force
```

ENU/FLU: Convert universal robots

---

resources/web/wwi/Stream.js

I saw the unused `onstdout` and `onstderr` callbacks in the webots.js view component. Probably they were intended to be used. 
#3711
**Tasks**
Unfortunately, currently the output with color is not wrapped properly, I already asked on stackoverflow why this is like it is (see https://stackoverflow.com/questions/69336052/console-log-with-color-doesnt-wrap-first-line).
If there is a fix for that problem, I will push it, otherwise, I would probably don't use colors in the default implementation of `onstdout` or `onstderr`.

Use stdout and stderr callbacks

---

docs/reference/changelog-r2021.md
src/webots/nodes/utils/WbSolidUtilities.cpp

Related to https://github.com/cyberbotics/webots-projects/issues/7 and it may also (fix) https://github.com/cyberbotics/webots/issues/3577.
We don't handle the mass property when used with Mesh nodes, this PR fixes it.

Fix mass calculation of Mesh nodes

---

src/webots/nodes/WbBox.cpp
src/webots/nodes/WbCylinder.cpp
src/webots/nodes/WbPlane.cpp
tests/api/worlds/asymmetric_friction.wbt

The `computeFrictionDirection` was wrongly converted in #3510 
I discovered that the cylinder asymmetric friction was wrong when trying to run robots with mecanum wheel such as SummitXL or Youbot.
With some more extensive inspection I believe that Box and Plane were wrong too.

FLU: fix asymetric friction

---

docs/reference/changelog-r2021.md
docs/reference/distancesensor.md
src/webots/nodes/WbDistanceSensor.cpp
src/webots/nodes/WbGeometry.cpp
src/webots/nodes/WbGeometry.hpp

This pull-request fixes issue #3468
The change make Laser Distance sensor ignore transparent objects (Bounding Box).
What was done: 
* Added a isTransparent const function to the WbGeometry class.
* Added check ignore transparent objects in WbDistanceSensor::rayCollisionCallback when in Laser mode.
I think that the documentation section here should also be changed to reflect the new behavior.
https://cyberbotics.com/doc/reference/distancesensor?version=develop#distancesensor-types
Like adding a new line in the table describing the behavior.
Ignore Transparent Objects | No | No | No | Yes
Warning: 
You need to have the transparency set to 1.0 on the BoundingBox and the Child object to have the proper behavior.
Having only one of them set can lead to unnatural effects.
Extension to other …

Fix Laser intersecting transparent objects #3468

---

.github/workflows/tests_sources.yml
src/webots/core/WbSysInfo.cpp
src/webots/scene_tree/WbPhysicsViewer.cpp
src/webots/scene_tree/WbPhysicsViewer.hpp

This PR aims at fixing the tests_sources CI test on the master branch.
It seems the newest version of cppcheck has problems with the `RELATIVE` and `ABSOLUTE` keywords.

Fix tests_sources on Windows (master branch)

---

src/controller/Makefile

Makefile of controller was failling because for Windows it tries to compile even if the `PYTHON3X_HOME` was not defined (for python 3.7, 3.8 or 3.9).
This PR add checks to avoid to compile if those paths are not defined.

fix issue with python3X_path for Windows installation from sources

---

resources/web/streaming_viewer/setup_viewer.js
resources/web/wwi/Server.js

When the simulation server is offline, we noticed that we don't get any errors message.
I fixed this issue in `server.js`, but I'm not sure if we should call `this._view.onquit()`, since it's also not called when the response from the session server starts with `Error:`: https://github.com/cyberbotics/webots/blob/53b60081c13e3b3f9dfee31fa4046c45dc870219/resources/web/wwi/Server.js#L31
What's your opinion on that @BenjaminDeleze ?

Add error message on connection timeout

---

projects/objects/stairs/protos/StraightStairs.proto
projects/robots/pal_robotics/tiago++/worlds/tiago++.wbt

The conversion of the `StraightStairs` PROTO was incorrect, resulting in wrong textures for the steps.
The staircase in tiago++ world also had a small mistake where the rail was not in the right position.
Before
After
Before
After

Fix `StraightStairs` and tiago++ world

---

.github/workflows/test_suite_windows.yml
.github/workflows/test_suite_windows_develop.yml
scripts/install/bash_profile.windows

The OpenJDK package was updated yesterday on Chocolatey and a path change broke the Windows build.

Fix Windows builds due to OpenJDK update

---

docs/reference/changelog-r2021.md
src/webots/nodes/utils/WbSupervisorUtilities.cpp

Fixes #3863.
Although node deletion using the "delete" button and node deletion from supervisor ultimately rely on a same call to `WbNodeOperations::deleteNode` in order to clear it, when deleting from supervisor the scene tree wasn't refreshed (i.e it didn't trigger `WbMultipleValue::itemRemoved` in `WbTreeItem`). The reason for the difference is that when deleting from keyboard the exposed scene tree node is actively selected [here](https://github.com/cyberbotics/webots/blob/d6a89d8f6ad9c6b8ac2f2dd822247082e2e1219a/src/webots/scene_tree/WbSceneTree.cpp#L426-L429) whereas when deleting from supervisor what is being referenced is the internal node to the PROTO.
The proposed fix climbs the ladder until a PROTO parameter is found (if any) before deleting.
Also, deletion of …

Fix node deletion from supervisor not refreshing scene tree

---

docs/guide/tutorial-3-appearance.md

Tutorial 3 is no longer up to date after the change introduced in 2021b.
I've added also an hands-on example for the pre-existing PBRAppearances (provided as PROTO files), it could be useful to let people know they exist, especially since textures aren't included out of the box anymore.

Fix tutorial 3 broken due to missing texture

---

docs/reference/changelog-r2021.md
src/webots/gui/WbView3D.cpp
src/webots/gui/WbView3D.hpp
src/webots/nodes/utils/WbSupervisorUtilities.cpp

Fixes: https://github.com/cyberbotics/webots/issues/3483
The process that leads to the crash is:
- Robot A is created when loading the world, being a supervisor, a connection is made between the signal `worldModified` and `handleWorldModificationFromSupervisor`.
- The controller uses a supervisor  `field_set_...` function to change an exposed parameter of the PROTO.
- When the controller is executed, during the execution of the [immediate messages](https://github.com/cyberbotics/webots/blob/1d3919e5212a1a9b2db580bcbe8a537771482506/src/webots/nodes/utils/WbSupervisorUtilities.cpp#L367-L384) a auto-regeneration is triggered, which results in the destruction of Robot A, and the creation of Robot B.
- After the regeneration, an emission of `worldModified` is triggered …

Fix auto-regeneration crash

---

docs/guide/web-animation.md
resources/web/templates/x3d_playback.html
resources/web/wwi/AnimationSlider.js
resources/web/wwi/WebotsAnimation.js
src/webots/nodes/utils/WbWorld.cpp

- Split the function `setNames` in `setX3d` and `setJson`
- Introduce the `autoplay` (true by default) attribute
- Introduce the `x3d` and `json` attribute. If the x3d attribute is not set, the animation will not be loaded
- Remove the feature allowing the animation player to guess its name from the html page
- Update the animation template accordingly
- Correct the animation slider such that it would be correct if `autoplay` is set to `false`
- Update the doc
The new files are already on the server to ease the tests

Improve API of animation

---

src/wren/Scene.cpp

The lightning is not computed correctly when the `castShadow` option is set to `true` in a `Light`.
**Context**
In `city_night.wbt` the `streetLights` seems to go "off" when we press play. It is because the BMW car has its frontlights activated and they cast shadow.
The error came from the function `affectedByLight` in WREN that is called to determine if objects are illuminated. This function is called as soon as at least one light cast shadow.
This functions contained several mistakes that I will describe thereafter.
**Tasks**
```
attenuationFactor = 1/(attenuation[0] + distanceToLight * (attenuation[1] + distanceToLight * attenuation[2])
color = 1/attenuationFactor * color * ...
```

Fix lights cast shadow

---

src/webots/scene_tree/WbExtendedStringEditor.cpp

Once set, it isn't possible to remove a physics plugin other than removing it from the world file.

Add `none` to physics plugin selector window

---

src/webots/maths/WbAxisAngle.hpp
src/webots/maths/WbMathsUtilities.hpp
src/webots/maths/WbRotation.hpp

This PR is related to these two issues #3556 and #3915 and the PR #3741. The bug came from the `clampedAcos` function in `WbMathsUtilities.hpp`
The boundaries of acos are [0,pi] for the values between [-1,1]. 
So the clamp should happen for `value` ]-1,1[ and take the value 0 or pi. However, for performance reason we can clamp between [-1,1].
Otherwise, The `NaN` issue can be reproduced by sending a rotation exactly equals to M_PI [0, 0, 1,3.14159265358979323].
In addition, I added a `ToString` function to `WbAxisAngle` Class and a default precision to the `toString` function of `WbRotation` Class.

fix arccos boundaries

---

src/webots/control/WbController.cpp

On some systems detecting a Python installation path gives incorrect result. In example:
```
/usr/local/Cellar/python@3.9/3.9.8/bin/python3.9 -c 'import sys; print(sys.exec_prefix)'
/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9
```
The solution is to not execute Python at all and just compare `mPythonCommand` against `/usr/local/Cellar`. In this case a user can explicitly declare the version they uses by setting it in Webots settings.
This fixes #3925

Change Python installation detection for macOS

---

docs/reference/changelog-r2021.md
src/wren/TextureCubeMapBaker.cpp

The issue came from the brdf texture. This texture is only created once, so if we were starting webots in wireframe mode it was created only to be compatible with wireframe. Whereas if the brdf texture is create in plain rendering mode it is compatible for both mode.
To find this bug I used [RenderDoc](https://renderdoc.org/), it seems to be a very useful tool for digging into OpenGL issues.
Fix #3938 
Plain Rendering brdf          |  wireframe rendering brdf
:-------------------------:|:-------------------------:

Fix rendering when switching from wireframe

---

docs/guide/web-animation.md
docs/guide/web-scene.md
docs/guide/web-simulation.md
docs/reference/light.md
resources/web/streaming_viewer/setup_viewer.js
resources/web/wwi/Animation.js
resources/web/wwi/Parser.js
resources/web/wwi/Stream.js
resources/web/wwi/WebotsView.js
resources/web/wwi/WrenRenderer.js
resources/web/wwi/X3dScene.js
resources/wren/shaders/pbr.frag
resources/wren/shaders/pbr_stencil_diffuse_specular.frag
resources/wren/shaders/phong.frag
resources/wren/shaders/phong_stencil_ambient_emissive.frag
resources/wren/shaders/phong_stencil_diffuse_specular.frag
resources/wren/shaders/shadow_volume.vert
src/wren/Constants.hpp

Enhancement of WebotsJS

---

src/webots/gui/WbView3D.cpp
src/webots/nodes/WbBackground.cpp
src/webots/nodes/WbViewpoint.cpp
src/webots/nodes/WbViewpoint.hpp

It seems like the orthographic mode was already converted. It could feel different depending on the `orthographicViewHeight`.
The `orthographicViewHeight` is a parameter that define the frustum height when in orthographic mode and that is modified when zooming in/out the scene. This parameter is automatically saved in the `.wbproj`. If we don't know that it is saved, the behviour can feel strange. For example if we:
1. Load the world and switch to orthographic mode.
2. Navigate the scene and zoom in/out.
3. Switch back to perspective mode and forget about orthographic.
4. Reload the world with the same viewpoint as in 1.
5. Switch to orthographic mode.
In 5. we will not see the same rendering as in 1. We will see the same viewpoint as in 1. __but__ with the zoom level of …

FLU: fix orthographic mode

---

docs/automobile/sumo-interface.md
projects/default/protos/SumoInterface.proto
projects/samples/robotbenchmark/highway_driving/controllers/highway_driving_benchmark/highway_driving_benchmark.py
projects/vehicles/worlds/city_traffic.wbt
projects/vehicles/worlds/highway.wbt
projects/vehicles/worlds/highway_overtake.wbt
projects/vehicles/worlds/sumo_interface_example.wbt
projects/vehicles/worlds/village_center.wbt
src/webots/scene_tree/WbSceneTree.cpp

All our worlds but `Sumo_interface_example` are using useNetconvert as FALSE. The sumo_interface proto is not include by default in some of the worlds (`city_*`, `village_*`) so for the moment the user has to add the proto and put useNetconvert to FALSE. To use netConvert, the user has to setup a netConvert configuration file (sumo.netccfg) for which is not our "scenario tutorial". Indeed, a common way of implementing a SUMO interface is to create a net (so by using Netconvert outside webots).
Drawback: the user using the default value of useNetconvert will face to issue.

Enhancement-useNetconvert

---

docs/reference/changelog-r2021.md
docs/reference/radar.md
src/webots/nodes/WbRadar.cpp
src/webots/nodes/utils/WbObjectDetection.cpp

As far as I can tell, no 360°-radar sensors exist in the market currently. This feature is either achieved by combining 2 or 4 separate radars or by rotating it.
Currently, when setting a horizontal field of view to a value higher than PI, the detection breaks down because of [this](https://github.com/cyberbotics/webots/blob/1508457090e341e1bbadc81a7f019234dc9376ab/src/webots/nodes/utils/WbObjectDetection.cpp#L318-L333) snippet, instead of detecting objects in the frustum, it detects them in the slice it isn't supposed to (and occasionally certain random angles also give positive hits). This is because although in practice it was allowed, the detection logic behind the scenes wasn't meant for it:
- normals of the frustum planes are flipped
- bottom plane becomes the top …

Fix Radar sanity check and restrict field of view to 180°

---

resources/web/wwi/viewer.js
resources/web/wwi/webots.js

Fixes the computation of the texture path which was missing and causing the loading of scenes with textures to fail on webots.cloud.
This is already updated on https://cyberbotics.com/wwi/R2022a/ and in  production on https://beta.webots.cloud

Fix webots.js texture path

---

docs/reference/changelog-r2021.md
docs/reference/mesh.md
src/webots/gui/WbImportWizard.cpp
src/webots/nodes/WbImageTexture.cpp
src/webots/nodes/WbMesh.cpp
src/webots/scene_tree/WbExtendedStringEditor.cpp

The texture mapping with `Mesh` node was not working properly. This can be seen when using `.obj` files.
I just added an option to flip the `y` axis for the texture mapping as Wren might not be aligned with the convention of `OpenGl`.
`OpenGl` and `.obj` define the `y` axis up.
This pull-request fixes issue #3945

Correction of the texture mapping for the Mesh node

---

docs/reference/skin.md

As per [this](https://github.com/cyberbotics/webots/blob/733b1bb2f5df73a95f61bb7b2ab5b45b8f772f82/src/webots/nodes/WbSkin.cpp#L223), FBX is the only supported file type.

Clarify `WbSkin` model supported formats

---

docs/guide/sojourner.md

It looks bad in the documentation to have a broken video link.
This PR fixes it by linking to a new video.
Old version: https://cyberbotics.com/doc/guide/sojourner
New version: https://cyberbotics.com/doc/guide/sojourner?version=fix-missing-video

The sojourner video is missing

---

src/webots/sound/WbSoundEngine.cpp

Prevent the instantiation of an openAL entity if the sound is mute. It aims to avoid the warnings in the CI and improve the performance.

Prevent open-al instantiation when sound is mute

---

docs/blog/Webots-2022-a-release.md
docs/guide/tutorial-9-using-ros.md
docs/guide/using-ros.md
lib/controller/matlab/WB_NODE_COLLADA_SHAPE.m
projects/robots/universal_robots/resources/ros_package/ur_e_webots/README.md

As discussed with @omichel and @BenjaminDeleze, we will no longer support `ROS Melodic` as it runs with `Python 2` on `Ubuntu 18` (end of support in March 2022). It requires too many settings to make it run with `Python 3` as the `libcontroller` use `Python 3`.
Thus I changed the documentation accordingly.

Remove mentions of ROS Melodic from the documentation

---

src/webots/nodes/WbSolidReference.cpp
src/webots/nodes/WbSolidReference.hpp

I'm not sure about that, but I've encountered this while trying to fix another bug.
I'm not sure about the repercussion of it, so please give me any feedback :)
Without this, when switching to "static environment" in joint endpoint, the mSolid pointer stay with the same value. I don't think it's the expected behavior. But not sure if setting it to NULL is the way to go !

Switch mSolid endPoint pointer to NULL when using static environnement

---

src/webots/core/WbTelemetry.cpp
src/webots/core/WbWebotsUpdateManager.cpp
src/webots/nodes/utils/WbDownloader.cpp

[QNetworkReply](https://doc.qt.io/qt-5/qnetworkreply.html) objects need to be released using the `deleteLater()` method.

Fixed small memory leaks

---

resources/web/wwi/webots.js

Since version 15, Safari support webgl2. 
I tested if with https://www.cyberbotics.com/animations/soccer_example/soccer.html. It works more or less, there is sometimes some troubles to load the page, but once it is loaded it works well.
And with https://cyberbotics1.epfl.ch/open-roberta/ and I experimented no issue with this one.

Allow the use of WebotsView in Safari

---

src/controller/c/motor.c
src/webots/nodes/WbMotor.cpp

Currently, in the context of coupled motors when Webots receives an API request (for instance setting of the target position), it relays this message to the other motors within the same coupling which results in each of them notifying libcontroller about their own updated state. This is necessary to ensure data symmetry between Webots and libcontroller, since for example when requesting data, the locally available one is usually provided (without asking Webots for it, hence it needs to be up to date). This is especially a problem with coupled motors since (currently) a single API call may affect multiple motors, not just the one associated with the tag from which the request stemmed.
This continuous exchange of information is however unnecessarily heavy and currently …

Remove webots -> libcontroller notification of relayed commands in motor couplings

---

src/controller/cpp/Makefile

The management of the dependencies was broken in the libCppController:
```bash
$ cd src/controller/cpp
$ make release
[...]
$ touch ../../../include/controller/cpp/webots/Robot.hpp
$ make release
make: Nothing to be done for 'release'.
```
This was due to the fact that the `build/release/Robot.d` dependency file was starting with:
```
Robot.o: Robot.cpp \
```
whereas it should start with:
```
build/release/Robot.o: Robot.cpp \
```
Hence the dependencies for `Robot.o` where silently ignored.
This PR fixes this bug.

Fixed broken dependencies in libCppController

---

docs/reference/changelog-r2022.md
docs/reference/supervisor.md
include/controller/c/webots/supervisor.h
src/controller/c/supervisor.c

The function `supervisor_world_save` isn't behaving as documented/intended.
If no argument is provided (or if NULL is provided in case of C API), the world should be saved.
If an argument is provided but isn't valid (no `.wbt` extension ), a warning should be printed.
If a valid argument (filename + extension, or path + filename + extension), the world should be saved as such.
The PR restores this functionality.
~~PS: I don't know if the change of argument name is warranted. C api uses "filename" and all others "file". Technically the provided string can be a path, so "file" might make more sense but it's debatable. Either way should be consistent.~~

Fix world save API

---

scripts/converter/convert_nue_to_enu_rub_to_flu.py

The [`convert_nue_to_enu_rub_to_flu.py`](https://github.com/cyberbotics/webots/blob/42fc2753ccda54b7747cf6e1c2d97820f609f7e6/scripts/converter/convert_nue_to_enu_rub_to_flu.py#L224) script only allows to update the version at the first line of the world or proto file if the version being updated is `R2021b`. 
For instance, the line `#VRML_SIM R2018b utf8` is not updated by the script and therefore requires to be modified by hand to `#VRML_SIM R2022a utf8`. 
This pull request should allow the script to update the Webots version in any case.

Generalize update of Webots version in world file header

---

projects/objects/television/protos/Television.proto

The led was not converted to FLU (it was floating around)

Fix television

---

src/webots/gui/WbNewProtoWizard.cpp
src/webots/scene_tree/WbValueEditor.cpp
src/webots/vrml/WbField.cpp
src/webots/vrml/WbMultipleValue.cpp
src/webots/vrml/WbSingleValue.hpp
src/webots/vrml/WbVariant.cpp
src/webots/vrml/WbVariant.hpp
tests/parser/expected_results.txt

In https://github.com/cyberbotics/webots/pull/4104, in order to pre-fill the PROTO parameters the function `toStringRepresentation` was modified such that for SFNodes the `{}` is also included in the representation (just the name alone is not VRML compliant for a node, the brackets are needed). This function however didn't aim to be VRML compliant and is used for other things, most notably to display the names of nodes in the scene tree, which meant this change added curly brackets in the GUI as well.
Although the addition of curly brackets could have been done at the level of other functions (like `WbMultipleValue::toString`, `itemToString`), these too serve other purposes and changing it would have side-effects.
All things considered, the best option appears to be to add …

Fix node string display

---

docs/guide/web-simulation.md
resources/web/server/session_server.py
resources/web/server/simulation_server.py
resources/web/wwi/Server.js
resources/web/wwi/webots.js

This PR changes the simulation server so that it will notify a server (for example webots.cloud) about its availability to host public simulations.
The monitor page of the simulation was also improved.
Additionally, the `webots.js` API is improved: the URL passed to the connect method is now `https` instead of `wss` which is more straightforward.
The result can be seen at https://beta.webots.cloud/server

Advertise simulation servers

---

docs/reference/changelog-r2022.md
projects/samples/howto/gears/worlds/gears.wbt

The sample world was still in NUE.
https://user-images.githubusercontent.com/44834743/152831872-699c2755-aeb1-4af4-8211-c8461c43c8c0.mp4

Convert `gears.wbt` to ENU

---

docs/guide/mavic-2-pro.md
docs/guide/object-traffic.md
docs/reference/changelog-r2022.md
projects/objects/traffic/protos/PedestrianCrossing.proto
projects/samples/howto/gears/worlds/gears.wbt

Fixes https://github.com/cyberbotics/webots/issues/4204
I tried again to clean the proto cache and let webots rebuild it but no warnings are shown. Yet somehow the mavic does show a warning when opened, rightfully so. It means there might be more, but at this point I don't know how to find them other than opening all PROTO one by one.

Fix unlinked field in `Mavic2Pro` and `PedestrianCrossing` PROTO

---

tests/physics/plugins/physics/ode_dif_exporter/ode_dif_exporter.c

The compilation of this file in the CI was raising a warning:
```bash
ode_dif_exporter.c: In function ‘webots_physics_step’:
ode_dif_exporter.c:70:47: warning: ‘ode.dif’ directive output may be truncated writing 7 bytes into a region of size between 0 and 4095 [-Wformat-truncation=]
70 |     snprintf(filename, sizeof(filename), "%s%code.dif", current_path, SEP);
|                                               ^~~~~~~
In file included from /usr/include/stdio.h:867,
from /home/runner/work/webots/webots/artifact/webots/include/ode/ode/odeconfig.h:29,
from /home/runner/work/webots/webots/artifact/webots/include/ode/ode/ode.h:28,
from ode_dif_exporter.c:1:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output between 9 and 4104 bytes into a destination of …
```

Fixed compilation warning

---

src/webots/nodes/WbBackground.cpp

The warning messages for missing locally-defined irradiance file prints the url of the corresponding texture instead.

Fix missing irradiance warning message

---

projects/samples/devices/worlds/track.wbt
resources/web/streaming_viewer/index.html
resources/web/wwi/Parser.js
src/webots/nodes/WbTrack.cpp
tests/api/worlds/track.wbt

Fix several issues related to tracks:

Fix bugs tracks

---

dependencies/Makefile.linux
dependencies/Makefile.mac

Since Qt6 requires C++17, all the include files used by Webots should be C++17 compliant, including libpico, which wasn't.
So, I fixed the libpico package to be C++17 compliant and uploaded this new version.
Consequently the MD5 sums changed and need to be fixed.
#4202 fixed the MD5 sum for the Windows version.
This PR fixes the MD5 sums for the Linux and macOS versions.

Uploaded new libpico packages compatible with C++17

---

docs/guide/using-matlab.md
docs/reference/changelog-r2022.md
src/webots/control/WbController.cpp
src/webots/control/WbLanguageTools.cpp
src/webots/core/WbPreferences.cpp
src/webots/core/WbPreferences.hpp
src/webots/gui/WbPreferencesDialog.cpp
src/webots/gui/WbPreferencesDialog.hpp

Until now, Matlab is started by Webots by searching in the PATH of the system. This approach could cause problems, especially on MacOS where PATHs are managed differently between the terminal and the Finder (see issue #2608). Also, symlinks were needed on some operating systems.
To simplify the procedure for the user, this PR aims to create a General Webots preference to specify the absolute path to the Matlab executable. This way the user also has more control over which version of Matlab to use. When a Matlab controller is started, the specified executable is directly used as the start command.
This pull-request does not directly fix issue #2608, but brings an easier way to handle Matlab execution.
**Tasks** …

Add new matlab command preference

---

src/webots/nodes/WbBackground.cpp
src/webots/nodes/WbCamera.cpp
src/webots/nodes/WbImageTexture.cpp
src/webots/nodes/WbMesh.cpp
src/webots/nodes/WbSkin.cpp
src/webots/nodes/utils/WbUrl.cpp

If a `webots://` url is not found locally, automatically convert it to `raw.githubusercontent.com` format.
It is usefull especially in the context of webots.cloud.

Automatically convert urls

---

docs/reference/changelog-r2022.md
projects/samples/devices/worlds/track.wbt
src/webots/nodes/utils/WbNodeUtilities.cpp

USE of TrackWheel are a bad practice, here is why:
- Define two tracks: T1 and T2.
- Define a TrackWheel in T1 with a DEF.
- Insert a USE of this TrackWheel in T2.
- Run T1 at speed v1 and T2 at speed v2.
- The USEd TrackWheel in T2 will go at speed v1 which is wrong.
So it is better to forbid the USE of TrackWheel.
(I took advantage of this PR to harmonize a bit the naming in `track.wbt`.)
Does it need to add an entry in the changelog?

Forbid USE of TrackWheel

---

resources/web/server/simulation_server.py

Pass the Webots tmp folder path as a build argument to use it in a `Dockerfile`.

dockerfile-server-implementation

---

src/webots/control/WbController.cpp
src/webots/control/WbLanguageTools.cpp
src/webots/control/WbLanguageTools.hpp
src/webots/core/WbPreferences.cpp
src/webots/core/WbPreferences.hpp

PR #4233 was adding a new MATLAB preference to indicate a custom MATLAB path. Its first behavior was to set the default MATLAB installation path in the preference when starting Webots for the first time.
This implementation is problematic in case the user installs MATLAB after Webots. 
This PR removes the default preference settings. Instead, when the user runs a MATLAB controller, Webots first checks the preference field. If it is empty, it will check the default installation path of MATLAB. If both paths are missing, an error message is displayed.

modified behavior of default matlab command

---

docs/reference/changelog-r2022.md
src/webots/nodes/WbSkin.cpp
src/webots/nodes/WbSkin.hpp

Fixes https://github.com/cyberbotics/webots/issues/4266
The Skin class doesn't inherit from the `WbGeometry` but instead loads and instantiates its own meshes. As such, both the segmentation and range finder logic is currently missing for the Skin node, meaning it's invisible to both types of camera.
As these features are entirely missing, perhaps it's not really a bug but since it doesn't seem an intended behavior I still targeted the master branch.
Range finder behavior
https://user-images.githubusercontent.com/44834743/155672494-486251df-701b-4c13-ba2d-73d204583fca.mp4
https://user-images.githubusercontent.com/44834743/155672550-fdbf8cbc-35ea-4091-982e-4d471a9fc1a5.mp4
Segmentation behavior
https://user-images.githubusercontent.com/44834743/155672571-a91d45e5-49dd-4198-a …

Fix `Skin` segmentation and  Range Finder invisibility

---

resources/web/server/simulation_server.py

When a github repo has a structure like:
`https://github.com/cyberbotics/my_robot_repository/worlds/my_world.wbt`
It was not possible to load it with the `simulation_server.py`
It had to be something like:
`https://github.com/cyberbotics/my_robot_repository/my_robot/worlds/my_world.wbt`
It was because, when copying the files from github, the simulation server put them in a folder: the `my_robot` folder. But if this folder did not exist, the folder took the name of the repository:`my_robot_repository`. However, the path of the `.wbt` was not updated so webots was trying to open:
`/tmp/xxxxxxxxx/worlds/my_worlds.wbt`
instead of 
`/tmp/xxxxxxxxx/my_robot_repository/worlds/my_worlds.wbt`

Fix simulation server when worlds is a top folder

---

src/webots/engine/WbAnimationRecorder.cpp
src/webots/engine/WbAnimationRecorder.hpp
src/webots/gui/WbStreamingServer.cpp
src/webots/gui/WbStreamingServer.hpp
src/webots/gui/WbX3dStreamingServer.cpp
src/webots/gui/WbX3dStreamingServer.hpp

Webots was not sending an update to webotsjs at each timetep but according to the number of fps which is not what we want.
I put some `assert` to make sure that `currentTime > mLastUpdateTime` but I'm not sure if it's really necessary because the two variables (`currentTime` and `mLastUpdateTime`) are only used for the assert.

Fix update rate of webotsjs

---

.github/workflows/test_suite_linux_develop.yml
.github/workflows/tests_sources.yml

Since the develop branch is not compatible any more with Ubuntu 18.04 due to the upgrade to Qt6, we need to adapt the workflows accordingly.
Now the diff between the `test_suite_linux.yml` and `test_suite_linux_develop.yml` is so important that the workflow synchronization test is not very useful and more painful to maintain, so I disabled it.

Remove Ubuntu 18 from develop tests

---

src/webots/nodes/WbMesh.cpp
src/webots/nodes/WbMesh.hpp

Fixes https://github.com/cyberbotics/webots/issues/4313
Although these fields should only apply to collada files, no distinction was made if the mesh happened to be an `obj`, resulting in crashes.

Fix `name` and `materialIndex` causing crash on `.obj` meshes

---

src/webots/nodes/utils/WbDownloader.cpp
src/webots/nodes/utils/WbDownloader.hpp

Fixes https://github.com/cyberbotics/webots/issues/4312 (more details about the issue available here).
As far as I can see, this is the cleanest approach (I could think of) to keep the assert while preventing a memory leak. Basically we trigger the second download only after the reply of the first has been properly destroyed. I'm open to better solutions though, if there's better ways.

Fix download of invalid url

---

src/webots/nodes/utils/WbNodeOperations.cpp

As far as I can tell, this loop was used only for debugging purposes. Currently therefore the code extracts from the material property the same parameters multiple times for no apparent reason

Remove unnecessary loop in ColladaShape

---

docs/guide/using-ros.md

A user reported that the `ros_python.py` link was broken.
See https://cyberbotics.com/doc/guide/using-ros?version=fix-reference-to-deprecated-example

Removed reference to deprecated example

---

src/controller/c/supervisor.c

Fixes #4356.
This function should not display a warning for SF fields as it may be used to determine if a field is SF or MF. See https://cyberbotics.com/doc/reference/supervisor#wb_supervisor_field_get_count

Fixed annoying warning

---

scripts/packaging/files_msys64.txt

The nightly builds failed on Windows because of a rename of the libassimp DLL in MSYS2. This PR fixes it.

Fixed assimp renaming on Windows

---

docs/reference/changelog-r2022.md
src/controller/c/supervisor.c
tests/api/controllers/supervisor_field/supervisor_field.c

*I*HAVE*NOT*TESTED*THIS*!!! wb_supervisor_node_get_field_by_index was calling find_field_by_id with the node id and index arguments reversed, causing it to return the wrong field if the one with the numbers reversed had been accessed. Similarly for the proto version.

fix get_field_by_index (#4363)

---

.github/workflows/test_suite_linux.yml
.github/workflows/test_suite_linux_develop.yml
.github/workflows/test_suite_mac.yml
.github/workflows/test_suite_mac_develop.yml
.github/workflows/test_suite_windows.yml
.github/workflows/test_suite_windows_develop.yml

The failed test revealed a tagging issue with the generation of the nightly.
For reference, the latest master commit is `d45037c` and the latest develop commit is `365d318`. The reason the cache test failed is that the urls of the distribution uploaded as artifact are correct (i.e `365d318`), but when updating the urls to run the test suite (which are not included in the distribution), the assets were tagged with `d45037c`, and in master of course the texture used for the test doesn't exist.
Fundamentally the issue is that the nightly builds and scheduled tests are run from the master branch workflows, so any reference of `${{ github.sha }}` will reference the `d45037c`.
To see this is in fact the case, when checking the headers of the latest nightlies they both mention …

Fix scheduled tests and nightly header

---

projects/samples/robotbenchmark/pit_escape/protos/Pit.proto

Without this parameter, inserting several pits in a single worlds will trigger warnings

Add parameter name to pit

---

src/webots/nodes/WbContactProperties.cpp
src/webots/nodes/WbImageTexture.cpp

Although the fall-back mechanism of attempting to retrieve online an asset that cannot be found locally was working as intended, the internal representation of the url remained unchanged. So, when it came time to load the asset we still attempted to load the `webots://` asset instead of the correctly determined `https://` fallback, which of course failed.
The issue appears to exist only for textures and contact properties, the other assets are handled correctly.
To test it, a nightly should be created:
```
python scripts/packaging/set_commit_and_date_in_version.py $(git log -1 --format='%H')
make -j12 distrib
```

Fix loading of textures and contact properties when the fallback mechanism activates

---

docs/guide/preferences.md
docs/guide/samples-community-projects.md
docs/reference/changelog-r2022.md
resources/translations/wb_de.ts
resources/translations/wb_es.ts
resources/translations/wb_fr.ts
resources/translations/wb_generic.ts
resources/translations/wb_it.ts
resources/translations/wb_ja_JP.ts
resources/translations/wb_zh_CN.ts
src/webots/core/WbControllerPlugin.cpp
src/webots/core/WbProject.cpp
src/webots/core/WbProject.hpp
src/webots/gui/WbPreferencesDialog.cpp
src/webots/gui/WbPreferencesDialog.hpp
src/webots/nodes/WbRobot.cpp
src/webots/nodes/utils/WbUrl.cpp
src/webots/scene_tree/WbAddNodeDialog.cpp
src/webots/scene_tree/WbExtendedStringEditor.cpp
src/webots/vrml/WbProtoList.cpp

***Enhancement proposal***
Allows to list and import multiple extra projects defined in the `WEBOTS_EXTRA_PROJECT_PATH` environment variable.
The preferences option `Extra project path` is also enabled with the same functionality. Both can define multiple paths by separating them with `:` (or `;` on Windows)
This will enable the usage of Webots in projects using robots defined in multiple places.
- Defining each robot in a different place (being packages) is a common pattern when working with ROS, where each robot might have its own package with its definition, the launch files required to spawn the robot, its controller, and so on.
- On the same line, `webots_ros` can be improved to set `WEBOTS_EXTRA_PROJECT_PATH` by using rospack together with the …

Allow multiple extra projects. Add WEBOTS_EXTRA_PROJECT_PATH env variable

---

docs/guide/the-user-interface.md
docs/reference/changelog-r2022.md
src/webots/gui/WbMainWindow.cpp
src/webots/gui/WbMainWindow.hpp
src/webots/gui/WbSimulationView.cpp
src/webots/wren/WbWrenTextureOverlay.cpp

Fixes https://github.com/cyberbotics/webots/issues/4341 and an issue with overlays where what is shown in the menu doesn't correspond to what's selected.
If the variable is not defined or is false:
- any change to the layout/overlays persists across reloads and restarts, except where expressly undesired (while making movies) 
If the variable is true:
- any change to the layout/overlays is ignored
- if the user saves, the disabler is ignored and we do indeed save the perspective.
It is unclear to me why in the `selectedRobot` method we arbitrarily take the first robot as selection by default (if a node isn't selected). This has the following side-effects:
- is counter-intuitive, because the robot picked isn't actually selected as the name entails (i.e by the user) but …

Fix perspective save and camera overlays

---

docs/reference/changelog-r2022.md
src/webots/nodes/WbGeometry.cpp

Fix #4424 
The arrays were previously allocated on the stack.
For very large elevation grids, it could overload the stack.
So now the arrays are allocated on the heap where there is more room

Fix crash export elevation grid

---

resources/web/wwi/Animation.js
resources/web/wwi/X3dScene.js
resources/web/wwi/webots.js
src/webots/engine/WbAnimationRecorder.cpp

After seeing the animation generated by Robocup (https://robocup-hlvs.de/GAME_K-GD6-3/public_logs/K-GD6-3.html) , I improved the loading time of the animation by:
- starting the loading of JSON ealier.
- Then I generated some keyframes (think about it like snapshots of the simulation) in order to increase the response time when jumping forward or backward in the replay. The keyframes are generated during the loading.
- I measured an overhead of 300ms on the Robocup animation for a total loading time of about 16 seconds. It seems acceptable to me knowing that this animation has a JSON file of 400MB.
- I also reordered some loops to minimize the number of iterations
- Finally I made some cleanup.
To test and compare with the original: https://cyberbotics.com/animations/robocup/K-GD6-3.html

Enhancement animation loading

---

projects/default/controllers/ros/Ros.cpp
projects/default/controllers/ros/RosSupervisor.cpp

Fixes https://github.com/cyberbotics/webots/issues/4441
When advertising devices, their name is sanitized (i.e., spaces/dashes replaced by underscores), so for instance a `imu accelerometer` can be enabled with `rosservice call /MyRobot/imu_accelerometer/enable`. 
However, when we call for instance `/MyRobot/robot/get_device_list` a sanitized list of the devices was proposed to the user (in this case `imu_accelerometer` was returned), which if they were subsequently queried, for example to find the noderef of a particular device, resulted in a crash since none could be found with such a name. Since most devices used in the Webots library are unsanitized, I think it makes more sense for them to be accessible in an unsanitized way, otherwise the users need to manually edit …

Fix crash with unsanitized device names

---

.github/workflows/test_suite_linux.yml
.github/workflows/test_suite_linux_develop.yml
scripts/packaging/publish_release.py

As far as I can tell from the debug messages, the job that creates the release is always unable to include the distribution files itself created. As tonight's messages have shown, the binaries are indeed available so that's not the problem, therefore I suspect the issue lies with the fact that between [creating the release](https://github.com/cyberbotics/webots/blob/9c87a9d4f7332e764e6bb01947a761444bc488b1/scripts/packaging/publish_release.py#L95) on github and [requesting the list of all releases](https://github.com/cyberbotics/webots/blob/9c87a9d4f7332e764e6bb01947a761444bc488b1/scripts/packaging/publish_release.py#L127) available not enough time passes and therefore no upload occurs since the newly created release is not present (as far as the script is concerned).
I've …

Fix nightly issues

---

src/webots/nodes/WbMesh.cpp

As surfaced in https://github.com/assimp/assimp/issues/849, importing in assimp non-obj files results in them being rotated 90°. Although the fix proposed in https://github.com/cyberbotics/webots/pull/4172 is technically correct, it ends up overwriting the root transform and therefore any translation & scaling information already present at the root level would end up being overwritten by the fix, which resulted in the behavior shown in the last image of https://github.com/cyberbotics/webots/issues/4447 (coordinate system not centered and scaling issue)
A simpler approach which doesn't suffer from this issue is to simply rotate the root transform by the desired amount.
From this issue also emerged the fact that when loading mesh nodes, the call to …

Fix collada orientation

---

.github/workflows/discord_updater.yml
.github/workflows/test_suite_linux.yml
.github/workflows/test_suite_linux_develop.yml
.github/workflows/test_suite_mac.yml
.github/workflows/test_suite_mac_develop.yml
.github/workflows/test_suite_windows.yml
.github/workflows/test_suite_windows_develop.yml
.github/workflows/tests_doc.yml
.github/workflows/tests_sources.yml

Apparently the bot failed again, this time it couldn't push because supposedly its branch was behind the remote one, which doesn't make much sense since it's a fresh clone. There has been an update to the github action "checkout" recently, I haven't found any similar issue on their github but shouldn't hurt to upgrade either. On top of it the PR forces the branch to be recreated. 
It theory it should be sufficient to make a pull before creating the commit, but it really shouldn't be necessary to do so, hence it seems the best approach (or at least, the only I can think of, but I'm open to ideas)

Upgrade checkout and attempt fixing discord bot

---

src/webots/nodes/utils/WbWorld.cpp
src/webots/nodes/utils/WbWorld.hpp

When launching webots with `--enable-x3d-meta-file-export` (typically to re-generated web component) we also generate the css which is not really necessary for that task, and it needs to be manually filtered out before committing.
I've also renamed a function as it makes more sense given what it does.

Don't generate css if exporting metafile

---

src/webots/control/WbController.cpp

This PR cleans-up the `WbController` class.
The `QProcess` doesn't need to be created in case of extern controller, so it shouldn't be created in the constructor of `WbController`, but only in the `start` method of this class which is not called in case of extern controller.
This PR aims at the develop branch because I will need it in #4344 and I see little interest seeing this back-ported to the master branch.

Clean-up creation of QProcess in the WbController class

---

resources/web/wwi/X3dScene.js

Fix warning message during loading

---

resources/web/wwi/Parser.js
resources/web/wwi/nodes/WbBaseNode.js
resources/web/wwi/nodes/WbBox.js
resources/web/wwi/nodes/WbCapsule.js
resources/web/wwi/nodes/WbCone.js
resources/web/wwi/nodes/WbCylinder.js
resources/web/wwi/nodes/WbDirectionalLight.js
resources/web/wwi/nodes/WbElevationGrid.js
resources/web/wwi/nodes/WbGeometry.js
resources/web/wwi/nodes/WbImageTexture.js
resources/web/wwi/nodes/WbIndexedLineSet.js
resources/web/wwi/nodes/WbPlane.js
resources/web/wwi/nodes/WbPointLight.js
resources/web/wwi/nodes/WbPointSet.js
resources/web/wwi/nodes/WbShape.js
resources/web/wwi/nodes/WbSphere.js
resources/web/wwi/nodes/WbSpotLight.js
resources/web/wwi/nodes/WbTrack.js
resources/web/wwi/nodes/WbTransform.js
resources/web/wwi/nodes/WbTriangleMeshGeometry.js
resources/web/wwi/nodes/WbWorld.js
src/webots/gui/WbX3dStreamingServer.cpp

This pull-request fixes issue #1875 
**Tasks**
Both the crash and the problem of updates after PROTO regeneration happened because `createWrenObject` was called twice on some objects.
Some objects were not deleted in WebotsJS because the id sent along the `delete:` was not matching the id sent at the world creation.

WebotsJS: Fix PROTO regeneration and update bugs

---

docs/reference/changelog-r2022.md
src/webots/engine/WbSimulationCluster.cpp

With the removal of the DifferentialWheels node (R2021b), the logic handling the collision between kinematic robots was also removed by accident. 
Before:
https://user-images.githubusercontent.com/44834743/166713306-27073a2f-cd8f-4cbd-a837-60aef0a304ba.mp4
https://user-images.githubusercontent.com/44834743/166713363-eca16946-0cc8-4a72-adf6-fbd52d9ed089.mp4
After:
https://user-images.githubusercontent.com/44834743/166715245-980f1be1-b5e1-416f-850e-dbe8c863fd4b.mp4
https://user-images.githubusercontent.com/44834743/166715262-70d81d05-9b36-4eb5-8b79-0a2b02b3ca1f.mp4

Fix collision between kinematic robots

---

docs/guide/tutorial-8-the-supervisor.md
docs/reference/supervisor.md

We regularly receive questions about using the Supervisor to access device measurements from other robots.
I will try to add some additional specifications and change misleading text.

Improve Supervisor unlimited power description

---

docs/guide/using-python.md
docs/guide/using-your-ide.md
src/controller/python/Makefile
src/webots/control/WbLanguageTools.cpp

Fix warning when compiling the Python 3.10 API and errors computing the path to the Python 3.10 API.
I also updated the documentation.

Fix errors using to python3.10 and update documentation

---

scripts/packaging/Makefile
tests/test_suite.py

Address comments in #4502.
md5-related functions are deprecated in OpenSSL 3.
For the moment it seems that the new version of OpenSSL is only used on macOS and Ubuntu 22.04 so we need to ignore the warnings only on these platforms.

Improve deprecation flags and double initialization

---

docs/reference/camera.md
docs/reference/display.md

It seems there has been issue during branches synchronization and the changes applied to the documentation in PR  #2452 have been overwritten.
However, changes to the code have been applied correctly.

Fix documentation for copying camera image in display

---

docs/reference/changelog-r2022.md
src/webots/nodes/WbGeometry.cpp
src/webots/nodes/WbTransform.cpp

Fix #4324.
In case of Fluid objects, the NULL solid pointer was used.

Fix crash due to Transform updates in Fuild.boundingObject

---

docs/reference/changelog-r2022.md
src/webots/nodes/WbSolid.cpp

Fix #4280.
If `numberOfContactPoints` value greater than `mSupportPolygon` size, `mSupportPolygon` was often accessed outside his bounds.
If `numberOfContactPoints` is lower than 32 (default size of the QVarLengthArray `mSupportPolygon`) nothing bad occurs, otherwise we may overwrite other WbSolid structures like the `mJointChildren` vector.

Fix support polygon access out of bounds

---

resources/web/wwi/Parser.js

The `assimpjs.wasm` file was loaded multiple time (once by mesh) and was causing Firefox to stall the loading

Fix assimpjs loading

---

src/controller/python/Makefile

When compiling the python 3.10 controller on the CI on Windows the following warning is printed in the log:
```
#
controller310.cpp: In function 'PyObject* PyInit__controller()':
controller310.cpp:984:64: warning: 'void PyEval_InitThreads()' is deprecated [-Wdeprecated-declarations]
984 | #     define SWIG_PYTHON_INITIALIZE_THREADS  PyEval_InitThreads()
|                                              ~~~~~~~~~~~~~~~~~~^~
controller310.cpp:27471:3: note: in expansion of macro 'SWIG_PYTHON_INITIALIZE_THREADS'
27471 |   SWIG_PYTHON_INITIALIZE_THREADS;
|   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:/hostedtoolcache/windows/Python/3.10.4/x64/include/Python.h:130,
from controller310.cpp:182:
C:/hostedtoolcache/windows/Python/3.10.4/x64/include/ceval.h:122:37: note: declared here
122 …
```

Fix SWIG deprecation warning with Python 3.10 on Windows

---

src/webots/gui/main.cpp

Fixes #4574.
It seems better to use forward slashes for the Qt plugins paths, see comment [at the bottom of this page](https://forum.qt.io/topic/110914/qt-5-14-0-plugins-path/4).

Use forward slashs in Qt plugins path

---

src/webots/nodes/WbConnector.cpp

This gcc warning is not recognized on macOS.

Fixed compilation warning on macOS

---

src/webots/nodes/WbConnector.cpp

This gcc warning is only recognized on Windows.

Fixed compilation warning on Linux

---

src/webots/nodes/WbConnector.cpp

It seems the buggy `-Wdangling-pointer` warning was introduced in [gcc 12.1.0](https://gcc.gnu.org/onlinedocs/gcc-12.1.0/gcc/Warning-Options.html) as compared to [gcc 11.3.0](https://gcc.gnu.org/onlinedocs/gcc-11.3.0/gcc/Warning-Options.html#Warning-Options) which is not yet present on the Windows CI machines. I prefer to make a strict test on gcc 12.1.0 to be able to detect when we can get rid of these pragmas after a gcc update.

Fix compilation on Windows CI

---

.github/workflows/test_suite_linux.yml
.github/workflows/test_suite_mac.yml
.github/workflows/test_suite_windows.yml

This is done to allow other tags to be created without publishing a release
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-branches-and-tags

Trigger release only on nightly and release tags

---

dependencies/Makefile.windows
docs/reference/changelog-r2022.md
resources/Makefile.include
scripts/install/msys64_installer.sh
scripts/packaging/windows_distro.py
src/controller/c/Makefile

This code was used for building controller programs linked against libraries that are available only for i686 architecture. This was the case for the Nao simulator SDK libraries and some old versions of MATLAB, Python, Java, etc. Hopefully, this is not needed any more.
Thanks to this PR, the size of the installation setup will shrink from 453 to 341 MB.

Remove i686 code (libController 32 bits on Windows)

---

src/webots/nodes/WbCadShape.cpp

if we had an `.obj` with:
```
mtllib Cat 3D Model.mtl
```
CadShape believe there was 3 `.mtl` files. So I had to modifiy a bit how it was split

Fix cadshape with .mtl spaced name

---

src/webots/gui/WbSingleTaskApplication.cpp
src/webots/nodes/WbJoint.cpp
src/webots/nodes/WbSolid.hpp

Fixes #4332.
The crash was already fixed in PR #4102. Therefore robot.getUrdf() is now displaying a warning if the robot contains closed-loop kinematics.
However, this is not the case when using `webots convert` command line for an URDF conversion. The parsing of the PROTO isn't updating the solid children and solid end point references. Therefore, the closed-loop is not detected and no warning is displayed. This PR adds the references update, as well as the warnings for a better user experience.

Closed-loop kinematics detection in webots convert URDF

---

resources/web/templates/x3d_playback.html

Link did not open in new tab because `:` should have been `=`.

Hotfix CORS new tab

---

projects/default/libraries/vehicle/python/Makefile
projects/robots/robotis/darwin-op/libraries/python/Makefile
src/controller/python/Makefile

Following #4638, this PR fixes the optional build of python libraries depending on the python-dev packages.

Fixed optional python library build

---

src/webots/core/WbPreferences.cpp
src/webots/gui/WbMainWindow.cpp
src/webots/gui/WbPreferencesDialog.cpp
src/webots/gui/WbPreferencesDialog.hpp
src/webots/gui/WbSimulationView.cpp
src/webots/gui/WbSimulationView.hpp

- Improves usability of animation and scene sharing by pausing when the dialog is displayed and resuming afterwards (+ code cleanup)
- Gives a more clear indication of what is happening on simulation reset during animation recording with an info log message .
- Improves thumbnail robustness by only resizing back to original size once screenshot is written thanks to a new signal.
- Add checkbox to preferences to disable thumbnails if wanted

Enhancement share reset and thumbnail robustness

---

src/webots/control/WbLanguageTools.cpp

Python 3.10 controllers are not running on Windows. This PR fixes the problem.

Fixed Python 3.10 controller execution on Windows

---

dependencies/Makefile.windows
scripts/install/msys64_installer.sh
scripts/packaging/files_msys64.txt
scripts/packaging/webots_distro.py
src/webots/Makefile
src/webots/control/WbLanguageTools.cpp
src/wren/Makefile

Fixes #4653.
Since assimp 5.2.4 introduced a bug breaking up the skeletons / skins in Webots, this PR reverts to version 5.2.3 which works well.
On the long term, it might be a good solution to have the same version of assimp on Linux, macOS and Windows, regardless of MSYS2 updates.

Use assimp-5.2.3 on Windows

---

.github/workflows/test_suite_windows.yml

As the release will happen quite soon, it is not worth investing time trying to fix the R2022a package for windows
(for more information check #4668)

Remove R2022a windows nigthly

---

scripts/packaging/generate_proto_list.py
scripts/packaging/webots_distro.py

generate_proto_list.py was not respecting FLAKE8 W605, see https://stackoverflow.com/questions/69983472/how-to-satisfy-flake8-w605-invalid-escape-sequence-and-string-format-in
This PR also makes that `generate_proto_list.py` will do nothing if no PROTO file changed, thus making the global `make` run faster.
Finally, it disable the `webots --sysinfo` on the Windows platform because it crashes on the CI machine due to the lack of audio card.

Fixed PEP8 in generate_proto_list.py

---

docs/guide/installation-procedure.md

This note has been added for R2022a, but it is incomplete given that it doesn't specify for example that Python won't work out of the box and you need to install a different versions, etc.
When R2022b is released we should promote the use of the latest version instead.

Remove note about running old versions of Webots

---

.github/workflows/test_suite_linux_develop.yml

The failing test suite and world update is likely due to the fact that the scheduled nightly tests are actually run from the master branch's version of the workflow. As such, the test_suite_develop.yml workflow in the master branch needs to reflect the changes that have been made in the workflows on the develop side of things, otherwise it won't work. The fix should address both issues at once.
Assuming this PR https://github.com/cyberbotics/webots/pull/4688 passes without problems, it means that on the develop side we don't have issues

Fix scheduled tests

---

src/webots/gui/main.cpp

While testing @carikaser experienced a failure at start-up: Webots complained it could not find the Qt plugins and refused to launch. This failure is difficult to reproduce, especially on our development machines (even with a different user account), because it seems that Qt is somehow caching the path to the Qt plugins and manages to find them even though they are not correctly specified by Webots.
This PR fixes the problem (tested on a new PC on which Webots was never installed).
The previous code assumed that `WEBOTS_HOME` was properly defined, which is not the case unless the user explicitly did so.

Fix Qt plugin path on Windows

---

docs/guide/tutorial-9-using-ros.md

Installing the `webots_ros` package was a bit unclear and not well-structured. The documentation now also mentions installation from sources which should be used to get the last modifications to the `webots_ros` repository.

Improve Using-ROS tutorial documentation

---

src/webots/gui/WbOpenSampleWorldDialog.cpp

Worlds from the `webots_ros` submodule are located in the `resources` directory and were added to the sample worlds in #3835. This is not really useful and a bit confusing as these worlds can't work alone. Instead, they should be launched using `roslaunch` directly from the package folder.

Remove webots_ros from sample worlds

---

scripts/install/linux_compilation_dependencies.sh

Some dependencies were not installed because of a broken library with unmet dependencies.

Remove broken dependency on Ubuntu 22.04

---

.github/workflows/test_suite_mac.yml
.github/workflows/test_suite_mac_develop.yml

Backport #4714 on the master branch so that it is executed on schedule and the nightly builds for macOS should be working again.

Fix macOS workflow on master

---

.github/workflows/test_suite_linux_develop.yml

The first upload job is not executed for the "scheduled" event, so the assets need to be uploaded in the second upload task, hence why the world upload worked for the manual trigger but not with a [scheduled run](https://github.com/cyberbotics/webots/runs/7033478162?check_suite_focus=true)

Fix test world update

---

docs/reference/changelog-r2022.md
projects/default/resources/Makefile

SUMO 1.10.0 depends on libgdal.29.dylib which has been updated to version 31 on recent MacOS distributions. This PR updates SUMO to 1.13.0 on MacOS to fix the library dependency.
Note: the [wiki page](https://github.com/cyberbotics/webots/wiki/SUMO-compilation#mac) on how to create a SUMO package on Mac needed a refresh and is now up-to-date.

MacOS update SUMO from 1.10.0 to 1.13.0

---

src/webots/nodes/WbAbstractCamera.cpp

There was a bug introduced in #4748 causing a robot camera to crash Webots when resetting a simulation.
This PR fixes this crash.

Fixed camera reset

---

.github/workflows/test_suite_linux_develop.yml
scripts/packaging/files_core.txt
scripts/packaging/generic_distro.py

Fixes #4729.
The PROTO wizard is not working in distributed packages because `template.proto ` is not distributed. The PR also removes the .cache file verification and copy when creating a distribution.

Added template.proto to distributions

---

projects/vehicles/worlds/highway.wbt

Adding the missing EXTERNPROTO files to the `projects/vehicle/highway.wbt` world.
This pull-request fixes issue #4730.

adding the missing EXTERNPROTO definitions to the highway.wbt world

---

src/webots/vrml/WbProtoModel.cpp

In the distribution, Webots is unable to locate the robot window for a PROTO when it has to climb-up the PROTO file path, which is the case for the automobile robot window. This PR fixes the problem.
Basically, in the distribution the following folder doesn't exist: `WEBOTS_HOME/projects/vehicles/protos/` because the PROTOs are not distributed in the package any more. However, the algorithm searching for the robot window plugin will start from: `WEBOTS_HOME/projects/vehicles/protos/licoln/LincolnLKZ.proto` and climb-up to the `WEBOTS_HOME/projects/vehicles/` folder to finally find `WEBOTS_HOME/projects/vehicles/plugins/robot_windows/automobile/`. The climb-up algorithm relied on `QDir::cdUp()` which actually fails to cd up if the resulting folder doesn't exist. Thus, it was failing to cd …

Fixed path to proto robot windows

---

projects/robots/robotis/darwin-op/libraries/managers/src/RobotisOp2DirectoryManager.cpp
src/webots/core/WbStandardPaths.cpp

Continue fix #4761 as Contents was missing from vehicle library paths.

Fix macOS contents path

---

projects/robots/robotis/darwin-op/libraries/managers/src/RobotisOp2DirectoryManager.cpp

Backslash was in wrong position

Hotfix darwin-op motion path

---

tests/default/controllers/test_suite_supervisor/test_suite_supervisor.py

Fixes #4632.
The robot windows CI test requires to start a browser on the CI machine. This may be a long process as the browser start-up on these machines may be slow. Maybe it needs to install some updates from time to time.

Attempt to fix random robot window test failures

---

src/webots/core/WbPreferences.cpp

We need to update the default webots.cloud URL.

Fix webots.cloud default URL

---

resources/web/wwi/RobotWindow.js
src/webots/gui/WbRobotWindow.cpp
src/webots/gui/WbTcpServer.cpp

#4803 introduced a new way to describe robot-windows files of projects located in the Webots installation directory (WEBOTS_HOME) using a tilde symbol: `/~/path/to/project`.
This PR adds WEBOTS_HOME to the tilde to clarify its signification: `/~WEBOTS_HOME/path/to/project`

Fix clarify robot windows URLs with WEBOTS_HOME

---

src/webots/scene_tree/WbSceneTree.cpp
src/webots/scene_tree/WbSceneTree.hpp

The field editor is currently hidden by default in many sample worlds and it is difficult for the user to find a way to unhide it to edit fields in the scene tree.
This PR ensures that when an item is selected in the scene tree, the field editor is visible. If no field is selected and the field editor shows an empty gray frame, it is automatically collapsed. The user can always collapse the editor manually to get a better visibility of the scene tree.

Improve field editor visibility

---

scripts/packaging/linux_distro.py

Attempt to fix #4715.
Inspired from https://askubuntu.com/questions/342202/failed-to-load-module-canberra-gtk-module-but-already-installed

Fix snap warnings

---

src/webots/scene_tree/WbExternProtoEditor.cpp
src/webots/scene_tree/WbInsertExternProtoDialog.cpp

Fixes #4823:
(Tested on Windows and Linux with various themes)

Fixed font in ephemeral proto warning

---

src/webots/scene_tree/WbExtendedStringEditor.cpp

The `Edit` button to open a controller in the text editor is not working for PROTOs in distributions because of their changed URLs (raw.githubusercontent.com/...).

Fix open controller in text editor

---

docs/guide/installation-procedure.md
docs/guide/setup-a-webots-project-repository.md
docs/reference/proto-design-guidelines.md

I missed some R2022a references in my previous PR.
We should also update `setup-a-webots-projects-repository.md` once we have the final docker image for R2022b

Forgotten R2022a references

---

src/webots/editor/WbProjectRelocationDialog.cpp
src/webots/nodes/WbRobot.hpp

Fixes #4864.
In addition to the automatic update of controller paths, the PR adds a condition to the `controllers` folder copy to avoid multiple redundant copies causing warnings in worlds having external protos.

Fix controllers directory in project relocation

---

docs/reference/changelog-r2022.md
src/webots/gui/WbMainWindow.cpp
src/webots/gui/WbRenderingDeviceWindow.cpp
src/webots/nodes/WbSpeaker.cpp

Fix retrieving ancestor Robot node.
The previous version was returning an invalid pointer when casting the top node to `WbRobot` independently from the node type.
For example it was failing in this case:
```
Group {
children [
Robot {
children [
Speaker { }
]
}
]
}
```

Fix invalid retrieve of non-top ancestor Robot

---

src/webots/gui/WbMainWindow.cpp
src/webots/scene_tree/WbExternProtoEditor.cpp
src/webots/scene_tree/WbFieldEditor.cpp
src/webots/scene_tree/WbFieldEditor.hpp
src/webots/scene_tree/WbSceneTree.cpp
src/webots/scene_tree/WbSceneTree.hpp

The WbExternProtoEditor content was previously saved as soon as the "SAVE" action was triggered but it is too early because the user could still abort the saving (from the dialog boxes that will be shown for warning about the simulation status or asking for the filename).
In this PR, instead of connecting directly to the "SAVE" action signal, the `WbExternProtoEditor::updateContents` is called just after the world is saved.

Fix early WbExternProtoEditor update

---

scripts/packaging/generate_proto_list.py
src/webots/vrml/WbProtoManager.hpp

As exposed in[ #4860 (comment)](https://github.com/cyberbotics/webots/pull/4860#issuecomment-1184078213), some fields are not completely captured when generating the PROTO list. In consequence, using some PROTOs (e.g. Cabinet) in the PROTO wizard as base node will create an incomplete resulting PROTO.

Fix missing interface informations in PROTOs

---

src/webots/core/WbProject.cpp
src/webots/editor/WbProjectRelocationDialog.cpp
src/webots/gui/WbMainWindow.cpp
src/webots/gui/WbNewProjectWizard.cpp
src/webots/nodes/WbCadShape.cpp
src/webots/nodes/WbCadShape.hpp
src/webots/nodes/utils/WbUrl.cpp
src/webots/nodes/utils/WbUrl.hpp
src/webots/scene_tree/WbAddNodeDialog.cpp
src/webots/vrml/WbProtoManager.cpp
src/webots/vrml/WbProtoModel.cpp
src/webots/vrml/WbProtoTreeItem.cpp
src/webots/vrml/WbProtoTreeItem.hpp
src/webots/vrml/WbTokenizer.cpp

This PR changes:
- tests of the extension should be case-insensitive
- the way urls were combined worked well, but the robustness of the solution was limited. The important change done is at this spot: https://github.com/cyberbotics/webots/blob/be46d7978b81d84fcc3fa9cc9382bbaa8b21429e/src/webots/nodes/utils/WbUrl.cpp#L294-L305
A good way of testing the change to combinePaths is to add
```
if (parent == NULL) {
combinePaths("../../asd.proto",
"https://raw.githubusercontent.com/cyberbotics/webots/projects/devices/sick/protos/SickS300.proto");
// etc
}
```
to the constructor of WbProtoTreeItem (or somewhere else where are guaranteed to pass) and print the results for different combinations (webots://, absolute, remote)

Improve robustness

---

src/webots/editor/WbTextBuffer.cpp
src/webots/editor/WbTextEditor.cpp
src/webots/gui/WbConsole.cpp
src/webots/gui/WbView3D.cpp
src/webots/scene_tree/WbTreeView.cpp
src/webots/user_commands/WbActionManager.cpp
src/webots/user_commands/WbActionManager.hpp

Complete #4889 (addressing WbTextBuffer only) by preventing and disabling the application actions:
undo, redo, cut, paste, save and replace actions on read-only text buffer.

Disable application edit actions for read-only text files

---

docs/guide/using-python.md
src/controller/python/.gitignore
src/controller/python/Makefile
src/webots/control/WbController.cpp

Fixes #4919.
It seems the execution of homebrew python controllers was broken after introducing the support for M1.
- The Makefile was not rebuilding the `_brew` version of the controllers.
- The `PYTHONPATH` was set to brew only if executing brew python from the `/usr/local/Cellar` folder. I also added the `/usr/local/opt` folder which is a common way to refer to the brew version of python as well.
Note: the M1 brew python is not supported because brew doesn't provide universal binaries and it would be complicated to support it (we would need to build universal binaries ourselves for brew which is not a trivial task).

Fixed execution of homebrew python controllers on x86_64

---

src/webots/gui/WbMainWindow.cpp
src/webots/scene_tree/WbAddNodeDialog.cpp
src/webots/scene_tree/WbInsertExternProtoDialog.cpp
src/webots/vrml/WbProtoManager.cpp
src/webots/vrml/WbProtoManager.hpp

Since there's multiple places where things are declared now, it's better to cleanup the paths directly in the function rather than prior to call it.

Favor relative urls when saving EXTERNPROTO declarations to file

---

docs/automobile/ackermannvehicle.md
docs/automobile/car.md
projects/vehicles/protos/bmw/BmwX5Simple.proto
projects/vehicles/protos/citroen/CitroenCZeroSimple.proto
projects/vehicles/protos/generic/BusSimple.proto
projects/vehicles/protos/generic/TruckSimple.proto
projects/vehicles/protos/lincoln/LincolnMKZSimple.proto
projects/vehicles/protos/mercedes_benz/MercedesBenzSprinterSimple.proto
projects/vehicles/protos/range_rover/RangeRoverSportSVRSimple.proto
projects/vehicles/protos/tesla/TeslaModel3Simple.proto
projects/vehicles/protos/toyota/ToyotaPriusSimple.proto

The robot window is set to `<none>` by default as those vehicles will be used as static objects most of the time.

Expose robot window of simple vehicles

---

docs/guide/generate_objects_doc.py

Currently the tag name used in `generate_objects_doc.py` doesn't match the one generated in the `proto-list.xml` file and the script to generate the objects documentation is broken.

Fix `generate_objects_doc.py`

---

src/webots/core/WbNetwork.cpp

Prior to R2022b, Qt's caching system was used which means that starting from R2022b (where everything is stored in the `/assets/` folder), the previous folder is likely to persist and occupy disk space for nothing (mine had 500 MB). When an instance of R2022b is launched, we should clear the previous cache. Of course if the user then opens an old Webots version, the folder will be re-generated and the assets will be downloaded again.

Clear old cache folder

---

projects/humans/c3d/controllers/c3d_viewer/c3d.py

Address #4942:
`array.fromstring` function (deprecated in Python 3.2 and removed in Python 3.9) is renamed `array.frombytes`:
https://docs.python.org/3/library/array.html#array.array.frombytes

Fix c3d controller

---

src/webots/vrml/WbProtoModel.cpp

Fixes issue 2 in #4953:
instead of using QDir::cdUp(), the upper folder is computed using based on the path and also removing the folder separator, so when reaching the root the new dir path is empty, that translates to `./` in QDir instance and is never detected as root folder.
If we do not remove the separator it works correctly.

Fix infinite loop when searching for 'protos' parent folder

---

src/webots/vrml/WbProtoManager.cpp

Fixes #4950.
We should never suggest a user to declare an EXTERNPROTO with an absolute path.

Fixed absolute EXTERNPROTO path

---

src/webots/vrml/WbNode.cpp
src/webots/vrml/WbProtoManager.cpp
src/webots/vrml/WbProtoManager.hpp

As reported in #4946, loading complex worlds is very slow.
The bottleneck is currently that the EXTERNPROTO Editor is updated continuously on load for each of the declared EXTERNPROTO.
This is useless and it is sufficient to update the editor only once at the end of the load.
I also removed a duplicated replace of the webots home path.

Speedup loading worlds

---

src/webots/engine/WbSimulationWorld.cpp
src/webots/nodes/WbGroup.cpp
src/webots/nodes/WbGroup.hpp
src/webots/nodes/WbMesh.cpp
src/webots/nodes/utils/WbWorld.cpp

Fixes: https://github.com/cyberbotics/webots/issues/4946
Although the finalization is comprised of multiple heavy steps, in practice the progress bar only tracked the progress of one of them which for some heavy worlds resulted in the dialog to either be black (until the steps with tracked progress were reached) or stuck at 0%.
There is still a small period of time where the progress bar is black before the "parsing nodes" phase, but it doesn't appear to be consistent nor reproducible. This might be related to the regex, but until we find an egregious example that allows to identify where it gets stuck, it's not easy to identify the source. Also, simplifying the PROTO might already do the trick.

Ameliorate load progress status

---

scripts/install/bash_profile.windows

Typing "atom" to launch atom from the MSYS2 console is more consistent with Linux and macOS than having to type "edit".

Better Windows alias for atom

---

src/webots/scene_tree/WbAddNodeDialog.cpp
src/webots/scene_tree/WbExternProtoEditor.cpp

This PR display the exact `EXTERNPROTO` declaration line in the tooltips.
Moreover, it skips the `tr` as no translation is needed for this.

Minor improvement to EXTERNPROTO tooltips

---

docs/reference/changelog-r2022.md
src/webots/core/WbNetwork.cpp
src/webots/core/WbNetwork.hpp
src/webots/core/WbStandardPaths.cpp
src/webots/core/WbStandardPaths.hpp
src/webots/editor/WbProjectRelocationDialog.cpp
src/webots/editor/WbTextBuffer.cpp
src/webots/editor/WbTextEditor.cpp
src/webots/gui/WbMainWindow.cpp
src/webots/nodes/WbBackground.cpp
src/webots/nodes/WbCadShape.cpp
src/webots/nodes/WbCamera.cpp
src/webots/nodes/WbContactProperties.cpp
src/webots/nodes/WbImageTexture.cpp
src/webots/nodes/WbMesh.cpp
src/webots/nodes/WbMotor.cpp
src/webots/nodes/WbSkin.cpp
src/webots/nodes/utils/WbUrl.cpp
src/webots/scene_tree/WbAddNodeDialog.cpp
src/webots/scene_tree/WbInsertExternProtoDialog.cpp
src/webots/scene_tree/WbSceneTree.cpp
src/webots/vrml/WbNode.cpp
src/webots/vrml/WbProtoManager.cpp
src/webots/vrml/WbProtoModel.cpp
src/webots/vrml/WbProtoTreeItem.cpp
src/webots/vrml/WbTokenizer.cpp
src/webots/vrml/WbTokenizer.hpp

Addresses #4955:
I think that opening the generated PROTO sources as read-only is cleaner for the user that can easier understand that any changes to this file won't be taken into account by Webots.
If they want to modify the file, they can use the "Save as" option.
Note that the action is also named "Show" and not "Edit", so it seems more coherent to not allow to modify this file.
Other improvements:
* I moved the definition of the assets cached path to the `WbStandardPaths` namespaces with all the other path declarations
* fixed generated PROTO sources path containing double path separator
* fixed cppcheck errors:
* `WbTokenizer` class: arguments passed by copy instead of reference
* `WbNetwork` class:
* some functions that can be defined as static and return reference to string
* fix …

Open generated template PROTO sources in read-only mode

---

scripts/packaging/generic_distro.py
tests/api/protos/.gitignore
tests/cache/protos/.gitignore
tests/other_api/protos/.gitignore
tests/parser/protos/.gitignore
tests/physics/protos/.gitignore
tests/protos/protos/.gitignore
tests/rendering/protos/.gitignore
tests/test_suite.py
tests/with_rendering/protos/.gitignore

It is no longer needed to copy the PROTO nodes from the `test/default` folder.

Remove PROTO nodes copy in test suite

---

src/webots/gui/main.cpp

The previous code was relying on `cygpath` to determine if MSYS2 was installed. This failed on @ygoumaz's machine because he had Git installed in `C:\Program Files\Git` which comes with its own `cygpath` and provides a wrong path for MSYS2. This PR removes the dependency on `cygpath` and simply tests for the existence of the Qt plugins folder in the Webots installation folder. If not found, it assumes we are in the development environment and reverts to the Qt plugins folder of MSYS2.
Also, I removed the override of `QT_QPA_PLATFORM_PLUGIN_PATH` which doesn't work. This variable is taken into account only when set before starting Webots, and not if set from within Webots.

Fixed Qt plugins path on Windows

---

src/webots/launcher/webots-linux.sh

This adjusts the Linux launch script to deal with a scaling bug in the i3 window manager and Qt6 on high DPI monitors.
The high DPI handling of Qt6 is disabled and the UI is manually scaled.
Scaling issue in simulation UI R2022b https://github.com/cyberbotics/webots/issues/5024

Fix high DPI scaling bug on i3 window manager (Linux)

---

.eslintrc.json

I added all the global variables/functions that we use in WebotsJS in the eslintrc to avoid warning.
However I did not add the wrenjs functions (functions that begin with `_wr` or _wrjs) because I would need to add them all and there is a lot of them...
I tried to see if some pattern matching was possible (something like `_wr*`) but I couldn't find anything.
Another solution would be to use the complete syntax and to replace all `_wr` functions by `Module.wr` but I do not think it is worth to make the code more heavy to read.

Add globals to eslintrc

---

docs/guide/webots-cloud.md
src/webots/nodes/utils/WbNodeOperations.cpp
src/webots/nodes/utils/WbNodeOperations.hpp
src/webots/vrml/WbProtoManager.cpp
src/webots/vrml/WbProtoManager.hpp

#5049 introduced a bug when importing PROTOs that contain other nested PROTOs with a supervisor (e.g. RectangleArena), causing an assertion to trigger. The variable `mImportedFromSupervisor` should only be true for level 1 of the PROTO.
The PR also removes the signal/slot mechanism which is not the lightest solution to synchronize the `mImportedFromSupervisor` variable between `WbNodeOperations` and `WbProtoManager`.

Fix assertion crash when importing some PROTOs with supervisor

---

src/webots/scene_tree/WbAddNodeDialog.cpp
src/webots/scene_tree/WbAddNodeDialog.hpp
src/webots/scene_tree/WbInsertExternProtoDialog.cpp
src/webots/scene_tree/WbInsertExternProtoDialog.hpp

Fixes #4771.
An IMPORTABLE EXTERNPROTO can now be added to the list by double-clicking. Also the Insert button is greyed out by default.

Improve new IMPORTABLE EXTERNPROTO dialog

---

docs/reference/changelog-r2022.md
src/webots/scene_tree/WbColorEditor.cpp

Fix #5090: pause the simulation while a dialog is open to avoid UI refresh issues.
I can reproduce the same issue in R2021b as well.

Fix executing color edit dialog when running in fast mode

---

src/webots/nodes/WbConnector.cpp

GCC 12.1.0 and 12.2.0 seem to display false warnings about dangling pointers (tested on Windows). This PR extends the silencing of the warning to GCC 12.2.0 which came as a MSYS2 update today.

Silence false GCC 12.2.0 warning

---

src/webots/core/WbNetwork.cpp
src/webots/core/WbNetwork.hpp
src/webots/gui/WbMainWindow.cpp
src/webots/nodes/WbBackground.cpp
src/webots/nodes/WbCadShape.cpp
src/webots/nodes/WbCamera.cpp
src/webots/nodes/WbContactProperties.cpp
src/webots/nodes/WbImageTexture.cpp
src/webots/nodes/WbMesh.cpp
src/webots/nodes/WbMotor.cpp
src/webots/nodes/WbSkin.cpp
src/webots/scene_tree/WbAddNodeDialog.cpp
src/webots/scene_tree/WbInsertExternProtoDialog.cpp
src/webots/scene_tree/WbSceneTree.cpp
src/webots/vrml/WbNode.cpp
src/webots/vrml/WbProtoManager.cpp
src/webots/vrml/WbProtoModel.cpp
src/webots/vrml/WbProtoTreeItem.cpp

The way `WbNetwork` is used is not consistent. Sometimes it is called as a singleton, sometimes not. This PR cleans up the class to get consistent use as a singleton class. 
The side effect of this inconsistency is that the value of `gCacheMap` was not the same in all calls to the `get`, `isCached` and `getUrlFromEphemeralCache` methods. This is leading to errors when loading worlds that have some PROTOs already present in the assets cache, e.g. the worlds loaded in the `world update` test of the CI (see #5087).

Cleanup `WbNetwork` to a singleton class

---

src/webots/gui/WbTcpServer.cpp

Due to past changes, the list of the world was not sent anymore to webotsJS as `nao_demo.wbt` for example but as `worlds/nao_demo.wbt`.
This causes a bug because when WebotsJS was sending back the name to request to switch the worlds, Webots adds the name from WebotsJS to the path of the current world which would give something like:
```
/home/benjamin/webots/projects/robots/adept/pioneer3/worlds//worlds/pioneer3dx_gripper.wbt
```

Fix the switching of worlds in webotsJS

---

src/webots/nodes/WbMesh.cpp

Fix #5111 
I just replace `updateUrl()` at its initial place.
I could not find any side effect to that. Either the function was moved by error or the thing it was supposed to fix was also fixed by something else in the meantime.

Fix additional mesh loading

---

src/webots/nodes/WbTriangleMeshGeometry.cpp

Fix #5111 
The meshes were loaded twice when in a Proto:
- once in `WbTriangleMeshGeometry::createTriangleMesh()`
- once in `WbTriangleMeshGeometry::createWrenObjects()`
By removing the call in `createWrenObjects` the mesh are now loaded only once.
However, I could not find/understand why there was this additional call in `createWrenObjects`. All that I know is that it is very old (prior to R2019).
I tested all the functionnalities I thought of and everything seems fine (regeneration, convert to base node, test suite, load mesh in proto,...).
I anybody know more about why we called `updateTriangleMesh` in `WbTriangleMeshGeometry::createWrenObjects`, let me know!

Load meshes only once

---

dependencies/Makefile.windows
docs/reference/changelog-r2022.md
src/webots/gui/main.cpp
src/webots/nodes/WbConnector.cpp
src/webots/nodes/WbMesh.cpp
src/webots/nodes/utils/WbDisplayFont.cpp
src/webots/nodes/utils/WbDisplayFont.hpp
src/webots/vrml/WbNode.cpp
src/webots/vrml/WbProtoModel.cpp
src/webots/vrml/WbProtoModel.hpp
src/wren/FileImport.cpp
src/wren/Font.cpp
src/wren/Font.hpp
src/wren/ShaderProgram.cpp

Fix #4757.
I had to fix [libpico.dll](https://github.com/naggety/picotts/commit/049f942c833048a1dbabca3a8a52841618ba69f9) which was having problems with UTF-8 paths on Windows. Therefore, you will have to re-install pico to test this PR on Windows.
I can now run the guided tour without any error with Webots installed in a path with UTF-8 characters (e.g., Chinese characters).
I also tested a few other world files and they all run flawlessly in that path.
In addition to fixing UTF-8 paths, this PR also:
- Fixes a bug with the `mTemplate` field of `WbProtoModel` which was wrongly set: the `textured_proto_shape.wbt` example was causing the initialization of the Lua engine which was completely useless.
- The computation of the hash for the meshes was wrong, causing different UTF-8 URLs to …

Fixed running Webots in UTF-8 path

---

src/webots/nodes/WbBackground.cpp
src/webots/nodes/WbCadShape.cpp
src/webots/nodes/WbImageTexture.cpp
src/webots/nodes/WbMesh.cpp
src/webots/nodes/utils/WbUrl.cpp
src/webots/nodes/utils/WbUrl.hpp

Currently, when converting a PROTO to base node from the scene tree, the URLs of `ImageTextures`, `CadShapes`, `Backgrounds` and `Meshes` are automatically converted to web format (`raw.githubusercontent.com/`). This should not be the case if we are not in a distribution and not streaming in x3d mode.

Fix URL format when converting to base node

---

src/webots/app/WbApplication.cpp

Fix #5127:
always unset the postponed logs flag and print queued messages when canceling a world load.

Print postponed log messages when load is cancelled

---

src/webots/gui/WbX3dStreamingServer.cpp

When streaming assets that have spaces in their path (either in some folder name or directly in their filename), the urls are automatically converted by `fetch` such that all spaces are replaced by `%20`.
However, in Webots we need to convert the `%20` back to normal spaces otherwise Webots will not found the files.

Fix urls that are send to webotsJS with a space

---

src/webots/gui/WbMainWindow.cpp
src/webots/nodes/WbRobot.cpp

The conversion to `<generic>` controllers and robot-windows when opening a remote Robot PROTO in the text editor is only working in distributions, but not in the development environment. Moreover, relative and `webots://` URLs in remote PROTOs were not correctly converted when editing them locally from the development environment.
This PR fixes these issues, and adds `INFO` logs in the console to warn the user that `controller` and `window` fields have been updated.

Fix conversion to `<generic>` and warn user

---

src/webots/vrml/WbNode.cpp

This PR want to fix #5135 
It comes from [here](https://github.com/cyberbotics/webots/blob/7a09896b9e0080ba4360efae828f93d0a5925fb6/src/webots/vrml/WbNode.cpp#L772).
This was introduced in #5092 to fix https://github.com/cyberbotics/webots/issues/5092#issuecomment-1222366931
Adding an additional condition seems to fix it. However I am not 100% convinced is it correct and it is not just some "luck"

Fix crash transparency

---

resources/projects/worlds/empty.wbt

With the introduction of EXTERNPROTO declarations, a minimum of one space is enforced during a save (before and after the declarations). Even if no declarations are present, at least one line of space is generated between the header and the first node.
`empty.wbt` currently doesn't follow this rule and therefore generates a diff when running test_worlds.

Add space to empty.wbt

---

docs/reference/changelog-r2022.md
src/webots/vrml/WbNode.cpp

Fixes: https://github.com/cyberbotics/webots/issues/5148 (both issues)
Due to the lack of a link between field and parameter in a derived PROTO context (without derivation everything works), changes to the parameter didn't propagate (first issue) and it wasn't possible to insert the second Lincoln in a slot of a Truck (second issue, add-node showed up empty whereas it was possible to insert it in a TruckSimple).
Intuitively it seems wrong to me that the alias connection is made only if the parameter belongs to the base PROTO. In the Lincoln case for example, the parameter `plate` is indeed a parameter exclusive to the derived PROTO (Lincoln), not the base ones (Car, Ackermann).
So far I haven't encountered side effects but I'll keep investigating

Fix alias not propagating in derived proto and empty add-node

---

src/webots/scene_tree/WbAddNodeDialog.cpp
src/webots/scene_tree/WbInsertExternProtoDialog.cpp
src/webots/scene_tree/WbSceneTree.cpp
src/webots/vrml/WbProtoManager.cpp
src/webots/vrml/WbProtoManager.hpp

Fixes https://github.com/cyberbotics/webots/issues/5156
When cutting a PROTO node that contains additional (slotted) PROTO nodes, all of them need to be re-declared on a paste.

Restore lost declaration after cut-paste

---

resources/osm_importer/utils/misc_utils.py

When roads are written, so are RoadLines which currently aren't declared and therefore show a warning

Add missing declaration in osm_importer

---

resources/web/wwi/X3dScene.js

This minor feature is needed for the SimGait project as I need to scale non-uniformly the shape of the muscles.
Although the scale of a Transform should never change while a simulation is running (except if a supervisor changes it explicitly), I needed this feature in my [conversion script](https://github.com/cyberbotics/scone-playback/blob/main/convert.py) that produces Webots animations from OpenSim model and motion files.

Added scale update in animations

---

src/webots/control/WbControlledWorld.hpp
src/webots/control/WbController.cpp
src/webots/core/WbFileUtil.cpp
src/webots/core/WbFileUtil.hpp
src/webots/core/WbProject.cpp
src/webots/core/WbVersion.hpp
src/webots/editor/WbFindReplaceDialog.cpp
src/webots/engine/WbSimulationWorld.hpp
src/webots/gui/WbRobotWindow.cpp
src/webots/nodes/WbHingeJointParameters.hpp
src/webots/nodes/utils/WbJoystickInterface.cpp
src/webots/nodes/utils/WbUrl.cpp
src/webots/nodes/utils/WbWorld.hpp
src/webots/scene_tree/WbSceneTree.cpp
src/webots/vrml/WbNode.cpp
src/webots/vrml/WbProtoManager.cpp
src/webots/vrml/WbProtoModel.cpp
src/wren/Debug.hpp
src/wren/Material.cpp
src/wren/Material.hpp
src/wren/PostProcessingEffect.cpp
src/wren/Primitive.hpp
src/wren/ShaderProgram.cpp

Fixes: https://github.com/cyberbotics/webots/issues/5173
Also fixes 2 issues with the conversion:
- If slots with PROTO nodes were present prior to the conversion, when deleting the node (prior to spawning the converted version) the declaration of these slots would be removed and they weren't re-added afterwards
- In the process of recursively exposing the declarations needed when converting derived PROTO to base-node, it could happen that the parent file was a cached file, and its disk location (rather than the original URL) was used when determining the full URL of a relatively-defined PROTO.
Concerning the relative URL appearing after conversion:
It turns out that solution 2 is not really an option, or at least not without rethinking the writer logic from the ground up. …

Fix convert root to basenode and other conversion issues

---

docs/guide/running-extern-robot-controllers.md
resources/Makefile.include
src/webots/app/WbApplication.cpp
src/webots/editor/WbBuildEditor.cpp
src/webots/editor/WbProjectRelocationDialog.cpp

Fixes #5186.
In addition to fixing the above mentioned issue, this PR also enforce the copy of a controller compiled from the Webots build editor. This is actually needed when compiling extern controllers because Webots won't make the copy of the controller before starting an extern controller. It does it only for non-extern controllers. So, it is annoying when developing an extern controller to have to make the copy manually after re-compiling.

Fix copy of binary controllers

---

src/webots/nodes/utils/WbNodeOperations.cpp
src/webots/scene_tree/WbAddNodeDialog.cpp
src/webots/scene_tree/WbExternProtoEditor.cpp
src/webots/scene_tree/WbInsertExternProtoDialog.cpp
src/webots/scene_tree/WbSceneTree.cpp
src/webots/vrml/WbProtoManager.cpp
src/webots/vrml/WbProtoManager.hpp

Fix #5189:
the `WbExternProtoEditor` content was updated when modifying a new PROTO to the externproto list, even if the editor was not visible, and this was increasing the size of all the field editors.
Given the latest changes in the IMPORTABLE vs other EXTERNPROTO declarations, the importable list can currently only be changed by `WbExternProtoEditor` itself and it is not modified by other user actions.
Thus, we can simplify the code and completely remove the notification when the list of EXTERNPROTO changes.

Fix field editor size update

---

src/webots/user_commands/WbUndoStack.cpp

Essentially the logic seems to be that actions that result in a template regeneration are not even pushed to the undo stack although the action itself takes place otherwise the scene tree wouldn't be updated. 
The function itself seems rather odd since we set `mClearRequest` to false 2 lines above, but I suspect that the execution of `QUndoStack::push(cmd)` calls `setClearRequest` which changes the flag back to positive, ensuring that we enter the `clear()` function. In short we push it, do the action, and remove it from the stack and since it's no longer there neither the menu option nor CTRL+Z have anything to revert to (i.e., the button remains disabled) .
These two lines appear in the source code of R2022a but no longer do in our repo. I've tried to figure out at which …

Fix UNDO crash

---

src/webots/scene_tree/WbAddNodeDialog.cpp

The clean-up of #5193 removed the wrong boolean in the call to `declareExternProto` in `WbAddNodeDialog`, causing the Add Node button to also add the PROTO to the IMPORTABLE list.

Fix incorrect insertion in IMPORTABLE EXTERNPROTO list

---

src/webots/gui/WbMainWindow.cpp

If a resource had a name like `Cat 3D Model`, the name was cut in the POST request in just `Cat`

Fix upload of resources that have a space in their name

---

src/webots/nodes/WbLidar.cpp
src/webots/nodes/WbLidar.hpp

Before the rotating head was export side-by-side with the lidar and not _in_ the lidar.
The consequence was that if the lidar has a translation/rotation, it was not applied to the rotating head once exported in x3d.

Fix lidar rotating head export to x3d

---

docs/reference/inertialunit.md

Applies task 2 of #5197.
The documentation was misleading because it was associating the `InertialUnit` node with an IMU, which is incorrect.

Improve InertialUnit documentation

---

docs/reference/changelog-r2022.md
src/webots/nodes/WbLightSensor.cpp

In `WbLightSensor::computeLightMeasurement`, `R` is directly used from `spotLight->direction()`.
So `WbLightSensor` class does not work correctly when spot light object is moved.
I think `R` should be calculate using `spotLight->upperTransform()->rotation()`.
Thank you for making nice application, and maintenance!

fix WbLightSensor: collect behavior of recieving light of SpotLight

---

resources/web/wwi/Animation.js
resources/web/wwi/webots.js

At setup we check if all labels are present in the first frame to have a reference point when jumping backward and forward in the animation.
If it is not the case, create a label instruction in the first frame which set the label to transparent (and empty)
Fix #5227

Fix labels reset

---

scripts/converter/declare_externproto.py

As reported by a user, PROTO files can be rather messy (useless spaces, newlines, tabs, ..) which made the script fail. For example:
```
#VRML_SIM R2022a utf8
PROTO MineGearsRover [
field SFVec3f    translation  0 0 0
field SFRotation rotation     0 0 1 0
field SFString   name            "MineGearsRover" # Is `Solid.name`.
field SFString   controller      "mine_gears_rover"
]
{
Robot {
}
```
This PR improves robustness

Make conversion script more robust

---

docs/reference/gps.md
include/controller/c/webots/gps.h
include/controller/cpp/webots/GPS.hpp
src/controller/c/gps.c
src/controller/cpp/GPS.cpp

wb_gps_get_speed() was labeled as const, and should not.
This pull-request fixes issue #5235

GPS: Remove wrong const attribute

---

docs/reference/changelog-r2022.md
resources/web/wwi/nodes/WbViewpoint.js

Fix #5228 
I tried several things but finally went for a very simple solution:
- If the viewpoint follow is not enabled, we never touch the viewpoint position (except if the user reset it manually).
- If the viewpoint follow is enable, we reset it **but** we preserve the transformations (translation and rotation) done by the user.
We are force to kind of reset the position otherwise we have some problems with the follow (it does not like big jump).

Fix webotsJS follow viewpoint

---

resources/web/wwi/css/progress.css

Some errors/warning does not hold on one line.
Can be seen here: https://testing.webots.cloud/run?version=R2022b&url=https://github.com/BenjaminDeleze/sandbox/blob/master/simulation_testing/worlds/testing.wbt

Allow progress text to be on two lines

---

docs/guide/tutorial-5-compound-solid-and-physics-attributes.md

Due to the axis convention change
https://cyberbotics.com/doc/guide/tutorial-5-compound-solid-and-physics-attributes?version=doc-axis-typo

Fixed an axis typo

---

docs/guide/tutorial-2-modification-of-the-environment.md

The caption seems to refer to a later exercise (Hands-on #7) instead of what the figure shows
https://cyberbotics.com/doc/guide/tutorial-2-modification-of-the-environment?version=doc-figure-caption-fix

Changed a figure's caption to correspond more to it

---

docs/guide/tutorial-6-4-wheels-robot.md

When following the tutorial step-by-step, the low-level representation seems to come too early as it gives information from the next sections. Placing it at the end of the HingeJoint chapter seems more suited.
https://cyberbotics.com/doc/guide/tutorial-6-4-wheels-robot?version=doc-better-fig-placement

Better figure order

---

resources/wren/shaders/merge_spherical.frag

Updates  #2295
This PR provides a fisheye shader adapted from https://www.shadertoy.com/view/lssGD4 to create a spherical image which distorts in both directions instead of only one. 
It currently only works for rgb cameras as the merge_spherical.frag shader is also a basis for the LIDAR class and changing these projection for range images therefore destroys lidar range images and point clouds.
In general a test, if this shader projects the image correct, should be done.
Maybe the two shaders should be split into an equirectangular and a fisheye shader class which can be properly assigned.

added shader that creates a more promissing spherical image

---

src/webots/nodes/WbLightSensor.cpp

Fix bug using a NULL pointer introduced in https://github.com/cyberbotics/webots/pull/5231

Fix measurement of spot light

---

docs/reference/changelog-r2023.md
resources/web/streaming_viewer/index.html
resources/web/wwi/Parser.js
resources/web/wwi/Server.js
resources/web/wwi/Stream.js
resources/web/wwi/Toolbar.js
resources/web/wwi/WebotsView.js
resources/web/wwi/X3dScene.js
resources/web/wwi/webots.js
src/webots/gui/WbTcpServer.cpp
src/webots/gui/WbTcpServer.hpp
src/webots/gui/WbX3dStreamingServer.cpp
src/webots/gui/WbX3dStreamingServer.hpp
src/webots/nodes/WbRobot.cpp
src/webots/nodes/WbWorldInfo.cpp

The internal windowing system and the robot windows were not supporting mjpeg streaming.
Moreover, the information regarding the robot window was sent in the `.x3d` file and by websocket messages with `robot window:`.
**Tasks**

Enhance robot window in webots.js for mjpeg mode

---

docs/reference/proto-design-guidelines.md

The default `translation` field for PROTOs should preferably be set at origin. PROTOs should also be created so that they lie on the ground when imported. However, in the case of devices derived from `Base Nodes` such as `Lidars`, `Cameras`, etc., the sensor itself may not be located at the center of the contact surface of the device shape. In this case, the PROTO can have a default translation to compensate for the offset, so that the device does not float in the air or sink into the ground.
This PR adds this exception to the documentation.
https://www.cyberbotics.com/doc/reference/proto-design-guidelines?version=documentation-improve-proto-translation-convention#translation-and-rotation

Improve default PROTO translation field documentation

---

resources/web/wwi/nodes/WbCadShape.js

The case of invalid CadShape URL was wrongly handled and resulted in different crashes.

Fix handling errors in CadShape URLs in the web interface

---

resources/wren/shaders/point_set.frag

The PointSet shader was working fine on desktop, but in some situations on the web it was crashing the simulation.
It is because webgl is less permissive than openGL when it comes to shaders.
The issue was that the draw buffer is expecting fragment output: `color` and `normal`, as for `Phong` shader for example.
However, the PointSet shader was only returning a `color` output because the `normal` one is not used.
I added a null `normal` output to fix the issue.

Fix pointSet shader for web

---

docs/reference/changelog-r2022.md
src/webots/gui/WbMultimediaStreamingServer.cpp
src/webots/gui/WbSimulationView.cpp

Qt6.4 arrived on MSYS2 with a couple of deprecation issues. This PR fixes them.
See https://doc.qt.io/qt-6/qmouseevent-obsolete.html#QMouseEvent-2

Fixed Qt6.4 deprecation warnings

---

projects/samples/devices/controllers/imu/imu.c

The controller of the imu sample world (`imu.c`) is using the `abs()` method instead of the `fabs()` one. This triggers a compilation error on macOS.

Fix macOS compilation due to imu.c

---

docs/reference/changelog-r2022.md
src/webots/gui/WbTcpServer.cpp

If a TCP controller tries to connect to a Webots instance that is currently loading a world, Webots crashes.

Fix TCP extern controller connection when world is loading

---

resources/web/wwi/protoDesigner/classes/FieldModel.js

Note: it does not bring full support for VRML cadshape (the texture urls are not passed to `x3d` for example), but just prevents an exception to be raised.

 Add cadshape fieldmodel

---

docs/reference/changelog-r2022.md
resources/wren/shaders/overlay.frag

Resize and close buttons in RangeFinder overlay are sometimes completely black
It seems that this is because the `mix` function cannot properly handle the values (like FLT_MAX) of the RangeFinder image pixel color.
For the close and resize buttons where the alpha channel is 1 or 0 it is simpler to not mix the colors.

Fix black buttons in RangeFinder overlay

---

docs/reference/changelog-r2022.md
src/webots/scene_tree/WbAddNodeDialog.cpp
src/webots/vrml/WbTokenizer.cpp
src/webots/vrml/WbTokenizer.hpp

The description of base nodes in the `add node` dialog have been broken by both the removal of `WBO` and the introduction of `EXTERNPROTO`

Restore the description of base node

---

projects/robots/clearpath/pr2/protos/Pr2.proto

The [test-worlds](https://github.com/cyberbotics/webots/actions/runs/3277524121/jobs/5395245692) was broken by #5266. This PR fixes it.

Fix deprecated field in PR2 camera

---

docs/reference/changelog-r2022.md

In R2022b-rev1 changelog the indent in only by 1 space instead of 2 (as in the rest of the file).

Fix ChangeLog indent

---

docs/reference/changelog-r2022.md
src/webots/nodes/utils/WbNodeOperations.cpp
src/webots/scene_tree/WbAddNodeDialog.cpp
src/webots/scene_tree/WbInsertExternProtoDialog.cpp
src/webots/scene_tree/WbSceneTree.cpp
src/webots/vrml/WbProtoManager.cpp
src/webots/vrml/WbProtoManager.hpp

Fix  #5325:
generalize the `WbExternProto::isFromRootNodeConversion()` flag to apply for any user action (and including the node insertion) so that the PROTO declaration is correctly found also when copying and pasting a PROTO node inserted in the world from the add node dialog.

Fix PROTO declaration error when copy and pasting inserted nodes

---

docs/reference/changelog-r2022.md
src/webots/nodes/WbCadShape.cpp
src/webots/nodes/WbCadShape.hpp
src/webots/nodes/WbMesh.cpp

Fix duplicated CadShape mesh load and improve warnings

---

resources/web/wwi/nodes/WbMesh.js
resources/web/wwi/nodes/utils/WbTriangleMesh.js
resources/web/wwi/nodes/utils/WbVector3.js
resources/web/wwi/test.html

For example the `shrimp`
This was not needed before as the tessellation and everything was done in Webots, but now it is done in WebotsJS

Add support for 5+ vertices polygon

---

docs/reference/changelog-r2022.md
src/webots/vrml/WbNode.cpp
src/webots/vrml/WbProtoModel.cpp
src/webots/vrml/WbProtoModel.hpp

Fix #5214:
this is a regression from R2022a introduced in #5103 where the instruction to pass the `isTemplate` flag from the base to the inherited node has been removed.
Additionally I also updated some debug instructions throwing errors during compilation.

Fix isTemplate flag not passed from base PROTO

---

scripts/packaging/files_msys64.txt

Webots doesn't depend any more on this DLL (probably due to some other DLL dependency change) and it doesn't get installed in the GitHub CI machine, causing the creation of the Windows package to fail.
Removing this obsolete dependency should fix the package creation on Windows in the CI.

Removed obsolete dependency

---

resources/nodes/Capsule.wrl
resources/nodes/Cone.wrl
resources/nodes/Cylinder.wrl

When the FLU conversion took place we forgot to change the description of `Cone`/`Cylinder`/`Capsule` in the `.wrl` files.

Update axis orientation in wrl

---

projects/samples/robotbenchmark/humanoid_marathon/controllers/marathon/.gitignore

There was a typo in the `.gitignore` file of the marathon controller.

Fix wrong .gitignore

---

docs/guide/using-your-ide.md

Fixed a linking issue that may appear in some examples (I found it in the the crazyflie) in the CMake template. The issue was a missing link to libm. It will show the following linking error: 
undefined reference to symbol 'fmax@@glibc_2.2.5' 
Also added the WEBOTS_HOME variable in the CMake, just to avoid the hassle of having to export it in the console every time.

Improvements on CMake template

---

docs/reference/changelog-r2023.md
src/controller/c/supervisor.c
src/webots/nodes/utils/WbSupervisorUtilities.cpp
src/webots/vrml/WbField.cpp

Fix #5365:
use the WbFieldStruct::count variable in the libController to store if the SFNode value is NULL without having to request the field value.

Fix SFNode field flagged empty in libController

---

src/webots/engine/WbAnimationRecorder.cpp

When an animation is done in a simulation where nothing happens (for example when \<generic\> controllers are used for the robots), the error message incorrectly says:
> Error: No animation content is available because the simulation did not start
even though the simulation did start.
I changed the error message to be more specific and added a recommendation to use a scene instead
This pull-request fixes #4994

Improved error message of empty animation

---

src/webots/engine/WbAnimationRecorder.cpp
src/webots/gui/WbMainWindow.cpp

If an animation recording is started and Webots is closed before it is stopped, the json animation file is not created. This adds a small check to stop the animation correctly when Webots is closed by the user in the GUI, with ctrl-C in the console or by a supervisor.

Stop pending animation on close

---

docs/reference/changelog-r2023.md
src/webots/scene_tree/WbSceneTree.cpp

Fixes #5141.
The `updateSelection()` method of the `SceneTree` was called on a deleted node, leading to a crash in some cases (e.g. the one reported in the issue). This can be fixed by using the `mRowsAboutToBeRemoved` boolean, which is already used when simply deleting a node from the `SceneTree`.
In addition, this PR fixes another issue, where the newly created `Node` was not selected after the conversion.

Fix crash double `root to base node`

---

src/webots/gui/WbNewProjectWizard.cpp

1. open spot.wbt (or another project in a protected location)
2. `file > new > new project directory`
3. The path contains two `//`
doing the same in a non-protected location doesn't require the correction (line 58).

Fix suggested project path

---

docs/reference/accelerometer.md

Added info regarding the default name tag in Accelerometer.md.
To be evaluated as a template for other sensors nodes.
Relates to the discussion https://github.com/cyberbotics/webots/discussions/5449
Preview: https://www.cyberbotics.com/doc/reference/accelerometer?version=toshiharutf-doc-acccelerometer-1

Added info regarding the name tag

---

src/webots/core/WbStandardPaths.cpp

Fixes #5477.
This PR makes that Webots uses the local user tmp folder instead of the global one, thus avoiding problems like the one raised in #5477.

Fixed tmp path on macOS

---

docs/guide/the-3d-window.md
resources/translations/wb_de.ts
resources/translations/wb_es.ts
resources/translations/wb_fr.ts
resources/translations/wb_generic.ts
resources/translations/wb_it.ts
resources/translations/wb_ja_JP.ts
resources/translations/wb_zh_CN.ts
src/webots/gui/WbMainWindow.cpp
src/webots/scene_tree/WbExtendedStringEditor.cpp

Fixes https://github.com/cyberbotics/webots/issues/5479

Fix external force/torque instructions

---

projects/default/controllers/sumo_supervisor/sumo_supervisor.py

Fixes #5481.
This PR also replaces `optparse` (deprecated in Python 3.10) by `argparse`.

remove path normalization + replace optparse

---

docs/reference/device.md
src/controller/c/robot.c

Merge master into develop

---

docs/reference/changelog-r2023.md
src/webots/sound/WbMotorSoundManager.cpp

The text-to-speech sample demo was generating a motor sound whereas no motor was running.
This PR fix this problem which was noticed on macOS, but could be also on other platforms.

Fix motor sound on macOS

---

src/webots/control/WbController.cpp

Removed obsolete Java controller warning for non-ASCII path

---

src/webots/wren/WbWrenShaders.cpp

Possibly fix #5491 and #5515.
"firstRender" uniform is created with the wrong type (introduced in #5436).
This might cause the not fully reproducible issues experienced on various systems.

Fix motion blur shader

---

lib/controller/python/controller/camera.py

This PR fixes a data type incompatibility in the new Python API reported by @vitormartins01 on Discord:
That used to work with the previous version of the Python API and doesn't work any more in the R2023a nightly build.
This PR fixes it.
It also fixes the segmentation image getter in the same way.
**Note**: the new getter, e.g., `Camera.image` returns the raw value without any conversion and is therefore the fastest way to get image data. So we want to keep it like that and use of the old getter `Camera.getImage()` for backwards compatibility, not performance.

Fixed camera image data type

---

src/controller/c/supervisor.c

Fixes https://github.com/cyberbotics/webots/issues/5365
The `data.sf_node_uid` field is set only if the user explicitly requests the value of the field (with `.getSFNode()`), which is not a necessary step when one wants to remove the current value from a field (we don't care what it is, we just want it gone). After the removal however we need to ensure this variable is set back to 0 (i.e. NULL) on top of setting the counter to 0. Otherwise we cannot insert a new node in its place unless once again the user explicitly does a `getSFNode()` in order to "refresh" the data on the libcontroller side.
Alternatively, it would also be an option to only check for the count [here](https://github.com/cyberbotics/webots/blob/4a43cf70e6ad9cf5bdb8be09a4aceb7d1ee45f01/src/controller/c/supe …

Fix `SFNode` removal and string insertion

---

docs/reference/supervisor.md
include/controller/cpp/webots/Supervisor.hpp

Address https://github.com/cyberbotics/webots/pull/5582#discussion_r1033197011
Set a default value of 0 for the transparency in the Supervisor setLabel method of the C++ and Java APIs.
In addition, this PR fixes a missing parameter in the documentation of the MATLAB API.

Fixed supervisor setLabel API function

---

docs/reference/changelog-r2023.md
projects/samples/howto/openai_gym/controllers/openai_gym/openai_gym.py

The OpenAI Gym sample was not converging any more after the ENU/FLU conversion.
This PR fixes it after a report from a user:
>Dear Sir or Madam,
>
> I just started working with webots to build a simulation environment for robot reenforcement learning.
> I tested your openai_gym example which does not stabilize the pendulum correctly, because the vehicle always drifts away in one direction.
>
> After I changed the code in line 97 with the correct parameters (X instead of Z directions and rotation around Y axis), the pendulum is stabilized reliably.
>
> Old:
> ```python
>       self.state = np.array([robot.getPosition()[2], robot.getVelocity()[2],
>                               self.__pendulum_sensor.getValue(), endpoint.getVelocity()[3]])
> ```
>New:
> ```python
>        self.state = …
```

Fixed OpenAI Gym sample

---

lib/controller/python/controller/node.py

The wrong C function is called in `Node.disablePoseTracking`.

Fix Python Node.disablePoseTracking

---

docs/reference/supervisor.md

The doc is inconsistent with the [function](https://github.com/cyberbotics/webots/blob/2491d02ff6070a33b294100a8e18e23d50e05009/src/controller/c/supervisor.c#L2931).

Fix pose tracking docs

---

.github/workflows/test_suite_mac.yml
.github/workflows/test_suite_mac_develop.yml
docs/reference/changelog-r2023.md
projects/robots/softbank/nao/protos/Nao.proto
projects/robots/softbank/nao/protos/NaoLeftWristH21.proto
projects/robots/softbank/nao/protos/NaoLeftWristH25Realistic.proto
projects/robots/softbank/nao/protos/NaoRightWristH21.proto
projects/robots/softbank/nao/protos/NaoRightWristH25Realistic.proto
resources/web/wwi/nodes/WbAppearance.js
resources/web/wwi/nodes/WbBackground.js
resources/web/wwi/nodes/WbGeometry.js
resources/web/wwi/nodes/WbPbrAppearance.js
resources/web/wwi/nodes/WbPointSet.js
resources/web/wwi/nodes/WbScene.js
resources/web/wwi/nodes/WbShape.js
resources/web/wwi/nodes/WbTriangleMeshGeometry.js
resources/web/wwi/nodes/WbViewpoint.js
resources/web/wwi/wren/WbWrenBloom.js
resources/web/wwi/wren/WbWrenGtao.js
resources/web/wwi/wren/WbWrenHdr.js
resources/web/wwi/wren/WbWrenPicker.js
resources/web/wwi/wren/WbWrenPostProcessingEffects.js
resources/web/wwi/wren/WbWrenShaders.js

Conflicts:
- resources/web/wwi/nodes/WbAppearance.js
- resources/web/wwi/nodes/WbGeometry.js
- resources/web/wwi/nodes/WbPbrAppearance.js
- resources/web/wwi/nodes/WbPointSet.js
- resources/web/wwi/nodes/WbShape.js

Merge develop in feature-web-proto

---

docs/reference/changelog-r2023.md
lib/controller/python/controller/field.py

Fix `Field.enableSFTracking` and `Field.disableSFTracking`:
add missing argument in Python API.

Fix enable/disable SF tracking in Python API

---

docs/guide/epuck.md
docs/reference/changelog-r2023.md
projects/robots/gctronic/e-puck/controllers/line_follower/runtime.ini
projects/robots/gctronic/e-puck/controllers/obstacle/runtime.ini
projects/samples/curriculum/controllers/beginner_better_collision_avoidance_algorithm/runtime.ini
projects/samples/curriculum/controllers/beginner_blinking_e-puck/runtime.ini
projects/samples/curriculum/controllers/beginner_e-puck_dance/runtime.ini
projects/samples/curriculum/controllers/beginner_finite_state_machine/runtime.ini
projects/samples/curriculum/controllers/beginner_linear_camera/runtime.ini
projects/samples/curriculum/controllers/beginner_move_your_e-puck/runtime.ini
projects/samples/curriculum/controllers/beginner_rally/runtime.ini
projects/samples/curriculum/controllers/novice_remain_in_shadow/runtime.ini
projects/samples/curriculum/controllers/novice_train/runtime.ini

Address #5642:
BotStudio controllers need a `runtime.ini` file specifying the location of the qt_utils library to correctly be executed by Webots.
In this PR we add the `runtime.ini` file to all the distributed BotStudio controllers so that they work out of the box.
_Note: same `runtime.ini` also used for Robotis OP2_

Distribute runtime.ini for BotStudio controllers

---

resources/web/wwi/FloatingProtoParameterWindow.js
resources/web/wwi/nodes/WbBallJoint.js
resources/web/wwi/nodes/WbHinge2Joint.js
resources/web/wwi/nodes/WbHingeJoint.js
resources/web/wwi/test.html

Joints now also work if they do not have specific parametersJoints attached to them
Test it here:
https://proto.webots.cloud/run?version=proto&url=https://github.com/BenjaminDeleze/sandbox/blob/master/protoExample/protos/Thymio2Ball.proto

Ball joint slider

---

src/webots/nodes/WbCadShape.cpp

The `recomputeBoundingSphere` function in `WbCadShape` was called in a different place than in `WbGroup` and `WbGeometry` and I could not find out why.
This causes, since https://github.com/cyberbotics/webots/pull/5359, the `move Viewpoint to Object` to not work.
@ad-daniel maybe you remember why it was done differently in `WbCadShape`?

Fix cadshape move to viewpoint

---

docs/reference/changelog-r2023.md
projects/robots/franka_emika/panda/protos/Panda.proto
src/webots/nodes/WbCadShape.cpp
src/webots/nodes/WbRobot.cpp
src/webots/nodes/utils/WbDictionary.cpp
src/webots/nodes/utils/WbDictionary.hpp
src/webots/nodes/utils/WbNodeOperations.cpp
src/webots/nodes/utils/WbNodeOperations.hpp
src/webots/nodes/utils/WbNodeUtilities.cpp
src/webots/nodes/utils/WbNodeUtilities.hpp
src/webots/nodes/utils/WbTemplateManager.cpp
src/webots/nodes/utils/WbTemplateManager.hpp
src/webots/scene_tree/WbSceneTree.cpp
src/webots/vrml/WbNode.cpp
src/webots/vrml/WbVrmlNodeUtilities.cpp
src/webots/vrml/WbVrmlNodeUtilities.hpp

Fix #5360 and https://github.com/cyberbotics/webots/issues/5463:
Webots is blocked in an infinite loop when converting a PROTO node in a field triggering an upper PROTO node regeneration if it contains a DEF node and its USE node.
This is because updating the DEF node associated to the USE node triggers a PROTO regeneration and after the regeneration the new USE node needs to be updated again.
This fix prevents nested PROTO regeneration during the dictionary update.
TODO:

Fix infinite dictionary update

---

docs/reference/changelog-r2023.md
src/webots/scene_tree/WbExtendedStringEditor.cpp
src/webots/scene_tree/WbExtendedStringEditor.hpp

Address  #5466:
in the `WbExtendedStringEditor` class check if the current field has restricted values and, if it is the case, hide the `Select...` button.
I evaluated the possibility to check the list of accepted values and remove the ones that are not available.
But it seems clearer and easier to understand for the user if all the accepted values are shown in the combo box and Webots throws an error in the console if the requested resources is not found.
In case the value, for example the controller, is not found or not compiled Webots will still use the default one even if it is not in the list (e.g. the <generic> controller).

Disable Select button in WbExtendedStringEditor for restricted fields

---

src/controller/c/robot.c

When running an extern controller with WEBOTS_STDOUT_REDIRECT set to 1, the logs are redirected to the Webots console. However, this causes Webots to crash in debug compilation mode because of an assertion. 
If nothing is written to the buffer at a timestep, the buffer was not set back to NULL.

Fix wrong assertion failure for console redirection

---

docs/guide/tutorial-7-your-first-proto.md

For a newbie it is not easy to find that the first line in a proto file has to be `#VRML_SIM R2023a utf8`.
Current page is https://cyberbotics.com/doc/guide/tutorial-7-your-first-proto
Modified page is https://cyberbotics.com/doc/guide/tutorial-7-your-first-proto?version=stepkun:patch-1

Add necessary first line in proto file examples

---

projects/samples/howto/openai_gym/controllers/openai_gym/openai_gym.py

`stable_baselines3` is only compatible with gym up to version 0.21.0, an error is currently thrown when following the instructions.

Fix `openai_gym` instructions

---

projects/robots/rec/fabtino/protos/Fabtino.proto

Fabtino's left wheels are wrong:
before 
after
It's just a visual bug, the bounding object is correct so should have no impact for the users

Fix Fabtino wheel orientation

---

tests/api/controllers/supervisor_import_remove/supervisor_import_remove.c
tests/api/controllers/supervisor_notify_import_remove_mfnode/supervisor_notify_import_remove_mfnode.c

Change the controllers associated with the `supervisor_import_remove.wbt` test so that the `SPHERE2` node does not get removed by `wb_supervisor_node_remove()` until a full step after it's been checked for. This is necessary because `wb_supervisor_node_remove()` is immediate. Without this change, the test fails for me approximately 20% of the time with "Wrong DEF name for top node at index 5: found , expected SPHERE2."

Fix race condition when testing node removal.

---

tests/test_suite.py

Change test_suite.py's generateWorldsList()  to return a list of strings instead of a list of lists when generating the list from file arguments. Returning a list of lists resulted in this error when running an individual test (e.g. `./test_suite.py api/worlds/center_of_mass_and_contact_points.wbt`):
```
Traceback (most recent call last):
File "/home/brettle/git/webots/tests/./test_suite.py", line 345, in <module>
f.write(world + '\n')
~~~~~~^~~~~~
TypeError: can only concatenate list (not "str") to list
```

Fix error when running individual tests.

---

docs/reference/changelog-r2023.md
src/webots/scene_tree/WbNodePane.cpp
src/webots/scene_tree/WbNodePane.hpp

Address #4925:
keep track of the selected tab in the Field Editor for nodes so that it can automatically restored when selecting a different node.

Keep track of selected node pane tab

---

resources/web/wwi/ProtoManager.js
resources/web/wwi/protoVisualizer/Parameter.js
resources/web/wwi/test.html

For proto web viewer, when the Proto is an `Appearance`/`PBRAppearance` we add a sphere geometry to be able to see the appearance, and a transform such that the sphere is not in the floor.
At first I tought I needed to keep the transform id to replace it on regeneration but finally we alway reuse the same so I think that it is useless.
preview: https://proto.webots.cloud/run?version=R2023b&url=https://github.com/BenjaminDeleze/sandbox/blob/master/protoExample/protos/Grass.proto&type=undefined

Enhancement sphere for appearances

---

resources/web/wwi/X3dScene.js
resources/web/wwi/nodes/WbBaseNode.js

Fixes `colorOverride` parameter not having an effect after regeneration. Specifically, it fixes the `Grass.proto`. The reason the change didn't happen is that the wren objects of the regenerated node were not created (`wrenObjectsCreatedCalled` was always true). Fixing this issue however broke the DEF-USE mechanism for the OfficeChair `legAppearance` (appearance changes no longer propagated to all legs). The issue was that the process of "unfinalizing" the parent (Shape) node to which we're changing the appearance occurred only for the DEF node, and we weren't doing the same for the parent of the USE ones. In short, when finalizing a DEF node we were notifying all USE nodes, however when "unfinalizing" it, we did so only for the DEF and not the USE ones, which resulted in …

Fix notification after regeneration

---

resources/web/wwi/ImageLoader.js
resources/web/wwi/Parser.js
resources/web/wwi/nodes/WbCadShape.js
resources/web/wwi/nodes/WbImageTexture.js
resources/web/wwi/test.html
resources/web/wwi/viewer.js
src/webots/nodes/WbImageTexture.cpp

`ImageTexture` transparency was previously handled on the Webots side, a `isTransparent` field included in the x3d of the `ImageTexture` node. This is however not an option when loading PROTO, resulting in this:
The same happens with many logos.
The logic to determine the transparency was already present on the webotsjs side, but wasn't being applied in practice. With this PR:
- Webots no longer sends the `isTransparent` information
- A `checkTransparency` parameter is retained as `highlightX3DElement` explicitly doesn't want any transparency (not sure why)

Fix transparency in webotsjs

---

docs/reference/rangefinder.md

The provided c array to numpy array code did not successfully receive the whole array for me, and instead I found success using numpy's conversion from  base ctypes. This I propose this change for future users.
[If this pull-request changes the doc, add the link to the related page, including the `?version=BRANCH_NAME`, such as:
](https://cyberbotics.com/doc/reference/rangefinder?version=develop)

WIKI: Update python image grab example code

---

resources/web/wwi/Animation.js

The issue was that before all the labels needed to be already present at the beginning of the animation and so when looking backward, we knew what was the previous state of the label and could update it.
However we introduced some time ago the possibility to display labels that were not present at the beginning of the animation.
The issue comes from there: when going backward we tried to see if there was a previous state of the label to update it and, as there was no previous state, we would keep it unchanged.
This PR fixes that by introducing a default empty label at timestep 0 for all labels that are not present at the beginning of the animation.
(I already patched the server such that you can test it)

Fix labels when going back

---

docs/reference/changelog-r2023.md
docs/reference/charger.md
src/webots/nodes/WbCharger.cpp
src/webots/nodes/WbCharger.hpp

Addresses #5765:
continues with the Charger behavior refactor (see also  #2879) and improve the discharging behavior.
Changes:

Improve Charger behavior

---

resources/web/wwi/FloatingWindow.js

The problem was that we were calculating the remaining width relatively to the size of the 3d window but we were getting the absolute position of the mouse.
Fix #5761 
Note: we cannot use `document.getElementsByClassName('webots-view')[0].offsetLeft` to solve the issue because if the `webots-view` element is included in another one which is not the full width of the screen we will have the same problem.

Fix floating window resize

---

docs/reference/changelog-r2023.md
src/controller/c/supervisor.c

Fix #5757: add a new flag to `WbFieldStruct` to mark if the field is a PROTO field or parameter.
In the Supervisor API the the `WbFieldStruct.is_proto_internal` flag was used to determine if the cached field was read only (i.e. not visible from the scene tree).
Then in #4363, it was added a check was added to make sure that if a PROTO field and parameter with the same name exist the correct one is returned. This check is fine and is needed to retrieve the correct field.
However, the value contained in the former `WbFieldStruct.is_proto_internal` (renamed `WbFieldStruct.is_read_only`) cannot be used to determine the field is a PROTO field or parameter.

Fix retrieving cached PROTO internal fields in Supervisor API

---

lib/controller/python/controller/field.py

Signed-off-by: Gaël Écorchard <gael.ecorchard@cvut.cz>
If the field cannot be found during construction, `Field.type` is left undefined. This is a fix for that. It avoids a crash e.g. when accessing `Field.value`.
Not relevant
Not relevant
None

Avoid having Field.type undefined

---

src/webots/engine/WbSimulationCluster.cpp
src/webots/engine/WbSimulationCluster.hpp

This fixes an issue where it was possible for 2 different ODE cluster threads to simulteously try to append to `mCollisionedRobots`.

Make robot collisions thread-safe.

---

projects/robots/rec/fabtino/worlds/fabtino.wbt
projects/robots/robotnik/summit_xl_steel/worlds/summit_xl_steel.wbt
src/webots/engine/WbSimulationCluster.cpp
src/webots/engine/WbSimulationCluster.hpp

This builds on PR #5790 by finding *all* of the contact points instead of just the first 100. It uses the same technique as PR #5769 to ensure that all contact points are found, but doesn't make the ABI-incompatible changes in that PR that are needed to add `maxContactPoints` and `maxContactJoints` to ContactProperties. Instead it hard-codes those to -1 (i.e. all) and 10, respectively.
If this PR is merged, PR #5790 can be closed and PR #5769 can be easily changed to just add the new fields to `ContactProperties`.

Hotfix to find all contacts quickly

---

projects/samples/devices/controllers/laser_pointer/laser_pointer.c

There is a difference in laser point visualization update rate (64 ms) the update rate of the distance sensor rays (8ms). This is causing a noticable difference in the pointer position and the sensor rays. Updating the laser pointer controller time step to the basic time step of robot (8ms).
This pull-request fixes issue #https://github.com/cyberbotics/webots/issues/5492

Laser visualization update rate differs from distance sensor rays #5492

---

docs/guide/simulation-server.md

In PR https://github.com/cyberbotics/webots-server/pull/15 we added a `persistantDockerImages` list that protects the Docker images in it from being removed from cache after a simulation ends.
In this PR I added this mechanism to Webots' documentation
https://www.cyberbotics.com/doc/guide/simulation-server?version=doc-add-persistantDockerImages-to-server-doc

Add persistantDockerImages mention to server doc

---

resources/qt_warning_filters.conf

It seems that the warning filters needed an update.
All the warnings currently filtered out don't seem to occur any more.
I introduced a new rule to filter out a warning occurring on Windows since the upgrade to Qt 6.4.2.
I kept the warning about retina display as I could not test it and it is likely still there.
I tested on both Windows and Linux and could not any warning popping-up.

Fixed warning filters

---

tests/test_suite.py

Add system failures to the output file before the final message because
the final message tells the outputMonitor to stop processing the output.

Report system failures from test_suite.py.

---

docs/reference/receiver.md

In the Python API the `Receiver.getData` function is deprecated but still documented.

Update Python receiver get data documentation

---

scripts/install/linux_compilation_dependencies.sh
scripts/install/linux_optional_compilation_dependencies.sh
scripts/install/linux_runtime_dependencies.sh
scripts/install/linux_test_dependencies.sh
scripts/install/linux_web_viewer_dependencies.sh

After #5845, I am getting errors on Ubuntu 20.04 that can be safely ignored, so we don't want the script to fail in this case.
```
Err:5 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BA6932366A755776
Reading package lists... Done
W: GPG error: http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BA6932366A755776
E: The repository 'http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user …
```

Fix dependencies installations on Ubuntu 20.04

---

docs/reference/changelog-r2023.md
src/webots/gui/WbMainWindow.cpp

The current code is not working correctly for me and `QDir(fileName).dirName()` is returning the file name instead of the directory name.
However, using QFileInfo for retrieving the directory from the file path works correctly.

Fix wrong save world warning

---

src/controller/c/camera.c

Valgrind's memcheck tool reported this while I was doing some other testing.
It looks like at most this could cause a little bit of unnecessary communication between the controller and webots.

Fix uninitialized set_exposure variable.

---

tests/sources/test_cppcheck.py

Add missing space to separate options on cppcheck command line. I'm wondering if this is related to some of the test-sources errors I'm seeing in CI.

Add missing space to cppcheck command line.

---

docs/reference/camera.md
docs/reference/lidar.md
docs/reference/rangefinder.md
docs/reference/robot.md

This fixes the documentation to say not to access image (or point cloud) data during a step.
See issue #5780.
Links to versions on the branch to be merged:
https://www.cyberbotics.com/doc/reference/camera?version=DeepBlueRobotics:hotfix-document-not-to-access-image-data-during-step
https://www.cyberbotics.com/doc/reference/lidar?version=DeepBlueRobotics:hotfix-document-not-to-access-image-data-during-step
https://www.cyberbotics.com/doc/reference/rangefinder?version=DeepBlueRobotics:hotfix-document-not-to-access-image-data-during-step
https://www.cyberbotics.com/doc/reference/robot?version=DeepBlueRobotics:hotfix-document-not-to-access-image-data-during-step

Document not to access image data during a step.

---

resources/web/wwi/X3dScene.js

In the kukubox example (https://webots.cloud/run?version=R2023b&url=https://github.com/cyberbotics/webots/blob/doc-add-robots/projects/robots/kuka/youbot/protos/KukaBox.proto&type=undefined) we can delete and reset the physic node.
However this have no influence over WebotsJS as the physic node is just ignored by it.
So it results no new node and we need to check it before attempting to `delete` or `finalize` it.

Fix delete physic

---

resources/web/wwi/FloatingProtoParameterWindow.js

Test it here: https://testing.webots.cloud/run?version=R2023b&url=https://github.com/cyberbotics/webots/blob/doc-add-robots/projects/robots/pal_robotics/tiagopp/protos/Tiagopp.proto&type=undefined

WebotsJS: fix web mf

---

lib/controller/python/vehicle/car.py

The wheel_base vs wheelbase part might want some further looking into for the sake of consistency

Fix typos in Python Car Lib

---

docs/reference/changelog-r2023.md
src/webots/control/WbController.cpp

Currently the libController path is appended at the end of the existing `LD_LIBRARY_PATH`, `DYLD_LIBRARY_PATH` and `Path` (respectively on Linux, macOS and Windows). This can lead to the wrong libController being used by Webots.

Prepend libController path to environment

---

docs/reference/changelog-r2023.md
docs/reference/supervisor.md
src/webots/nodes/WbConnector.cpp

After a reset, the value returned by `wb_connector_is_locked` was not updated, because the controller
didn't received new value.
I can't emphasis enough the fact that I'm asking for help to assess this fix, and moreover ensure that this bug is not present in others node. This could be a pattern issue, and might have been reproduced elsewhere.
However, it's seems that is a specific bug of the Connector : it's the only one to make use of both `mNeedToReconfigure` and a custom `reset()` function. I do think it's because contrary to others node that are pure sensor, this one actively impact the simulation, hence the code pattern change a bit. Am I right ?
Ensure that after a reset the correct status is sent to a controller. 
This pull-request fixes issue …

Connector: Fix status after reset

---

docs/css/webots-doc.css
docs/reference/supervisor.md

This PR tries to make the supervisor reload/reset/etc. table easier to read:
https://cyberbotics.com/doc/reference/supervisor?version=fix-make-table-easier-to-read

Better reload/reset table

---

docs/reference/changelog-r2023.md
src/webots/nodes/utils/WbObjectDetection.cpp

Detected object center was not computed correctly for scaled objects or in general if the Solid with recognition enabled has a parent Transform node with a non-default scale or rotation.
This is a first bug fix to the Camera recognition but there are other in case the bounding object (and not the bounding sphere) is used to compute the position.
Additionally, the Camera recognition only works for planar projections (not for spherical and cylindrical).

Fix Camera recognition for scaled objects

---

src/webots/nodes/utils/WbNodeUtilities.cpp
src/webots/nodes/utils/WbNodeUtilities.hpp

Allow robots in joints endpoint.
While checking that, I saw that it was also not possible to insert `robot` in 
- `fastHelix` and `slowHelix` of a propeller
- `rotatingHead` of a lidar.
But I am not sure if we want to change it.
I do not really see a utility but on the other point it is strange that:
- `fastHelix` -> `robot` is wrong
- `fastHelix` -> `solid` -> `robot` is correct
What do you think @omichel @stefaniapedrazzi ?

Robots insertion

---

docs/reference/changelog-r2023.md
src/controller/c/Makefile
src/controller/c/robot.c
src/webots/nodes/WbRobot.cpp

Resolves #3505.
With extern controllers (namely TCP ones) and the `webots_ros2` package it happens that the user uses different versions of Webots and of the libController, which is forbidden, as both could be incompatible with each other.
Webots is now sending its version in the configure message of the robot. The version is compared on the libController side and a warning is displayed if they are not equal.

Add version comparison between libController and Webots

---

projects/robots/dji/mavic/controllers/mavic2pro/mavic2pro.c

Fixes https://github.com/cyberbotics/webots_ros2/issues/297.
Complementary to https://github.com/cyberbotics/webots_ros2/pull/636.

Rename Mavic gyro variables to velocity

---

resources/web/wwi/protoVisualizer/Node.js

In the case of the RobotisOp2, the `backlash` parameter was not flagged as template regenerator also it should have.
It was correctly flagged in its subproto (`Darwin-op`) but the information was not transmitted to the upper level.
Test it here: https://testing.webots.cloud/run?version=R2023b&url=https://github.com/cyberbotics/webots/blob/doc-add-robots/projects/robots/robotis/darwin-op/protos/RobotisOp2.proto&type=undefined

WebotsJS: Fix nested templateregenerator

---

src/webots/nodes/WbConnector.cpp

I refactor code, to make it easier to understand for human and compilers alike.
This removes the requirement for compiler specific suppression mechanisms.
I moved the lines `const dReal *d1 = b1 ? dBodyGetPosition(b1) : matrix().translation().ptr();` to where it is  used
and removed the trinary operator.
I opened #5937 because I believed there was a bug.
This cleanup is not critical.

refactor wbconnector::snapOrigins removing pragmas

---

resources/web/wwi/protoVisualizer/Vrml.js

As it was just checking the name of the current node, it was not attributing the correct role to protos.
For example in the `Eyescrew.proto`, the `TorusBoundingObject.proto` was not given the role `boundingObject` and it was crashing webotsJS.
Test it here: https://testing.webots.cloud/run?version=R2023b&url=https://github.com/cyberbotics/webots/blob/doc-add-objects/projects/objects/factory/tools/protos/EyeScrew.proto&type=undefined

Fix basetype for role attribution

---

src/webots/nodes/utils/WbDictionary.cpp

Fix #5821 (introduced in #5676 ):
currently the `WbMFNode::setItem` function doesn't work correctly because the `itemChanged` signal is not correctly handled.
A more complete fix for `WbMFNode::setItem` is inspected in #5950 but should target the develop branch.

Fix USE node setup in WbDictionary

---

docs/reference/changelog-r2023.md
src/webots/nodes/WbBasicJoint.cpp
src/webots/nodes/WbSolid.cpp
src/webots/nodes/WbSolid.hpp

Fix #5951:
listen to changes in descendant joint `endPoint` field and update the children list when needed.
Note that given that the joint solid end point is also added to the `WbSolid::mSolidChildren` list, the `WbSolid::updateChildren` function is automatically called when the end point is deleted. Thus, it is not needed to call `WbSolid::updateChildren` when the `WbBasicJoint::endPointChanged` node argument is NULL.

Fix update of joint endPoint after regeneration

---

src/controller/c/supervisor.c
src/controller/cpp/Node.cpp
src/webots/nodes/utils/WbSupervisorUtilities.cpp

I found three issues with contact points:
- It seems that the idea was to remove the `include_descendants` of the `wb_supervisor_node_disable_contact_points_tracking` function.
- However, we use both the `solid` and the `include_descendants` parameters to disable the tracking in the Webots side: https://github.com/cyberbotics/webots/blob/d995dbc073c7d370a95ce56aff8c0b51d43a3e73/src/webots/nodes/utils/WbSupervisorUtilities.cpp#L1286
- The result is that if we use `wb_supervisor_node_enable_contact_point_tracking` with `include_descendants` = True, then it is not possible to disable it later (and worse we risk to disable the tracking of the same solid but without the descendants
- It seems consistent (but still wrong) with the python and matlab API. However when looking in …

Fix contact points

---

resources/web/wwi/protoVisualizer/Parameter.js
resources/web/wwi/protoVisualizer/Vrml.js

Introduce a more permissive definition of `equals` to use in the context of restrictions.
Example:
In the `AddLaneRoadSegment` proto, the `lines` parameter is restricted and accept only one type of node: `RoadLine { }`.
It seems to work as intended at first glance: we can insert new `RoadLine { }`.
However, if we modify a `RoadLine { }`, let's say we change the line `type` from `dashed` to `double` and later we trigger a regeneration of the proto, it will not work.
This is the case because now we are comparing `RoadLine { }` with  `RoadLine { type double }`

WebotsJS: Comparison without value

---

docs/guide/mavic-2-pro.md

Specify WorldInfo settings needed to make the default controllers working correctly.

Add mavic2pro WorldInfo settings

---

src/webots/nodes/WbCadShape.cpp
src/webots/nodes/WbSphere.cpp

Complete #5980:
fix bounding sphere radius for Sphere and CadShape geometries that are still scaled.

Fix bounding sphere radius for Sphere and CadShape

---

resources/web/wwi/Parser.js

Some floats/int were passed as string.
It was undetected until now because in most operation JS succeed to use string instead of number, for example:
```
"3" / 2 = 1.5
```
But it results in some `NaN` in #5985

Fix webotsjs type in parser

---

resources/web/wwi/protoVisualizer/Parameter.js

Notify the upper parameter when a `setParentRegeneration` flag is set.
Test it here: https://testing.webots.cloud/run?version=R2023b&url=https://github.com/cyberbotics/webots/blob/doc-add-objects/projects/objects/road/protos/CurvedRoadSegment.proto&type=undefined

Fix mf regeneration derivatedProto

---

docs/guide/webots-cloud.md

The `webots.yml` file should be located at the root level of the project, not the repository.

Fix instructions for the location of the webots.yml file

---

resources/web/wwi/ImageLoader.js

In the case of animation/scene/proto with local textures, we do not have a `worldsPath`

Fix webjs undefined

---

resources/web/wwi/nodes/WbCadShape.js
resources/web/wwi/nodes/WbMesh.js

You can test it here: https://webots.cloud/run?version=R2023b&url=https://github.com/omichel/Shelf/blob/main/protos/Shelf.proto

Fix OBJ DAE

---

docs/reference/changelog-r2023.md
lib/controller/python/controller/motor.py

Motor setAcceleration missed device tag parameter in Python controller lib.

Fix Motor setAcceleration bug in Python.

---

projects/objects/lights/protos/CeilingSpotLight.proto
projects/robots/mir/mir100/protos/Mir100.proto
projects/samples/devices/worlds/hinge_2_joint_with_backlash.wbt
projects/samples/devices/worlds/motor2.wbt
projects/samples/devices/worlds/motor3.wbt
projects/samples/environments/factory/worlds/hall.wbt
projects/samples/geometries/worlds/extended_solids.wbt
projects/vehicles/worlds/village_center.wbt

Fixes #6027.
I checked all the use of the SolidPipe, SolidBox, SolidRoundedBox and SolidTorus in proto and world files and found these 8 files which had one or several default translation value.

Fixed CeilingSpotLight SolidPipe translation

---

docs/reference/changelog-r2023.md
src/webots/core/WbDownloader.cpp
src/webots/nodes/WbMesh.cpp

Fix #6032 
The meshes where sometimes loaded twice and the first downloader was deleted before it was finished, resulting in a infinite loading.
After further testing, it turns out that the issue came from `mNetworkReply` of [WbDownloader.cpp](https://github.com/cyberbotics/webots/blob/fix-mesh-double-loading/src/webots/core/WbDownloader.cpp).
When a download is triggered before the previous one is finished (because of double loading in our case), we need to delete the downloader and create a new one.
The problem is that we use `deleteLater()` for the `mNetworkReply`  of the downloader, which is right according to the [doc](https://doc.qt.io/qt-6.2/qnetworkreply.html#finished). But for some reasons (bug?) in a very specific edge case:
- ubuntu 20 or 22
- no other meshes or textures …

Fix mesh double loading

---

src/webots/control/WbController.cpp

I don't understand the purpose of this line and it seems wrong for several reasons:
1. It is executed on Windows only and rely on `sh` and `chmod` which are not available on Windows.
2. Everything works well without it.
3. Removing these lines doesn't change anything to the rights of this folder:
```
$ ls -l /C/Users/Olivier/AppData/Local/Temp/webots-1234/ipc/
total 0
drwxr-xr-x 1 Olivier Aucun 0 Apr 13 10:35 ea4c880fba3d97f56c30ebf6519137ef73b77b2d
```
Note: it was introduced in #5959.

Cleanup wrong code

---

resources/qt_warning_filters.conf

Since the upgrade to Qt 6.5.0 on Windows, this warning doesn't show up any more.

Clean-up warning filter

---

src/webots/gui/WbMainWindow.cpp

The load progress dialog was not a child window of the main window. As a consequence, it may appear on a different screen as the main window. This PR fixes this small problem.

Fixed load progress dialog parenting

---

projects/robots/nasa/worlds/sojourner.wbt
projects/samples/rendering/worlds/animated_skin.wbt
src/webots/engine/WbSimulationCluster.cpp
src/webots/engine/WbSimulationCluster.hpp

Fix #5819 and display more useful information in the contact point warnings allowing the user to understand which contacts properties should be updated to handle more contact points.

Fix contact points warnings

---

src/webots/nodes/utils/WbObjectDetection.cpp
src/webots/nodes/utils/WbObjectDetection.hpp

As discussed in #6095, this PR restores the missing `const` keywords.

Restore missing const

---

projects/robots/pal_robotics/tiago_extensions/protos/TiagoGripper.proto
tests/api/controllers/robot_urdf/tiago_reference.urdf

In the process of updating the TIAGo to improve the compatibility with the real robot, the joints of the gripper fingers must be updated.
See #6046, #6082 and #6093 for related PRs and issues.

Update TIAGo finger joint names

---

docs/reference/changelog-r2023.md
src/controller/c/robot.c
src/webots/control/WbController.cpp
src/webots/core/WbStandardPaths.cpp
src/webots/core/WbTemplateEngine.cpp
src/webots/gui/WbVideoRecorder.cpp

See discussion at https://github.com/cyberbotics/webots/pull/6067#issuecomment-1521257898
The problem affects only Linux and macOS where the Webots temporary files are stored in the global `/tmp` folder, which is necessary for shared memory segments and pipes.
On Windows the temporary directory used by Webots already contains the user name (as it is located in the local `AppData` folder).
If user A crashes Webots, it a `/tmp/webots-1234` folder will remain which user B cannot delete and hence they cannot launch a new instance of Webots on this port, although the port is available.
Changing the permissions of this folder and its contents to allow anyone to write/delete is not a good solution because it would allow any user to kill another one's simulation by deleting these files.
It seems …

Fix tmp path to include username on Linux and macOS

---

docs/reference/changelog-r2023.md
src/ode/ode/src/joints/joint.cpp
src/ode/ode/src/joints/joint.h

Fixes #3947.
There was a singularity in ODE, when the min and max limits were set close to PI (or -PI). Depending on the basicTimeStep and on the torque applied, if the next computed angle was above PI or under -PI, it was directly clamped in range [-PI; +PI], switching the sign and messing with the limit computation. The fix uses the delta with the previous angle to correctly compute the limit to use for the LCP contraints algorithm.

Fix ODE hinge joints limits

---

docs/reference/changelog-r2023.md
src/webots/vrml/WbProtoTemplateEngine.cpp

Fix #6060:
if a path used in the Javascript (or Lua) template file contains the `'` character, the code becomes invalid and it is not possible to load the template PROTO.
All the paths need to be correctly escaped before writing them in the template file.

Fix errors loading template PROTO nodes

---

resources/nodes/Accelerometer.wrl
resources/nodes/Altimeter.wrl
resources/nodes/Camera.wrl
resources/nodes/Charger.wrl
resources/nodes/Compass.wrl
resources/nodes/Connector.wrl
resources/nodes/Display.wrl
resources/nodes/DistanceSensor.wrl
resources/nodes/Emitter.wrl
resources/nodes/GPS.wrl
resources/nodes/Gyro.wrl
resources/nodes/InertialUnit.wrl
resources/nodes/LED.wrl
resources/nodes/Lidar.wrl
resources/nodes/LightSensor.wrl
resources/nodes/Microphone.wrl
resources/nodes/Pen.wrl
resources/nodes/Radar.wrl
resources/nodes/Radio.wrl
resources/nodes/RangeFinder.wrl
resources/nodes/Receiver.wrl
resources/nodes/Speaker.wrl
resources/nodes/TouchSensor.wrl
resources/web/wwi/protoVisualizer/FieldModel.js
resources/web/wwi/protoVisualizer/scripts/basenode_encoder.py

* Remove scale field from WRL files for nodes inheriting from Solid
* Sort nodes in alphabetical order when generating `FieldModel.js` in order to produce the same list independently on the system
* Regenerate `FieldModel.js`

Remove scale field from devices WRL and improve JS basenode encoder

---

scripts/converter/convert_transform_to_pose.py
scripts/converter/webots_parser.py
src/webots/nodes/utils/WbConcreteNodeFactory.cpp
src/webots/nodes/utils/WbNodeUtilities.cpp
src/webots/vrml/WbNode.cpp
src/webots/vrml/WbNodeReader.cpp
src/webots/vrml/WbVrmlNodeUtilities.cpp
src/webots/vrml/WbVrmlNodeUtilities.hpp
tests/parser/expected_results.txt

The introduction of the `Pose` node breaks the backward compatibility.
This PR adds:
- The script has several known limitations: 
- it does not support protos with templating
- it requires the protos/worlds to be well formated. 
- it does not convert the parameters of the protos
I could not see a performance impact.

Enhancement backward compatibility pose

---

src/webots/vrml/WbNode.cpp

An assert checking that two nodes with the same name should have the same number of fields was triggered in some cases, resulting in a Webots crash.
When it was introduced, the assert made sense.
However it is not true anymore since the introduction of extern protos.
Here is the example I used to debug it:
- I have a world with a classic `Door.proto` .
- I added a `DoorLever.proto` to the door, but not the default one, a custom one that has one more fields than the default one.
- This custom `DoorLever.proto` is declared via the EXTERNPROTO mechanism: 
```
EXTERNPROTO "../protos/DoorLever.proto"
```
When trying to open this world, if Webots was compiled in debug mode, it was crashing it.
The reason is:
- At some time during the loading, Webots checks if the fields of …

Fix node comparison

---

src/webots/vrml/WbNode.cpp

Better patch than #6141.
The previous fix did not work correctly when the two protos had the same fields, but not the same bodies.

Better fix to comparison issue

---

projects/robots/epfl/lis/controllers/blimp/js.h
src/wren/StaticMesh.cpp

`sprintf` is deprecated and `snprintf` should be used instead. This is triggering warnings on macOS preventing the manual creation of packages.

Fix compilation warnings on macOS

---

.github/workflows/test_suite_linux.yml
.github/workflows/test_suite_linux_develop.yml
.github/workflows/test_suite_mac.yml
.github/workflows/test_suite_mac_develop.yml
.github/workflows/test_suite_windows.yml
.github/workflows/test_suite_windows_develop.yml
.github/workflows/tests_doc.yml
.github/workflows/tests_sources.yml
.github/workflows/tests_sources_with_latest_cppcheck.yml

Upgrade upload/download artifacts and checkout actions to version 3.
Version 2 is throwing errors due to the deprecation of Node.js 12:
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/upload-artifact@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

Upgrade action version to solve deprecation errors

---

docs/reference/changelog-r2023.md
src/wren/StaticMesh.cpp

Follow-up on #3917.
When the shadows are globally disabled, we should skip the shadow computations for meshes.

Disable shadow reception computation on mesh when shadows are globally disabled

---

resources/webots_classic.qss
resources/webots_dusk.qss
resources/webots_night.qss
src/webots/gui/WbNewVersionDialog.cpp
src/webots/gui/WbNewVersionDialog.hpp

The checkbox check mark was not displayed during the first launch of Webots: neither in the new version window, neither in the preferences and so on.
It was working in qt 6.2 because we were using the default check mark of qt (not working anymore since 6.4)
The reason of the issue is:
1. We define the path to the check mark icon with a q-property that is in the qss (because the path depends on the theme.
2. We add the path to qt when creating the main window, however, the new version window is created *before* the main window.
3. It seems that once qt tried to access a wrong image (the check mark in the version window) it will still display it wrongly even if, in the meantime, the path became correct: which explain why the check mark does not appear in preferences  for the …

Fix checkbox check mark first launch

---

docs/reference/changelog-r2023.md
src/webots/app/WbPerspective.cpp
src/webots/nodes/WbMesh.cpp
src/webots/nodes/WbSkin.cpp

Fixes #6210.
The crash was due to a dangling reference to a temporary string buffer (char *).

Fixes random crashes with skins and meshes

---

docs/reference/changelog-r2023.md
src/webots/nodes/WbCharger.cpp
src/webots/nodes/WbLed.cpp

Fix #6213 
When deleting the group present in LED it was crashing because the appearances/lights lists of led was not reset.
This bug was also present in battery.

Fix led crash

---

docs/reference/changelog-r2023.md
src/webots/nodes/WbLidar.cpp

As reported in https://github.com/cyberbotics/webots_ros2/pull/770, the Lidar head is written two times when exported to URDF. This PR limits the exports to subnodes for URDFs.

Fix double Lidar head export

---

docs/guide/tutorial-9-using-ros.md

I had to make the change because the old way was not working anymore
Source: https://wiki.ros.org/noetic/Installation/Ubuntu

Doc fix ros tutorial instruction

---

resources/web/wwi/nodes/utils/WbBoundingSphere.js
src/webots/nodes/WbCamera.cpp
src/webots/nodes/WbCamera.hpp
src/webots/nodes/WbSkin.cpp
src/webots/nodes/WbTransform.cpp
src/webots/nodes/utils/WbBoundingSphere.cpp
src/webots/nodes/utils/WbVisualBoundingSphere.cpp

Fix bounding sphere updates

---

docs/reference/changelog-r2023.md
src/webots/core/WbTemplateEngine.cpp
src/webots/core/WbTemplateEngine.hpp
src/webots/vrml/WbProtoTemplateEngine.cpp

Fixes #6286:
backslash in paths passed to the template PROTO JS script are not correctly escaped producing invalid JS scrips that cannot load the PROTO models.

Fix PROTO load when a context path contains backslash

---

docs/reference/changelog-r2023.md
src/webots/gui/WbMainWindow.cpp
src/webots/gui/WbMainWindow.hpp
src/webots/nodes/utils/WbWorld.cpp
src/webots/nodes/utils/WbWorld.hpp
src/webots/user_commands/WbContextMenuGenerator.cpp
src/webots/user_commands/WbContextMenuGenerator.hpp

Address #6277:
show all robots' overlays in the general Overlay menu.

Enhancement overlays menu

---

src/controller/c/Makefile

Whenever [version.txt](https://github.com/cyberbotics/webots/blob/master/resources/version.txt) changes, [robot.c](https://github.com/cyberbotics/webots/blob/master/src/controller/c/robot.c) should be recompiled.

Fixed missing dependency of libController from version.txt

---

resources/web/wwi/FloatingProtoParameterWindow.js
resources/web/wwi/Parser.js
resources/web/wwi/WebotsView.js
resources/web/wwi/X3dScene.js
resources/web/wwi/nodes/WbBackground.js
resources/web/wwi/nodes/WbBillboard.js
resources/web/wwi/nodes/WbCylinder.js
resources/web/wwi/nodes/WbDevice.js
resources/web/wwi/nodes/WbGroup.js
resources/web/wwi/nodes/WbImageTexture.js
resources/web/wwi/nodes/WbJoint.js
resources/web/wwi/nodes/WbLed.js
resources/web/wwi/nodes/WbShape.js
resources/web/wwi/nodes/WbSlot.js
resources/web/wwi/nodes/utils/utils.js
src/webots/nodes/WbShape.cpp
src/webots/nodes/WbShape.hpp

Replace `instanceof` by a check with `nodeType` when possible because it:
- improves the performance
| Node | Instanceof | nodeType | 
| --- | --- | --- |
|Background| 0.06ms | 0.019 ms | 
|Shape| 0.27ms  | 0.077ms |
|Robot| 0.28ms | 0.09ms |
- moreover using instanceof was the cause of a lot of imports and we had circular dependencies errors by the past.
The only reason to still use `instanceof`sometimes it to check for a node and its derived ones. For example, when checking
```if (node instanceof WbGroup)```it checks against group, but also, pose, transform, solid, and so on.
This PR also adds support for `castShadows` and `isPickable` in WbShape that were missing.

Cleanup instanceof

---

docs/guide/installation-procedure.md

Fixes #6267.
See it [here](https://cyberbotics.com/doc/guide/installation-procedure?version=fix-apt-installation-instructions#installing-the-debian-package-with-the-advanced-packaging-tool-apt).

Fix apt installation instructions

---

src/webots/nodes/utils/WbBoundingSphere.cpp

Bounding sphere update could also be requested by the Skin node, so the assertion is wrong and results in a failure.
The assertion is not necessary and can be removed.
This issue occurs only when compiling in debug mode on not with the released versions of Webots.

Fix assertion failure with Skin node

---

docs/reference/changelog-r2023.md
projects/robots/husarion/rosbot_xl/protos/RosbotXl.proto

The ROSbot XL bounding object was made of a Mesh, which is not recommended. This PR replaces the Mesh by multiple Boxes.

Update ROSbot XL Bounding Object to Primitives

---

projects/objects/factory/pipes/protos/LJoint.proto

The scaling parameter was only applied on the graphical part but not on the bounding object

Fix ljoint bo

---

docs/guide/matlab.md
docs/guide/running-extern-robot-controllers.md
docs/reference/changelog-r2023.md
lib/controller/matlab/launcher.m
projects/robots/robotis/darwin-op/controllers/symmetry_matlab/symmetry_matlab.m
projects/robots/softbank/nao/controllers/supervisor_matlab/supervisor_matlab.m
projects/samples/howto/force_control/controllers/force_control_matlab/force_control_matlab.m
src/controller/launcher/webots_controller.c

This will add features as described in https://github.com/cyberbotics/webots/issues/6362#issuecomment-1695794195
This pull-request fixes issue https://github.com/cyberbotics/webots/issues/6362
**Tasks**
The following pages have been changed:
- https://cyberbotics.com/doc/guide/matlab#using-the-matlab-desktop
- https://cyberbotics.com/doc/guide/running-extern-robot-controllers

Enable launching MATLAB desktop from the extern launcher

---

docs/reference/changelog-r2023.md
lib/controller/python/controller/receiver.py

Fix returning 3D vector (list) instead of object. Fix based on `gps.py::getValues`
This pull-request fixes issue #6392

Fix values returned by getEmitterDirection

---

src/controller/launcher/webots_controller.c

- fixes creation of the path were matlab is installed on macOS
- fixes search for latest matlab version
This pull-request fixes issue #6387
**Tasks**
No change in documentation.
See issue #6387

FIX:Matlab path search on macOS

---

docs/reference/changelog-r2023.md
lib/controller/python/controller/receiver.py
src/webots/nodes/utils/WbObjectDetection.cpp
src/webots/nodes/utils/WbObjectDetection.hpp

Changes the calculation of mIsOmniDirectional to horizontalFov > pi / 2.
This pull-request fixes issue #6395
Details on how the spherical projections were wrong before can be seen in #6395

fixed mIsOmnidirectional in WbObjectDetection

---

scripts/install/linux_optional_compilation_dependencies.sh

Do not install wrenJS dependencies when building the snap are they are not needed.

Fix snap build

---

docs/reference/changelog-r2023.md
src/webots/nodes/WbElevationGrid.cpp

This pull-request fixes the issue with the collision of ElevationGrids not matching the displayed mesh.
This pull-request fixes issue #6363 and #4169 
Before the fix
https://github.com/cyberbotics/webots/assets/12954392/1a624ef2-cc6e-48b5-89ad-c8b9604af4fd
After the fix
https://github.com/cyberbotics/webots/assets/12954392/07e1406a-bbef-421a-a006-0eb542291ed7
Test worlds ([archive](https://github.com/cyberbotics/webots/files/12859212/test_worlds.zip)) obtained and modified from #6363 and #4169

Fix the EvelationGrid height used for ODE

---

resources/wren/shaders/merge_spherical.frag
src/webots/nodes/WbLidar.cpp
src/webots/wren/WbWrenCamera.cpp

This pull request fixes the issue with missing points in lidar scan.
I was trying (and failing) to fix #5810 and came across this issue. For horizontal FOV higher than around 1 (depends on the vertical FOV), there are corners of points that are missing.
Looking at `faceCoord` in [merge_spherical.frag](https://github.com/cyberbotics/webots/blob/master/resources/wren/shaders/merge_spherical.frag) I noticed that the values in the corners fall outside the [0, 1] range.
In black pixels where `faceCoord.y` is not within [0, 1]:
Depth image:
Looking at which face of the cube is used for each pixels:
As far as I understand the lidar depth is computed by merge_spherical.frag as a depth image using 6 images computed for each side of a cube. However, the 6 images form a flattened …

Fix missing points in lidar scan

---

docs/reference/changelog-r2023.md
src/webots/nodes/utils/WbSupervisorUtilities.cpp

Avoid crashes and better warn when getting the PROTO in `WbSupervisorUtilities::getProtoParameterNodeInstance()`.
I discovered the bug when we used a cache to save nodes in Python. When calling `getPose()` or `getPosition()` we got an error message that `wb_supervisor_node_get_position() can exclusively be used with Pose (or derived)`. Now, the error message is `Cannot get the PROTO instance for node `LED` (type LED).` plus the old message. This helped me fixing the bug in our code.
None
**Tasks**
No documentation change
We probably save the result of `getMFNode()` in Python too soon because the pointed object is not a valid node later in our code (maybe the pointer changes when …

Avoid crashes and better warn when getting PROTO

---

docs/reference/changelog-r2023.md
src/controller/java/Makefile

Ensure that libController.dylib can be found on MacOS by fixing the relative path in JNILIB_FLAGS.
This pull-request fixes issue #5181
**Tasks**

Fix jnilibs flags

---

docs/reference/viewpoint.md

Fixed field type of followType in Viewpoint and updated default value of bloomThreshold to 21.
See : https://github.com/cyberbotics/webots/blob/eff554879c961f24542659a7a182ab029a5d196c/docs/reference/viewpoint.md

[Doc/Ref] Fixed Viewpoint VRML code block

---

projects/robots/bitcraze/crazyflie/protos/Crazyflie.proto

This simple change to the crazyflie proto should fix the bug where upon reset the crazyflie goes back to 0.0 position
This pull-request fixes issue #6467 
**Tasks**
N/A
N/A
N/A
N/A

remove position from crazyflie proto

---

src/webots/nodes/WbLidar.cpp

Rotating lidars produced points rotate by 180 degrees.
On develop, #6324 introduced changes to the rotating lidar to produce lidar images ranging from -M_PI to +M_PI instead of 0 to 2*M_PI. On master, #6417 fixed a few issues with the point cloud computation for some FOVs. Both change modified the way `theta0` is computed (one for rotating lidar and the other for fixed lidar). The changes made by #6324 were lost when #6417 was merged.
This bug was first identified in #6505

Fix missing pi offset after merge of #6417

---

src/webots/gui/WbGuiApplication.cpp
src/webots/nodes/WbDisplay.cpp

Fixes compilation error in the CI:
```
nodes/WbDisplay.cpp: In member function 'void WbDisplay::drawText(const char*, int, int)':
nodes/WbDisplay.cpp:718:27: error: 'CP_UTF8' was not declared in this scope
718 |   l = MultiByteToWideChar(CP_UTF8, 0, txt, -1, text, l + 1) - 1;
|                           ^~~~~~~
nodes/WbDisplay.cpp:718:7: error: 'MultiByteToWideChar' was not declared in this scope
718 |   l = MultiByteToWideChar(CP_UTF8, 0, txt, -1, text, l + 1) - 1;
|       ^~~~~~~~~~~~~~~~~~~
```

Fixed Windows compilation on the CI worker

---

.github/pull_request_template.md

Given that (I assume) new PRs are going to be released as part of R2024, they should be recorded in the 2024 changelog. This PR updates the default changelog link in the PR template to refer to [`changelog-r2024.md`](https://github.com/cyberbotics/webots/blob/master/docs/reference/changelog-r2024.md).
**Tasks**

Update PR template to Refer to 2024 Changelog

---

docs/reference/changelog-r2024.md
scripts/packaging/files_msys64.txt

Adds libssl to the packaged msys2 distribution in order to prevent Webots from looking for it in other msys2 installs.
This pull-request fixes issue #6503.
**Tasks**

Add libssl to MSys2 Windows Distribution

---

docs/reference/changelog-r2024.md
src/controller/java/controller.i

getPose() in Java was returning arrays of length 3 instead of 16.
This pull-request fixes issue #
**Tasks**
- [ x ] Update the [changelog](https://github.com/cyberbotics/webots/blob/master/docs/reference/changelog-r2024.md)

Fix getPose() returning arrays of length 3 in Java.

---

docs/reference/changelog-r2024.md
src/controller/java/controller.i

`CameraRecognitionObject.getColors()` is supposed to return an array of length `3*CameraRecognitionObject.getNumberOfColors()`. At the moment, the returned array is truncated to always have a length of `3`. Thus, only the first color can be retrieved. This PR updates the API so that an array of the correct length is returned.
**Tasks**

[Controller API (Java)] Fix Length of Arrays Returned by `CameraRecognitionObject.getColors()`

---

docs/reference/compass.md

Changed example code to convert compass readings into a bearing since it produced an angle using the x-axis as north rather than the y-axis as explained in the description above it.
The example code in the compass page of the documentation for computing the bearing in degrees from compass readings produces the incorrect output or it is misleading given the description above it. This is caused by the function adjusting the produced angle to consider the positive x-axis as the north direction rather than the positive y-axis as described in the description above the example code in the documentation.
None.
**Tasks**
No tasks.
Original documentation: https://cyberbotics.com/doc/reference/compass?version=R2023b
Also present in the main …

Canged code to convert compass readings into a bearing

---

docs/reference/changelog-r2024.md
src/webots/vrml/WbProtoManager.cpp

Remote assets do no require any inferring mechanisms from the parent files. This is only valid for local files. Remote asset was being treated as local.
This pull-request fixes issue #6571 
**Tasks**
**Additional Information**
`WbNetwork::instance()->isCachedWithMapUpdate(modelPath)`  in line 174 did nothing, as `modelPath` was empty. This was changed to check `WbNetwork::instance()->isCachedWithMapUpdate(protoDeclaration)`, which makes more sense here.

Remote assets per URL

---

docs/reference/changelog-r2024.md
src/webots/nodes/WbHinge2Joint.cpp
tests/physics/controllers/hinge_2_joint_damping_axis/.gitignore
tests/physics/controllers/hinge_2_joint_damping_axis/Makefile
tests/physics/controllers/hinge_2_joint_damping_axis/hinge_2_joint_damping_axis.c
tests/physics/worlds/hinge_2_joint_damping_axis.wbt

Fixes bug where`Brake`s added to the second axis of a `Hinge2Joint` were being applied to the non-transformed axis.
**Tasks**
I'll upload a test world that demonstrates the issue.

Fix `Brake`s added to the second axis of a `Hinge2Joint` being applied to the non-transformed axis.

---

docs/reference/changelog-r2024.md
resources/wren/shaders/merge_spherical.frag
src/webots/wren/WbWrenCamera.cpp
src/webots/wren/WbWrenShaders.cpp

Some graphics cards/drivers do not allow uniforms that are unused because they are optimized away by the GLSL compiler. The uniforms "subCamerasResolutionX" and "subCamerasResolutionY" were present in merge_spherical.frag but were never used. As a result, when trying to call to glGetUniformLocation() would return -1 for those names, crashing webots.
**Tasks**

Remove references to unused custom uniforms.

---

scripts/packaging/publish_release.py

This allows for major releases, hot fixes, and one-off snapshots of branches to happen on weekends. It's particularly useful where a project that uses Webots has a CI workflow that needs to download a version of webots with unmerged fixes for testing (potentially across multiple platforms). Without this change, that project's development may be delayed waiting for the next official nightly that contains the fixes. With this fix, the developer can push a tag starting with "R20" (e.g. "R2024a_MyFork_YYYY_MM_DD") to a branch on their unofficial fork of Webots and use the generated release in their unofficial fork until the the branch is merged into the official master.

Allow non-nightly builds on weekends.

---

.github/workflows/test_suite_mac.yml
.github/workflows/test_suite_mac_develop.yml

GitHub no longer includes swig by default on the macos 14 runner. Thus, as a result of #6580, builds made on mac with the current ci do not include the java controller api ([example](https://github.com/cyberbotics/webots/actions/runs/10135426969/job/28022815297#step:5:3077)). This PR installs swig, fixing the problem. I've also verified that [the other dependencies mentioned in the workflow](https://github.com/DeepBlueRobotics/webots/blob/d0b12071b400633dd83fb649de31d8bfae5c7233/.github/workflows/test_suite_mac.yml#L45) are still installed by default.
Once I verify that this does, in fact, solve the bug, I'll mark this PR as ready for review.

[CI] Install Swig on Mac

---

docs/reference/changelog-r2024.md
src/webots/nodes/WbSpeaker.cpp
src/webots/sound/WbWaveFile.cpp

Using the Speaker to play a WAV file: using an absolute path that does not exist result in Webots crashing.
- `QObject` was expected on the `catch` block of `WbSoundEngine.cpp:246`, but a `char*` was returned.
- Existance of file with absolute path was not checked.
This pull-request fixes issue #6592 
**Tasks**

6592 invalid sound path results in crash

---

src/webots/sound/WbSoundEngine.cpp

Treat the "Null Audio Device" returned by Apple's OpenAL during CI the same as NULL so we don't attempt to open it. Attempting to open it was causing the code to hang for 6.5 minutes.

Fix macos CI being slow.

---

src/webots/core/WbStandardPaths.cpp

Currently, if run in debug mode and the base path for the temp directory doesn't exist (default: `/tmp/webots/<username>/`), Webots crashes with an assertion failure. (In a release build, the assertion doesn't exist and [I'm guessing] `directory.entryList` returns an empty list, so nothing happens.) This PR updates the code so that if the base path does not exist, Webots does not try to find and delete temporary files within it.

Only Try To Delete Old Temp Directories if Root Temp Directory Exists

---

docs/generate_thumbnails.py
docs/reference/changelog-r2024.md

Fixed the bug that when using Python to write a controller, using getTargets() could not correctly obtain multiple target data detected by radar

Fixed bug radar.py

---

docs/reference/changelog-r2024.md
projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_bluetooth/Serial.cpp
scripts/install/qt_mac_installer.sh
src/controller/c/robot.c
src/webots/gui/WbRenderingDeviceWindow.cpp
src/webots/nodes/WbRobot.cpp
src/webots/wren/WbWrenCamera.cpp
tests/api/controllers/robot_urdf/robot_urdf.c
tests/test_suite.py

These are changes I needed to run make and test_suite.py on my MacOS laptop as a regular user without it crashing.
At least one test (`supervisor_export_image`) still fails for me on MacOS but at least the test suite now runs without crashing.
Notable user-visible changes:
- Fixed connection errors when using long robot names in some environments (issue #5452). This is not MacOS specific but is more likely to occur on a Mac because it's max socket path length is shorter than on Linux.
- Fixed crash on MacOS when quitting under some circumstances. One reproducible case was quitting after running `check_saved_hidden_parameters.wbt`.
- Fixed error when putting displays and cameras in separate windows on MacOS (e.g. with the `mirror.wbt` test). This was caused by using …

Mostly MacOS-related fixes

---

src/webots/gui/WbVideoRecorder.cpp
src/webots/gui/WbWrenWindow.cpp

PR #6622 causes grabs to come from an offscreen fbo instead of the default framebuffer. The latter can be scaled (e.g. on a MacOS Retina display) and the code was still compensating for that, resulting in screen grabs where the screen's image was only in the top left quadrant of the resulting screenshot. There was a similar problem with video recording. This PR addresses both.

Fix bugs (introduced in PR #6622) when grabbing/recording with devicePixelRatio != 1.

---

src/webots/gui/WbVideoRecorder.cpp
src/webots/launcher/webots-linux.sh

If the system ffmpeg links (possibly indirectly) to a different openssl than what we bundle, ffmpeg will fail to start. This fixes that by restoring the original LD_LIBRARY_PATH while running ffmpeg.

Fix failure of supervisor_start_stop_movie introduced by PR #6623.

---

src/webots/gui/WbRenderingDeviceWindow.cpp

Fixes bug introduced by PR #6635 which forced the format of the *context* for a rendering device window to be the same as the format of the main opengl context.  This resulted in the context not being usable with  rendering device windows created under wayland. This PR fixes that by requesting that the format of the *window" to be the same as the main opengl context.

Fix-mirror-crash-under-wayland

---

docs/reference/changelog-r2024.md
src/controller/c/supervisor.c
tests/api/controllers/supervisor_field/supervisor_field.c

Currently, calling `wb_supervisor_field_get_name(NULL)` crashes the supervisor. This PR fixes that and adds a test for the new behavior.

Fix Crash When `wb_supervisor_field_get_name` is Called With NULL

---

.github/workflows/test_suite_linux.yml
.github/workflows/test_suite_linux_develop.yml
.github/workflows/test_suite_mac.yml
.github/workflows/test_suite_mac_develop.yml
.github/workflows/test_suite_windows.yml
.github/workflows/test_suite_windows_develop.yml

#6652  bumped `actions/download-artifact` to v4.1.7. This is incompatible with `actions/upload-artifact@v3`, leading to CI failures. This PR bumps `actions/upload-artifact` to the latest version, fixing the CI.

Bump actions/upload-artifact to v4

---

src/webots/nodes/utils/WbWorld.cpp
src/webots/nodes/utils/WbWrenVertexArrayFrameListener.cpp
src/webots/nodes/utils/WbWrenVertexArrayFrameListener.hpp
tests/api/controllers/track_animated_geometry_muscles/.gitignore
tests/api/controllers/track_animated_geometry_muscles/Makefile
tests/api/controllers/track_animated_geometry_muscles/track_animated_geometry_muscles.c
tests/api/worlds/track_animated_geometry_muscles.wbt

The issue was that `WbWrenVertexArrayFrameListener` thought that the frame had already been handled because it had been handled in the previous world.
This pull-request fixes issue #6659
**Tasks**
No changelog update because the issue did not exist in R2023a.

Fix crash when using muscles and animatedGeometry in sequential worlds.

---

tests/api/controllers/Makefile
tests/cache/controllers/Makefile
tests/other_api/controllers/Makefile
tests/parser/controllers/Makefile
tests/physics/controllers/Makefile
tests/protos/controllers/Makefile
tests/rendering/controllers/Makefile

Switching between master and develop branches can result in controller directories sticking around that only contain the results of a build on the previous branch. test_suite.py was trying (and failing) to run make in those directories.

Ensure that test_suite.py only tries to build controllers which have Makefiles.

---

docs/reference/changelog-r2024.md
src/webots/app/WbContactPointsRepresentation.cpp

Fix bug where the wrong y coord was used for one corner of the box drawn to represent a box-plane collision.
**Tasks**

Fix bug where the wrong y coord was used for one corner of the box drawn to represent a box-plane collision.

---

docs/reference/changelog-r2024.md
src/webots/app/WbContactPointsRepresentation.cpp

Show box-plane contact point normals when showing contact points. This had been intentionally prevented, but it isn't clear why. I found it confusing that these were missing when I enabled showing contact points.
**Tasks**

Show box-plane contact point normals when showing contact points.

---

docs/guide/the-standard-file-hierarchy-of-a-project.md

This is a minor typo fix in the documentation in [the standard file hierarchy](https://github.com/cyberbotics/webots/blob/master/docs/guide/the-standard-file-hierarchy-of-a-project.md), in the first section (The Root Directory of a Project), in the "plugins" bullet point. 
No issue was submitted.
**Tasks**
No tasks needed
Related change:
On my branch:
https://github.com/eleciawhite/webots/blob/doc-wordinfo-typo-in-file-hierarchy/docs/guide/the-standard-file-hierarchy-of-a-project.md
According to the suggested link mangling which doesn't seem to work.
https://github.com/cyberbotics/webots/blob/master/docs/guide/the-standard-file-hierarchy-of-a-project.md?version=eleciawhite:doc-wordinfo-typo-in-file-hierarchy

Minor typo of WordInfo -> WorldInfo

---

docs/reference/changelog-r2024.md
src/webots/nodes/WbGeometry.cpp
src/webots/nodes/WbMatter.cpp

Currently, when `WbMatter` creates an ode geometry from a newly inserted `WbGeometry` in a `Shape` node, `WbGeometry::setOdeData` is called twice by `WbMatter::createOdeGeomFromInsertedShapeItem` (once directly and once through the call to `WbMatter::createOdeGeomFromGeometry`). Because `setOdeData` destroys its old geometry, this has the effect of setting the geometry to an invalid pointer. This PR removes one of these calls so that the geometry is only set once. Additionally, the assumption that `geom != mOdeGeom` in `WbGeometry::setOdeData` is now included in an assertion, so future similar problems should be easier to identify.
I also did a small bit of deduplication in e254766. Those changes can be reviewed independently. If they are determined to be out of scope for …

Fix Bounding Box Initialization when a Geometry is Inserted into a Shape

---

docs/guide/using-your-ide.md

- Fix typo
- update the Cpp wrapper directory from `C:\Program Files\Webots\resources\languages\cpp` to `C:\Program Files\Webots\src\controller\cpp`- Fix typo
- update the Cpp wrapper directory from `C:\Program Files\Webots\resources\languages\cpp` to `C:\Program Files\Webots\src\controller\cpp`
- Fix typo
- update the Cpp wrapper directory from `C:\Program Files\Webots\resources\languages\cpp` to `C:\Program Files\Webots\src\controller\cpp` on the https://cyberbotics.com/doc/guide/using-your-ide?tab-language=c++&tab-os=windows#visual-studio page, since the directory has been changed in `Webot R2023b` version.
This pull-request fixes issue #
**Tasks**
If this pull-request changes the doc, add the link …

docs: Update using-your-ide.md

---

.github/workflows/test_suite_linux.yml
.github/workflows/test_suite_linux_develop.yml
tests/test_worlds.py

Currently, the `test-worlds` job in the Linux CI workflow explicitly refers to the `cyberbotics/Webots` repository when attempting to download the necessary scripts. This causes the workflow to fail when run on a fork. This PR updates the job to use a sparse checkout to retrieve the files, which is repo-agnostic.

Fix Worlds Test on Forked Repositories

---

lib/controller/python/controller/field.py
projects/languages/python/controllers/driver/driver.py

When running the simulation this error message appears: _Error: wb_supervisor_field_get_type() called with invalid 'field' argument._
Fixes #6707
**Tasks**
**Additional Information**
I suspect that the bug is related to PR #6613.
https://github.com/cyberbotics/webots/blob/37f0c144eb311a598e5f99345021060aad04fca4/src/controller/c/supervisor.c#L1398-L1422
The _check_field_ failed, meaning the field reference (_WbFieldRef_) was not found in the _field_list_. 
That means that the _field_list_ is not updated correctly, or the field reference _f_ was not properly retreived from _wb_supervisor_field_get_type_ method.

Fix bug in Python "example.wbt" world

---

docs/reference/changelog-r2024.md
resources/webots_classic.qss
resources/webots_dusk.qss
resources/webots_night.qss

Adapt the QtToolTip by adding styles for Webots classic, dusk and dark mode.
Fixes #6709
**Tasks**
Old theme for all modes:
New theme for classic mode:
New theme for dusk mode:
New theme for night mode:
Since the old theme looked outdated, I decided to adapt the QtToolTip for every theme for better user experience.

Add styles for webots classic, dusk and dark mode

---

docs/reference/changelog-r2024.md
projects/samples/howto/omni_wheels/worlds/omni_wheels.wbt

Omni wheeled robot in webots sample project is having issue with the rollers rotation.
The rollers are rotating around wrong axis.
Fixes #6616 
**Tasks**
Rotating axis of the rollers before the modification:
Rotating axis of the rollers after the modification:
After the fix, the rollers of all three omni wheels are rotating as expected.

Fix rollers rotating angle In "omni_wheels.wbt" sample world

---

scripts/install/linux_compilation_dependencies.sh
scripts/install/linux_runtime_dependencies.sh

#6719 removed support for Ubuntu 20.04 in some of the setup scripts. However, because the master branch is still built against 20.04 (iirc only develop has been fully updated for 24.04), this is causing CI failures. IMO, this removal should only target develop and not master. However, given that the other changes from that PR are necessary to fix the Windows and develop builds, it does not make sense to fully revert #6719.
This PR reverts enough to fix the master CI and retains support for 24.04. Given that develop no longer supports 20.04, after this is synchronized, another PR should be opened to fully revert this PR (#6736) *on develop only*. (This can be done by either me or another contributor/maintainer.)

Restore Support for Ubuntu 20.04 in Dependency Installation Scripts

---

.github/workflows/test_suite_linux.yml

Pins the empy version in the ros CI to 3.3.4 (as suggested [here](https://stackoverflow.com/a/77656642/22362115)) to fix the ros CI failure.

Pin empy Version in Ros CI Test

---

docs/reference/changelog-r2024.md
src/webots/nodes/utils/WbTemplateManager.cpp
src/webots/nodes/utils/WbTemplateManager.hpp
src/webots/scene_tree/WbAddNodeDialog.cpp
src/webots/scene_tree/WbExtendedStringEditor.cpp
src/webots/vrml/WbField.cpp
src/webots/vrml/WbField.hpp

Updates `WbField::isParameter()` so that it returns true even on `unconnectedFields` (which have no internal fields). This fixes the linked issue.
Some parts of the codebase previously assumed that `field->isParameter() => !field->internalFields().isEmpty()`. Given that that is no longer the case, those sections have been updated to perform that check explicitly. Additionally, `WbTemplateManager::regenerateNodeFromFieldChange` and `WbTemplateManager::regenerateNodeFromParameterChange` appeared to be workarounds to call `WbTemplateManager::regenerateNodeFromField` given that there was no way to directly tell if a field was a parameter, so I updated `regenerateNodeFromField` to make use of `WbField::isParameter` and deleted the other two.
This pull-request …

Fix `WbField::isParameter` for Unconnected Fields

---

docs/reference/changelog-r2024.md
src/webots/nodes/WbBackground.cpp

Currently, if an invalid HDR image is loaded by `WbBackground`, the input data is read as `NULL`, causing a segfault. This PR adds a statement to check for that condition and print an error message which contains the cause from `stb_image`.

Fix Crash When Loading an Invalid Background HDR Image

---

.github/workflows/test_suite_linux.yml

#6697 accidently deleted the directive to run the Linux build job when the `test-suite` label is applied to a PR. This PR restores that condition.

Fix `test-suite` Label on Linux

---

.github/workflows/test_suite_linux.yml
.github/workflows/test_suite_linux_develop.yml
.github/workflows/test_suite_mac.yml
.github/workflows/test_suite_mac_develop.yml
.github/workflows/test_suite_windows.yml
.github/workflows/test_suite_windows_develop.yml

The CI is currently failing because `geekyeggo/delete-artifact` is unable to list artifacts correctly. My guess is that this is because `v4` artifacts support wasn't introduced until v4 of the action. (Although I'm not sure why this didn't occur when #6654 was originally merged.)
This PR bumps the action version to v5, which should fix this issue.

Bump `geekyeggo/delete-artifact` to v5

---

src/wren/FileImport.cpp

We need to allocate an extra byte for null termination.

Fix buffer overflow

---

docs/reference/changelog-r2025.md
docs/reference/javascript-procedural-proto.md
src/webots/Makefile
src/webots/core/WbQjsEnv.cpp
src/webots/core/WbQjsEnv.hpp
src/webots/core/WbTemplateEngine.cpp

Add the `wbenv` JavaScript module. For now only `wbenv.getFromEnv()`.
https://github.com/cyberbotics/webots/discussions/6475
**Tasks**
https://www.cyberbotics.com/doc/reference/javascript-procedural-proto?version=galou:feature-wbenv
https://discord.com/channels/565154702715518986/565155651395780609/1348362740556759081

Add the `wbenv` JavaScript module

---

docs/reference/changelog-r2025.md
src/controller/launcher/Makefile

Currently the `webots-controller` executable is only built with the default cxx options, meaning that on macos, it only contains code for the platform it was built on. This PR updates the relevant `Makefile` to use the same approach as the rest of Webots to generate object code for both platforms.
This pull-request fixes issue #6805 
**Tasks**

Build `webots-controller` for both x86 and arm on MacOS

---

.github/workflows/test_suite_linux.yml
.github/workflows/test_suite_linux_develop.yml
.github/workflows/test_suite_mac.yml
.github/workflows/test_suite_mac_develop.yml
.github/workflows/test_suite_windows.yml
.github/workflows/test_suite_windows_develop.yml

#6787 was merged into master, however, this means that it never made its way into `released`, so PRs targeting that branch will still fail (e.x. #6818). This PR backports that patch so that PRs targeting `released` will be able to pass CI.

Backport #6787

---

.github/workflows/test_suite_windows.yml
.github/workflows/test_suite_windows_develop.yml

The Windows Server 2019 runner image will be fully unsupported by June 30, 2025. To raise awareness of the upcoming removal, we will temporarily fail jobs using Windows Server 2019. Builds that are scheduled to run during the brownout periods will fail. The brownouts are scheduled for the following dates and times:
- June 3 13:00-21:00 UTC
- June 10 13:00-21:00 UTC
- June 17 13:00-21:00 UTC
- June 24 13:00-21:00 UTC
Jobs using the windows-2019 YAML workflow label should be updated to windows-2022, windows-2025 or windows-latest.

Upgrade workflows to windows-2022

---

docs/reference/changelog-r2025.md
src/webots/editor/WbBuildEditor.cpp

`QMessageBox::exec()` returns an opaque value when used with custom buttons [[1]](https://doc.qt.io/qt-6/qmessagebox.html#exec). However, `WbBuildEditor` was treating this result as an indication of the user's selection. This lead to implementation-dependent behavior, causing the "Reload" and "Reset" buttons to work on Linux but do nothing on Windows.
This PR updates the relevant code to use `QMessageBox::clickedButton()`, which has predictable behavior on both platforms.
I did a quick scan for similar issues throughout the codebase and didn't find any.
**Tasks**

Fix Checking of Reload/Reset Selection in WbBuildEditor

---

.github/workflows/tests_sources.yml
.github/workflows/tests_sources_with_latest_cppcheck.yml

The Windows sources tests are currently failing because `windows-2019` is no longer supported. This PR bumps the relevant tests to use `windows-2022`.

Use Windows Server 2022 in Sources Tests

---

include/controller/c/webots/supervisor.h
tests/sources/test_matlab_functions.py

This PR is a breakoff of #6740 containing just the changes to the MATLAB sources test. It updates the test to search for functions in the exposed header files rather than relying on the `Controller.def` file. This means that it can catch new functions whether or not the contributor remembers to place them in the def file.
The previous test also excluded constants from its search. I see no reason to do this, so I removed that restriction. I've created and attached a diff of the functions the test searches for before and after this change. Viewing it reveals that, with the exception of the aforementioned constants, there is no difference between the functions checked by the two versions.
Keep in mind that in order to achieve this, I had to update the function exclusion list. …

Decouple MATLAB Functions Test from `Controller.def`

---

tests/test_suite.py

As discussed in [#6780 (comment)](https://github.com/cyberbotics/webots/pull/6780#pullrequestreview-3126168912), this PR removes the test exclusion for `supervisor_start_stop_movie.wbt` on Ubuntu 22.04. This actually removes the only use of `is_ubuntu_22_04` in the suite, which I think is neat. However, I've elected to leave the variable in until Ubuntu 22.04 support is phased out in case it becomes necessary. If maintainers want me to just remove it now, I can.

Remove Movie Test Exclusion from Ubuntu 22.04

---

docs/reference/changelog-r2025.md
lib/controller/python/controller/node.py

These python methods call the wrong C-API methods. This PR fixes that.
This pull-request fixes issue #6879 and ~~maybe~~ #6345 ~~(some investigation needed)~~.
**Tasks**

Fix `addTorque` and `addForceWithOffset` Python Implementations

---

scripts/new_version/new_version.sh
scripts/packaging/webots.metainfo.xml

Add appstream for `webots`. Recently I tried to build and run `webots` by flatpak. Yes, I did it and linux arm64 is also supported. I've submitted it to [flathub](https://github.com/flathub/flathub/pull/6852). Now it's being examined. appstream is needed by flatpak apps, and it tells the mata info of the app. It should be managed by upstream. https://github.com/flathub/flathub/pull/6852#discussion_r2293735935
**Tasks**
https://cyberbotics.com/doc/guide/getting-started-with-webots?version=my_repo:my_branch
or
https://cyberbotics.com/doc/guide/getting-started-with-webots?version=my_branch …

chore: add appstream metadata
