- README.md
Slightly smaller subtitle sizes.
> Better README title sizes

- docs/guide/building-webots.md
- docs/guide/foreword.md
- docs/guide/menu.md
Preview (working again :-) ):
- https://cyberbotics.com/doc/guide/foreword?version=enhancement-open-source-documentation
- https://cyberbotics.com/doc/guide/building-webots?version=enhancement-open-source-documentation
> Improve the documentation relatively with the open source migration

- src/webots/nodes/utils/WbVirtualRealityHeadset.cpp
- src/webots/nodes/utils/WbVirtualRealityHeadset.hpp
Compilation was broken in #100 on Windows (probably because of a more recent version of GCC).
> Hotfix Windows compilation.

- Makefile
- projects/default/controllers/ros/Makefile
- projects/default/libraries/vehicle/java/Makefile
- projects/default/libraries/vehicle/python/Makefile
- projects/robots/mobsya/thymio/libraries/Makefile
- projects/vehicles/controllers/ros_automobile/Makefile
- resources/languages/cpp/Makefile
- resources/languages/java/Makefile
- resources/languages/python/Makefile
- resources/osm_importer/osm_gui/Makefile
- resources/projects/plugins/physics/Makefile
- src/packaging/Makefile
> Fixed used of space protected WEBOTS_HOME_PATH variable

- docs/guide/generate_objects_doc.py
- docs/guide/object-backgrounds.md
- docs/guide/object-road.md
- projects/objects/backgrounds/protos/TexturedBackground.proto
- projects/objects/backgrounds/protos/TexturedBackgroundLight.proto
> Regenerate Docs

- include/wren/scene.h
- src/webots/gui/WbView3D.cpp
- src/webots/gui/WbView3D.hpp
- src/webots/gui/WbWrenWindow.cpp
- src/webots/gui/WbWrenWindow.hpp
- src/webots/nodes/utils/WbVirtualRealityHeadset.cpp
- src/webots/wren/WbWrenCamera.cpp
- src/webots/wren/WbWrenPicker.cpp
- src/wren/Scene.cpp
- src/wren/Scene.hpp
> Transfer all Textures to GPU at Load

- src/packaging/files_msys64.txt
This library was updated in recent version of MSYS.
> Update MSYS Packaging

- docs/guide/system-requirements.md
> Fix OpenGl Required Version in Docs

- change_logs/ChangeLog.html
- resources/languages/python/controller.i
> Fix Various Crash in Python API.

- src/install_scripts/msys64_installer.sh
> Fixed missing tar dependency (needed on Windows 7)

- change_logs/ChangeLog.html
- src/webots/nodes/WbAbstractAppearance.hpp
- src/webots/nodes/WbPbrAppearance.cpp
> Fix VRML Export Crash.

- resources/osm_importer/elevation.py
Fix issue reported in https://stackoverflow.com/questions/54367579/webots-r2019-osm-importer-with-3d-enabled/54398885#54398885
> Fix 3D Feature of OSM Importer.

- resources/Makefile.include
- src/webots/Makefile
> Remove binary strip

- change_logs/ChangeLog.html
- src/webots/nodes/WbPbrAppearance.cpp
> Fix TextureTransform Updates

- change_logs/ChangeLog.html
- resources/translations/wb_de.ts
- resources/translations/wb_es.ts
- resources/translations/wb_fr.ts
- resources/translations/wb_generic.ts
- resources/translations/wb_it.ts
- resources/translations/wb_ja_JP.ts
- resources/translations/wb_zh_CN.ts
> Update files for the release

- src/packaging/files_msys64.txt
> Fixed reference to a msys2 library

- change_logs/ChangeLog.html
> Fixed release date

- docs/guide/telemetry.md
> Fix typo in telemetry documentation

- projects/default/controllers/braitenberg/braitenberg.c
> Fix Braitenberg Controller

- src/webots/nodes/utils/WbNodeUtilities.cpp
It should not be possible to transform any node into a DifferentialWheels node from Webots.
> Deny Transform to Differentialwheels

- src/webots/maths/WbImage.cpp
- src/webots/maths/WbImage.hpp
- src/webots/nodes/WbImageTexture.cpp
> Fixed memory leak

- change_logs/ChangeLog.html
> Update Changelog Date

- src/webots/maths/WbImage.cpp
Avoiding the use of float and conversion from float to int allow us to speed up the image scale down algorithm. Before this PR, it took 127 ms on my PC, with this PR, it takes 69 ms.
> Optimized image scale down performance

- src/webots/gui/WbView3D.cpp
- src/webots/nodes/WbCubemap.cpp
> Fix crash on NVIDIA 2Gb GPU.

- src/packaging/files_msys64.txt
> Fixed wrong msys2 library version (Windows)

- docs/guide/telemetry.md
Add reference to the telemetry page.
> Improve Telemetry Doc.

- projects/robots/robotis/darwin-op/worlds/.robotis_op3_motion_player.wbproj
> Improve Robotis-OP3 WBPROJ file.

- src/packaging/files_msys64.txt
> Fixed FFMPEG missing dependencies

- src/packaging/files_msys64.txt
> Fixed typo in path

- docs/guide/starting-webots.md
> Added instructions to launch Webots from a DOS console

- docs/guide/preferences.md
- docs/guide/telemetry.md
- src/webots/core/WbPreferences.cpp
- src/webots/core/WbTelemetry.cpp
- src/webots/gui/WbGuiApplication.cpp
- src/webots/gui/WbPreferencesDialog.cpp
- src/webots/gui/WbPreferencesDialog.hpp
- src/webots/gui/WbView3D.cpp
- src/webots/nodes/WbViewpoint.cpp
- src/webots/util/WbPerformanceLog.cpp
> Cleanup-up anti-aliasing preferences

- docs/guide/starting-webots.md
> Merge master into revision

- src/webots/nodes/WbSolidReference.cpp
> Fix code duplication in WbSolidReference.cpp.

- resources/web/wwi/webots.js
The quit button was not visible by default.
I also fixed other ESLint errors.
> Fix default quit button on webots.js

- docs/reference/connector.md
Partially fix #238.
https://www.cyberbotics.com/doc/reference/connector?version=improve-connector-doc
> Improve Connector Doc

- src/webots/nodes/WbSolidReference.cpp
> Merge revision into develop

- projects/robots/softbank/nao/controllers/nao_demo_python/nao_demo_python.py
- projects/robots/softbank/nao/protos/Nao.proto
Fixed PEP8 for nao_demo_python.py controller, removed useless DEF in Nao proto.
👍
> Hotfix cleanup Nao

- tests/sources/test_clang_format.py
- tests/sources/test_cppcheck.py
- tests/sources/test_icons.py
- tests/sources/test_license.py
- tests/sources/test_matlab_functions.py
- tests/sources/test_project_structure.py
- tests/sources/test_proto_names.py
- tests/sources/test_textures.py
> Add '*.wproj' Test

- projects/vehicles/controllers/Makefile
> Fix Ros-Automobile Compilation on Windows

- src/webots/gui/WbDragScaleEvent.cpp
- src/webots/gui/WbDragTransformEvent.cpp
- src/webots/maths/WbPrecision.cpp
- src/webots/maths/WbPrecision.hpp
- src/webots/maths/WbRotation.hpp
- src/webots/maths/WbVector3.hpp
- src/webots/scene_tree/WbColorEditor.cpp
- src/webots/scene_tree/WbDoubleEditor.cpp
- src/webots/scene_tree/WbVector2Editor.cpp
- src/webots/scene_tree/WbVector3Editor.cpp
> Fix Translation/Rotation Rounding with Handles

- src/packaging/files_core.txt
> Fix Windows Packaging

- projects/default/controllers/sumo_supervisor/sumo_supervisor.py
We had recently several questions about where should exactly be the SUMO network files.
> Improve Sumo Interface Error Message

- docs/guide/object-floors.md
- projects/objects/floors/protos/CircleArena.proto
- projects/objects/floors/protos/RectangleArena.proto
> Fixed Arena protos

- projects/objects/factory/containers/protos/WoodenBox.proto
> Fixed minimum mass of WoodenBox which was too high (for balsa for example)

- docs/guide/irb4600-40.md
Preview: https://www.cyberbotics.com/doc/guide/irb4600-40?version=feature-abb-arm-movie
> ABB arm movie

- src/packaging/webots_distro.c
> Add libnss3 to Debian Package

- README.md
This should contribute to a better understanding of the license of Webots.
> Better reference to license

- docs/reference/light.md
> Fix Light Doc.

- docs/js/viewer.js
- src/webots/nodes/utils/WbWorld.cpp
> Fix Track X3D export.

- docs/reference/pointlight.md
Fix #309.
Preview: https://www.cyberbotics.com/doc/reference/pointlight?version=fix-pi-display
> Fixed the display of pi and added explanation about formula

- docs/guide/tutorial-1-your-first-simulation-in-webots-20-minutes.md
- docs/guide/tutorial-4-more-about-controllers-20-minutes.md
- docs/guide/tutorial-6-4-wheels-robot.md
- docs/reference/motor.md
- include/controller/cpp/webots/Motor.hpp
Tutorial 1: https://www.cyberbotics.com/doc/guide/tutorial-1-your-first-simulation-in-webots-20-minutes?version=feature-cross-language-tutorial
Tutorial 4: https://www.cyberbotics.com/doc/guide/tutorial-4-more-about-controllers-20-minutes?version=feature-cross-language-tutorial&tab=c
Tutorial 6: https://www.cyberbotics.com/doc/guide/tutorial-6-4-wheels-robot?version=feature-cross-language-tutorial
> Cross Language Tutorial

- docs/guide/tutorial-6-4-wheels-robot.md
https://www.cyberbotics.com/doc/guide/tutorial-6-4-wheels-robot#?version=improve-tutorial-6
> Improve Tutorial 6

- change_logs/ChangeLog.html
- projects/robots/k-team/khepera4/protos/Khepera4.proto
- projects/robots/k-team/khepera4/protos/Khepera4InfraredSensor.proto
> Fix Khepera4 Ground Sensors Calibration

- docs/guide/tutorial-1-your-first-simulation-in-webots-20-minutes.md
- docs/reference/proto-definition.md
- docs/reference/proto.md
This PR aims at reviewing and improving the tutorials of the user guide.
Test link: https://cyberbotics.com/doc/guide/tutorial-1-your-first-simulation-in-webots-20-minutes?version=fix-tutorials
> Improve tutorial 1

- src/webots/core/WbPreferences.cpp
- src/webots/engine/WbSimulationWorld.cpp
- src/webots/engine/WbSimulationWorld.hpp
- src/webots/gui/WbPreferencesDialog.hpp
> Cleanup threadingPolicy.

- docs/reference/proto-definition.md
- docs/reference/proto.md
This PR fixes the PROTO definition that didn't get merged from #318.
> Fix PROTO definition

- resources/templates/controllers/template.c
- resources/templates/controllers/template.cpp
- resources/templates/controllers/template.java
- resources/templates/controllers/template.m
- resources/templates/controllers/template.py
> Cleanup Controller Templates.

- change_logs/ChangeLog.html
- src/webots/nodes/utils/WbNodeOperations.cpp
> Fix Crash when Copy-Pasting some Node.

- change_logs/ChangeLog.html
- src/webots/nodes/WbTrack.cpp
> Fix Assertion  Failure when Adding AnimatedGeometry to Track.

- docs/guide/interfacing-webots-to-third-party-software-with-tcp-ip.md
@physar thank you for this contribution, feel free to open PR on our repository to fix such errors.
> Fix file path in doc

- docs/guide/interfacing-webots-to-third-party-software-with-tcp-ip.md
> Fix Missing Links in Doc

- docs/guide/starting-webots.md
Following #351: remove other old references to Ogre.
> Remove wrong references to Ogre

- change_logs/ChangeLog.html
- src/packaging/copy_msys64_files.py
- src/packaging/files_msys64.txt
> Fix release of the OpenCV packages on Windows

- resources/web/wwi/animation.js
- resources/web/wwi/console.js
- resources/web/wwi/context_menu.js
- resources/web/wwi/dialog_window.js
- resources/web/wwi/editor.js
- resources/web/wwi/help_window.js
- resources/web/wwi/mouse_events.js
- resources/web/wwi/server.js
- resources/web/wwi/stream.js
- resources/web/wwi/texture_loader.js
- resources/web/wwi/toolbar.js
- resources/web/wwi/util.js
- resources/web/wwi/webots.js
- resources/web/wwi/x3d.js
- resources/web/wwi/x3d_scene.js
Prefer the EC6 arrow function over the "var that = this;" pattern, and "function" keyword.
> Use ES6 arrow functions, and remove the "var that = this;" pattern

- change_logs/ChangeLog.html
- src/webots/nodes/utils/WbPaintTexture.cpp
> Fix DistanceSensors with Pen

- docs/guide/samples-environments.md
Fixes #414.
Test link: https://www.cyberbotics.com/doc/guide/samples-environments?version=hotfix-documentation-links
> Fixed broken links and added new links

- docs/guide/samples-devices.md
- docs/guide/samples-geometries.md
- docs/guide/samples-rendering.md
- docs/guide/web-streaming.md
- docs/reference/plugin-setup.md
- docs/tests/test_hyperlinks.py
This test will prevent issues like #414.
> Add Test for Github Links.

- docs/guide/controller-programming.md
> Fix controller-programming.md

- Contents/Info.plist
- resources/version.txt
- src/packaging/webots_version.txt
- src/webots/core/WbApplicationInfo.cpp
> Update Webots version to R2019a revision 2

- projects/languages/ros/webots_ros/CMakeLists.txt
- projects/languages/ros/webots_ros/package.xml
Some dependencies were missing.
> Fix Webots-Ros package

- resources/web/wwi/animation.js
- resources/web/wwi/default_url.js
- resources/web/wwi/editor.js
- resources/web/wwi/toolbar.js
- resources/web/wwi/webots.js
Fix value of `wwi_url` in case a query was added in the script include declaration as in robotbenchmark use case.
This PR also fixed a problem with the format of the `menu.png` url.
> Fix wwi_url value in webots.js

- docs/js/viewer.js
> Fix ESLint warnings

- projects/default/controllers/ros/RosGyro.cpp
> Hotfix RosGyro

- src/webots/nodes/utils/WbTriangleMesh.cpp
- tests/rendering/worlds/normals.wbt
> Fix Crash Loading Normals without NormalIndex

- .travis.yml
- docs/local_exporter.py
- docs/tests/test_images.py
- projects/default/controllers/ros/headersFromMSG.py
- projects/default/controllers/ros/headersFromSRV.py
- projects/default/controllers/ros/headersGenerator.py
- projects/default/controllers/sumo_supervisor/Objects.py
- projects/default/controllers/sumo_supervisor/SumoDisplay.py
- projects/default/controllers/sumo_supervisor/SumoSupervisor.py
- projects/default/controllers/sumo_supervisor/sumo_supervisor.py
- projects/humans/pedestrian/controllers/pedestrian/pedestrian.py
- projects/robots/gctronic/e-puck/transfer/populate_xc16_directory.py
- projects/robots/tinkerbots/controllers/two_wheels_vehicle/two_wheels_vehicle.py
- projects/robots/tinkerbots/controllers/vision_car/vision_car.py
- projects/samples/contests/rockin/package_generator.py
- projects/samples/robotbenchmark/square_path/controllers/square_path_supervisor/real_robot_performance.py
- projects/vehicles/worlds/sumo_interface_example_net/generate_route_file.py
- resources/osm_importer/importer.py
- resources/osm_importer/parser_objects.py
- resources/osm_importer/webots_objects/road.py
- resources/osm_importer/webots_objects/speed_limit.py
- resources/sumo_exporter/road.py
- scripts/icon_studio/controllers/leds/leds.py
- src/packaging/check_rpath.py
- tests/command_test.py
- tests/manual_tests/controllers/procedural_proto_regenerator/procedural_proto_regenerator.py
- tests/manual_tests/test_worlds_warnings.py
- tests/sources/test_clang_format.py
- tests/sources/test_icons.py
- tests/sources/test_pep8.py
It is possible to launch the test with multiple instances in parallel using different versions of Python.
> Test Multiple Python Version with Travis

- src/packaging/exist_in_projects.txt
- src/packaging/exist_in_projects_linux.txt
- src/packaging/exist_in_projects_mac.txt
These files are not released on Windows anymore
> Hotfix Windows Packaging

- change_logs/ChangeLog.html
- resources/languages/python/controller.i
> Fix  Python getRangeImageArray Function

- docs/reference/ros-api.md
> ROS doc: Add link to the list of ROS services and messages.

- docs/reference/light.md
> Improve documentation of Light.ambientIntensity

- change_logs/ChangeLog.html
- src/webots/engine/WbSimulationCluster.cpp
- src/webots/nodes/WbBox.cpp
- src/webots/nodes/WbCapsule.cpp
- src/webots/nodes/WbCylinder.cpp
- src/webots/nodes/WbElevationGrid.cpp
- src/webots/nodes/WbIndexedFaceSet.cpp
- src/webots/nodes/WbSphere.cpp
- src/webots/ode/WbOdeGeomData.hpp
- tests/lib/ts_assertion.h
- tests/physics/controllers/kinematic_geometry_update/.gitignore
- tests/physics/controllers/kinematic_geometry_update/Makefile
- tests/physics/controllers/kinematic_geometry_update/kinematic_geometry_update.c
- tests/physics/worlds/kinematic_geometry_update.wbt
> Fix Geometry Update not Awakening Solids

- projects/samples/tutorials/controllers/4_wheels_collision_avoidance/4_wheels_collision_avoidance.c
> Fixed wrong variable type

- projects/samples/robotbenchmark/visual_tracking/controllers/visual_tracking/visual_tracking.py
> Ported visual_tracking controller to python 3

- resources/web/wwi/mouse_events.js
- resources/web/wwi/webots.js
Fix touchEnd callback re-adding the selection and long click functionality.
> Readd selection and context menu functionlity on webots.min.js for mobile devices

- src/webots/vrml/WbVrmlWriter.cpp
> Merge revision to develop

- docs/guide/generate_objects_doc.py
This script was not update in #492
> Handle Thumbnails in Doc Generator

- projects/objects/backgrounds/protos/TexturedBackground.proto
> Fix TexturedBackground description

- projects/default/Makefile
My recent commit #559 broke `make cleanse` on Windows
> Fix make cleanse on Windows

- projects/robots/telerob/telemax_pro/controllers/telemax_demo/telemax_demo.c
Following a comment of @omichel
> Improve variable name

- projects/robots/kinematics/tinkerbots/controllers/vehicle/vehicle.c
- projects/robots/kinematics/tinkerbots/worlds/tinkerbots_demo.wbt
Fix #562
The distance sensor response has slightly changed due to #340. Take the advantage to simplify this world (drop one distance sensor to increase robustness).
> Fix and simplify tinkerbots demo

- .travis.yml
- docs/guide/tutorial-8-using-ros.md
- src/packaging/generate_projects_files.py
- src/packaging/webots_distro.c
> Fix Release

- projects/robots/robotis/darwin-op/libraries/Makefile
> Fix typo in Makefile comment

- docs/reference/muscle.md
> Fix Muscle.color field name in docs

- docs/guide/controller-plugin.md
- docs/reference/robot.md
Preview: https://www.cyberbotics.com/doc/guide/controller-plugin?version=enhancement-remote-control-doc#remote-control-plugin
> Improve the wbr_start documentation

- src/packaging/files_core.txt
> Remove obsolete file references

- projects/samples/devices/worlds/led.wbt
> Fix warnings about attenuation in led.wbt

- docs/reference/muscle.md
> Merge master to revision

- resources/translations/wb_de.ts
- resources/translations/wb_es.ts
- resources/translations/wb_fr.ts
- resources/translations/wb_generic.ts
- resources/translations/wb_it.ts
- resources/translations/wb_ja_JP.ts
- resources/translations/wb_zh_CN.ts
> Update translation files for the release

- projects/guided_tour.txt
> Fix Missing Devices in Guided tour

- projects/default/controllers/sumo_supervisor/SumoSupervisor.py
Fix #620.
That is still not perfect as our way to add 3D information in SUMO is a bit artificial, but at least it fixes the bug introduced when we did update the SUMO version.
> Fix Sumo Vehicle Height

- docs/guide/tutorial-8-using-ros.md
Since we are going to release really soon, I think we can afford to merge this in develop instead of master.
> Fix Tutorial Number

- projects/languages/ros/webots_ros/CMakeLists.txt
Fix #630
I am currently sending the update to ROS distro.
> Fix ROS Package

- projects/robots/telerob/telemax_pro/worlds/telemax.wbt
This was not updated from the `wall.wbt` world.
> Fix Telemax World Description

- projects/default/protos/Supervisor.proto
> Fix typo in Supervisor deprecation warning

- src/packaging/webots_distro.c
> Delete more dangerous DLLs from C:\Windows\System32

- projects/vehicles/controllers/highway_overtake/highway_overtake.py
- projects/vehicles/worlds/.highway_overtake.wbproj
> Fix Highway Overtake Simulation

- src/packaging/publish_release.py
Any better warning message is welcome.
> Improved Nightly Build Description

- docs/guide/ure.md
This was founded by the ROSIN FTP project.
> Add ROSin Acknowledgement

- src/packaging/publish_release.py
When creating a new nightly build all the nightly build older than 2days12hours are removed (tag too). This way we should have always only the last 3 nightly builds.
> Delete Old Nightly Builds

- docs/doc.php
- src/bin/new_version.sh
- src/bin/new_version_file.sh
This is allow us to automatically update the default blog page.
> Fix default blog page

- projects/languages/ros/webots_ros/package.xml
This url is used for example when they announce new packages.
> Add Url to ros package.

- src/packaging/publish_release.py
This way we will be able to perform the nightly builds both on develop and revision and to put both in the same nightly build.
> Feature Several Branches in Nightly Builds

- change_logs/ChangeLog.html
- projects/default/controllers/ros/Ros.cpp
Reported here: https://stackoverflow.com/questions/56775714/using-the-webots-connector-device-with-ros
> Fix Connector Behavior in ROS Controller

- tests/sources/generate_diff.py
The fourth commit was successfully tested outside of a PR.
👍
> Fix generate diff bug

- .travis.yml
Fix  #674 and random failure on mac (e.g. https://api.travis-ci.com/v3/job/211634837/log.txt)
> Fix travis Python 2.7 and mac

- change_logs/ChangeLog.html
> Fix Changelog

- docs/reference/change-log-4.md
- docs/reference/change-log-5.md
- docs/reference/change-log-6.md
- docs/reference/change-log-7.md
- docs/reference/change-log-8.md
- docs/reference/change-log-r2018.md
- docs/reference/change-log-r2019.md
Restore release date lost during the conversion html => md.
> Restore Changelogs Release Date.

- .travis.yml
- src/packaging/publish_release.py
We don't want to create nightly release during the week-end.
> Avoid Nighlty Release During Weekend

- docs/guide/using-java.md
> Update JDK installation instructions

- .travis.yml
- tests/sources/generate_diff.py
- tests/sources/test_pep8.py
That should fix the Jenkins source test with Python 2.7.
It also fixes the test on Windows which was failing.
> Fixed Travis source tests

- dependencies/.gitignore
- dependencies/Makefile.windows
That should speed up the installation process.
> Stripped down openvr download

- src/webots/gui/WbNewVersionDialog.cpp
> Add a newsletter link in the 'new version dialog'

- src/packaging/publish_release.py
Normal nightly build (not from tag) should not be draft.
> Fix Nightly Build Draft

- docs/guide/running-extern-robot-controllers.md
See problem at https://cyberbotics.com/doc/guide/running-extern-robot-controllers?tab=undefined#environment-variables
> Fix Unprotected Underscore

- src/packaging/publish_release.py
This should help the users to see what's new / fixed in the nightly builds.
> Added links to nightly build descriptions

- .appveyor-test-sources-scheduled.yml
This should enable nightly source tests on Windows.
> AppVeyor nightly source tests

- src/webots/nodes/WbImageTexture.cpp
> Fix Texture Picking 2

- docs/guide/the-user-interface.md
- docs/reference/change-log-r2020.md
- docs/reference/viewpoint.md
- resources/nodes/Viewpoint.wrl
- src/webots/gui/WbMainWindow.cpp
- src/webots/gui/WbView3D.cpp
- src/webots/gui/WbView3D.hpp
- src/webots/nodes/WbViewpoint.cpp
- src/webots/nodes/WbViewpoint.hpp
- src/webots/user_commands/WbActionManager.cpp
- src/webots/user_commands/WbActionManager.hpp
- src/webots/user_commands/WbContextMenuGenerator.cpp
- tests/protos/protos/TemplateViewpoint.proto
This PR adds the possibility to set various follow solid behavior:
- Tracking Shot
- Mounted Shot
- Pan and Tilt Shot
> Enhance Solid Following Behavior

- .appveyor-build-tag.yml
May fix #708.
The order of instructions in the YML file may have some influence. I found several examples with this order. I hope this will fix the problem, otherwise, I will report the problem to the appveyor support.
(note this modification need to be merged into develop as well, I will do it later on)
👍
> Attempt to fix the build on tag except nightly

- tests/protos/protos/TemplateViewpoint.proto
> Fix template_viewpoint_proto test

- projects/objects/traffic/protos/CrossRoadsTrafficLight.proto
> Fix CrossRoad PROTO

- docs/guide/running-extern-robot-controllers.md
> Fix typo in External Controller Doc

- docs/guide/mavic-2-pro.md
Preview: https://cyberbotics.com/doc/guide/mavic-2-pro?version=enhancement-mavic-movie
> Include the new Mavic 2 PRO movie

- resources/osm_importer/webots_objects/area.py
- resources/osm_importer/webots_objects/road.py
> Improve OSM importer

- docs/guide/tutorial-4-more-about-controllers-20-minutes.md
The code example from C++ was from C (below is correct)
> Update tutorial 4

- docs/reference/changelog-r2019.md
- resources/web/wwi/x3d.js
> webots.min.js: Fix fog type

- .appveyor.yml
- README.md
- docs/guide/generate_objects_doc.py
- tests/sources/test_pep8.py
Port several fixes of appveyor from revision to master.
> Fix appveyor on master

- docs/guide/tutorial-8-using-ros.md
- docs/guide/using-ros.md
Fix #660
Preview:
- https://cyberbotics.com/doc/guide/using-ros?version=fix-ros-instruction
- https://cyberbotics.com/doc/guide/tutorial-8-using-ros?version=fix-ros-instruction
This PR also include modifications on the ros wiki:
- http://wiki.ros.org/webots_ros
- http://wiki.ros.org/webots_ros/Tutorials/Sample%20Simulations
> Update ROS Instructions

- docs/guide/using-ros.md
Fix https://github.com/omichel/webots/pull/714#pullrequestreview-271763178
> Fix ROS Doc

- resources/web/wwi/texture_loader.js
> Fix typo in webots.min.js:TextureLoader

- docs/guide/samples-environments.md
Fix https://github.com/omichel/webots/pull/656#pullrequestreview-271861879
> fix-appartment-note

- projects/robots/robotis/darwin-op/libraries/python27/.gitignore
- projects/robots/robotis/darwin-op/libraries/python35/.gitignore
- projects/robots/robotis/darwin-op/libraries/python36/.gitignore
- projects/robots/robotis/darwin-op/libraries/python37/.gitignore
> Fixed gitignore files for robotis python libraries

- projects/languages/python/controllers/driver/driver.py
- projects/languages/python/controllers/slave/slave.py
These controllers were not very 'pythonic'.
> Improve Python Sample Controllers

- docs/reference/changelog-r2019.md
- src/lib/Controller/api/robot.c
- src/lib/Controller/api/system.c
Fix https://github.com/omichel/webots_ros2/issues/3
> Improve External Controller to Wait for Webots.

- docs/guide/using-python.md
> Add a Link to PyCharm Page

- docs/reference/changelog-r2019.md
- projects/vehicles/protos/abstract/VehicleLights.proto
- projects/vehicles/protos/bmw/BmwX5BackwardsLight.proto
- projects/vehicles/protos/bmw/BmwX5BrakingLight.proto
- projects/vehicles/protos/bmw/BmwX5FrontLight.proto
- projects/vehicles/protos/bmw/BmwX5LeftIndicator.proto
- projects/vehicles/protos/bmw/BmwX5RearLight.proto
- projects/vehicles/protos/bmw/BmwX5RightIndicator.proto
- projects/vehicles/protos/citroen/CitroenCZeroBrakeLight.proto
- projects/vehicles/protos/citroen/CitroenCZeroHeadLight.proto
- projects/vehicles/protos/citroen/CitroenCZeroLeftIndicator.proto
- projects/vehicles/protos/citroen/CitroenCZeroRightIndicator.proto
- projects/vehicles/protos/generic/Bus.proto
- projects/vehicles/protos/generic/TruckFrontLight.proto
- projects/vehicles/protos/generic/TruckRearLight.proto
- projects/vehicles/protos/lincoln/LincolnMKZ.proto
- projects/vehicles/protos/lincoln/LincolnMKZCoachworkMesh.proto
- projects/vehicles/protos/range_rover/RangeRoverSportSVR.proto
- projects/vehicles/protos/tesla/TeslaModel3FrontLights.proto
- projects/vehicles/protos/toyota/ToyotaPriusFrontLight.proto
- projects/vehicles/protos/toyota/ToyotaPriusLeftIndicator.proto
- projects/vehicles/protos/toyota/ToyotaPriusRearLight.proto
- projects/vehicles/protos/toyota/ToyotaPriusRightIndicator.proto
Example in the night:
Example with the indicators:
> Improve Vehicle Light Intensity 

- docs/reference/changelog-r2019.md
- resources/web/wwi/Makefile
- resources/web/wwi/editor.js
- resources/web/wwi/mouse_events.js
- resources/web/wwi/system_info.js
- resources/web/wwi/webots.js
Fix https://github.com/omichel/robotbenchmark/issues/303
> webots.min.js/macOS: Fix `Ctrl + left click`

- docs/guide/nao.md
Prepare the naoqisim migration to cyberbotics organization
> Update naoqisim repo path

- docs/reference/robot.md
This function was not documented for Python, Java and Matlab.
> Add missing setMode function to doc

- docs/reference/changelog-r2019.md
- resources/web/wwi/toolbar.js
- resources/web/wwi/webots.js
> webots.min.js: Fixed console button disabled in broadcast streaming

- src/webots/gui/WbStreamingServer.cpp
> Hotfix WbStreamingServer compilation

- tests/sources/generate_diff.py
> Fix source tests for deleted files (backported from develop)

- docs/reference/changelog-r2019.md
- src/webots/core/WbStandardPaths.cpp
- src/webots/core/WbStandardPaths.hpp
- src/webots/gui/WbMainWindow.cpp
- src/webots/gui/WbMainWindow.hpp
Implement proposal discussed in #873
Implemented the following menu:
Doc is compliant with this modification:
- https://cyberbotics.com/doc/guide/the-user-interface#help-menu
- https://cyberbotics.com/doc/guide/general-faq
> Update the help menu

- docs/README.md
> Update doc readme to python3

- docs/guide/tutorial-2-modification-of-the-environment.md
- docs/guide/tutorial-3-appearance.md
- docs/guide/tutorial-4-more-about-controllers.md
- docs/guide/tutorial-5-compound-solid-and-physics-attributes.md
- docs/guide/tutorial-6-4-wheels-robot.md
- docs/guide/tutorial-7-your-first-proto.md
- docs/guide/tutorial-8-using-ros.md
Improvement of tutorials 1-8 following the reading of a second reviser.
> Improvement of tutorial doc

- dependencies/Makefile.linux
- dependencies/Makefile.windows
The warning was:
```
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
```
> Fixed compilation of lua which was displaying a warning

- docs/reference/contactproperties.md
> Fix non-escaped hyphen in ContactProperties doc

- .gitignore
- dependencies/Makefile.linux
- docs/reference/changelog-r2019.md
- resources/projects/libraries/qt_utils/gui/MainWindow.cpp
- src/install_scripts/qt_linux_installer.sh
- src/webots/editor/WbProjectRelocationDialog.cpp
- src/webots/editor/WbSyntaxHighlighter.cpp
- src/webots/editor/WbTextBuffer.cpp
- src/webots/gui/WbDragTransformEvent.cpp
- src/webots/gui/WbGuiApplication.cpp
- src/webots/gui/WbMainWindow.cpp
- src/webots/gui/WbVideoRecorder.cpp
- src/webots/gui/WbVideoRecorderDialog.cpp
- src/webots/scene_tree/WbTreeView.cpp
- src/webots/widgets/WbDockTitleBar.cpp
This PR will also help to progress with the snap package and hopefully fix the dependency problem of QtWebEngine on `/sys/devices/pci0000:00/0000:00:17.0/resource` as explained here: https://forum.snapcraft.io/t/qtwebengine-blocked-by-apparmor/13312
> Upgrade to Qt 5.13.1 on Linux

- src/install_scripts/qt_linux_installer.sh
I'm I wrong or the paths in the `qt_linux_installer.sh` have to be updated?
> Update webots library path in qt_linux_installer.sh

- docs/guide/tutorial-8-using-ros.md
Fix path to system `setup.bash`
> Fix path in  ROS Tutorial

- docs/guide/installation-procedure.md
> Better command line to install Cyberbotics signature

- docs/reference/changelog-r2019.md
- resources/Makefile.os.include
Last XCode update contains the new Catalina SDK (10.15).
> Fix Catalina SDK support

- docs/reference/changelog-r2019.md
- resources/translations/wb_de.ts
- resources/translations/wb_es.ts
- resources/translations/wb_fr.ts
- resources/translations/wb_generic.ts
- resources/translations/wb_it.ts
- resources/translations/wb_ja_JP.ts
- resources/translations/wb_zh_CN.ts
> Update release files

- docs/reference/changelog-r2019.md
Fix underscores in libraries name that are interpreted as italic text.
> Fix libraries names in Changelog

- docs/reference/propeller.md
Fix #930
Preview: https://cyberbotics.com/doc/reference/propeller?version=fix-pi-display
> Fix Pi display

- projects/humans/c3d/controllers/c3d_viewer/c3d_viewer.py
- projects/humans/c3d/protos/C3dViewer.proto
> Fix C3D file not defined.

- docs/reference/changelog-r2019.md
- resources/web/wwi/x3d.js
Fix #937: adjust default values to match the Webots ones.
> Fix default values for geometries

- docs/guide/modeling.md
- docs/guide/programming.md
- docs/guide/tutorial-5-compound-solid-and-physics-attributes.md
http://ode-wiki.org is dead, use http://ode.org/wiki instead.
> Fix ODE links.

- projects/guided_tour.txt
Any other re-ordering suggestion is welcome.
> Re-order Guided Tour

- src/webots/core/WbDesktopServices.cpp
- src/webots/gui/WbMainWindow.cpp
Fix https://github.com/cyberbotics/webots/issues/943 as described there.
> Improve external URLs robustness

- projects/samples/devices/worlds/camera.wbt
- projects/samples/devices/worlds/camera_motion_blur.wbt
- projects/samples/devices/worlds/camera_noise_mask.wbt
> Apply the update_all_worlds.py script

- docs/reference/changelog-r2019.md
> Update release date

- src/packaging/Makefile
Fixes #961 and adds more consistency.
> Fixed clean target

- projects/default/controllers/ros/Ros.cpp
- projects/default/controllers/ros/Ros.hpp
Fix https://stackoverflow.com/questions/58232623/how-to-sync-robot-in-ros
The clock need to be published non-stop (which was not the case when the controller was waiting for a call to the step service).
> Fix clock not published in synchronized mode.

- docs/guide/tutorial-3-appearance.md
- docs/guide/tutorial-6-4-wheels-robot.md
Fix symbol for lists to be consistent
Changes can be viewed:
[File:  doc/guide/tutorial-3-appearance.md](https://www.cyberbotics.com/doc/guide/tutorial-3-appearance?version=michou214:doc-improve-tutorial)
[File:  doc/guide/tutorial-6-4-wheels-robot.md](https://www.cyberbotics.com/doc/guide/tutorial-6-4-wheels-robot?version=michou214:doc-improve-tutorial)
> Doc improve tutorial

- docs/guide/using-java.md
> We support Java 8 and later versions

- .travis.yml
- tests/ros.sh
> Fix Travis Tests

- docs/reference/changelog-r2019.md
- resources/web/server/config/simulation/local.json
- resources/web/server/session_server.py
- resources/web/server/simulation_server.py
Fix running issues with Python3
> Port simulation_server.py to Python3

- src/webots/control/WbController.cpp
- src/webots/core/WbSysInfo.hpp
- src/webots/gui/WbPreferencesDialog.cpp
> Added an explanation message for MATLAB controllers / snap

- projects/samples/robotbenchmark/highway_driving/plugins/robot_windows/highway_driving/highway_driving.js
- projects/samples/robotbenchmark/humanoid_marathon/plugins/robot_windows/humanoid_marathon/humanoid_marathon.js
- projects/samples/robotbenchmark/inverted_pendulum/plugins/robot_windows/inverted_pendulum/inverted_pendulum.js
- projects/samples/robotbenchmark/maze_runner/plugins/robot_windows/maze_runner/maze_runner.js
- projects/samples/robotbenchmark/obstacle_avoidance/plugins/robot_windows/obstacle_avoidance/obstacle_avoidance.js
- projects/samples/robotbenchmark/pick_and_place/plugins/robot_windows/pick_and_place/pick_and_place.js
- projects/samples/robotbenchmark/pit_escape/plugins/robot_windows/pit_escape/pit_escape.js
- projects/samples/robotbenchmark/robot_programming/plugins/robot_windows/robot_programming/robot_programming.js
- projects/samples/robotbenchmark/square_path/plugins/robot_windows/square_path/square_path.js
- projects/samples/robotbenchmark/viewpoint_control/plugins/robot_windows/viewpoint_control/viewpoint_control.js
- projects/samples/robotbenchmark/visual_tracking/plugins/robot_windows/pan_tilt_camera_view/pan_tilt_camera_view.js
- projects/samples/robotbenchmark/visual_tracking/plugins/robot_windows/visual_tracking/visual_tracking.js
- projects/samples/robotbenchmark/wall_following/plugins/robot_windows/wall_following/wall_following.js
> Enhancement robotbenchmark js files

- .travis.yml
This explains why the releases are not uploaded on Github.
> Fix Travis not Publishing Releases

- .github/FUNDING.yml
> Add myself to sponsor

- .appveyor-test-sources-scheduled.yml
- .appveyor.yml
Use version 9 of clang-format on appveyor
> Upgraded clang-format to version 9 on appveyor

- .github/FUNDING.yml
I am currently blocked by github sponsor due to an address issue :-/
> Fix Sponsor

- docs/reference/changelog-r2019.md
- resources/languages/cpp/Field.cpp
- resources/languages/python/controller.i
Fixes #1020.
Here is the code I used to test it:
```python
from controller import Robot, Display
class CameraDisplay(Robot):
timeStep = 32
motors = []
def __init__(self):
super(CameraDisplay, self).__init__()
self.camera = self.getCamera('camera')
self.display = self.getDisplay('display')
self.camera.enable(self.timeStep)
self.motors.append(self.getMotor('right wheel motor'))
self.motors.append(self.getMotor('left wheel motor'))
self.motors[0].setPosition(float('inf'))
self.motors[1].setPosition(float('inf'))
self.motors[0].setVelocity(1)
self.motors[1].setVelocity(-1)
def run(self):
while True:
a = self.camera.getImageArray()
if a:
image = self.display.imageNew(a, Display.RGB)
self.display.imagePaste(image, 0, 0)
self.display.imageDelete(image)
if self.step(self.timeStep) == -1:
break …
```
> Fixed Display.imageNew from array in Python

- resources/Makefile.os.include
- src/lib/Controller/Makefile
> Fix problematic lsb_release in Makefile.os.include

- tests/sources/test_pep8.py
This fixes the nightly test failure.
> Fix PEP8 Test Failure.

- dependencies/Makefile.mac
- docs/reference/changelog-r2019.md
- src/install_scripts/qt_mac_installer.sh
- src/webots/gui/WbMainWindow.cpp
- src/webots/gui/main.cpp
> macOS: Update Qt

- docs/guide/web-scene.md
- docs/tests/test_lists.py
Document workaround for issue #1057
> Add instructions to run web scenes on Firefox 68 or later

- src/webots/engine/WbAnimationRecorder.cpp
- src/webots/gui/WbMainWindow.cpp
Related to #1057.
Improve note about browser CORS issues when asking to open the web model and web animation
> Improve message about CORS issue when opening the web interface

- .github/FUNDING.yml
> Update sponsor list

- src/webots/control/WbControlledWorld.cpp
- tests/api/worlds/extern.wbt
Fix #1047
The bug is also visible on the first world of the guided tour.
> Fix none Controllers

- resources/web/wwi/Makefile
Ditto
Following our discussion on Discord
> Hotfix issues in the babel-plugin-minify-simplify update

- docs/reference/changelog-r2019.md
- src/lib/Controller/api/abstract_camera.c
- src/lib/Controller/api/abstract_camera.h
- src/webots/core/WbPosixSharedMemory.hpp
- src/webots/nodes/WbAbstractCamera.cpp
> Fix Lidar cloud point access in controllers

- scripts/preferences_cleaner/preferences_cleaner.py
- scripts/web_component_studio/controllers/web_component_studio_supervisor/web_component_studio_supervisor.py
- scripts/web_component_studio/web_component_studio.py
> Python3 support for web component script

- projects/samples/robotbenchmark/maze_runner/worlds/maze_runner.wbt
- projects/samples/robotbenchmark/obstacle_avoidance/worlds/obstacle_avoidance.wbt
In order to render better in the web interface.
> Slightly improve the robotbenchmark worlds lighting

- docs/guide/lidar-sensors.md
- projects/devices/sick/protos/SickLdMrs.proto
> SICK LD-MRS 800001S01: Improve vertical azimuth constants

- docs/reference/changelog-r2019.md
- resources/web/server/simulation_server.py
Port fix from develop to revision branch.
> Fix overwriting DISPLAY variable in simulation server.py 

- projects/samples/howto/plugins/robot_windows/custom_html_robot_window/custom_html_robot_window.js
> Fix typo in comment

- docs/doc.php
- docs/guide/controller-plugin.md
- docs/guide/samples-howto.md
- docs/guide/web-streaming.md
- docs/reference/robot.md
- projects/samples/howto/plugins/robot_windows/custom_html_robot_window/custom_html_robot_window.c
- projects/samples/howto/plugins/robot_windows/custom_html_robot_window/custom_html_robot_window.html
- resources/projects/plugins/robot_windows/generic/generic.c
- resources/web/wwi/webots.js
> Fix spelling of JavaScript and other typos

- src/packaging/files_core.txt
The windows package was broken on develop since a while because of a bad merge: #934
> Fixed Windows Packaging

- src/webots/nodes/WbSolid.cpp
> Fix Reset of Hidden Kinematic Parameters

- src/webots/gui/WbRobotWindow.cpp
Fix compilation issue on Windows introduced in #1120.
> Fix Webots Compilation on Windows

- docs/reference/changelog-r2019.md
- docs/reference/changelog-r2020.md
Remove the ChangeLog entry for R2019b revision 2 and merge it with the one of R2020a.
> Merge ChangeLog for r2020a

- resources/web/server/config/session/cyberbotics1.json
- resources/web/server/config/simulation/video.json
- resources/web/wwi/server.js
- resources/web/wwi/webots.js
> Update cyberbotics server host name

- docs/guide/general-faq.md
Preview: https://www.cyberbotics.com/doc/guide/general-faq?version=feature-document-old-release-login#can-i-still-use-a-webots-version-before-the-r2019a-release
> Document login to old Webots releases

- src/webots/nodes/WbCamera.cpp
> Fix memory leak

- resources/Makefile
The osm_gui was removed in #1130
> Fix wrong clean target.

- docs/reference/changelog-r2020.md
Fixed incorrect entry in changelog.
> Fixed Changelog

- scripts/web_component_studio/controllers/web_component_studio_supervisor/web_component_studio_supervisor.py
> Fix background export of robot component.

- docs/guide/appearances.md
- docs/guide/camera-sensors.md
- docs/guide/lidar-sensors.md
- docs/guide/object-factory.md
- docs/reference/changelog-r2020.md
- projects/devices/multisense/protos/MultiSenseS21.proto
- projects/devices/robotis/protos/RobotisLds01.proto
- projects/devices/sick/protos/SickLdMrs.proto
- projects/objects/factory/tools/protos/CapScrew.proto
> Rename 'physics' fields into 0enablePhysics'

- src/webots/gui/WbMainWindow.cpp
> Fix typo in Help menu

- docs/guide/tiago-base.md
- docs/guide/tiago-iron.md
- docs/guide/tiago-steel.md
- docs/guide/tiago-titanium.md
- docs/guide/tiagopp.md
- projects/robots/pal_robotics/tiago++/protos/Tiago++.proto
- projects/robots/pal_robotics/tiago_base/protos/TiagoBase.proto
- projects/robots/pal_robotics/tiago_base/worlds/tiago_base.wbt
- projects/robots/pal_robotics/tiago_extensions/protos/TiagoBody.proto
- projects/robots/pal_robotics/tiago_extensions/protos/TiagoFrontArm.proto
- projects/robots/pal_robotics/tiago_extensions/protos/TiagoLeftArm.proto
- projects/robots/pal_robotics/tiago_extensions/protos/TiagoRightArm.proto
- projects/robots/pal_robotics/tiago_iron/protos/TiagoIron.proto
- projects/robots/pal_robotics/tiago_steel/protos/TiagoSteel.proto
- projects/robots/pal_robotics/tiago_titanium/protos/TiagoTitanium.proto
**Minor changes**
* Renamed fields to extend the robot to be more consistent
* Update the documentation page of each model
> Update PROTOs and doc

- src/webots/gui/WbMainWindow.cpp
- src/webots/gui/WbMainWindow.hpp
> Remove link to Support Ticket from Help menu

- resources/translations/wb_de.ts
- resources/translations/wb_es.ts
- resources/translations/wb_fr.ts
- resources/translations/wb_generic.ts
- resources/translations/wb_it.ts
- resources/translations/wb_ja_JP.ts
- resources/translations/wb_zh_CN.ts
> Update translation files

- docs/guide/running-extern-robot-controllers.md
> Update path to lib/controller in documentation

- projects/robots/festo/robotino3/controllers/robotino3/robotino3.c
- projects/robots/festo/robotino3/worlds/robotino3.wbt
- projects/robots/pal_robotics/tiago++/worlds/tiago++.wbt
- projects/robots/pal_robotics/tiago_base/worlds/tiago_base.wbt
- projects/robots/pal_robotics/tiago_extensions/protos/TiagoFrontArm.proto
- projects/robots/pal_robotics/tiago_extensions/protos/TiagoLeftArm.proto
- projects/robots/pal_robotics/tiago_extensions/protos/TiagoRightArm.proto
- projects/robots/pal_robotics/tiago_iron/worlds/tiago_iron.wbt
- projects/robots/pal_robotics/tiago_steel/worlds/tiago_steel.wbt
- projects/robots/pal_robotics/tiago_titanium/worlds/tiago_titanium.wbt
This PR implements various minor fixes + improvements.
> Various Fixes

- docs/reference/changelog-r2020.md
> Update release date in ChangeLog

- projects/robots/softbank/nao/controllers/nao_demo/nao_demo.c
Follow-up of https://github.com/cyberbotics/webots/pull/1208#pullrequestreview-333170608
> Improve Nao Controller Messages

- docs/guide/mavic-2-pro.md
Remove path based on revision branch.
> Fix path to mavic worlds

- src/packaging/webots_distro.c
Fix libssl and libcrypto symlinks.
> Fix libssl and libcrypto symlinks.

- Contents/Info.plist
- docs/js/showdown-extensions.js
- resources/version.txt
- src/packaging/webots_version.txt
- src/webots/core/WbApplicationInfo.cpp
> Update version to R2020a-rev1

- docs/reference/changelog-r2020.md
- projects/robots/abb/irb/protos/Irb4600-40.proto
> Fix abb default controller

- docs/guide/installation-procedure.md
Fixed and simplified installation instructions.
> Fixed installation instructions

- tests/sources/test_icons.py
The tests are sometimes failing with Python3 because of unclosed files.
> Fixed unclosed files in test.

- .travis.yml
> Fix nightly from master

- .travis.yml
> Extend Travis Tests.

- projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/e-puck/EPuckFacade.cpp
- projects/robots/mobsya/thymio/controllers/thymio2_demo/thymio2_demo.c
- projects/samples/curriculum/controllers/advanced_slam_2/advanced_slam_2.c
- src/lib/Controller/api/camera.c
- src/lib/Controller/api/supervisor.c
- src/lib/Controller/api/system.c
- src/webots/nodes/WbBallJoint.cpp
- src/webots/nodes/WbBaseNode.cpp
- src/webots/nodes/utils/WbNodeOperations.cpp
- src/webots/vrml/WbProtoList.hpp
- src/webots/vrml/WbProtoModel.hpp
- src/wren/StaticMesh.cpp
- tests/sources/test_cppcheck.py
> Fix cppcheck errors

- src/webots/nodes/WbBaseNode.cpp
> Fix Webots Compilation

- .travis.yml
Avoid many useless lines in the log: https://travis-ci.com/cyberbotics/webots/jobs/273197344#L280
> Fix Travis Output

- docs/automobile/sumo-interface.md
- docs/reference/changelog-r2020.md
- projects/default/controllers/sumo_supervisor/SumoSupervisor.py
- projects/default/controllers/sumo_supervisor/sumo_supervisor.py
- projects/vehicles/worlds/sumo_interface_example_net/plugin.py
> Add SUMO_HOME support.

- dependencies/Makefile.linux
- dependencies/Makefile.mac
> Cleanup dependencies urls.

- dependencies/Makefile.linux
- dependencies/Makefile.mac
- docs/guide/samples-howto.md
- docs/reference/changelog-r2020.md
- include/.gitignore
- projects/samples/howto/controllers/Makefile
- projects/samples/howto/controllers/vision/Makefile
- projects/samples/howto/controllers/vision/vision.cpp
- src/install_scripts/msys64_installer.sh
- src/packaging/copy_msys64_files.py
- src/packaging/files_core.txt
- src/packaging/files_msys64.txt
- src/packaging/webots_distro.c
> Remove OpenCV

- projects/default/libraries/Makefile
- projects/default/resources/Makefile
These makefiles where not removing the archive once downloaded and exctracted (worse the archive was included in the release).
> Fixed SUMO and ROS dependencies makefiles.

- docs/guide/modeling.md
> Fix field name responsible for the ODE number of threads

- projects/default/controllers/ros/include/Makefile
- projects/default/libraries/Makefile
- projects/default/resources/Makefile
- projects/robots/gctronic/e-puck/transfer/Makefile
> Replaced curl with more robust wget

- docs/guide/pioneer-3at.md
- docs/guide/pioneer-3dx.md
Changes can be viewed:
* [File: doc/guide/pioneer-3at.md](https://cyberbotics.com/doc/guide/pioneer-3at?version=michou214:doc-update-pioneer-link-reference)
* [File: doc/guide/pioneer-3dx.md](https://cyberbotics.com/doc/guide/pioneer-3dx?version=michou214:doc-update-pioneer-link-reference)
> Doc - Update reference links of Pioneer 3-AT and 3-DX

- docs/reference/changelog-r2020.md
> Set Release Date

- resources/translations/wb_de.ts
- resources/translations/wb_es.ts
- resources/translations/wb_fr.ts
- resources/translations/wb_generic.ts
- resources/translations/wb_it.ts
- resources/translations/wb_ja_JP.ts
- resources/translations/wb_zh_CN.ts
This should have been done in the previous release.
> Update the translation files.

- projects/samples/devices/controllers/range_finder/range_finder.c
> Fix Range-Finder Sample.

- src/packaging/files_msys64.txt
Fix https://github.com/cyberbotics/webots/issues/1261#issuecomment-574110966
> Fix LUA GD on Windows

- Contents/Info.plist
- docs/js/showdown-extensions.js
- resources/version.txt
- src/packaging/webots_version.txt
- src/webots/core/WbApplicationInfo.cpp
> Update Webots Version.

- docs/reference/supervisor.md
A user reported that this was not clear in the documentation.
> Improve Supervisor set/get Velocity function

- docs/reference/motor.md
- docs/reference/positionsensor.md
> Added missing units to parameter descriptions

- src/lib/Controller/api/robot_private.h
> Removed undefined function

- scripts/web_component_studio/web_component_studio.py
Fixes #1155
https://stackoverflow.com/questions/42694112/when-using-pathlib-getting-error-typeerror-invalid-file-posixpathexample-t?answertab=oldest#tab-top
> Improve Web Component Studio to Support Python3.5

- projects/robots/robotis/darwin-op/controllers/soccer/runtime.ini
This soccer vision library doesn't exist anymore.
> Remove Useless Runtime.ini File

- projects/appearances/protos/Soil.proto
- projects/objects/rocks/protos/Rock10cm.proto
- projects/objects/rocks/protos/Rock17cm.proto
- projects/robots/nasa/worlds/sojourner.wbt
Fix #1269.
Before this PR:
After this PR:
> Fixed red planet color

- docs/automobile/driver-library.md
- docs/guide/robotis-op2.md
- docs/guide/tutorial-5-compound-solid-and-physics-attributes.md
- docs/reference/accelerometer.md
- docs/reference/changelog-5.md
- docs/reference/connector.md
- docs/reference/differentialwheels.md
- docs/reference/fluid.md
- docs/reference/immersionproperties.md
- docs/reference/lightsensor.md
- docs/reference/linearmotor.md
- docs/reference/motor.md
- docs/reference/physics.md
- docs/reference/positionsensor.md
- docs/reference/receiver.md
- docs/reference/rotationalmotor.md
- docs/reference/spotlight.md
- docs/reference/touchsensor.md
Addressing #1260.
I also cleaned-up a little bit the way units are presented.
> Fix missing units

- .github/ISSUE_TEMPLATE/config.yml
- .github/pull_request_template.md
This PR template is recommended by Github (see https://github.com/cyberbotics/webots/community)
> Add a Pull-Request Template

- docs/guide/running-extern-robot-controllers.md
This issue was reported by a user: https://stackoverflow.com/questions/59840278/running-an-external-python-controller-from-console#comment105846278_59856562
> Fix macOs extern controller doc

- .travis.yml
- docs/guide/using-python.md
- docs/reference/changelog-r2020.md
- resources/languages/Makefile
- resources/languages/python/Makefile
- src/packaging/files_core.txt
> Add python3.8 macOS Support.

- src/packaging/copy_msys64_files.py
Flake8 doesn't like naming a variable `l`...
> Fixed flake8 warnings

- tests/sources/test_pep8.py
> Fix PEP8 Test Failure

- docs/reference/changelog-r2020.md
- src/webots/app/WbProtoCachedInfo.cpp
- src/webots/app/WbProtoCachedInfo.hpp
- src/webots/scene_tree/WbAddNodeDialog.cpp
Webots wont import proto with connector as child.
This pull-request attempts to fix issue  #1316
> Fixed Importation of Connectors in PROTO.

- docs/guide/telemetry.md
> Documentation: fix typos in telemetry page

- CONTRIBUTING.md
> Invite new contributors to address beginner issues

- docs/css/webots-doc.css
- docs/js/viewer.js
Minor adjustments to fix:
Preview: https://www.cyberbotics.com/doc/reference/accelerometer?version=hotfix-webots-doc-css
> Hotfix webots-doc.css

- src/lib/Controller/api/display.c
- src/webots/nodes/WbDisplay.cpp
Fix Display Compilation Warning
> Fix Display Compilation Warning

- docs/guide/thymio2.md
> Fix misspelling in the Thymio brandname

- lib/controller/matlab/WB_IMAGE_ABGR.m
The `mgenerate.py` file was correctly updated but not called.
> Add Missing WB_IMAGE_ABGR.m file

- docs/guide/robotino3.md
Update the Robotino 3 documentation
[Modification visible here](https://cyberbotics.com/doc/guide/robotino3?version=michou214-patch-1)
> Add an important remark for user

- .gitignore
Remove signature from gitignore
> Remove signature from gitignore

- docs/guide/ure.md
- docs/reference/changelog-r2020.md
Added Supervisor Field to Universal Robots
> Added Supervisor Field to Universal Robots

- docs/guide/tutorial-7-your-first-proto.md
As users are 'often' copy-pasting this solution without reading the text it is better to let the 'solution' works even if not complete.
> Improve PROTO tutorial

- resources/web/wwi/Makefile
This condition was doing the exact opposite of what it is supposed to do.
> Fix wwi make cleanse

- projects/default/libraries/vehicle/Makefile
- projects/default/libraries/vehicle/python/Makefile
- projects/robots/robotis/darwin-op/libraries/Makefile
- projects/robots/robotis/darwin-op/libraries/python/Makefile
Fix Missing Python3.8 Libraries on Windows
> Fix Missing Python3.8 Libraries on Windows

- resources/web/server/kill_old_webots_instances.py
- src/packaging/files_core.txt
Fix time comparison in `kill_old_webots_instances.py` and add script in the Webots package.
> Fix kill_old_webots_instances.py

- .travis.yml
Fix the Travis release rule.
https://github.com/cyberbotics/webots/issues/1159#issuecomment-586874137
> Fix Travis Release

- docs/reference/changelog-r2020.md
> Updated change log

- src/webots/user_commands/WbActionManager.cpp
> Fix Reset Simulation Tooltip

- docs/reference/changelog-r2020.md
I forget the changelog in #1378 (I think this is wrose mentionning).
> Fix Missing Changelog Entry

- docs/guide/running-extern-robot-controllers.md
- projects/vehicles/importer_demo.sh
Similar to #1392 other paths were wrong for macOS.
> Fix Webots application paths on mac.

- docs/guide/running-extern-robot-controllers.md
- docs/guide/using-your-ide.md
> Fixed PyCharm documentation

- docs/reference/supervisor.md
The reset is actually applied at the end of the step and not immediately.
> Fix wb_supervisor_simulation_reset doc

- projects/robots/universal_robots/resources/ros_package/ur_e_webots/README.md
This PR adds to the README all the required steps to start the simulation, control the robot with RVIZ and use RViz to send MoveIt! commands.
>  Improve Universal Robot ROS README 

- docs/reference/changelog-r2020.md
- projects/robots/universal_robots/controllers/universal_robots_ros/joint_state_publisher.py
- projects/robots/universal_robots/controllers/universal_robots_ros/trajectory_follower.py
- projects/robots/universal_robots/controllers/universal_robots_ros/universal_robots_ros.py
- projects/robots/universal_robots/resources/ros_package/ur_e_webots/README.md
> Fix/Improve UR robots ROS support

- docs/reference/changelog-r2018.md
Fixed a wrong line in the change log of Webots R2018.
> Fixed status of naoqisim

- projects/default/controllers/sumo_supervisor/SumoSupervisor.py
- projects/samples/robotbenchmark/visual_tracking/controllers/visual_tracking/visual_tracking.py
- resources/web/server/kill_old_webots_instances.py
- resources/web/server/session_server.py
- resources/web/server/simulation_server.py
- src/packaging/generate_projects_files.py
- src/packaging/publish_release.py
> Fix Misc Python Issues

- src/packaging/exist_in_projects_linux.txt
- src/packaging/exist_in_projects_mac.txt
Fixes problem introduced in #1426 and causing the nightly builds to fails on Linux and macOS: https://travis-ci.com/cyberbotics/webots-snap/jobs/294143033
> Attempt to fix travis nightly builds on Linux and macOS

- docs/reference/contactproperties.md
> Fixed English

- docs/reference/changelog-r2020.md
Add a changelog entry for #1448.
> Hotfix Missing Changelog Entry

- docs/reference/changelog-r2020.md
- src/webots/nodes/WbIndexedLineSet.cpp
This pull-request fixes issue #1443
> Add condition to protect IndexedLineSet when no coord

- docs/guide/using-numerical-optimization-methods.md
Improve the `Using Numerical Optimization Methods` documentation page to include the new `wb_supervisor_world_reset-function` function.
https://www.cyberbotics.com/doc/guide/using-numerical-optimization-methods?version=enhancement-optimization-doc#using-the-wb_supervisor_world_reset-function
> Improve the Using Numerical Optimization Methods Documentation

- docs/reference/supervisor.md
A user reported that this was not clear.
> Improve wb_supervisor_node_get_velocity doc

- docs/guide/tiagopp.md
Add Video to Tiago Doc
https://cyberbotics.com/doc/guide/tiagopp?version=enhancement-tiago-doc
> Add Video to Tiago Doc

- docs/reference/changelog-r2020.md
- include/wren/static_mesh.h
- src/webots/nodes/WbGeometry.cpp
- src/webots/nodes/WbGeometry.hpp
- src/webots/scene_tree/WbNodeEditor.cpp
- src/webots/scene_tree/WbNodeEditor.hpp
- src/wren/StaticMesh.cpp
Geometry node now displays the triangle count for its element.
This pull-request fixes issue #1323
> Enhancement display triangles geometry node

- docs/reference/changelog-r2020.md
From R2020b we decided to put a link to the PR un the changelog.
> Fix R2020b Changelog

- docs/guide/using-matlab.md
- docs/reference/changelog-r2020.md
- lib/controller/matlab/launcher.m
> Fix MATLAB launcher

- docs/reference/changelog-r2020.md
I think this PR deserves an entry in the changelog as it might be important for the user (it may break backward compatibility): #1304
This was already reported by a user using the nightlies: #1460
> Add Missing Changelog Entry

- docs/reference/robot.md
- docs/reference/supervisor.md
Improves the [Robot](https://cyberbotics.com/doc/reference/robot?version=fix-robot-docs) and [Supervisor](https://cyberbotics.com/doc/reference/supervisor?version=fix-robot-docs) documentation pages.
> Fixes Robot documentation

- docs/reference/changelog-r2020.md
- src/webots/nodes/WbInertialUnit.cpp
This pull-request fixes issue #1409
> Default Y value for gravity now equals 1.0

- docs/reference/changelog-r2020.md
- projects/objects/factory/conveyors/protos/ConveyorBelt.proto
- projects/objects/factory/conveyors/protos/ConveyorPlatform.proto
- projects/robots/neuronics/ipr/worlds/ipr_factory.wbt
- projects/robots/universal_robots/worlds/ure.wbt
- projects/samples/devices/worlds/sick_point_cloud.wbt
- projects/samples/devices/worlds/track.wbt
- projects/samples/robotbenchmark/pick_and_place/worlds/pick_and_place.wbt
- src/webots/nodes/WbTrack.cpp
- tests/api/worlds/track.wbt
This will try to make the Track TextureAnimation field a bit more transparent to the user.
> Fix track texture animation field

- docs/guide/supervisor-programming.md
We should encourage users to make a physics reset after moving robots as we know that without the reset it can lead to physic instabilities.
> Improve supervisor-programming doc

- docs/reference/mesh.md
- resources/nodes/Mesh.wrl
- src/webots/scene_tree/WbExtendedStringEditor.cpp
This PR updates the Mesh node according to #1463 to support the same file formats.
> Update Mesh Node Supported Formats

- .travis.yml
- docs/guide/supervisor-programming.md
- src/lib/Controller/api/supervisor.c
- tests/sources/generate_diff.py
No conflicts but manual edition in 64dfe22.
> Merge master into develop

- projects/objects/factory/conveyors/protos/ConveyorPlatform.proto
Attempt to fix #1483
@remi-cyberbotics since I am not able to reproduce the issue, can you please check if this fixes the issue?
> Attempt to Fix ConveyorPlatform

- docs/reference/changelog-r2020.md
- projects/samples/devices/worlds/track.wbt
- src/webots/nodes/WbTrack.cpp
> Fix crash with track texture animation

- projects/robots/universal_robots/resources/ros_package/ur_e_webots/README.md
> Fix Universal Robot Documented Launch Files.

- projects/samples/robotbenchmark/square_path/plugins/robot_windows/square_path/square_path.html
A user reported this documentation bug.
> Fix wrong sensor name

- docs/guide/system-requirements.md
Supported OS fix/update related documentation.
https://cyberbotics.com/doc/guide/system-requirements?version=fix-doc-supported-os
> Update System Requirements Doc

- docs/guide/supervisor-programming.md
Add examples in different programming languages into supervisor documentation.
This pull-request fixes issue #1498 
https://cyberbotics.com/doc/guide/supervisor-programming?version=enhancement-translate-supervisor-doc-samples#tracking-the-position-of-robots
> Translate Supervisor Samples in Doc to other API

- docs/automobile/driver-library.md
> Fix Doc about Electric Motors

- src/packaging/files_core.txt
This file was renamed in #1554.
> Fix Packaging

- docs/reference/changelog-r2020.md
- src/webots/app/WbSelection.cpp
This PR fixes the bug mentioned and closes issue #1545
> hotfix-no-resize-handles-on-use-node

- docs/guide/the-user-interface.md
- docs/reference/mesh.md
- src/webots/gui/WbImportWizard.cpp
> Fix docs typo

- docs/reference/changelog-r2020.md
- projects/default/controllers/ros/RosMotorSensor.cpp
- projects/default/controllers/ros/RosMotorSensor.hpp
- projects/languages/ros/webots_ros/src/complete_test.cpp
The motor torque/force feedback was not working in the ros controller.
This pull-request fixes issue cyberbotics/webots_ros#16
> Simplify and fix ROS motor feedback.

- src/webots/Makefile
- src/webots/launcher/launcher.c
At some point the Windows launchers were failing on machine but I could not understand why. Now they are working fine again and I don't understand why, but I cannot debug any more what was the problem. So, I introduced a better error reporting in these launchers to be able to better understand the problem whenever it strikes back.
> Fixed Windows launchers

- .travis.yml
- src/webots/launcher/launcher.c
- tests/sources/generate_diff.py
Attempt to understand and fix #1589.
> Improve generate_diff.py

- src/webots/launcher/launcher.c
> Fix cppcheck warning

- src/webots/Makefile
- src/webots/launcher/launcher.c
Added more checks when compiling launcher.c and fixed some warning.
> Display more warnings when compiling launcher.c

- docs/guide/epuck.md
- projects/robots/gctronic/e-puck/protos/E-puck.proto
- projects/robots/gctronic/e-puck/protos/E-puckDistanceSensor.proto
Models the distance sensors better (most noticeably ToF) ~~and allows configurable aperture~~.
Fixes #1574
**Tasks**
> Add aperture to ToF sensor

- src/webots/launcher/launcher.c
A problem with the new binary launcher on Windows was that when the `webots.exe` launcher was killed (for example by the `simulation_server.py`), the `webots-bin.exe` was not killed. This PR fixes that problem.
> Kill webots-bin.exe whenever webots.exe (resp. webotsw.exe) is killed

- docs/guide/installation-procedure.md
> Improve the snap documentation

- src/webots/gui/WbStreamingServer.cpp
- src/webots/nodes/utils/WbNodeOperations.cpp
- src/webots/vrml/WbNode.cpp
- src/webots/vrml/WbNode.hpp
> Fix streaming crash

- docs/guide/spot.md
This PR adds the video of the spot robot to the corresponding doc: https://cyberbotics.com/doc/guide/spot?version=add-spot-movie-to-doc
> Add Spot Movie to Docs

- docs/reference/changelog-r2020.md
- src/webots/nodes/WbLidar.cpp
Rotating Lidars were not reset correctly.
This pull-request fixes issue #1624
> Fix Lidar Reset

- src/webots/nodes/utils/WbUrl.cpp
> Code cleanup

- src/lib/Controller/api/remote_control.c
That should ease debugging problems like #1625.
> Improved error messages for remote control library

- docs/guide/using-your-ide.md
Added bullets
Description
A new user might find bullets much comfortable while reading the points under instructions.
link:https://cyberbotics.com/doc/guide/using-your-ide?version=chaytanyasinha:master
Related Issues
This pull-request fixes issue cyberbotics#1671
> Added bullets

- docs/reference/troubleshooting.md
> Fix Debugging Doc Pathes

- src/packaging/files_core.txt
- src/packaging/webots_distro.c
> Fix MacOS Packaging

- docs/guide/debugging-c-cpp-controllers.md
- docs/guide/using-your-ide.md
Makes just a few minor changes to the documentation.
**Tasks**
1. Minor changes in the initial few lines .
2. Adding the word "defunct".
3. Providing a sequence to the final steps.
4. On the page "Using Your IDE" : 'Therefore' is mentioned as 'Thefore'
1. This PR changes the following page of the documentation:
https://cyberbotics.com/doc/guide/debugging-c-cpp-controllers
{ For the first 3 tasks}
2. This PR also changes the following page of documentation:
https://cyberbotics.com/doc/guide/using-your-ide?tab-language=c
{ With regard to the 4th task}
> Minor changes to the documentation

- docs/guide/controller-programming.md
Fixes #1674. See: https://cyberbotics.com/doc/guide/controller-programming?version=hotfix-improve-controller-termination-doc#controller-termination
> Improve controller termination documentation

- docs/guide/controller-start-up.md
Reverts cyberbotics/webots#1692
> Revert "Update controller-start-up.md:- Corrects a few grammatical errors"

- src/webots/gui/WbMultimediaStreamingLimiter.cpp
- src/webots/gui/WbMultimediaStreamingLimiter.hpp
Fix compilation issues on mac introduced in  #1352
> Fix Mac Compilation

- docs/reference/node-chart.md
> Fixed small typo

- src/webots/gui/WbMultimediaStreamingServer.cpp
> Fixed another Qt5.15 warning

- docs/reference/changelog-r2020.md
- src/webots/app/WbContactPointsRepresentation.cpp
> Fix contact point representation update

- tests/command.py
- tests/default/controllers/test_suite_supervisor/test_suite_supervisor.py
- tests/test_suite.py
The PR improves the test suite to make it location independant, the 'test' folder doesn't have anymore to be located in the 'webots' folder it can be located anywhere, this way it is possible for example to test with another version of Webots than the one of its development environment.
It also add support for Github actions.
I did this while testing the Github Actions and I think it is worth integrating these changes as it just makes the test suite more robust.
> Improve Test Suite Robustness

- docs/reference/propeller.md
This PR improves the documentation of the propeller following some user questions about it.
> Improve propeller documentation

- src/webots/gui/WbStreamingServer.cpp
This warning was caused by merge issue in #1752
> Fix compilation warning

- docs/reference/changelog-r2020.md
> Remove outdated log entry

- docs/reference/motor.md
The use of PID was not very clear in the motor doc.
> Improved motor PID control table.

- .travis.yml
- tests/api/controllers/robot_urdf/.gitignore
- tests/api/controllers/robot_urdf/robot_urdf.c
Fix various issues with the URDF test.
> Fix urdf test

- docs/guide/robotis-op2.md
- docs/guide/robotis-op3.md
- docs/reference/changelog-r2020.md
- projects/robots/robotis/darwin-op/protos/RobotisOp2.proto
- projects/robots/robotis/darwin-op/protos/RobotisOp3.proto
Add missing Robotis-op 2 and 3 supervisor field.
> Add missign Robotis-op2 supervisor field.

- .appveyor-build-tag.yml
- .appveyor-build.yml
- .appveyor-test-sources-scheduled.yml
Fixes #1696.
Revert #1689 which is not needed any more.
> Removed unneeded appveyor patch

- docs/reference/camera.md
- docs/reference/differentialwheels.md
> Fixed noise description

- docs/reference/changelog-r2020.md
- docs/reference/motor.md
- docs/reference/robot.md
- src/webots/nodes/WbLinearMotor.cpp
- src/webots/nodes/WbMotor.cpp
- src/webots/nodes/WbRobot.cpp
- tests/api/controllers/battery_empty/.gitignore
- tests/api/controllers/battery_empty/Makefile
- tests/api/controllers/battery_empty/battery_empty.c
- tests/api/worlds/battery.wbt
> Fix Various Battery Issues

- src/webots/nodes/WbRobot.cpp
- src/webots/nodes/WbRobot.hpp
I studied the possible side effects of this patch and I am pretty confident there is no side effect.
I tested this patch against the test suite on Windows and found no problem.
> Simpler patch for camera reset bug

- projects/objects/road/protos/Crossroad.proto
simply add a recognition color to crossRoad.proto
> correction of Bug https://github.com/cyberbotics/webots/issues/1810

- docs/js/showdown-extensions.js
- docs/reference/supervisor.md
Add a short tutorial to supervisor.md, under the getPosition function. Explaining how to get the position and orientation of any node relative to another. 
https://cyberbotics.com/doc/guide/getting-started-with-webots?version=develop
If this pull-request includes any new robots/simulations/etc. add one or more screenshots of the result.
Add any other context about the pull-request here.
> supervisor.md tutorial pos/rot relative to other nodes

- .github/workflows/tests_doc.yml
This PR creates a Github action workflow that runs the test doc at each commit/pull request.
For now, for a transitional test period, the test will be duplicated with the Travis/Appveyor ones (but this will not hurt).
Tests output: https://github.com/cyberbotics/webots/actions/runs/143575802
> Add Github Action Doc Test

- tests/test_suite.py
> Simplify test_suite.py

- docs/reference/changelog-r2020.md
- src/webots/nodes/WbIndexedFaceSet.cpp
- src/webots/nodes/utils/WbTriangleMesh.cpp
- tests/rendering/protos/IndexedFaceSetWithNormals.proto
- tests/rendering/worlds/normals.wbt
> Fix Crash with Normals

- docs/reference/camera.md
- docs/reference/rangefinder.md
This formula was changed a long time ago: https://github.com/cyberbotics/webots/blob/8f961d31a216ee2ad62e57623aedd36fccace592/src/webots/wren/WbWrenCamera.cpp#L515
new doc: https://www.cyberbotics.com/doc/reference/camera?version=fix-camera-doc#field-summary
> Fix camera/rangefinder vertical field of view doc

- docs/reference/solidreference.md
Added a mechanical loop example in [this page](https://cyberbotics.com/doc/reference/solidreference).
This pull-request fixes issue #1818 
**Tasks**
https://cyberbotics.com/doc/guide/getting-started-with-webots?version=develop
https://cyberbotics.com/doc/reference/solidreference?version=master
If this pull-request includes any new robots/simulations/etc. add one or more screenshots of the result.
Add any other context about the pull-request here.
> docs: add a mechanical loop example

- .github/workflows/test_suite.yml
> Remove Useless Test Suite Workflow Step

- docs/guide/preferences.md
- docs/reference/changelog-r2020.md
- src/webots/core/WbPreferences.cpp
- src/webots/gui/WbGuiApplication.cpp
- src/webots/gui/WbPreferencesDialog.cpp
- src/webots/gui/WbPreferencesDialog.hpp
- src/webots/gui/WbView3D.cpp
- src/webots/nodes/WbImageTexture.cpp
- src/webots/nodes/WbImageTexture.hpp
Fix :
- #1830
- limit filtering to 5 as documented.
> Fix Texture Filtering Field auto-changed.

- .github/workflows/test_suite.yml
- projects/robots/festo/robotino3/worlds/robotino3.wbt
This PR add the test about world update in the `Test Suite` workflow.
> Test World Update

- docs/reference/changelog-r2020.md
Merge R2020a rev2 and R2020b change logs and add links to PRs for the R2020a rev2 entries.
> Merge R2020b changelog

- src/webots/nodes/WbBox.cpp
> Fixed outline offset for boxes

- src/webots/app/WbPerspective.cpp
Should have been removed in #1856
> Fix Remaining WEBOTS_DISABLE_SAVE_PERSPECTIVE_ON_CLOSE

- projects/default/controllers/ros/runtime.ini
- projects/vehicles/controllers/ros_automobile/runtime.ini
These runtime files are raising some warnings (introduced in #1440).
> Fix runtime.ini Pathes

- docs/guide/tutorial-8-using-ros.md
> Enhancement webots_ros installation instructions

- .github/workflows/test_suite.yml
I missed the second step of the test in #1893.
> Fix test Workflow

- projects/objects/factory/conveyors/protos/ConveyorBelt.proto
- projects/objects/factory/conveyors/protos/ConveyorPlatform.proto
- projects/samples/robotbenchmark/inverted_pendulum/protos/InvertedPendulumBenchmark.proto
- projects/samples/robotbenchmark/visual_tracking/protos/VisualTrackingBenchmark.proto
- tests/protos/protos/TemplateRobot.proto
The backward compatibility feature was not working on these PROTO files because the header version was preventing the backward compatibility mechanism.
This pull-request fixes issue #1896
> Fix not updated PROTO.

- docs/reference/changelog-r2020.md
Minor consistency issue in change log.
> Small typo in change log

- docs/automobile/introduction.md
List the main sponsors who contributed to develop the Webots for automobile software.
You can review it at https://cyberbotics.com/doc/automobile/introduction?version=doc-automobile-sponsors
> Added main sponsors of Webots for Automobile

- docs/automobile/introduction.md
> Removed odd-looking double dots

- projects/robots/boston_dynamics/spot/worlds/spot.wbt
Improve spot world description and title.
This pull-request fixes issue #1848
> Improve Spot World Description

- docs/guide/samples-devices.md
- docs/reference/changelog-r2020.md
- projects/samples/devices/controllers/sample_supervisor/sample_supervisor.c
Improve Supervisor sample.
This pull-request fixes issue #1612.
Replaces #1691.
> Improve Supervsior Sample

- docs/guide/modeling.md
> Fixed reproducibility documentation

- src/lib/Controller/api/robot_private.h
> Fixed libController assertion failures in release mode

- docs/reference/changelog-r2020.md
- src/webots/nodes/WbBackground.cpp
> Fixed Background VRML Export.

- .github/workflows/test_suite.yml
The goal of this PR is to upload the generated Ubuntu 20.04 package to the Github release.
> Improve Workflow to Upload 20.04 Release

- .github/workflows/test_suite.yml
Some dependencies of publish_release.py were missing.
> Add missing python module to workflow

- src/packaging/publish_release.py
This script was not working if `WEBOTS_HOME` was not defined: https://github.com/cyberbotics/webots/runs/889079866?check_suite_focus=true#step:9:83
> Improve publish_release Script

- docs/reference/balljoint.md
> Fix typo in BallJoint doc

- src/packaging/publish_release.py
I forget one level of hierarchy in my previous PR (#1940): https://github.com/cyberbotics/webots/runs/889637083?check_suite_focus=true#step:9:86
> Fix publish_release script

- src/lib/Controller/Makefile
Fix macOS libController build
This pull-request fixes issue #1945
> Fix macOS libController build

- docs/reference/changelog-r2020.md
- src/webots/nodes/utils/WbSupervisorUtilities.cpp
- tests/api/controllers/supervisor_force_torque/supervisor_force_torque.c
The supervisor add force/torque functions were not working when the solid was disabled.
This pull-request fixes issue #1942
> Fix Supervisor Add Force/Torque

- tests/api/controllers/accelerometer/accelerometer.c
- tests/api/worlds/accelerometer.wbt
Better test for the accelerometer device, inspired from #1693.
> Better accelerometer test

- src/lib/Controller/Makefile
The fix of #1948 was unfortunately not working on Windows.
> Fix libController Makefile

- docs/reference/connector.md
- docs/reference/node-chart.md
> Document insertion rules

- docs/reference/changelog-r2020.md
- src/webots/engine/WbAnimationRecorder.cpp
> Fixed crash on reverting the world while recording an animation

- src/packaging/publish_release.py
Fix upload of nightly build from GithHub Actions.
> Fix upload of nightly packages.

- resources/languages/python/controller.i
Fix Python 2.7 ANSI Codes.
This pull-request fixes issue #1980
> Fix Python 2.7 ANSI Codes.

- docs/discord/development.md
- docs/discord/documentation.md
- docs/discord/technical-questions.md
Following up #1962, this PR reverts the manual changes in the Discord pages which will cause conflicts on the next Discord PR.
> Reverted manual changes on Discord pages

- projects/robots/gctronic/e-puck/plugins/robot_windows/e-puck/e-puck.c
Fix e-puck robot window error message on Enable All.
This pull-request fixes issue #1983
> Fix E-Puck Robot-Window

- projects/vehicles/worlds/CH_Morges.wbt
> Update CH_Morges world

- src/webots/nodes/WbWorldInfo.cpp
- src/webots/vrml/WbParser.cpp
> Fix backwards compatibility

- src/webots/nodes/WbAccelerometer.cpp
- src/webots/nodes/WbAccelerometer.hpp
> Fixed accelerometer warning and return value

- projects/default/controllers/sumo_supervisor/Objects.py
This pull-request fixes issue #1999
No checngelog entry because nevere released.
> Fix invalid texture paramter of TruckTrailer PROTO inserted by SumoInterface

- projects/robots/neuronics/ipr/libraries/ipr/IPR.cpp
- projects/robots/saeon/controllers/vehicle_driver_altino/vehicle_driver_altino.py
- projects/samples/curriculum/controllers/beginner_better_collision_avoidance_algorithm/runtime.ini
- projects/samples/curriculum/controllers/beginner_blinking_e-puck/runtime.ini
- projects/samples/curriculum/controllers/beginner_e-puck_dance/runtime.ini
- projects/samples/curriculum/controllers/beginner_finite_state_machine/runtime.ini
- projects/samples/curriculum/controllers/beginner_linear_camera/runtime.ini
- projects/samples/curriculum/controllers/beginner_move_your_e-puck/runtime.ini
- projects/samples/curriculum/controllers/beginner_rally/runtime.ini
- projects/samples/curriculum/controllers/novice_remain_in_shadow/runtime.ini
- projects/samples/curriculum/controllers/novice_train/runtime.ini
Fix some issues reported in #1966:
> Fix various world errors and warnings

- projects/default/libraries/vehicle/python/vehicle.i
- projects/robots/robotis/darwin-op/libraries/python/managers.i
- projects/samples/robotbenchmark/humanoid_marathon/controllers/marathon/runtime.ini
> Fixed Python 3.8 vehicle library which was broken on Windows

- projects/languages/ros/webots_ros/worlds/catch_the_bird.wbt
- projects/languages/ros/webots_ros/worlds/complete_test.wbt
- projects/languages/ros/webots_ros/worlds/e-puck_line.wbt
- projects/languages/ros/webots_ros/worlds/keyboard_teleop.wbt
- projects/languages/ros/webots_ros/worlds/panoramic_view_recorder.wbt
- projects/languages/ros/webots_ros/worlds/pioneer3at.wbt
- projects/languages/ros/webots_ros/worlds/ros_python.wbt
> Fixed ROS worlds

- src/webots/wren/WbWrenRenderingContext.cpp
- src/webots/wren/WbWrenRenderingContext.hpp
This pull-request fixes issue #1969
> Fix Laser DistanceSensors

- src/webots/gui/WbGuiApplication.cpp
- src/webots/gui/WbGuiApplication.hpp
- src/webots/gui/WbMultimediaStreamingServer.cpp
- src/webots/gui/WbMultimediaStreamingServer.hpp
- src/webots/gui/WbStreamingServer.cpp
- src/webots/gui/WbStreamingServer.hpp
- src/webots/gui/WbX3dStreamingServer.cpp
- src/webots/gui/WbX3dStreamingServer.hpp
Fixes #1981, by providing an error in Webots console.
Closes #1981
> Notify user if stream mode is not valid

- docs/reference/changelog-r2020.md
- docs/reference/supervisor.md
- src/webots/nodes/utils/WbSupervisorUtilities.cpp
- src/webots/nodes/utils/WbSupervisorUtilities.hpp
- tests/api/controllers/supervisor_import_remove/supervisor_import_remove.c
- tests/api/controllers/supervisor_remove_self/.gitignore
- tests/api/controllers/supervisor_remove_self/Makefile
- tests/api/controllers/supervisor_remove_self/supervisor_remove_self.c
- tests/api/worlds/supervisor_import_remove.wbt
This pull-request fixes issue #1996
**Tasks**
> Fix supervisor.getSelf().remove() crash

- .appveyor-build-tag.yml
- .appveyor-build.yml
- .appveyor-test-sources-scheduled.yml
It seems to [work](https://github.com/cyberbotics/webots/releases/tag/untagged-d9524e4b5bee06f7a33e).
See build [here](https://ci.appveyor.com/project/omichel/webots-9ufow/builds/34338179).
> Attempt to fix appveyor build

- docs/guide/general-bugs.md
Closes #1982
https://www.cyberbotics.com/doc/guide/general-bugs?version=doc-virtualbox
> Add usage VirtualBox notice

- docs/guide/installation-procedure.md
- docs/guide/system-requirements.md
- docs/guide/using-python.md
- docs/reference/changelog-r2020.md
Ubuntu 20.04 is not mentioned in the documentation.
> Update latest Ubuntu LTS in documentation

- docs/blog/Webots-2020-b-release.md
- docs/reference/changelog-r2020.md
> Updated release date

- .github/workflows/test_suite.yml
- .travis.yml
Rename the `webots-R2020b-x86-64_ubuntu-20.04.tar.bz2` into `webots-R2020b-x86-64.tar.bz2` and the `webots-R2020b-x86-64.tar.bz2` package into `webots-R2020b-x86-64_ubuntu-16.04.tar.bz2`.
> Rename Ubuntu Archive Package

- Contents/Info.plist
- docs/js/showdown-extensions.js
- resources/version.txt
- src/packaging/webots_version.txt
- src/webots/core/WbApplicationInfo.cpp
> Update Webots Version

- docs/guide/running-extern-robot-controllers.md
> Fix Windows Extern Controller Doc

- tests/api/controllers/radar_relative_speed/radar_relative_speed.c
The wrong assert function was used since it need double comparison.
> Fix Radar Relative Speed Test

- .github/workflows/test_suite.yml
Minor improvements to the Github workflows to speed up the tests.
> Remove Workflow Useless Step

- docs/reference/changelog-r2020.md
- projects/robots/festo/robotino3/protos/Robotino3Webcam.proto
- projects/robots/festo/robotino3/worlds/robotino3.wbt
> Fix Robotino3

- docs/reference/changelog-r2020.md
- projects/robots/abb/irb/controllers/inverse_kinematics/inverse_kinematics.py
- src/webots/nodes/WbJoint.cpp
This PR improves the inverse kinematic sample by automatically parsing the robot kinematic using the URDF definition instead of hard-coding the kinematic.
This way it will be very simple to use it with other robots.
It also improves the URDF exporter to add joint limit: http://wiki.ros.org/urdf/XML/joint#Elements
> Improve Inverse Kinematic Sample

- docs/reference/changelog-r2020.md
- src/webots/control/WbController.cpp
The firejail execution of controllers was broken due to a bad order of command line parameters.
> Fixed firejail controllers

- src/webots/nodes/WbBaseNode.cpp
- src/webots/nodes/WbTrack.cpp
- src/webots/nodes/WbTrackWheel.cpp
- src/webots/nodes/WbTrackWheel.hpp
- tests/api/controllers/robot_urdf/reference_robot.urdf
- tests/api/worlds/robot_urdf.wbt
This pull-request fixes issue  #2067
> Fix URDF Export with Track Node

- docs/reference/changelog-r2020.md
- src/packaging/files_msys64.txt
This pull-request fixes issue  #2069
> Fix Procedural PROTOs not Working on Windows Release

- docs/guide/menu.md
- docs/guide/sample-webots-applications.md
- docs/guide/samples-community-projects.md
Add the information of the community projects repo to the documentation and give a quick instruction on how to add them to webots
> Doc: add Community Projects

- docs/reference/changelog-r2020.md
- src/webots/gui/WbMainWindow.cpp
This pull-request fixes issue #2046
> Fix color of the first console message.

- .github/workflows/tests_doc.yml
We just decided that the doc test should run on one platform only.
> Improve Doc Test

- docs/reference/changelog-r2020.md
- projects/objects/road/protos/HelicoidalRoadSegment.proto
> Fix HelicoidalRoadSegment PROTO

- src/webots/gui/WbMultimediaStreamingServer.cpp
- src/webots/gui/WbX3dStreamingServer.cpp
Fixes #2093.
This should help the user to detect a mode mismatch between Webots and the web client.
> Improve streaming error messages

- .travis.yml
The nightly builds are failing on macOS: 
https://travis-ci.com/github/cyberbotics/webots/jobs/370148842#L2147
https://travis-ci.com/github/cyberbotics/webots/jobs/370148842#L4095
> Fix macOS nightly

- .github/workflows/test_suite.yml
This PR add the possibility to use the labels to define which test should run.
> Run workflows on label

- src/webots/gui/WbView3D.cpp
Fix the two last crashes of https://github.com/cyberbotics/webots/issues/2110#issuecomment-671897712
> Fix crash on macOS when deleting the world

- docs/reference/changelog-r2020.md
- projects/default/controllers/ros/RosCamera.cpp
- projects/default/controllers/ros/RosCamera.hpp
> Fix ROS camera recognition topic

- projects/languages/ros/webots_ros/src/complete_test.cpp
This pull-request fixes issue #2121
> Fix ROS complete_test

- scripts/converter/convert_to_enu.py
- scripts/converter/convert_to_nue.py
This PR improves the convert to support NUE to ENU conversion.
> Improve conversion.

- docs/reference/motor.md
> meter per radian => radian per secod

- docs/reference/changelog-r2020.md
- src/ode/Makefile
- src/ode/ode/src/fluid_dynamics/ode_fluid_dynamics.cpp
- src/ode/ode/src/ode.cpp
- src/ode/ode/src/ode_MT/clustering/cluster.cpp
- src/ode/ode/src/ode_MT/threading/threadManagerPthread.cpp
- src/ode/ode/src/ode_MT/util_MT.cpp
- src/ode/ode/src/ode_MT/util_MT.h
The ODE flag to disable debug mode is ``dNODEBUG`` and not ``NDEBUG``.
This pull-request fixes issue #2043
> Disable ODE DEBUG in release mode.

- src/ode/ode/src/ode_MT/clustering/cluster.cpp
- src/ode/ode/src/ode_MT/threading/threadManagerPthread.cpp
Most of the debugging code of the multi-threading part of ODE was not maintained at all (was probably only development debug prints) and was not compiling anymore.
> Cleanup ODE MT.

- docs/reference/changelog-r2020.md
- projects/samples/howto/controllers/vision/vision.cpp
This pull-request fixes issue #1974
> Fix wrong image in Display in vision.wbt

- docs/reference/changelog-r2020.md
- resources/osm_importer/elevation.py
- resources/osm_importer/importer.py
- resources/osm_importer/osm_objects.py
- resources/osm_importer/parser_objects.py
- resources/osm_importer/projection.py
- resources/osm_importer/settings.py
I updated 
`import urllib`
to 
`import urllib.parse
import urllib.request`
to work on python3
> OSM_Importer  upgrade lib urllib for python3

- docs/guide/object-road.md
- docs/reference/changelog-r2020.md
> Update documentation and changelog for releasing R2020b rev1

- docs/blog/index.md
The blog was missing an index page.
> Fix Missing Blog Index

- projects/objects/trees/protos/Forest.proto
If the forest does not contain any tree (e.g. the forest file is not found), the PROTO was raising two warnings, the first one about forest without trees (which is fine) and a second one about an IndexedFaceSet without coordinates.
> Fix Empty Forest

- projects/robots/gctronic/e-puck/controllers/line_follower/runtime.ini
- projects/robots/gctronic/e-puck/controllers/obstacle/runtime.ini
- projects/robots/robotis/darwin-op/controllers/motion_player/runtime.ini
- projects/robots/robotis/darwin-op/controllers/soccer/runtime.ini
- projects/robots/robotis/darwin-op/controllers/symmetry/runtime.ini
- projects/robots/robotis/darwin-op/controllers/symmetry_matlab/runtime.ini
- projects/robots/robotis/darwin-op/controllers/visual_tracking/runtime.ini
- projects/robots/robotis/darwin-op/controllers/walk/runtime.ini
- projects/samples/curriculum/controllers/beginner_better_collision_avoidance_algorithm/runtime.ini
- projects/samples/curriculum/controllers/beginner_blinking_e-puck/runtime.ini
- projects/samples/curriculum/controllers/beginner_e-puck_dance/runtime.ini
- projects/samples/curriculum/controllers/beginner_finite_state_machine/runtime.ini
- projects/samples/curriculum/controllers/beginner_linear_camera/runtime.ini
- projects/samples/curriculum/controllers/beginner_move_your_e-puck/runtime.ini
- projects/samples/curriculum/controllers/beginner_rally/runtime.ini
- projects/samples/curriculum/controllers/novice_remain_in_shadow/runtime.ini
- projects/samples/curriculum/controllers/novice_train/runtime.ini
- projects/vehicles/controllers/VehicleDriver/runtime.ini
- projects/vehicles/controllers/autonomous_vehicle/runtime.ini
- projects/vehicles/controllers/boomer/runtime.ini
- projects/vehicles/controllers/highway_overtake/runtime.ini
- projects/vehicles/controllers/racing_wheel/runtime.ini
- projects/vehicles/controllers/ros_automobile/runtime.ini
- projects/vehicles/controllers/vehicle_driver/runtime.ini
The native Qt robot windows were broken on Windows.
This PR fixes this problem.
> Fixed broken native Qt robot windows on Windows

- resources/languages/Makefile
> Fix macOS Python 2.7

- docs/js/viewer.js
Fixes #2160.
Test it here: https://www.cyberbotics.com/doc/reference/inertialunit?version=fix-ctrl-click-in-doc
> Fix Ctrl-click in documentation pages

- docs/js/viewer.js
Continuation of #2160 and #2174 (specifically, https://github.com/cyberbotics/webots/issues/2160#issuecomment-683915642).
This pull-request fixes issue #2174.
**Tasks**
This is untested but should mirror the other one.
I doubt the CI will publish my foreign branch.
N/A
Described in #2174 .
> Handle ctrl-click for intra-page anchor links

- docs/guide/tutorial-8-using-ros.md
Address #2165: add support for ROS noetic in documentation
https://www.cyberbotics.com/doc/guide/tutorial-8-using-ros?version=documentation-tutorial-ros-noetic
> Update supported ros version in tutorial 8

- docs/automobile/openstreetmap-importer.md
Fix #2177
Preview: https://cyberbotics.com/doc/automobile/openstreetmap-importer?version=DavidMansolino-patch-2#dependencies
> Update OSM importer doc to python3

- docs/reference/changelog-r2020.md
- src/webots/nodes/WbPointSet.cpp
- tests/rendering/worlds/point_set.wbt
> Fix PointSet crash

- projects/languages/ros/webots_ros/package.xml
Simple update to prepare the release of the new ros packages for R2020b-rev1.
> Update ROS Package

- projects/robots/irobot/create/worlds/create.wbt
- projects/robots/neuronics/ipr/worlds/ipr_factory.wbt
- projects/samples/curriculum/worlds/advanced_path_planning.wbt
- projects/samples/environments/indoor/worlds/apartment.wbt
- projects/samples/howto/worlds/biped.wbt
- projects/samples/howto/worlds/sick_terrain_scanning.wbt
> Replace flat ElevationGrids with Planes

- docs/reference/changelog-r2020.md
- projects/objects/floors/protos/UnevenTerrain.proto
- projects/robots/micromagic/mantis/worlds/mantis.wbt
- projects/robots/sphero/bb8/worlds/bb-8.wbt
- projects/samples/demos/worlds/anaglyph.wbt
- src/webots/nodes/WbElevationGrid.cpp
- src/wren/StaticMesh.cpp
Fix the generated size of the UnevenTerrain PROTO.
> Fix UnevenTerrain Size

- src/webots/gui/WbGuiApplication.cpp
- src/webots/gui/WbSplashScreen.cpp
Small cleanup (to be merged after the release).
> Cleanup simplify splash screen code

- scripts/packaging/webots_distro.c
The snap package was missing the ros controller dependencies.
> Add ros dependencies to snap package too.

- Contents/Info.plist
- docs/js/showdown-extensions.js
- resources/version.txt
- scripts/new_version/new_version.sh
- scripts/new_version/new_version_file_headers.sh
- scripts/packaging/webots_version.txt
- src/webots/core/WbApplicationInfo.cpp
Tasks:
* Update version of next release
* Fix `new_version.sh` script (needed after moving in a different directory)
* use global paths instead of relative ones
* remove update of `doc.php` that doesn't exist any longer
* fix duplicated update of `resources/projects/worlds/empty.wbt`
> Update Webots version on master

- docs/guide/tutorial-8-using-ros.md
Follow-up of discussion https://github.com/cyberbotics/webots/pull/2191#discussion_r482723706
> Fix ROS-Webots matching.

- .github/workflows/test_suite_mac.yml
Complete #2193:
Fix version in `.github/workflows/test_suite_mac.yml` and inspect if it not possible to automatically retrieve the version.
> Fix Webots version in github workflow

- src/webots/nodes/WbRobot.hpp
- src/webots/scene_tree/WbSceneTree.cpp
- src/webots/vrml/WbNode.hpp
There was no check for the extension entered by the user when exporting a node.
> Improve Export Functionnality.

- src/webots/nodes/WbWorldInfo.cpp
Is some cases the north direction (used for GPS for example) was changed without explicitely warning the user.
> Improve northDirection Field Warning

- projects/robots/mobsya/thymio/controllers/thymio2_aseba/Makefile
- projects/robots/mobsya/thymio/controllers/thymio2_aseba/Thymio2AsebaHub.cpp
This should fix the appveyor build failure: https://ci.appveyor.com/project/omichel/webots-master#L4671
> Fixed aseba controller link on Windows

- src/webots/scene_tree/WbSceneTree.cpp
Adress comment https://github.com/cyberbotics/webots/pull/2201#pullrequestreview-483262722
> Improve error message

- docs/reference/changelog-r2020.md
- src/Controller/api/default_robot_window.c
This pull-request fixes issue  #2208
> Fix Memory Leak in Robot-Window

- docs/reference/changelog-r2020.md
- projects/robots/abb/irb/controllers/inverse_kinematics/inverse_kinematics.py
This controller was broken by #2145
> Fixed Inverse Kinematics Controller

- docs/automobile/car-library.md
- docs/automobile/driver-library.md
All the headers/import of the docs where wrong.
https://cyberbotics.com/doc/automobile/driver-library?version=fix-vehicle-library-doc
https://cyberbotics.com/doc/automobile/car-library?version=fix-vehicle-library-doc
> Fix vehicle library doc

- docs/reference/changelog-r2020.md
- resources/wren/shaders/color_noise.frag
- resources/wren/shaders/color_noise.vert
- resources/wren/shaders/range_noise.frag
- resources/wren/shaders/range_noise.vert
Fix #2139: fix generation of pseudo random values in GLSL shaders that didn't properly work on RTX Nvidia GPUs.
> Fix noise generation in GLSL

- scripts/converter/convert_eun_to_nue.py
Follow-up of https://github.com/cyberbotics/webots/pull/2204#pullrequestreview-483720264
> Force 'NUE' in convert_eun_to_nue script

- docs/guide/installation-procedure.md
Document how to install and use the Docker image.
https://cyberbotics.com/doc/guide/installation-procedure?version=add-docker-instructions#installing-the-docker-image
> Add Docker Instructions

- projects/robots/fp_robotics/p-rob3/protos/P-Rob3.proto
This was wrongly converted in #1847 and was looking bad is it appeared as an empty item in the scene-tree.
> Fix P-Rob3 default field value.

- projects/robots/irobot/create/worlds/create.wbt
This Transform was made useless in #2188.
> Remove Useless Transform in Create world

- docs/guide/installation-procedure.md
This is a simple and efficient way to install Webots.
> Document Brew macOS Installation

- docs/guide/installation-procedure.md
It is probably good to use the 'headless' keyword here as it is often mentioned by users.
> Improve docker doc

- docs/guide/menu.md
- docs/guide/privacy-policy.md
- docs/guide/telemetry.md
- src/webots/gui/WbAboutBox.cpp
Address #1652:
add privacy policy for transparency and to be compliant with GDPR.
I also added a link to the privacy policy from the "About" window:
> Add Webots Privacy Policy

- docs/guide/installation-procedure.md
Document Ubuntu versions of the images.
> Update Docker Doc

- docs/js/viewer.js
The `isFirstArgument` value was not set correctly and the URL could have the form ``localhost?book=reference?page=index`` instead of ``localhost?book=reference&page=index``
> Fix forgeUrl in viewer.js

- resources/web/streaming_viewer/index-debug.html
Address comment in #2249 about missing update of the debug version of the streaming viewer page.
> Fixed debug streaming viewer page

- docs/guide/web-simulation.md
- scripts/install/linux_compilation_dependencies.sh
- scripts/install/linux_optional_compilation_dependencies.sh
- scripts/install/linux_runtime_dependencies.sh
Fix #2254: instructions to compile Webots on Docker container doesn't work on Ubuntu 16.04
**Tasks**
* https://www.cyberbotics.com/doc/guide/web-simulation?version=enhancement-docker-installation#using-docker
* https://github.com/cyberbotics/webots/wiki/Docker#run-streaming-server-in-docker-container
> Enhancement Docker installation instructions

- docs/guide/supervisor-programming.md
This was not very pythonic: https://docs.quantifiedcode.com/python-anti-patterns/readability/comparison_to_none.html
> Improve Python Supervisor Example

- .travis.yml
The nightly builds are broken due to #2271
> Fix Travis Nightlies

- projects/humans/c3d/controllers/c3d_viewer/c3d_viewer.py
Address @DavidMansolino comments in #2250.
I still have no idea for a better class name 😒...
> Various fixes in c3d_viewer.py

- docs/guide/web-simulation.md
> Remove unneeded variable definition in Docker example

- docs/guide/running-extern-robot-controllers.md
- docs/guide/using-your-ide.md
Fixes #2294.
Links to the new version of the documentation:
- [PyCharm](https://cyberbotics.com/doc/guide/using-your-ide?version=fix-pycharm-documentation&tab-os=windows#pycharm)
- [Extern controllers - environment variables](https://cyberbotics.com/doc/guide/running-extern-robot-controllers?version=fix-pycharm-documentation&tab-os=windows#environment-variables)
> Fix pycharm documentation

- .appveyor-build-tag.yml
- .appveyor-build.yml
- .appveyor-test-sources-scheduled.yml
- .appveyor.yml
Following the fix of the MSYS2 main server, these changes are not needed any more.
> Reverted MSYS2 server switch

- docs/reference/changelog-r2020.md
- src/webots/core/WbHttpReply.cpp
- src/webots/core/WbTelemetry.cpp
No other modification than the one in change log is needed.
> Updated to Qt 5.15.1 on Windows

- tests/sources/test_matlab_functions.py
> Fix typo in tests

- tests/ros.sh
Attempt to understand the ros nightly failures
> Debug ros test

- docs/reference/changelog-r2020.md
- src/webots/nodes/WbLinearMotor.cpp
- src/webots/nodes/WbPropeller.cpp
- src/webots/nodes/WbPropeller.hpp
- src/webots/nodes/WbRotationalMotor.cpp
Fix error message when using a battery with propeller: #2323
> Fix battery with propeller

- dependencies/Makefile.windows
> Fix downloading lua on Windows

- .github/workflows/test_suite_mac.yml
- .github/workflows/tests_sources.yml
- projects/default/controllers/ros/RosConnector.cpp
- projects/default/controllers/ros/RosLidar.cpp
- projects/robots/mobsya/thymio/controllers/thymio2_aseba/Thymio2Model.cpp
- projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/SSH.cpp
- src/webots/sound/WbPicoTextToSpeech.cpp
- src/wren/demo/default.cpp
> Fix cppcheck issues

- docs/guide/installation-procedure.md
- docs/guide/using-java.md
- docs/guide/using-matlab.md
- docs/reference/robot.md
The MATLAB and Java spelling was sometimes wrong.
> Fixed a few typos in the doc

- projects/samples/robotbenchmark/humanoid_marathon/controllers/marathon/runtime.ini
Fix issue reported here https://github.com/cyberbotics/webots/issues/2248#issuecomment-694693617
> Fix loading RobotisOp2 robot window in humanoid_marathon simulation

- src/webots/sound/WbPicoTextToSpeech.cpp
Fix bug checking if reallocation failed introduced in #2335:
> Fix invalid buffer condition

- scripts/packaging/publish_release.py
The Appveyor nightlies are sometimes failing due to this part raising an exception.
> Improve publish_release.py robustness

- docs/reference/changelog-r2020.md
- projects/vehicles/protos/generic/Tractor.proto
- projects/vehicles/protos/tesla/TeslaModel3.proto
The supervisor field was missing in these two PROTO files.
> Add missing supervisor fields

- docs/reference/changelog-r2020.md
- src/webots/nodes/utils/WbSupervisorUtilities.cpp
- src/webots/wren/WbWrenLabelOverlay.hpp
> Fixed label color-only change

- docs/reference/camera.md
- docs/reference/viewpoint.md
This field was never documented.
> Fix missing 'exposure' field documentation

- projects/samples/devices/controllers/sample_supervisor/sample_supervisor.c
This PR adds labels to the supervisor example.
> Improve supervisor sample

- .appveyor-build-tag.yml
- .appveyor-build.yml
This was likely causing the problem with the nightly builds and Python 3.9.
> Fixed appveyor Python 3.9 build

- docs/reference/changelog-r2020.md
- projects/objects/geometries/protos/TexturedParallelepiped.proto
> Fixed TexturedParallelepiped proto

- .github/workflows/test_suite_mac.yml
Fix macOS CI, see more details here:
https://github.com/actions/virtual-environments/issues/1811#issuecomment-708480190
> Fix macOS CI test suite

- CONTRIBUTING.md
Since we (or at least I) are often using these guides to contribute, it is worth mentioning their existence to committers.
> Add Guides to CONTRIBUTING.md

- docs/reference/changelog-r2020.md
- src/webots/nodes/WbImageTexture.cpp
- src/webots/nodes/WbImageTexture.hpp
- src/webots/nodes/WbPbrAppearance.cpp
- src/webots/nodes/WbPbrAppearance.hpp
- tests/api/controllers/distance_sensor_infra-red_cached_images/.gitignore
- tests/api/controllers/distance_sensor_infra-red_cached_images/Makefile
- tests/api/controllers/distance_sensor_infra-red_cached_images/distance_sensor_infra-red_cached_images.c
- tests/api/worlds/distance_sensor_infra-red_cached_images.wbt
- tests/protos/controllers/modify_proto_template_field/modify_proto_template_field.c
Fix Distance-Sensors Reading with Cached Textures
This pull-request fixes issue #2365
> Fix Distance-Sensors Reading with Cached Textures

- docs/guide/using-your-ide.md
Added some precision.
Fix #2379.
> PyCharm documentation

- .appveyor.yml
- projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_bluetooth/Serial.cpp
Fixes clang format issues causing the tests to fail on appveyor.
> Fixed clang format

- docs/guide/epuck.md
Add acknowledgment to the ROSIN project where missing in prevision of the Milestone2 report.
> Add ROSIN Acknowledgment

- docs/reference/changelog-r2020.md
- projects/objects/kitchen/breakfast/protos/BiscuitBox.proto
> Improve recognition color of BiscuitBox PROTO

- .github/workflows/test_suite_mac.yml
This link with python 3.8 from brew is causing issues when installing python 3.9 from brew (https://github.com/cyberbotics/webots/runs/1321185852#step:3:331)
> Fix Github Action macOS build

- .travis.yml
Attempt to fix nightly failure on macOS on Travis: https://travis-ci.com/github/cyberbotics/webots/jobs/417037757#L6583
> Fix Travis on mac

- .github/workflows/test_suite_windows.yml
This PR adds a Github action that compiles Webots on Windows using Github action.
> Feature Windows Github Action

- docs/guide/citing-webots.md
I am not sure about the capitalization, but it seems fine:
https://english.stackexchange.com/questions/157178/capitals-or-not-for-open-source
https://en.wikipedia.org/wiki/Open-source_software
> Commercial to Open-source

- docs/guide/using-python.md
> Improve Python guide

- .github/workflows/tests_doc.yml
- .github/workflows/tests_sources.yml
- docs/guide/actuators.md
Addresses the following issue:
https://github.com/cyberbotics/webots/pull/2422#issuecomment-719914230
> Fix CI `tests_sources.yml` workflow

- docs/reference/changelog-r2020.md
- src/webots/nodes/WbGeometry.cpp
- src/webots/nodes/WbGeometry.hpp
- src/webots/nodes/WbMatter.cpp
- src/webots/nodes/WbPlane.cpp
- src/webots/nodes/WbPlane.hpp
- src/webots/nodes/WbTransform.cpp
> Fixed performance issue

- src/webots/nodes/WbGeometry.cpp
That may lead to a minor performance improvement (not measured).
> Minor simplification for Cylinders and Capsules

- docs/guide/tutorial-6-4-wheels-robot.md
> Fixed typo

- docs/guide/using-your-ide.md
> Improved Visual C++ wizard explanations

- docs/guide/installation-procedure.md
- docs/guide/language-setup.md
- docs/guide/menu.md
link to Programming Language Setup instructions
> Update windows installation instructions

- docs/guide/installation-procedure.md
I just noticed this wrong subtitle indentation.
> Fix subtitle issue

- resources/wren/shaders/gtao_combine.frag
- resources/wren/shaders/gtao_spatial_denoise.frag
- resources/wren/shaders/gtao_temporal_denoise.frag
- resources/wren/shaders/smaa_blending_weights.frag
Following up #2453, many shader compilation errors popped-up on my Windows machine (with NVIDIA card).
This PR fixes them all.
> Fixed shaders causing compilation errors

- .github/workflows/test_suite_linux.yml
- .github/workflows/test_suite_linux_develop.yml
> Update setup-ros GitHub action

- projects/humans/c3d/worlds/c3d_viewer.wbt
This issue was detected by the `world_update` test:
https://github.com/cyberbotics/webots/runs/1450711387?check_suite_focus=true
> Fix fields order in c3d_viewer.wbt

- .github/workflows/test_suite_linux.yml
- .github/workflows/test_suite_linux_develop.yml
- docs/guide/installation-procedure.md
- docs/guide/running-extern-robot-controllers.md
- docs/guide/system-requirements.md
- docs/reference/changelog-r2020.md
- scripts/install/linux_optional_compilation_dependencies.sh
- scripts/packaging/webots_distro.c
Extend the Linux GitHub Actions to also upload the Ubuntu 18.04 tarball package and the debian package.
> Upload all the Linux packages using GitHub Actions

- scripts/install/linux_compilation_dependencies.sh
- scripts/install/linux_runtime_dependencies.sh
- scripts/packaging/Makefile
The build of the snap fails on a stock bionic system because xvfb is not installed.
> Add xvfb to requirements.

- .github/workflows/test_suite_linux.yml
- .github/workflows/test_suite_linux_develop.yml
Update name of Ubuntu 18.04 tarball package.
> Fix GitHub actions

- docs/reference/contactproperties.md
- src/webots/nodes/WbContactProperties.cpp
> Fixed ContactProperties.softCFM limits

- .github/workflows/test_suite_windows_develop.yml
- .github/workflows/tests_sources.yml
This PR actually closes #2126 (which I didn't had time to finalize in #2421)
> Windows Develop Nightly Test

- scripts/packaging/Makefile
> Fixed compilation warning of webots_distro.c on mac

- resources/web/wwi/Makefile
> Fix npm uninstall

- projects/robots/festo/robotino3/worlds/robotino3.wbt
Fixes world update test on the master branch: https://github.com/cyberbotics/webots/runs/1495907044?check_suite_focus=true
> Fixed world update test on master branch (robotino3.wbt)
